function n(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function k(l){l.done?d(l.value):Promise.resolve(l.value).then(b,c).then(k,e)}k(a.next())})}
const B=lui,ba=B.defer,ca=B.defer_end,da=B.dom_define,ea=B.hook_async,D=B.hook_dom,E=B.hook_effect,ha=B.hook_memo,ia=B.hook_model,ma=B.hook_rerender,na=B.hook_state,H=B.hook_static,I=B.node,J=B.node_dom,oa=B.node_map,pa=B.now,qa=window,ua=document,K=Math,va=K.PI,wa=.5*va,xa=180/va,M=K.floor,ya=K.ceil,za=K.round,P=K.min,Aa=K.max,Ba=K.cos,Ca=K.sin,Da=K.sqrt,Ja=K.log2,Ka=String.fromCharCode,La=Date,Ma=JSON,Na=Promise,Oa=Ma.stringify,Pa=Ma.parse,S=localStorage,Ua=S.setItem.bind(S),Va=S.removeItem.bind(S),
Wa=qa.indexedDB,Xa=Uint8Array,Ya=Uint32Array,Za=Map,T=Number,$a=Object,ab=$a.keys,bb=$a.entries,cb=setTimeout,db=setInterval,ib=clearTimeout,jb=clearInterval,U=a=>a*a,kb=()=>!1,lb=(a,b)=>{const c=new La;a=new La(a);var d=c-a;if(59E3>d)return za(d/1E3)+"s";if(3E6>d)return za(d/6E4)+"m";d=a.getFullYear();const e=a.getMonth(),k=a.getDate();let l="";d<c.getFullYear()&&(l=d+"/");if(l||e<c.getMonth())l+=e+1+"/";if(l||k<c.getDate())l+=k;if(b)return l||"today";l&&(l+="/");b=l+a.getHours()+":";a=a.getMinutes();
a=M(a).toString().padStart(2,"0");return b+a};let W=S.getItem("minicraft.config");if((W=W&&Pa(W))&&W.worlds&&W.version.startsWith("0.9.")){const a=new Set(W.worlds.map(b=>"minicraft.world."+b.id));for(const b of ab(S))b.startsWith("minicraft.world.")&&!a.has(b.split(":")[0])&&Va(b)}
const mb={init:()=>{let a=!1;var b={ha:!0,qa:3,V:4,ya:120,ca:64,Aa:0,worlds:[]};if(W){let c=W.flag_textures;null!=c&&(b.ha=c);null!=(c=W.mouse_sensitivity)&&(b.qa=c);b.V=W.resolution_scaling;b.ya=W.view_angle;b.ca=W.view_distance;null!=(c=W.world_last)&&(b.Aa=c);null!=(c=W.worlds)?b.worlds=c:S.getItem("minicraft.world.0:meta")&&(b.worlds[0]={id:0,label:(prompt("There was an unnamed world found. How should it be called?","")||"Unknown world").substring(0,16),mod_l:Date.now(),mod_r:0},a=!0);W=null}b=
{account:{label:"",rank:0},config:b,Ta:b};return a?(b.Ta=null,mb.Sa(b)):b},Sa:a=>{const b=a.config;if(b===a.Ta)return a;Ua("minicraft.config",Oa({version:"0.9.9",flag_textures:b.ha,mouse_sensitivity:b.qa,resolution_scaling:b.V,view_angle:b.ya,view_distance:b.ca,world_last:b.Aa,worlds:b.worlds}));return Object.assign({},a,{Ta:b})},nb:(a,b)=>Object.assign({},a,{account:b}),pb:(a,b)=>mb.Ua(a,b(a.config)),Ua:(a,b)=>Object.assign({},a,{config:Object.assign({},a.config,b)}),$a:(a,b)=>Object.assign({},a,
{config:Object.assign({},a.config,{worlds:[...a.config.worlds,b]})}),ab:(a,b)=>Object.assign({},a,{config:Object.assign({},a.config,{worlds:a.config.worlds.filter(c=>c.id!==b)})}),O:(a,b,c)=>Object.assign({},a,{config:Object.assign({},a.config,{worlds:a.config.worlds.map(d=>d.id===b?Object.assign({},d,c):d)})})},nb="air stone grass dirt cobble planks bedrock log leaves bricks wool sand gravel glass bookshelf obsidian stone_bricks sandstone lapis_block iron_block gold_block diamond_block emerald_block redstone_block quartz_block".split(" "),
ob=[0,8487297,4305266,4349313,8092539,5342114,7039851,3561583,4172910,6384533,15526888,10671324,8092798,16447200,4151672,1970708,8092539,9686227,9126695,15198183,5567485,14541182,7920469,662956,14936813],pb="WEBTSN".split(""),qb=(a,b=1,c=null)=>({amount:b,data:c,id:a}),rb=(a,b,c=a.content.amount)=>{if(b.content)a.content.id===b.content.id?(c=P(c,b.P-b.content.amount),a.content.amount-=c,b.content.amount+=c,0>=a.content.amount&&(a.content=null)):!(a.content.amount<=c&&a.content.amount<=b.P&&b.content.amount<=
a.P)||a.filter&&!a.filter(b.content.id)||b.filter&&!b.filter(a.content.id)||([b.content,a.content]=[a.content,b.content]);else if(!b.filter||b.filter(a.content.id))a.content.amount<=c&&a.content.amount<=b.P?[b.content,a.content]=[a.content,b.content]:(c=P(c,b.P),a.content.amount-=c,b.content=qb(a.content.id,c),0>=a.content.amount&&(a.content=null))},sb=(a,b)=>{for(const c of a)if(c.content&&c.content.id===b.id){const d=P(b.amount,c.P-c.content.amount);c.content.amount+=d;if(0>=(b.amount-=d))return null}for(const c of a)if(!c.content&&
(!c.filter||c.filter(b.id)))if(a=P(b.amount,c.P),a<=b.amount){if(c.content=qb(b.id,a),0>=(b.amount-=a))return null}else return c.content=b,null;return b},tb=(a,b)=>({Pa:0,bb:0,Qa:0,N:0,da:0,Ca:0,ea:0,W:-1,fa:0,la:null,ma:null,o:1,jb:20,B:Array(36).fill(null).map(()=>({content:null,filter:null,P:64})),Ka:0,name:b.label||"Player",G:a.va,H:a.wa,J:a.xa,lb:0,mb:0,L:0,ja:0,$:0,aa:0,ba:0}),ub=(a,b,c)=>{a.N=(a.N+b+100*va)%(2*va);a.da=Aa(-wa,P(wa,a.da+c))},vb=a=>{a+=32;33<a&&39>a?a++:38<a&&44>a?a+=2:43<a&&
127>a?a+=3:126<a&&55258>a?a+=37:55295<a&&(a+=8485);return Ka(a)},wb=a=>a-(63743<a?8517:159<a?69:46<a&&130>a?35:40<a&&46>a?34:34<a&&40>a?33:32),yb=()=>{var a=xb;const b=a.length,c=new Za,d=x=>{m=m<<1|x&1;15===++u&&(g+=vb(m),m=u=0)},e=()=>{for(let x=0;x<w;++x)d(0)},k=x=>{d(x);d(x>>1);d(x>>2);d(x>>3);d(x>>4);d(x>>5);d(x>>6);d(x>>7)},l=()=>{0===--v&&(v=1<<w++)},p=()=>{if(C)C=!1;else{let x=t.id;for(let G=0;G<w;G++)d(x>>G)}};let f=a[0],g="",m=0,u=2,w=2,v=2,h=2,t={id:h++,Ea:new Za},C=!0;k(f);c.set(f,t);
for(let x=1;x<b;++x){const G=t.Ea.get(f=a[x]);G?t=G:(p(),c.has(f)||(l(),e(),k(f),c.set(f,{id:h++,Ea:new Za}),C=!0),t.Ea.set(f,{id:h++,Ea:new Za}),t=c.get(f),l())}p();c.has(f)||(l(),e(),k(f));l();d(1);--w;e();return g+=vb(m<<15-u)},zb=a=>{var b=xb;if(!a)return null;const c=a.length,d=()=>{u+=(h>>--t&1)<<w++;0===t&&(t=15,h=wb(a.charCodeAt(v++)))};let e=[0,1],k=1,l=3,p=2,f=null;var g=null;let m=0,u=0;g=2;let w=0,v=0,h=wb(a.charCodeAt(v++)),t=15;for(;w<g;)d();if(1===u)return null;for(u=w=0;8>w;)d();f=
[u];e[2]=f;for(b[m++]=u;v<=c;){g=p;for(u=w=0;w<g;)d();if(0===u){for(u=w=0;8>w;)d();e[l]=[u];u=l++;0===--k&&(k=1<<p++)}else if(1===u)return b;g=u<e.length?e[u]:f.concat(f[0]);for(let C=0;C<g.length;C++)b[m++]=g[C];e[l++]=f.concat(g[0]);f=g;0===--k&&(k=1<<p++)}return null};let X=null;
if(Wa){let a,b;null==(a=navigator.storage)||null==(b=a.persist)||b.call(a);const c=Wa.open("minicraft",1);c.onupgradeneeded=d=>{d=d.target.result.createObjectStore("chunks",{keyPath:["world","coords"]});for(const e of ab(S))if(e.startsWith("minicraft.world.")){const [k,l]=e.substr(16).split(":");"meta"!==l&&(d.add({world:T(k),coords:l,data:S.getItem(e)}),Va(e))}};c.onsuccess=d=>{X=d.target.result}}
const Ab=(a,b)=>n(function*(){if(!X)return S.getItem(`minicraft.world.${a}:${b}`);const c=X.transaction("chunks","readonly").objectStore("chunks").get([a,b]);return new Na(d=>{c.onsuccess=()=>{let e;d(null==(e=c.result)?void 0:e.data)}})}()),Bb=(a,b)=>{var c=yb();return n(function*(){if(!X)return Ua(`minicraft.world.${a}:${b}`,c);const d=X.transaction("chunks","readwrite").objectStore("chunks").put({world:a,coords:b,data:c});return new Na((e,k)=>{d.onsuccess=()=>{e()};d.onerror=()=>{k(d.error)}})}())},
Cb=(a,b)=>n(function*(){if(!X)return Va(`minicraft.world.${a}:${b}`);const c=X.transaction("chunks","readwrite").objectStore("chunks").delete([a,b]);return new Na(d=>{c.onsuccess=()=>{d()}})}()),Db=a=>n(function*(){const b=`minicraft.world.${a}:`;if(!X){const e={},k=b.length;for(const l of ab(S))l.startsWith(b)&&(e[l.substr(k)]=S.getItem(l));return e}const c=X.transaction("chunks","readonly").objectStore("chunks").openCursor(),d={meta:S.getItem(b+"meta")};return new Na(e=>{c.onsuccess=()=>{const k=
c.result;k?(k.value.world===a&&(d[k.value.coords]=k.value.data),k.continue()):e(d)}})}()),Eb=(a,b)=>n(function*(){if(X){var c=X.transaction("chunks","readwrite"),d=c.objectStore("chunks");for(const [e,k]of bb(b))"meta"!==e?d.put({world:a,coords:e,data:k}):Ua(`minicraft.world.${a}:meta`,k);return new Na((e,k)=>{c.oncomplete=()=>{e()};c.onerror=()=>{k(c.error)}})}for(const [e,k]of bb(b))Ua(`minicraft.world.${a}:${e}`,k);Ua("__margin",Array(257).join("x"));Va("__margin")}()),Fb=a=>{if(X){Va(`minicraft.world.${a}:meta`);
var b=X.transaction("chunks","readwrite").objectStore("chunks").openCursor();b.onsuccess=()=>{const c=b.result;c&&(c.value.world===a&&c.delete(),c.continue())}}else{const c=`minicraft.world.${a}:`;for(const d of ab(S))d.startsWith(c)&&Va(d)}},Gb=(a,b)=>{if(X){Ua(`minicraft.world.${b}:meta`,S.getItem(`minicraft.world.${a}:meta`));Va(`minicraft.world.${a}:meta`);var c=X.transaction("chunks","readwrite").objectStore("chunks"),d=c.openCursor();d.onsuccess=()=>{const e=d.result;e&&(e.value.world===a&&
(e.value.world=b,c.put(e.value)),e.continue())}}else{const e=`minicraft.world.${a}:`,k=e.length,l=`minicraft.world.${b}:`;for(const p of ab(S))if(p.startsWith(e)){const f=S.getItem(p);Va(p);Ua(l+p.substr(k),f)}}},Y=new Ya(1024),xb=new Xa(Y.buffer),Hb=new Za,Ib=(a,b,c,d)=>0>c||63<c?0:a.X[(b<<a.K+4|d)<<6|c],Jb=(a,b,c,d)=>{const e=a.K;a.X[(b<<e+4|d)<<6|c]=0;a.Y[(b>>4<<e|d>>4)<<2|c>>4].ga=!0},Kb=(a,b,c,d,e)=>{const k=a.K,l=(b<<k+4|d)<<6|c;if(0<a.X[l])return!1;a.X[l]=e;return a.Y[(b>>4<<k|d>>4)<<2|c>>
4].ga=!0},Yb=(a,b,c)=>{const d=Aa(P(b.H,63),0)>>4,e=M(b.G)>>4;b=M(b.J)>>4;if(c||a.Ia!==d||a.ra+a.Ha!==e||a.sa+a.Ja!==b)c=1<<a.K,a.Ia=d,a.ra=e-(a.Ha=(65536+e)%c),a.sa=b-(a.Ja=(65536+b)%c),Lb(a);a.busy||Xb(a,!1)},Lb=a=>{const b=a.Ha,c=a.Ia,d=a.Ja,e=a.K,k=`${e} ${b} ${d} ${c}`;let l=Hb.get(k);if(null==l){const p=1<<e,f=U(.5*p);Hb.set(k,l=a.Y.map(({x:g,y:m,z:u},w)=>{let v=U(g-b),h=U(u-d),t=U(g-b-p),C=0,x=0;t<v&&(v=t,C=-p);(t=U(g-b+p))<v&&(v=t,C=p);(t=U(u-d-p))<h&&(h=t,x=-p);(t=U(u-d+p))<h&&(h=t,x=p);
return{Va:v+h+U(m-c),eb:w,ra:C,sa:x}}).filter(({Va:g})=>g<=f).sort((g,m)=>g.Va-m.Va))}a.Fa=l;a.na=0},$b=(a,b)=>{const c=b.B.map(({content:d})=>d&&[d.id,d.amount,d.data]);for(;0<c.length&&null===c[c.length-1];)c.pop();Ua(`minicraft.world.${a.id}:meta`,Oa({p:{h:b.jb,i:c,m:b.o,p:[b.G,b.H,b.J,b.N,b.da]},s:[a.va,a.wa,a.xa],v:1}));Na.all(a.Y.filter(d=>d.ga).map(d=>Zb(a,d)))},ac=(a,b)=>{const c=S.getItem(`minicraft.world.${a.id}:meta`);if(c){const {p:d,s:e,v:k}=Pa(c);null!=k&&(d.i.forEach((l,p)=>{l&&(b.B[p].content=
qb(l[0],l[1],l[2]))}),b.jb=d.h,b.o=d.m,b.G=d.p[0],b.H=d.p[1],b.J=d.p[2],b.N=d.p[3],b.da=d.p[4],a.va=e[0],a.wa=e[1],a.xa=e[2])}},bc=a=>n(function*(){const b=a.Y[a.Fa[a.na=0].eb];var c=b.y;yield Cb(a.id,`${b.Ba}/${b.Oa}`+(0<c?"/"+c:""));b.ga=!1;++b.Ba;return Xb(a,!1)}()),Zb=(a,b)=>{const c=a.Da;var d=a.K;const e=b.y,k=(256<<d)-256;for(let l=0,p=-1,f=((b.x<<d+4|b.z)<<6|e)<<2;16>l;++l){for(d=0;16>d;++d)Y[++p]=c[f],Y[++p]=c[++f],Y[++p]=c[++f],Y[++p]=c[++f],f+=13;f+=k}b.ga=!1;return Bb(a.id,`${b.Ba}/${b.Oa}`+
(0<e?"/"+e:""))},Xb=(a,b)=>n(function*(){const c=a.Y,d=a.Fa,e=a.ra,k=a.sa,l=d.length;for(;a.na<l;){var p=d[a.na++],f=c[p.eb],g=f.loaded,m=f.x;const h=f.y;var u=f.z,w=e+p.ra+m;const t=k+p.sa+u;if(!g||w!==f.Ba||t!==f.Oa){f.loaded=a.busy=!0;p=f.ga&&Zb(a,f);var v=a.id;w=f.Ba=w;f=f.Oa=t;f=zb(yield Ab(v,`${w}/${f}`+(0<h?"/"+h:"")));yield p;a.busy=!1;if(g||0===h||f){p=a.Da;w=a.K;v=(256<<w)-256;m=((m<<w+4|u)<<6|h)<<2;if(f)for(let C=0,x=-1;16>C;++C){for(g=0;16>g;++g)p[m]=Y[++x],p[++m]=Y[++x],p[++m]=Y[++x],
p[++m]=Y[++x],m+=13;m+=v}else for(u=0;16>u;++u){for(f=0;16>f;++f)p[m]=0<h?0:50397446,p[++m]=0<h?0:131843,g?(p[++m]=0,p[++m]=0,m+=13):m+=15;m+=v}if(!b)break}}}}());let cc=null,dc=null,ec=new Image;ec.crossOrigin="anonymous";ec.onload=()=>{const a=ua.createElement("canvas");a.width=16;a.height=416;const b=a.getContext("2d");b.drawImage(ec,0,0);da("tile","div[className=bitmap]",{S:{backgroundImage:`url(${a.toDataURL()})`}});cc=new Ya(b.getImageData(0,0,16,416).data.buffer);dc&&dc();ec=dc=null};
ec.src=ASSETS+"blocks.webp";const gc=(a,b)=>{const c={ob:b,Ra:b.getContext("2d",{alpha:!1,desynchronized:!0}),cb:null,hb:"",T:!1,ib:0,Wa:0,qb:db(()=>(c.ib=c.Wa,c.Wa=0),1E3),l:a};null===cc&&(dc=()=>c.T=!0);fc(c);return c},fc=a=>{const b=a.ob,c=a.l;(a.cb=a.Ra.createImageData(b.width=c.ta,b.height=c.ua)).data.fill(255);const d=c.ta*c.config.V/c.ia,e=c.ua*c.config.V/c.ia;b.style.width=d+"px";b.style.height=e+"px";b.style.left=za((c.La-d)/2)+"px";b.style.top=za((c.Ma-e)/2)+"px";a.Ra.fillStyle="rgba(255,255,255,.5)"};
let hc=0;
const kc=(a,b,c,d)=>{const e={X:null,Da:null,busy:!1,Y:null,Fa:null,na:0,u:!0,Ha:0,Ia:0,Ja:0,id:c.Aa,ra:0,sa:0,K:0,va:.5,wa:8.5,xa:.5,time:0,Na:0},k=tb(e,d);ac(e,k);a={actions:a,config:c,fb:0,gb:0,Ga:!1,oa:!0,pa:!1,rb:b,Z:0,U:new Set,Xa:"",j:0,M:[],g:k,Ya:null,A:null,ia:1,La:1,Ma:1,ta:0,ua:0,tb:db(()=>{e.u||(e.time=(e.time+1)%24E3,e.Na=1/24E3*(e.Na+6E3)%1,Yb(e,k,!1))},50),world:e};ic(a,null);jc(a);return a},lc=a=>{$b(a.world,a.g);a.actions.O(a.world.id,{mod_l:Date.now()})},jc=a=>{n(function*(){try{yield a.rb.requestPointerLock()}catch(b){}}())},mc=
(a,b)=>a===b?0:.1-.2*a,nc=a=>{a.g.Pa=mc((a=a.U).has(-12)||a.has(65),a.has(-13)||a.has(68))},oc=a=>{a.g.bb=mc((a=a.U).has(-15)||a.has(16),a.has(-14)||a.has(32))},pc=a=>{a.g.Qa=mc((a=a.U).has(-11)||a.has(83),a.has(-10)||a.has(87))},qc=a=>{a.g.lb=mc(a.U.has(-18),a.U.has(-19))},rc=a=>{a.g.mb=mc(a.U.has(-17),a.U.has(-16))},tc=(a,b,c)=>{if(!a.world)return!1;const d=a.U;var e=a.g;if(c){if(d.has(b))return!1;d.add(b);var k=e.ea,l=e.W;c=e.fa;switch(b){case -18:case -19:qc(a);break;case -17:case -16:rc(a);break;
case -1:2!==e.o&&0<=l&&(0===e.Ka?0===e.o&&(b=Ib(a.world,k,l,c),2===b?b=3:1===b&&(b=4),6===b||8!==b&&13!==b&&null!==sb(e.B,qb(b,1)))||(Jb(a.world,k,l,c),e.W=-1):sc(a,[k,l,c],!1));break;case -2:case 71:if(0<=l){const p=Ib(a.world,k,l,c);c=e.B.slice(0,9);l=c.findIndex(f=>null!==f.content&&f.content.id===p);0<=l?e.L=l:1===e.o&&(c[e.L].content&&(c=c.findIndex(f=>null===f.content),0<=c&&(e.L=c)),e.B[e.L].content=qb(p));e.ja=a.Z}break;case -3:if(2!==e.o&&0<=l)if(0===e.Ka){if(b=e.B[e.L],b.content){switch(e.Ca){case 0:--k;
break;case 1:++k;break;case 2:--l;break;case 3:++l;break;case 4:--c;break;default:++c}0<=l&&64>l&&Kb(a.world,k&(1<<4+a.world.K)-1,l,c&(1<<4+a.world.K)-1,b.content.id)&&1!==e.o&&0>=--b.content.amount&&(b.content=null)}}else sc(a,[k,l,c],!0);break;case -4:e.L=(e.L+9-1)%9;e.ja=a.Z;break;case -5:e.L=(e.L+1)%9;e.ja=a.Z;break;case 27:0===a.j&&(a.world.u=!0,a.j=1);break;case -15:case -14:case 16:case 32:oc(a);break;case 49:case 50:case 51:case 52:case 53:case 54:case 55:case 56:case 57:e.L=b-49;e.ja=a.Z;
break;case -12:case -13:case 65:case 68:nc(a);break;case 69:if(0===a.j){a.j=3;for(const p of d)tc(a,p,!1)}break;case 80:a.world&&(a.world.u=!a.world.u);break;case 81:e=e.B[e.L];if(d.has(17)||e.content&&0>=--e.content.amount)e.content=null;break;case -11:case -10:case 83:case 87:pc(a);break;case 84:if(0===a.j){a.j=2;for(const p of d)tc(a,p,!1)}break;case 112:a.oa=!a.oa;break;case 114:a.Ga=!a.Ga;break;default:return!1}}else{if(!d.delete(b))return!1;switch(b){case -15:case -14:case 16:case 32:oc(a);
break;case -12:case -13:case 65:case 68:nc(a);break;case -11:case -10:case 83:case 87:pc(a);break;case -18:case -19:qc(a);break;case -17:case -16:rc(a)}}a.Xa=[...d].join();return!0},uc=(a,b)=>(b=b.startsWith("~")?a+T(b.substr(1)):T(b),isNaN(b)?a:b),wc=(a,b)=>{const c=a.g;var d=a.world;if(b)if("/"===b.charAt(0)){b=b.substr(1).split(" ");const e=b.shift();switch(e){case "clear":a.M=[];break;case "clearinv":for(const k of c.B)k.content=null;Z(a,"Inventory cleared.",!0);break;case "gamemode":case "gm":b=
T(b[0]);!isNaN(b)&&0<=b&&3>b&&0===b%1?(c.o=b,Z(a,"Game mode set to: "+b,!0)):Z(a,"Game mode must be in 0..2!");break;case "give":if(0===b.length){Z(a,"/give <id> [Amount]\n"+nb.join(" "));break}d=nb.indexOf((b[0]||"").toLowerCase());d=0<=d?d:T(b[0]);b=T(b[1]||1);!isNaN(d)&&0<d&&25>d&&0===d%1?!isNaN(b)&&0<b&&0===b%1?Z(a,sb(c.B,qb(d,b))?"Inventory is full!":`${"Gave items"} ${b} ${nb[d]}`,!0):Z(a,"Amount must be at least 1!"):Z(a,"Invalid block type!");break;case "help":Z(a,"Commands: clear, clearinv, gamemode, give, help, load, me, save, spawn, teleport, version");
break;case "load":Xb(d,!0).then(()=>{a.A.T=!0;Z(a,"Chunks loaded.",!0)});break;case "me":Z(a,c.name+" "+b.join(" "),!0);break;case "save":lc(a);Z(a,"Game saved.",!0);break;case "smart":c.name="LFF5644";Z(a,"lff.smart: true",!0);break;case "spawn":d.va=c.G;d.wa=c.H;d.xa=c.J;Z(a,"Spawn updated.",!0);break;case "teleport":case "tp":0===b.length?(c.G=d.va,c.H=d.wa,c.J=d.xa,a.A.T=!0,Z(a,"Teleported to spawn.",!0)):3===b.length?(Z(a,"Teleported to"+` ${c.G=uc(c.G,b[0])} ${c.H=uc(c.H,b[1])} ${c.J=uc(c.J,
b[2])}`,!0),a.A.T=!0):Z(a,"Pitch!");c.$=0;c.aa=0;c.ba=0;break;case "version":Z(a,"Minicraft 0.9.9");break;case "/exit":c.Ka=0;Z(a,"Normal mouse mode.",!0);break;case "/expand":a.g.la&&a.g.ma?d=!0:(Z(a,"Selection required!"),d=!1);d&&("vert"===b[0]?(c.la[1]=0,c.ma[1]=63,Z(a,"Expanded selection.",!0)):Z(a,'Only "vert" supported!'));break;case "/pos1":case "/pos2":sc(a,[M(c.G),M(c.H),M(c.J)],"/pos2"===e);break;case "/regen":bc(d).then(()=>{a.A.T=!0;Z(a,"Chunk regenerated.",!0)});break;case "/show":Z(a,
`${"Primary"}: ${c.la?c.la.join(" "):"none"}, ${"Secondary"}: ${c.ma?c.ma.join(" "):"none"}`);break;case "/wand":c.Ka=1;Z(a,"Select using mouse buttons.",!0);break;default:Z(a,"Unknown command: "+e)}}else{const e=Z(a,`<${c.name}> `+b);ic(a,b).then(k=>{k&&vc(a,e)})}},Z=(a,b,c=!1)=>{const d=++hc;(a.M=a.M.slice(-49)).push({id:d,kb:c,time:pa(),value:b});return d},vc=(a,b)=>{const c=a.M.findIndex(d=>d.id===b);0<=c&&a.M.splice(c,1)},sc=(a,b,c)=>{c?a.g.ma=b:a.g.la=b;Z(a,`${c?"Secondary point":"Primary point"}: ${b.join(" ")}`,
!0)},ic=(a,b)=>(ib(a.Ya),(b?fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:Oa({msg:b})}):fetch("/api/chat")).then(c=>{if(c.ok)return c.text()}).then(c=>{if(c){c=c.split("\n").filter(Boolean);for(const d of c)d.startsWith("<")&&Z(a,d);return 0<c.length}return!1}).catch(()=>!1).then(c=>{a.Ya=cb(()=>{ic(a,null)},5E3);return c})),xc=({id:a})=>(D("#tile",{S:{backgroundPositionY:`-${2*(a-1)}rem`}}),null);
function yc({amount:a,o:b,id:c}){D("div[className=stack]",{title:nb[c]+(1===b?` (${c})`:"")});return[I(xc,{id:c}),1!==a&&J("div[className=amount]",{innerText:a})]}
function zc({g:a,ka:b}){D("div[className=bar]",{ontouchstart:H(d=>{a.L=Number(d.target.closest("[data-slot]").dataset.slot);a.ja=d.timeStamp}),S:{opacity:Aa(.5,P(1,1-5E-4*(b-a.ja-5E3)))}});const c=a.o;return cc&&a.B.slice(0,9).map(({content:d},e)=>J("div",{D:{slot:e},F:{active:e===a.L}},[d&&I(yc,{amount:d.amount,data:d.data,o:c,id:d.id})]))}
function Ac({sb:a}){D("div[className=grid]",{onclick:({target:b})=>{(b=b.closest("[data-id]"))&&rb({content:qb(T(b.dataset.id)),filter:null,P:64},a)}});return nb.map((b,c)=>0<c&&J("div",{D:{id:c}},[I(yc,{amount:1,data:null,o:1,id:c})]))}
function Bc({l:a}){const b=ha(()=>({content:null,filter:null,P:64})),c=a.g.o;D("div[className=menu overlay inventory]",ha(()=>({onclick:({target:d})=>{if("menu overlay inventory"===d.className)b.content?b.content=null:(a.j=0,a.world.u=!1,jc(a));else if(d=d.closest("[data-slot]"))d=a.g.B[T(d.dataset.slot)],b.content?rb(b,d):d.content&&rb(d,b)},oncontextmenu:({target:d})=>{if("menu overlay inventory"===d.className)b.content?0>=--b.content.amount&&(b.content=null):(a.j=0,jc(a));else if(d=d.closest("[data-slot]"))d=
a.g.B[T(d.dataset.slot)],b.content?rb(b,d,1):d.content&&rb(d,b,ya(d.content.amount/2))}})));return cc&&[J("div[className=window]",null,[J("h2[innerText=Inventory]"),1===c&&I(Ac,{sb:b}),J("div[className=grid]",null,a.g.B.map(({content:d},e)=>J("div",{D:{slot:e},F:{first:9>e}},[d&&I(yc,{amount:d.amount,data:d.data,o:c,id:d.id})])))]),b.content&&J("div[className=hand]",{S:{transform:`translate(${a.fb}px, ${a.gb}px)`}},[I(yc,{amount:b.content.amount,data:b.content.data,o:0,id:b.content.id})])]}
const Cc=({I:{kb:a,time:b,value:c},ka:d})=>(D(a?"div[className=minor]":"div",{innerText:c,S:{opacity:P(1,1-.001*(d-b-4500))}}),null);function Dc({M:a,ka:b}){D("div[className=messages]");const c=b-5E3;return[oa(Cc,a.slice(-10).filter(d=>d.time>c),{ka:b})]}
function Ec({actions:{pb:a,Ua:b},config:c,l:d,za:e}){E(()=>lc(d));D("div[className=menu overlay]");return[J("h1[innerText=Settings]"),H(J("center",null,[J("button[innerText=Back to game]",{onclick:()=>{d.j=0;d.world.u=!1;jc(d)}})])),J("div[className=settings]",null,[J("button",{innerText:"Surfaces:\n"+(c.ha?"Textured":"Plain"),onclick:H(()=>a(k=>({ha:!k.ha})))}),J("label[innerText=Resolution:]",null,[J("input[type=range][min=1][max=100][step=1]",{value:101-c.V,onchange:H(k=>b({V:101-Number(k.target.value)}))})]),
J("label[innerText=View angle:]",null,[J("input[type=range][min=1][max=180][step=1]",{value:c.ya,onchange:H(k=>b({ya:Number(k.target.value)}))})]),J("label[innerText=View distance:]",null,[J("input[type=range][min=1][max=128][step=1]",{value:c.ca,onchange:H(k=>b({ca:Number(k.target.value)}))})]),J("label[innerText=Mouse sensitivity:]",null,[J("input[type=range][min=1][max=15][step=1]",{value:c.qa,onchange:H(k=>b({qa:Number(k.target.value)}))})])]),H(J("center",null,[J("button[innerText=Leave world]",
{onclick:()=>{e(0)}})]))]}const Fc=({I:{kb:a,value:b}})=>(D(a?"div[className=minor]":"div",{innerText:b}),null);
function Gc({l:a,M:b}){const c=H({history:null,input:null});D("div[className=menu overlay terminal]",{onclick:d=>{d.target!==c.input&&c.input.focus()}});E(d=>{d&&cb(()=>c.history.scrollTop=1E9,0)},[b.length&&b[b.length-1].id]);return[H(J("div[className=toolbar]",null,[J("button[innerText=\u274c]",{onclick:()=>{a.j=0;a.world.u=!1;jc(a)}})])),J("div[className=history]",{R:H(d=>{c.history=d})},[oa(Fc,b)]),H(J("input[enterkeyhint=send][mozactionhint=send][name=message][required]",{onkeydown:d=>{const e=
d.keyCode;d=d.target;13===e?(wc(a,d.value),d.value=""):27===e&&(a.u=!1,a.j=0)},R:d=>{c.input=d;cb(()=>d.focus(),0)}}))]}const Hc=[["pick",-2],["up",-14],["down",-15],["E",69],["T",84],["F1",112],["F3",114],["...",27]],Ic=[["up",-10],["down",-11],["left",-12],["right",-13],["center",-1]],Jc=[["up",-16],["down",-17],["left",-18],["right",-19],["center",-3]];
function Kc({l:a}){const b=a.U,c=([d,e])=>J("div",{D:{code:e},F:{button:!0,[d]:!0,active:b.has(e)}});D("div[className=touch]",H({ontouchstart:d=>{d.preventDefault();const e=Number(d.target.dataset.code);if(null!=e&&tc(a,e,!0)){const k=d.changedTouches[0].identifier,l=p=>{p.changedTouches[0].identifier===k&&(removeEventListener("touchend",l),tc(a,e,!1))};addEventListener("touchend",l)}}}));return[J("div[className=top]",null,Hc.map(([d,e])=>J(`div[innerText=${d}]`,{D:{code:e},F:{button:!0,active:b.has(e)}}))),
J("div[className=move]",null,Ic.map(c)),J("div[className=move sec]",null,Jc.map(c))]}
function Lc({account:a,actions:b,config:c,frame:d,Za:e,za:k}){const l=pa(),p=ua.pointerLockElement===d,f=ha(()=>e.l=kc(b,d,c,a));E(()=>{const g=v=>{if(0!==f.j)return!0;f.pa=!1;ua.pointerLockElement===d?tc(f,-1-v.button,"mousedown"===v.type):jc(f);v.preventDefault();return!1},m=v=>{if(f.world.u)f.fb=v.clientX,f.gb=v.clientY;else{const h=f.config.qa*va/(Aa(f.La,f.Ma)*f.ia);ub(f.g,v.movementX*h,-v.movementY*h)}},u=v=>{f.pa=!1;if(0===f.j&&!f.world.u&&5<Math.abs(v.deltaY)){const h=0<v.deltaY?-5:-4;tc(f,
h,!0);tc(f,h,!1);v.preventDefault()}},w=v=>{f.pa=!0;0===f.j&&(f.world.u=!1,v.preventDefault())};d.addEventListener("mousedown",g);d.addEventListener("mouseup",g);d.addEventListener("mousemove",m);d.addEventListener("wheel",u);d.addEventListener("touchstart",w);return()=>{d.removeEventListener("mousedown",g);d.removeEventListener("mouseup",g);d.removeEventListener("mousemove",m);d.removeEventListener("wheel",u);d.removeEventListener("touchstart",w);ib(f.Ya);jb(f.tb);$b(f.world,f.g);jb(f.A.qb);e.l=
null}});E(()=>{f.config=c;f.A&&(f.A.T=!0);const g=f.world;var m=ya(Ja(f.config.ca/16*2+2));if(g.K!==m){var u=f.g;g.Y&&$b(g,u);const w=1<<(g.K=m),v=g.Y=[];for(let h=0;h<w;++h)for(let t=0;t<w;++t)for(let C=0;4>C;++C)v.push({ga:!1,loaded:!1,x:h,y:C,z:t,Ba:0,Oa:0});m=w<<m+12+2;null===g.X||g.X.length<m?g.Da=new Ya((g.X=new Xa(m)).buffer):g.Da.fill(0);Yb(g,u,!0)}},[c]);E((g,m,u)=>{f.ia=u;f.La=Aa(1,g);f.Ma=Aa(1,m);m=f.config.V;g=ya(f.La*f.ia/m);m=ya(f.Ma*f.ia/m);if(g!==f.ta||m!==f.ua)f.ta=g,f.ua=m,f.A&&
(f.A.T=!0,fc(f.A))},[d.offsetWidth,d.offsetHeight,qa.devicePixelRatio||1,c.V]);E(()=>{p||f.world.u||0!==f.j||(f.j=1);f.world.u=!p},[p]);E(g=>p&&g&&ua.exitPointerLock(),[f.world.u||0!==f.j]);E(()=>{if(f.world){if(f.Z&&!f.world.u){var g=f.g,m=P(5,.01*(l-f.Z));g.$-=.1*g.$*m;g.aa-=.1*g.aa*m;g.ba-=.1*g.ba*m;g.$+=(Ba(g.N)*g.Pa+Ca(g.N)*g.Qa)*m;g.aa+=g.bb*m;g.ba+=(-Ca(g.N)*g.Pa+Ba(g.N)*g.Qa)*m;ub(g,g.lb*m,g.mb*m);g.G+=g.$*m;g.H+=g.aa*m;g.J+=g.ba*m}if(f.A){g=f.A;++g.Wa;m=g.Ra;var u=g.cb;const ja=g.l,Ea=ja.config,
eb=ja.oa,z=ja.g,aa=ja.ta,fa=ja.ua,N=ja.world;if(!N.u||g.T){g.T=!1;const ra=u.data,Mc=Ea.ca;var w=z.N,v=z.da;const Nc=z.ea,Oc=z.fa;var h=z.G,t=z.H,C=z.J;const Pc=eb?z.W:-1,Qc=N.X;var x=N.K;const Rc=Ea.ha&&null!==cc;var G=1/aa,O=1/fa;const sa=aa>>1,ta=fa>>1,Mb=P(aa,fa),Nb=32<Mb,Ob=Ba(w);w=Ca(w);const Pb=Ba(-v);v=Ca(-v);var q=Ea.ya/45;const Sc=G*(aa<fa?q*aa*O:q);G=O*(fa<aa?q*fa*G:q);h+=65536;t+=65536;C+=65536;O=h%1;q=t%1;const Tc=C%1;x=4+x;const Qb=(1<<x)-1;let Rb=1===z.o?6:4,ka=z.ea=z.fa=z.Ca=0;z.W=
-1;for(let Qa=0;Qa<fa;++Qa){var r=(ta-Qa)*G;const Sb=r*Pb-v;var y=r*v+Pb;r=y*w;y*=Ob;for(let Ra=0;Ra<aa;++Ra){var A=(Ra-sa)*Sc;const Tb=r+Ob*A;A=y-w*A;let Fa=16757124,Sa=1,Ub=Mc;for(let L=0;3>L;++L){let Q=A;0===L&&(Q=Tb);1===L&&(Q=Sb);var V=1/(0>Q?-Q:Q);const Ta=Tb*V,la=Sb*V;V*=A;const Vb=Da(Ta*Ta+la*la+V*V);var F=Tc;0===L&&(F=O);1===L&&(F=q);0<Q&&(F=1-F);let Ga=h+Ta*F-(0===L&0>Q|0),Ha=t+la*F-(1===L&0>Q|0),Ia=C+V*F-(2===L&0>Q|0);F*=Vb;for(let fb,gb,hb,R;F<Ub;Ga+=Ta,Ha+=la,Ia+=V,F+=Vb)if(65536>Ha){if(0>
la)break}else if(65600<=Ha){if(0<la)break}else if(0!==(R=Qc[((fb=Ga&Qb)<<x|(hb=Ia&Qb))<<6|(gb=Ha&63)])){Qa===ta&&Ra===sa&&F<=Rb&&(z.ea=fb,z.W=gb,z.fa=hb,z.Ca=0>Q|L<<1,Rb=F);if(Rc){--R;1===L?6===R?R=25:13===R?R=4:1===R&&0<la&&(R=2):1===R&&(R=24);const Wb=cc[R<<8|(16*(1===L?Ia:Ha)&15)<<4|16*(1===L?Ga:(0<Q?Ga-Ia:Ia-Ga)+65536)&15];if(0===Wb>>>24)continue;Fa=Wb&16777215}else Fa=ob[R];Ub=F;Sa=(0===L?.8:2===L?.6:0<Q?.4:1)+(gb!==Pc||fb!==Nc||hb!==Oc?0:.2);break}}ra[ka]=(Fa&255)*Sa;ra[++ka]=(Fa>>8&255)*Sa;
ra[++ka]=(Fa>>16)*Sa;ka+=2}}eb&&!Nb&&(ra[ka=aa*ta+sa<<2]+=128,ra[++ka]+=128,ra[++ka]+=128);m.putImageData(u,0,0);eb&&Nb&&(u=ya(.05*Mb),m.fillRect(sa-u,ta-1,u<<1,2),m.fillRect(sa-1,ta-u,2,u-1),m.fillRect(sa-1,ta+1,2,u-1))}g.hb=ja.Ga?"Minicraft 0.9.9 "+M(g.ib).toString().padStart(2,"\u00a0")+" fps, T: "+M(24*N.Na).toString().padStart(2,"0")+":"+M(24*N.Na%1*60).toString().padStart(2,"0")+"; "+(N.u&&500>l%1E3?"":N.time)+"\nR: "+aa+"x"+fa+" (x"+Ea.V+"), D: "+Ea.ca+", C: "+N.na+"/"+N.Fa.length+", M: "+
(64*U(1<<4+N.K)>>10)+"k\nE: 0/0 M: "+z.o+"\n\nPosition: "+z.G.toFixed(2)+" "+z.H.toFixed(2)+" "+z.J.toFixed(2)+"\nAngle: "+(z.N*xa).toFixed(2)+" "+(z.da*xa).toFixed(2)+"\nBlock: "+(0>z.W?0:z.ea+" "+z.W+" "+z.fa+" "+pb[z.Ca]+": "+Ib(N,z.ea,z.W,z.fa))+"\nChunk abs: "+(M(z.G)>>4)+" "+(M(z.J)>>4)+" "+(M(z.H)>>4)+" rel: "+N.Ha+" "+N.Ja+" "+N.Ia:""}}f.Z=l},[l]);ma();return[J("canvas",{R:H(g=>{f.A=gc(f,g)})}),f.oa&&2!==f.j&&I(Dc,{M:f.M,ka:l}),f.A&&f.Ga&&J("div[className=diagnostics]",{innerText:f.A.hb}),
f.pa&&I(Kc,{l:f,Xa:f.Xa}),f.oa&&3!==f.j&&2!==f.g.o&&I(zc,{g:f.g,ka:l}),3===f.j&&I(Bc,{l:f,ka:l}),1===f.j&&I(Ec,{actions:b,config:c,l:f,za:k}),2===f.j&&I(Gc,{l:f,M:f.M})]}
function Uc({I:a,ub:b,vb:c,wb:d}){D("div",{F:{selected:a===c},onclick:()=>{d(a.id)}});c=`${a.local?"L":"_"}${a.local&&a.remote?a.local>a.remote?">":a.local<a.remote?"<":"=":"_"}${a.remote?a.public?"R":"r":"_"}`;b===a.id&&(c=`[${c}]`);return[J("span",{innerText:`${c} ${a.label}`,title:a.account_name?"Owner: "+a.account_name:"Just a local world"}),J("span",{innerText:lb(Math.max(a.local,a.remote),!0)})]}
function Vc({account:a,actions:b,config:c,za:d}){D("div[className=menu]");const [e,k,l]=na(0),p=H(()=>{k(l()+1)}),f=H({value:null}),g=ea(()=>n(function*(){try{const q=!f.value&&!e,r=yield fetch("/api/minicraft/"+`world?what=${q?"initial":"meta_all"}`);if(!r.ok)throw Error("Connection error.");const y=yield r.json();if(!q)return y;if("0.9.9"!==y.version_latest)return location.reload(),null;ba();b.nb(y.account);return y.worlds}catch(q){return alert("Error while loading world list: "+q.message),[]}}()),
[e],null),m=ha(()=>{g&&(f.value=g);const q=[];f.value&&q.push(...f.value.map(r=>({account_name:r.account_name,hash:r.hash,id:r.id,label:r.label,local:0,public:r.public,remote:r.modified,writable:r.writable})));for(const r of c.worlds){const y=q.find(A=>A.id===r.id);if(y){const A=y.local=r.mod_l,V=y.remote,F=r.mod_r;A>F&&V>F&&(confirm('Conflict! The world "'+r.label+'" was modified here and somewhere else.\nOK: Take variant from server ('+lb(V,!1)+") | Cancel: Keep local variant ("+lb(A,!1)+")")?b.O(r.id,
{mod_l:y.local=F}):b.O(r.id,{mod_r:y.remote=F}))}else 1<r.mod_r&&g&&g.length&&(alert('The world "'+r.label+'" was not found on the server, so it is a local world now.'),b.O(r.id,{mod_r:0})),q.push({account_name:"",hash:0,id:r.id,label:r.label,local:r.mod_l,public:!1,remote:1===r.mod_r?1:0,writable:!0})}return q.sort((r,y)=>Math.max(y.local,y.remote)-Math.max(r.local,r.remote))},[g,c.worlds]),[u,w,v]=na(c.Aa),h=ha(()=>m.find(q=>q.id===u)||null,[u,m]),t=ha(()=>{let q,r;return null!=(r=null==m?void 0:
null==(q=m.find(y=>0<y.local&&0<y.remote&&y.local!==y.remote))?void 0:q.id)?r:null},[m]);E(()=>{if(null!==t){var q=!1,r=m.find(y=>y.id===t);if(r.local<r.remote)fetch("/static/minicraft/worlds/"+`${r.hash}.json`).then(y=>y.json()).then(y=>{if(!q)return Eb(t,y).then(()=>{b.O(t,{mod_l:r.remote,mod_r:r.remote})})}).catch(y=>{q||("QuotaExceededError"===y.name?(alert("Insufficient storage!"),b.ab(t),Fb(t)):alert("Error while downloading world: "+y.message))});else{if(!r.writable){b.O(t,{mod_l:c.worlds.find(A=>
A.id===t).mod_r});return}let y=t;(1===r.remote?fetch("/api/minicraft/world",{method:"POST",headers:{"Content-Type":"application/json"},body:Oa({what:"meta",label:r.label})}).then(A=>{if(!A.ok)throw Error(403===A.status?"Missing permission. Logged in?":"Connection error.");return A.json()}).then(A=>{y=A.id}):Na.resolve()).then(()=>{if(q)throw null;return Db(t)}).then(A=>{if(q)throw null;return fetch("/api/minicraft/world",{method:"POST",headers:{"Content-Type":"application/json"},body:Oa({what:"data",
world:y,data:A})})}).then(A=>{if(!A.ok)throw Error(403===A.status?"Missing permission. Logged in?":"Connection error.");return A.json()}).then(A=>{ba();y===t?b.O(t,{mod_l:A.modified,mod_r:A.modified}):(Gb(t,y),b.ab(t),b.$a({id:y,label:r.label,mod_l:A.modified,mod_r:A.modified}),q||v()!==t||w(y));q||p();ca()}).catch(A=>{q||(alert("Error while uploading world: "+A.message),ba(),b.O(t,{mod_r:0}),ca())})}return()=>{q=!0}}},[t]);const [C,x]=na(!1);h||x(!1);const [G,O]=na(!1);return[J("h1[innerText=Worlds]"),
J("button[innerText=Refresh][style=position:absolute;left:0;top:0;height:2rem][title=Reload list]",{disabled:!g,onclick:p}),J("button[style=position:absolute;right:0;top:0;height:2rem]",{disabled:0<a.rank,innerText:a.rank?a.label:"Login",onclick:()=>{location.href="/account?redir=minicraft"}}),J("div[className=worlds]",null,[oa(Uc,m,{xb:e,ub:t,vb:h,wb:w})]),J("center",null,[J("button[innerText=Enter]",{disabled:!h||!h.local||h.remote>h.local,onclick:()=>{ba();b.Ua({Aa:h.id});d(1);ca()},title:h?h.local?
h.remote>h.local?"The world is still loading!":"Enter selected world":"The world is not downloaded yet!":"No world selected!"}),J("button[innerText=World...]",{disabled:!h||C,onclick:()=>{x(!0)},title:h?"Show world settings":"No world selected!"})]),J("hr"),J("center",null,[J("button[innerText=New world]",{onclick:()=>{const q=prompt("New world's label:\n(max. 16 characters)","New world");q&&(16<q.length?alert("Name is too long!"):b.$a({id:Math.min(0,...c.worlds.map(r=>r.id))-1,label:q,mod_l:Date.now(),
mod_r:0}))}}),J("button[innerText=Project page]",{onclick:()=>{open("//github.com/L3P3/minicraft")}})]),J("center",null,[J("small[innerText=Version 0.9.9 by L3P3]")]),C&&h&&J("div",{F:{"menu overlay advanced":!0,busy:G},onclick:q=>{"menu overlay advanced"===q.target.className&&x(!1)}},[J("div[className=window]",null,[J("h2",{innerText:'"'+h.label+'"',title:h.id}),J("table",null,[!!h.account_name&&J("tr",null,[J("td[innerText=Owner:]"),J("td",{innerText:h.account_name})]),J("tr",null,[J("td[innerText=Modified:]"),
J("td",{innerText:lb(Math.max(h.local,h.remote),!1)})])]),J("center",null,[J("button[innerText=Rename]",{disabled:G||!h.writable,onclick:()=>{const q=prompt("World's new label:\n(max. 16 characters)",h.label);!q||q===h.label||16<q.length||(h.local&&b.O(h.id,{label:q}),h.remote&&(O(!0),fetch("/api/minicraft/world",{method:"POST",headers:{"Content-Type":"application/json"},body:Oa({what:"meta",world:h.id,label:q})}).then(r=>{if(!r.ok)throw Error(403===r.status?"Missing permission. Logged in?":"Connection error.");
return r.json()}).catch(r=>{alert("Error while editing world: "+r.message)}).then(()=>{O(!1)})))},title:h.writable?"Change world name":"No permission!"}),J("button",{disabled:G||!h.local&&!h.writable,innerText:h.local?"Delete (local)":"Delete",onclick:()=>{confirm('Really delete world "'+h.label+'"?')&&(h.local?(b.ab(h.id),Fb(h.id)):(O(!0),fetch("/api/minicraft/world",{method:"DELETE",headers:{"Content-Type":"application/json"},body:Oa({what:"world",world:h.id})}).then(q=>{if(!q.ok)throw Error(403===
q.status?"Missing permission. Logged in?":"Connection error.");ba();w(null);x(!1);p();O(!1);ca();return q.json()}).catch(q=>{alert("Error while deleting world: "+q.message);O(!1)})))},title:h.local||h.writable?"Delete world":"No permission!"})]),J("center",null,[J("button",{disabled:G||!h.remote||!h.writable,innerText:`${"Public"}: ${h.public?"Yes":"No"}`,onclick:()=>{O(!0);fetch("/api/minicraft/world",{method:"POST",headers:{"Content-Type":"application/json"},body:Oa({what:"meta",world:h.id,public:!h.public})}).then(q=>
{if(!q.ok)throw Error(403===q.status?"Missing permission. Logged in?":"Connection error.");ba();p();O(!1);ca();return q.json()}).catch(q=>{alert("Error while editing world: "+q.message);O(!1)})},title:h.remote?h.writable?h.public?"Unpublish world":"Publish world":"No permission!":"The world is not uploaded!"}),J("button",{disabled:G||!g||0<h.local&&0<h.remote||!h.remote&&!a.rank,innerText:h.local?g&&h&&!h.remote?"Upload":"Transfer":"Download",onclick:()=>{h.local?h.remote||b.O(h.id,{mod_r:1}):b.$a({id:h.id,
label:h.label,mod_l:1,mod_r:h.remote})},title:g?h.local?h.remote?"The world is present on both sides!":a.rank?"Upload world to server":"Not logged in!":"Download world from server":"List is loading!"})])])])]}function Wc({account:a,actions:b,config:c,Za:d}){const [e,k]=na(0),l=D("div[className=game]");return[0===e&&I(Vc,{account:a,actions:b,config:c,za:k}),1===e&&I(Lc,{account:a,actions:b,config:c,frame:l,Za:d,za:k})]}
B.init(()=>{const [a,b]=ia(mb),c=H({l:null});E(()=>{let e=!1;onbeforeunload=onunload=onpagehide=onblur=()=>{e||(e=!0,c.l&&lc(c.l),b.Sa())};onpageshow=onfocus=()=>{e=!1};setInterval(()=>{b.Sa()},500)});const d=H(e=>{if("INPUT"===e.target.tagName||!c.l)return!0;c.l.pa=!1;tc(c.l,e.keyCode,"keydown"===e.type);e.preventDefault();return!1});return[{onkeydown:d,onkeyup:d,oncontextmenu:kb,ondragstart:kb},[I(Wc,{account:a.account,actions:b,config:a.config,Za:c})]]});
