function m(a){function b(e){return a.next(e)}function c(e){return a.throw(e)}return new Promise(function(e,d){function g(h){h.done?e(h.value):Promise.resolve(h.value).then(b,c).then(g,d)}g(a.next())})}
const w=lui,aa=w.defer,ba=w.defer_end,ca=w.hook_async,y=w.hook_dom,z=w.hook_effect,fa=w.hook_memo,ha=w.hook_model,ia=w.hook_prev,ja=w.hook_rerender,ka=w.hook_state,A=w.hook_static,na=w.init,B=w.node,C=w.node_dom,oa=w.node_map,pa=w.now,qa=window,ra=document,sa=navigator,D=Math,ta=D.PI,ua=ta*.5,xa=180/ta,ya=D.random,E=D.floor,za=D.ceil,Aa=D.round,G=D.min,J=D.max,Ba=D.cos,Ca=D.sin,Da=D.sqrt,Ha=D.log2,Ia=String.fromCharCode,Ja=qa.BroadcastChannel,Ka=Date,La=JSON,K=Promise,Ma=K.resolve,Na=La.stringify,
Oa=La.parse,L=localStorage,M=L.setItem.bind(L),Pa=L.removeItem.bind(L),Qa=qa.indexedDB||null,R=fetch,Ra=Array,Za=Uint8Array,$a=Uint32Array,ab=Set,bb=Map,S=Number,cb=Object,db=cb.keys,eb=cb.entries,fb=setTimeout,gb=setInterval,hb=clearTimeout,ib=clearInterval,jb=addEventListener,kb=removeEventListener,qb=alert,rb=confirm,sb=prompt,tb=sa.userAgent.includes("WebKit"),ub={method:"POST",headers:{"Content-Type":"application/json"}},vb=(a,b)=>(a=E(a).toString(),a.length<2?b+a:a),wb=a=>a*a,xb=()=>!1,yb=(a,
b)=>{if(a<2)return"...";const c=new Ka;a=new Ka(a);var e=c-a;if(e<59E3)return Aa(e/1E3)+"s";if(e<3E6)return Aa(e/6E4)+"m";e=a.getFullYear();const d=a.getMonth(),g=a.getDate();let h="";e<c.getFullYear()&&(h=e+"/");if(h||d<c.getMonth())h+=d+1+"/";if(h||g<c.getDate())h+=g;if(b)return h||"heute";h&&(h+="/");return h+a.getHours()+":"+vb(a.getMinutes(),"0")},zb=a=>{if(!a.ok)throw Error(a.status===403?"Keine Berechtigung. Angemeldet?":"Verbindungsfehler.");return a.json()},Ab="air stone grass dirt cobble planks bedrock log leaves bricks wool sand gravel glass bookshelf obsidian stone_bricks sandstone lapis_block iron_block gold_block diamond_block emerald_block redstone_block quartz_block".split(" "),
Bb="Luft Stein Grasblock Erde Bruchstein Holzbretter Grundgestein Stamm Laub Ziegelsteine Wolle Sand Kies Glas B\u00fccherregal Obsidian Steinziegel Sandstein Lapislazuliblock Eisenblock Goldblock Diamantblock Smaragdblock Redstoneblock Quarzblock".split(" "),Hb=[0,8487297,4305266,4349313,8092539,5342114,7039851,3561583,4172910,6384533,15526888,10671324,8092798,16447200,4151672,1970708,8092539,9686227,9126695,15198183,5567485,14541182,7920469,662956,14936813];let Ib=null;
const Jb=Qa?new K(a=>{var b;let c;(b=sa.storage)==null||(c=b.persist)==null||c.call(b);b=Qa.open("minicraft",1);b.onupgradeneeded=e=>{e=e.target.result.createObjectStore("chunks",{keyPath:["world","coords"]});for(const d of db(L))if(d.startsWith("minicraft.world.")){const [g,h]=d.slice(16).split(":",2);h!=="meta"&&(e.add({world:S(g),coords:h,data:L.getItem(d)}),Pa(d))}};b.onsuccess=e=>{Ib=e.target.result;a()}}):Ma(),Kb=Qa?(a,b)=>new K(c=>{const e=Ib.transaction("chunks","readonly").objectStore("chunks").get([a,
b]);e.onsuccess=()=>{let d;return c((d=e.result)==null?void 0:d.data)}}):(a,b)=>Ma(L.getItem(`minicraft.world.${a}:${b}`)),Lb=Qa?(a,b,c)=>new K((e,d)=>{const g=Ib.transaction("chunks","readwrite").objectStore("chunks").put({world:a,coords:b,data:c});g.onsuccess=()=>e();g.onerror=()=>d(g.error)}):(a,b,c)=>(M(`minicraft.world.${a}:${b}`,c),Ma()),Mb=Qa?(a,b)=>new K((c,e)=>{const d=Ib.transaction("chunks","readwrite").objectStore("chunks").delete([a,b]);d.onsuccess=()=>c();d.onerror=()=>e(d.error)}):
(a,b)=>(Pa(`minicraft.world.${a}:${b}`),Ma()),Nb=Qa?a=>new K(b=>{const c=L.getItem(`minicraft.world.${a}:meta`);if(!c)return b({});const e=Ib.transaction("chunks","readonly").objectStore("chunks").openCursor(),d={meta:c};e.onsuccess=()=>{const g=e.result;g?(g.value.world===a&&(d[g.value.coords]=g.value.data),g.continue()):b(d)}}):a=>{a=`minicraft.world.${a}:`;const b=a.length,c={};for(const e of db(L))e.startsWith(a)&&(c[e.slice(b)]=L.getItem(e));return Ma(c)},Ob=Qa?(a,b)=>new K((c,e)=>{const d=Ib.transaction("chunks",
"readwrite"),g=d.objectStore("chunks");for(const [h,l]of eb(b))h!=="meta"?g.put({world:a,coords:h,data:l}):M(`minicraft.world.${a}:meta`,l);d.oncomplete=()=>c();d.onerror=()=>e(d.error)}):(a,b)=>m(function*(){for(const [c,e]of eb(b))M(`minicraft.world.${a}:${c}`,e);M("__margin",Ra(257).join("x"));Pa("__margin")}()),Pb=Qa?a=>{const b=Ib.transaction("chunks","readwrite").objectStore("chunks").openCursor();b.onsuccess=()=>{const c=b.result;c&&(c.value.world===a&&c.delete(),c.continue())};Pa(`minicraft.world.${a}:meta`)}:
a=>{a=`minicraft.world.${a}:`;for(const b of db(L))b.startsWith(a)&&Pa(b)},Qb=Qa?(a,b)=>new K(c=>{const e=Ib.transaction("chunks","readwrite").objectStore("chunks"),d=e.openCursor();d.onsuccess=()=>{const g=d.result;g?(g.value.world===a&&(g.delete(),g.value.world=b,e.put(g.value)),g.continue()):c()};M(`minicraft.world.${b}:meta`,L.getItem(`minicraft.world.${a}:meta`));Pa(`minicraft.world.${a}:meta`)}):(a,b)=>{a=`minicraft.world.${a}:`;const c=a.length;for(const e of db(L))if(e.startsWith(a)){const d=
L.getItem(e);Pa(e);M(`minicraft.world.${b}:${e.slice(c)}`,d)}return Ma()};let T=null,Rb=0,Sb=null,Tb=0;
const Vb=()=>{U.ya||U.ga!==null||(hb(Rb),V.B({wb:!0,ya:!0}),Ub(!1))},Ub=a=>{m(function*(){Rb=fb(V.B,5E3,{wb:!1});try{const b=yield R(`${"/api/minicraft/"}world?what=${a?"initia":"meta_al"}l`),c=yield zb(b);a?c.version_latest!=="0.11.9"?location.reload(!0):(T=c.worlds,V.B(Object.assign({},{account:c.account,ya:!1},Wb(U.config)))):(T=c,V.B(Object.assign({},{ya:!1},Wb(U.config))))}catch(b){V.B({da:"Fehler beim Laden der Weltenliste: "+b.message,ya:!1})}}())},Xb=(a,b)=>J(b.local,b.remote)-J(a.local,a.remote),
Wb=a=>{const b=T?T.map(c=>({account_name:c.account_name,hash:c.hash,id:c.id,label:c.label,local:0,public:c.public,remote:c.modified,writable:c.writable})):[];for(const c of a.worlds){const e=b.find(d=>d.id===c.id);if(e){const d=e.local=c.mod_l,g=e.remote,h=c.mod_r;d>h&&g>h&&(rb('Konflikt! Die Welt "'+c.label+'" wurde sowohl hier als auch woanders ge\u00e4ndert.\nOK: Die vom Server \u00fcbernehmen ('+yb(g,!1)+") | Abbrechen: Die hier hochladen ("+yb(d,!1)+")")?a=Object.assign({},a,{worlds:a.worlds.map(l=>
l.id===c.id?Object.assign({},l,{mod_l:e.local=h}):l)}):e.remote=h)}else c.mod_r>1&&T&&(qb('Die Welt "'+c.label+'" wurde auf dem Server nicht gefunden, ist also jetzt eine lokale!'),a=Object.assign({},a,{worlds:a.worlds.map(d=>d.id===c.id?Object.assign({},d,{mod_r:0}):d)})),b.push({account_name:"",hash:0,id:c.id,label:c.label,local:c.mod_l,public:!1,remote:c.mod_r===1?1:0,writable:!0})}return{config:a,Qa:b.sort(Xb)}},Zb=()=>m(function*(){if(U.ga===null){var a;try{for(;a=U.Qa.find(b=>b.local>0&&b.remote>
0&&b.local!==b.remote);)yield Yb(a);V.B({ga:null})}catch(b){V.B({da:b.message,ga:null})}}}()),Yb=a=>m(function*(){const b=a.id;V.B({ga:b});if(a.local<a.remote)try{yield Ob(b,yield zb(yield R(`${"/static/minicraft/"}worlds/${a.hash}.json`))),V.fa(b,{mod_l:a.remote,mod_r:a.remote})}catch(c){if(c.name==="QuotaExceededError")qb("Der Speicherplatz reicht nicht!"),Pb(b),V.Qb(b);else throw Error("Fehler beim Herunterladen der Welt: "+c.message);}else if(a.writable){let c=b,e=null;try{const d=Nb(b);if(b<
0){const h=yield zb(yield R("/api/minicraft/world",Object.assign({},ub,{body:Na({what:"meta",label:a.label})})));e=Qb(Sb=b,Tb=c=h.id);V.fa(b,{id:c})}const g=yield zb(yield R("/api/minicraft/world",Object.assign({},ub,{body:Na({what:"data",world:c,data:yield d})})));b<0?T.push(g):Object.assign(T.find(h=>h.id===b),g);V.fa(c,{mod_l:g.modified,mod_r:g.modified})}catch(d){throw V.fa(b,{mod_r:0}),Error("Fehler beim Hochladen der Welt: "+d.message);}yield e}else V.fa(b,{mod_l:a.remote})}());
let Y=Oa(L.getItem("minicraft.config")||null);if(Y&&Y.worlds&&Y.version.startsWith("0.9.")){const a=new ab(Y.worlds.map(b=>"minicraft.world."+b.id));for(const b of db(L))b.startsWith("minicraft.world.")&&!a.has(b.split(":",1)[0])&&Pa(b)}
const $b={init:()=>{let a=!1;var b={sa:!1,Ia:1,Fa:3,$:4,V:1,Oa:120,na:64,xa:0,worlds:[]};if(Y){let c=Y.pixel_grouping;c!=null&&(b.Ia=c);(c=Y.mouse_sensitivity)!=null&&(b.Fa=c);b.$=Y.resolution_scaling;(c=Y.textures)!=null?b.V=c:b.V=Y.flag_textures?1:0;b.Oa=Y.view_angle;b.na=Y.view_distance;(c=Y.world_last)!=null&&(b.xa=c);(c=Y.worlds)?b.worlds=c:L.getItem("minicraft.world.0:meta")&&(b.worlds[0]={id:0,label:(sb("Es wurde eine namenlose lokale Welt gefunden. Wie soll sie hei\u00dfen?","")||"Unbekannte Welt").substring(0,
16),mod_l:Ka.now(),mod_r:0},a=!0);Y=null}b=Object.assign({},{account:{label:"",rank:0},config:b,nb:b,da:null,cursor:null,ja:qa.innerHeight,aa:qa.innerWidth,G:[{id:0,Kb:0,type:1}],wb:!0,ya:!0,ga:null,xb:[]},Wb(b));return a?(b.nb=null,$b.mb(b)):b},mb:a=>{const b=a.config;if(b===a.nb)return a;M("minicraft.config",Na({version:"0.11.9",pixel_grouping:b.Ia,mouse_sensitivity:b.Fa,resolution_scaling:b.$,textures:b.V,view_angle:b.Oa,view_distance:b.na,world_last:b.xa,worlds:b.worlds}));return Object.assign({},
a,{nb:b})},cc:(a,b)=>$b.pa(a,b(a.config)),pa:(a,b)=>Object.assign({},a,{config:Object.assign({},a.config,b)}),Va:(a,b)=>a.config.sa===b?a:$b.pa(a,{sa:b}),B:(a,b)=>Object.assign({},a,b),Xb:(a,b)=>(ra.activeElement.blur(),Object.assign({},a,{G:[...a.G,Object.assign({},{id:J(-1,...a.G.map(c=>c.id))+1,Kb:1,type:0},b)]})),Zb:(a,b)=>Object.assign({},a,{G:a.G.filter(c=>c.id!==b)}),Yb:(a,b)=>a.G[a.G.length-1].id===b?a:Object.assign({},a,{G:[...a.G.filter(c=>c.id!==b),a.G.find(c=>c.id===b)]}),Pb:(a,b)=>Object.assign({},
a,Wb(Object.assign({},a.config,{worlds:[...a.config.worlds,b]}))),Qb:(a,b)=>Object.assign({},a,Wb(Object.assign({},a.config,{worlds:a.config.worlds.filter(c=>c.id!==b)}))),fa:(a,b,c)=>Object.assign({},a,Wb(Object.assign({},a.config,{worlds:a.config.worlds.map(e=>e.id===b?Object.assign({},e,c):e)})))};let U,V;
const ac=(a,b=1,c=null)=>({amount:b,data:c,id:a}),bc=(a,b,c=a.c.amount)=>{if(b.c)a.c.id===b.c.id?(c=G(c,b.X-b.c.amount),a.c.amount-=c,b.c.amount+=c,a.c.amount<=0&&(a.c=null)):!(a.c.amount<=c&&a.c.amount<=b.X&&b.c.amount<=a.X)||a.filter&&!a.filter(b.c.id)||b.filter&&!b.filter(a.c.id)||([b.c,a.c]=[a.c,b.c]);else if(!b.filter||b.filter(a.c.id))a.c.amount<=c&&a.c.amount<=b.X?[b.c,a.c]=[a.c,b.c]:(c=G(c,b.X),a.c.amount-=c,b.c=ac(a.c.id,c),a.c.amount<=0&&(a.c=null))},cc=(a,b)=>{for(const c of a)if(c.c&&
c.c.id===b.id){const e=G(b.amount,c.X-c.c.amount);c.c.amount+=e;if((b.amount-=e)<=0)return null}for(const c of a)if(!c.c&&(!c.filter||c.filter(b.id)))if(a=G(b.amount,c.X),a<=b.amount){if(c.c=ac(b.id,a),(b.amount-=a)<=0)return null}else return c.c=b,null;return b},dc=(a,b)=>({jb:0,yb:0,kb:0,U:0,oa:0,za:0,ha:0,W:-1,ia:0,Aa:null,Ba:null,l:1,Ib:20,H:Ra(36).fill(null).map(()=>({c:null,filter:null,X:64})),ab:0,name:b.label||"Spieler",J:a.La,K:a.Ma,L:a.Na,Nb:0,Ob:0,N:0,ua:0,ka:0,la:0,ma:0}),fc=(a,b)=>{b=
G(5,b*.01);a.ka-=a.ka*.1*b;a.la-=a.la*.1*b;a.ma-=a.ma*.1*b;a.ka+=(Ba(a.U)*a.jb+Ca(a.U)*a.kb)*b;a.la+=a.yb*b;a.ma+=(-Ca(a.U)*a.jb+Ba(a.U)*a.kb)*b;ec(a,a.Nb*b*1.5,a.Ob*b*1.5);a.J+=a.ka*b;a.K+=a.la*b;a.L+=a.ma*b},ec=(a,b,c)=>{a.U=(a.U+b+ta*100)%(ta*2);a.oa=J(-ua,G(ua,a.oa+c))},hc=a=>{a+=32;a>33&&a<39?a++:a>38&&a<44?a+=2:a>43&&a<127?a+=3:a>126&&a<55258?a+=37:a>55295&&(a+=8485);return Ia(a)},ic=a=>a-(a>63743?8517:a>159?69:a>46&&a<130?35:a>40&&a<46?34:a>34&&a<40?33:32),kc=()=>{var a=jc;const b=a.length,
c=new bb,e=p=>{n=n<<1|p&1;++q===15&&(r+=hc(n),n=q=0)},d=()=>{for(let p=0;p<k;++p)e(0)},g=p=>{e(p);e(p>>1);e(p>>2);e(p>>3);e(p>>4);e(p>>5);e(p>>6);e(p>>7)},h=()=>{--v===0&&(v=1<<k++)},l=()=>{if(x)x=!1;else{let p=t.id;for(let F=0;F<k;F++)e(p>>F)}};let f=a[0],r="",n=0,q=2,k=2,v=2,u=2,t={id:u++,Ta:new bb},x=!0;g(f);c.set(f,t);for(let p=1;p<b;++p){const F=t.Ta.get(f=a[p]);F?t=F:(l(),c.has(f)||(h(),d(),g(f),c.set(f,{id:u++,Ta:new bb}),x=!0),t.Ta.set(f,{id:u++,Ta:new bb}),t=c.get(f),h())}l();c.has(f)||(h(),
d(),g(f));h();e(1);--k;d();return r+=hc(n<<15-q)},lc=a=>{var b=jc;if(!a)return null;const c=a.length,e=()=>{q+=(u>>--t&1)<<k++;t===0&&(t=15,u=ic(a.charCodeAt(v++)))};let d=[0,1],g=1,h=3,l=2,f=null;var r=null;let n=0,q=0;r=2;let k=0,v=0,u=ic(a.charCodeAt(v++)),t=15;for(;k<r;)e();if(q===1)return null;for(q=k=0;k<8;)e();f=[q];d[2]=f;for(b[n++]=q;v<=c;){r=l;for(q=k=0;k<r;)e();if(q===0){for(q=k=0;k<8;)e();d[h]=[q];q=h++;--g===0&&(g=1<<l++)}else if(q===1)return b;r=q<d.length?d[q]:f.concat(f[0]);for(let x=
0;x<r.length;x++)b[n++]=r[x];d[h++]=f.concat(r[0]);f=r;--g===0&&(g=1<<l++)}return null},mc=new bb,nc=new $a(1024),jc=new Za(nc.buffer),oc=new bb,pc=a=>{const b={ba:null,Sa:null,busy:!1,ca:null,Ua:null,Ca:0,A:!1,ra:!U.Qa.find(c=>c.id===a).writable,Ya:0,Za:0,$a:0,id:a,Ga:0,Ha:0,M:0,La:.5,Ma:8.5,Na:.5,time:0,tb:0};mc.set(a,b);V.B({xb:[...mc.keys()]});return b},Bc=(a,b,c,e)=>c<0||c>63?0:a.ba[(b<<a.M+4|e)<<6|c],Cc=(a,b,c,e)=>{const d=a.M;a.ba[(b<<d+4|e)<<6|c]=0;a.ca[(b>>4<<d|e>>4)<<2|c>>4].qa=!0},Dc=(a,
b,c,e,d)=>{const g=a.M,h=(b<<g+4|e)<<6|c;if(a.ba[h]>0)return!1;a.ba[h]=d;return a.ca[(b>>4<<g|e>>4)<<2|c>>4].qa=!0},Gc=(a,b,c)=>{m(function*(){a.ca&&(yield Ec(a,b));var e=1<<(a.M=c);const d=a.ca=[];for(let g=0;g<e;++g)for(let h=0;h<e;++h)for(let l=0;l<4;++l)d.push({qa:!1,l:!1,x:g,y:l,z:h,Ra:0,ib:0});e<<=c+12+2;a.ba===null||a.ba.length<e?a.Sa=new $a((a.ba=new Za(e)).buffer):a.Sa.fill(0);Fc(a,b,!0)}())},Fc=(a,b,c)=>{const e=J(G(b.K,63),0)>>4,d=E(b.J)>>4;b=E(b.L)>>4;if(c||a.Za!==e||a.Ga+a.Ya!==d||a.Ha+
a.$a!==b)c=1<<a.M,a.Za=e,a.Ga=d-(a.Ya=(65536+d)%c),a.Ha=b-(a.$a=(65536+b)%c),Hc(a);a.busy||Ic(a,!1)},Hc=a=>{const b=a.Ya,c=a.Za,e=a.$a,d=a.M,g=`${d} ${b} ${e} ${c}`;let h=oc.get(g);if(h==null){const l=1<<d,f=wb(l*.5);oc.set(g,h=a.ca.map(({x:r,y:n,z:q},k)=>{let v=wb(r-b),u=wb(q-e),t=wb(r-b-l),x=0,p=0;t<v&&(v=t,x=-l);(t=wb(r-b+l))<v&&(v=t,x=l);(t=wb(q-e-l))<u&&(u=t,p=-l);(t=wb(q-e+l))<u&&(u=t,p=l);return{ob:v+u+wb(n-c),Bb:k,Ga:x,Ha:p}}).filter(({ob:r})=>r<=f).sort((r,n)=>r.ob-n.ob))}a.Ua=h;a.Ca=0},
Ec=(a,b)=>m(function*(){if(!a.ra&&a.A){a.A=!1;for(var c=Ka.now(),e=b.H.map(({c:d})=>d&&[d.id,d.amount,d.data]);e.length>0&&e[e.length-1]===null;)e.pop();M(`minicraft.world.${a.id}:meta`,Na({p:{h:b.Ib,i:e,m:b.l,p:[b.J,b.K,b.L,b.U,b.oa]},s:[a.La,a.Ma,a.Na],t:a.time,v:1}));yield K.all(a.ca.filter(d=>d.qa).map(d=>Jc(a,d)));V.fa(a.id,{mod_l:c})}}()),Lc=(a,b)=>{const c=Oa(L.getItem(`minicraft.world.${a.id}:meta`));if(c){const e=c.p,d=c.s,g=c.t;c.v!=null&&(e.i.forEach((h,l)=>{h&&(b.H[l].c=ac(h[0],h[1],h[2]))}),
b.Ib=e.h,b.l=e.m,b.J=e.p[0],b.K=e.p[1],b.L=e.p[2],b.U=e.p[3],b.oa=e.p[4],a.La=d[0],a.Ma=d[1],a.Na=d[2],g!=null&&Kc(a,g))}},Kc=(a,b)=>{a.time=b%24E3;a.tb=(b+6E3)/24E3%1},Mc=a=>m(function*(){const b=a.ca[a.Ua[a.Ca=0].Bb];var c=b.y;yield Mb(a.id,`${b.Ra}/${b.ib}`+(c>0?"/"+c:""));b.qa=!1;++b.Ra;return Ic(a,!1)}()),Jc=(a,b)=>{const c=a.Sa;var e=a.M;const d=b.y,g=(256<<e)-256;for(let h=0,l=-1,f=((b.x<<e+4|b.z)<<6|d)<<2;h<16;++h){for(e=0;e<16;++e)nc[++l]=c[f],nc[++l]=c[++f],nc[++l]=c[++f],nc[++l]=c[++f],
f+=13;f+=g}b.qa=!1;return Lb(a.id,`${b.Ra}/${b.ib}`+(d>0?"/"+d:""),kc())},Ic=(a,b)=>m(function*(){const c=a.ca,e=a.Ua,d=a.Ga,g=a.Ha,h=e.length;for(;a.Ca<h;){var l=e[a.Ca++],f=c[l.Bb],r=f.l,n=f.x;const u=f.y;var q=f.z,k=d+l.Ga+n;const t=g+l.Ha+q;if(!r||k!==f.Ra||t!==f.ib){f.l=a.busy=!0;l=f.qa&&Jc(a,f);var v=a.id;k=f.Ra=k;f=f.ib=t;f=lc(yield Kb(v,`${k}/${f}`+(u>0?"/"+u:"")));yield l;a.busy=!1;if(r||u===0||f){l=a.Sa;k=a.M;v=(256<<k)-256;n=((n<<k+4|q)<<6|u)<<2;if(f)for(let x=0,p=-1;x<16;++x){for(r=0;r<
16;++r)l[n]=nc[++p],l[++n]=nc[++p],l[++n]=nc[++p],l[++n]=nc[++p],n+=13;n+=v}else for(q=0;q<16;++q){for(f=0;f<16;++f)l[n]=u>0?0:50397446,l[++n]=u>0?0:131843,r?(l[++n]=0,l[++n]=0,n+=13):n+=15;n+=v}if(!b)break}}}}());let Nc=null,Oc=null;
const Pc=new ab,Qc=a=>{if(a){const b=Oc=new Image;b.onload=()=>{if(Oc===b){var c=ra.createElement("canvas");c.width=16;c.height=416;c=c.getContext("2d");c.scale(1,-1);for(let e=0;e<26;++e)c.drawImage(b,0,e<<4,16,16,0,-(e<<4)-16,16,16);Nc=new $a(c.getImageData(0,0,16,416).data.buffer);for(const e of Pc)e.A=!0;Oc=null}};b.src=`${"/static/minicraft/"}textures/${a}.png`}else Nc=null},Sc=(a,b)=>{const c={Rb:b,lb:b.getContext("2d",{alpha:!1,desynchronized:!0}),zb:null,Ab:null,Eb:"",A:!1,Fb:0,pb:0,Sb:gb(()=>
(c.Fb=c.pb,c.pb=0),1E3),P:a};Pc.add(c);Rc(c);return c},Tc=(a,b)=>{++a.pb;const c=a.lb;var e=a.zb;const d=a.Ab,g=a.P,h=g.config,l=g.Ea,f=g.g,r=g.Ja,n=g.Ka,q=g.world;var k=0;if(!g.u||a.A){a.A=!1;var v=h.Ia;const od=h.na;var u=f.U,t=f.oa;const pd=f.ha,qd=f.ia,Sa=f.l;var x=f.J;k=f.K;var p=f.L;const rd=l?f.W:-1,sd=q.ba;var F=q.M;const td=Nc!==null;var lb=1/r,va=1/n;const da=r>>1,la=n>>1,qc=G(r,n),rc=qc>32,sc=Ba(u);u=Ca(u);const tc=Ba(-t);t=Ca(-t);var Ea=h.Oa/45;const ud=lb*(r<n?Ea*r*va:Ea);lb=va*(n<r?
Ea*n*lb:Ea);x+=65536;va=k+65536;p+=65536;Ea=x%1;const vd=va%1,wd=p%1;F=4+F;const Fa=(1<<F)-1;v=v<r?v:1;const xd=r-v;let uc=f.l===1?6:4,Ta=f.ha=f.ia=f.za=0,vc=0;f.W=-1;k=k<0||k>=64?0:Bc(q,x&Fa,va&63,p&Fa);if(Sa!==2&&k>0)f.ha=x&Fa,f.W=va&63,f.ia=p&Fa,f.za=6,d.fill(Hb[k]|4278190080);else{for(let Ua=0;Ua<n;++Ua){var mb=(la-Ua)*lb;const wc=mb*tc-t;var Cb=mb*t+tc;mb=Cb*u;Cb*=sc;let ea=0,Ga=!1;var Va=!1;a:for(let N=0;N<r;N+=v)for(let W=Va?1:0;W<v;++W){if(v<2)var H=N;else if(N===0)H=W===0?0:W===1?v:W-1,Ga=
W===1;else if(N<xd)H=(Ga=W===1)?N+v:N+W-1;else{if((H=W===0?N-1:N+W)>=r)break a;Ga=!1}var O=(H-da)*ud;Va=mb+sc*O;const xc=Cb-u*O,yd=vc;O=16757124;let nb=1,yc=od,ob=0;Sa===2&&k>0&&(ob=ya()*10);for(let Db=0;Db<3;++Db){const P=(yd+Db)%3;let X=xc;var I=wd;P===0&&(X=Va,I=Ea);P===1&&(X=wc,I=vd);var ma=-1/X;X>0&&(I=1-I,ma*=-1);const pb=Va*ma,wa=wc*ma;ma*=xc;const zc=Da(pb*pb+wa*wa+ma*ma);let Wa=x+pb*I-(P===0&X<0|0),Xa=va+wa*I-(P===1&X<0|0),Ya=p+ma*I-(P===2&X<0|0);I*=zc;for(let Eb,Fb,Gb,Q;I<yc;Wa+=pb,Xa+=
wa,Ya+=ma,I+=zc)if(!(Sa===2&&I<ob))if(Xa<65536){if(wa<0)break}else if(Xa>=65600){if(wa>0)break}else if((Q=sd[((Eb=Wa&Fa)<<F|(Gb=Ya&Fa))<<6|(Fb=Xa&63)])!==0){Sa!==2&&Ua===la&&H===da&&I<=uc&&(f.ha=Eb,f.W=Fb,f.ia=Gb,f.za=X<0|P<<1,uc=I);if(td){--Q;P===1?Q===6?Q=25:Q===13?Q=4:Q===1&&wa>0&&(Q=2):Q===1&&(Q=24);const Ac=Nc[Q<<8|((P===1?Ya:Xa)*16&15)<<4|(P===1?Wa:(X>0?Wa-Ya:Ya-Wa)+65536)*16&15];if(Ac>>>24===0)continue;O=Ac&16777215}else O=Hb[Q];yc=I;nb=(P===0?.8:P===2?.6:X>0?.4:1)+(Fb!==rd||Eb!==pd||Gb!==
qd?0:.2);vc=P;break}else Sa===2&&I<ob&&(ob=I)}O=4278190080|G((O>>16)*nb,255)<<16|G((O>>8&255)*nb,255)<<8|G((O&255)*nb,255);if(Va=(Ga=Ga&&(Ua!==la||H<da||H>da+v))&&ea===O){if(v>6){d.fill(ea,Ta+N+1,Ta+N+v+1);break}H=Ta+N+1;d[H]=ea;d[++H]=ea;if(v<3)break;d[++H]=ea;if(v<4)break;d[++H]=ea;if(v<5)break;d[++H]=ea;if(v<6)break;d[++H]=ea;break}if(Ga||H===0)ea=O;d[Ta+H]=O}Ta+=r}l&&!rc&&(d[r*la+da]^=16777215)}c.putImageData(e,0,0);l&&rc&&(e=G(za(qc*.05),8),c.fillRect(da-e,la-1,e<<1,2),c.fillRect(da-1,la-e,2,
e-1),c.fillRect(da-1,la+1,2,e-1))}a.Eb=g.Xa?`minicraft ${"0.11.9"} ${vb(a.Fb,"\u00a0")} fps, T: ${vb(q.tb*24,"0")}:${vb(q.tb*24%1*60,"0")}; ${g.u&&b%1E3<500?"":q.time}
R: ${r}x${n} (x${h.$}), D: ${h.na}, C: ${q.Ca}/${q.Ua.length}, M: ${wb(1<<4+q.M)*64>>10}k
E: 0/0, M: ${f.l}, I: ${k}

Position: ${f.J.toFixed(2)} ${f.K.toFixed(2)} ${f.L.toFixed(2)}
Angle: ${(f.U*xa).toFixed(2)} ${(f.oa*xa).toFixed(2)}
Focus: ${f.W<0?"":f.ha+" "+f.W+" "+f.ia+" "+"WEBTSNI"[f.za]+": "+Ab[Bc(q,f.ha,f.W,f.ia)]}
Chunk abs: ${E(f.J)>>4} ${E(f.L)>>4} ${E(f.K)>>4} rel: ${q.Ya} ${q.$a} ${q.Za}`:""},Rc=a=>{const b=a.Rb,c=a.P;a.Ab=new $a((a.zb=a.lb.createImageData(b.width=c.Ja,b.height=c.Ka)).data.buffer);const e=c.Ja*c.config.$/c.ta,d=c.Ka*c.config.$/c.ta;b.style.width=e+"px";b.style.height=d+"px";b.style.left=Aa((c.cb-e)/2)+"px";b.style.top=Aa((c.eb-d)/2)+"px";a.lb.fillStyle="rgba(255,255,255,.5)"};let Uc=0;
const Xc=(a,b,{config:c,account:e})=>{const d=pc(c.xa),g=dc(d,e);Lc(d,g);const h={config:c,Cb:0,Db:0,Xa:!1,Ea:!0,u:!0,Gb:a,ea:0,Z:new ab,qb:"",j:0,T:[],g,rb:null,o:null,ta:1,cb:1,eb:1,Ja:0,Ka:0,fb:0,Mb:0,gb:0,Vb:gb(()=>{var l;(l=h.u)||(d.A=!0,Kc(d,d.time+1),Fc(d,g,!1),l=void 0);return l},50),Pa:b,world:d};Vc(h,null);Wc(h);return h},Wc=a=>{m(function*(){if(!a.config.sa)return a.Gb.requestPointerLock().catch(()=>{})}())},Yc=(a,b)=>a===b?0:.1-a*.2,Zc=a=>{a.g.jb=Yc((a=a.Z).has(-12)||a.has(65),a.has(-13)||
a.has(68))},$c=a=>{a.g.yb=Yc((a=a.Z).has(-15)||a.has(16),a.has(-14)||a.has(32))},ad=a=>{a.g.kb=Yc((a=a.Z).has(-11)||a.has(83),a.has(-10)||a.has(87))},bd=a=>{a.g.Nb=Yc(a.Z.has(-18),a.Z.has(-19))},cd=a=>{a.g.Ob=Yc(a.Z.has(-17),a.Z.has(-16))},ed=(a,b,c)=>{if(!a.world)return!1;const e=a.Z;var d=a.g;if(c){if(e.has(b))return!1;e.add(b);var g=d.ha,h=d.W;c=d.ia;switch(b){case -18:case -19:bd(a);break;case -17:case -16:cd(a);break;case -1:!a.world.ra&&d.l!==2&&h>=0&&(d.ab===0?d.l===0&&(b=Bc(a.world,g,h,c),
b===2?b=3:b===1&&(b=4),b===6||b!==8&&b!==13&&cc(d.H,ac(b,1))!==null)||(Cc(a.world,g,h,c),d.W=-1):dd(a,[g,h,c],!1));break;case -2:case 71:if(h>=0){const l=Bc(a.world,g,h,c);c=d.H.slice(0,9);h=c.findIndex(f=>f.c!==null&&f.c.id===l);h>=0?d.N=h:d.l===1&&(c[d.N].c&&(c=c.findIndex(f=>f.c===null),c>=0&&(d.N=c)),d.H[d.N].c=ac(l));d.ua=a.ea}break;case -3:if(!a.world.ra&&d.l!==2&&h>=0)if(d.ab===0){if(b=d.H[d.N],b.c){switch(d.za){case 0:--g;break;case 1:++g;break;case 2:--h;break;case 3:++h;break;case 4:--c;
break;case 5:++c}h>=0&&h<64&&Dc(a.world,g&(1<<4+a.world.M)-1,h,c&(1<<4+a.world.M)-1,b.c.id)&&d.l!==1&&--b.c.amount<=0&&(b.c=null)}}else dd(a,[g,h,c],!0);break;case -4:d.N=(d.N+9-1)%9;d.ua=a.ea;break;case -5:d.N=(d.N+1)%9;d.ua=a.ea;break;case 27:a.j===0&&(a.u=!0,a.j=1);break;case -15:case -14:case 16:case 32:$c(a);break;case 49:case 50:case 51:case 52:case 53:case 54:case 55:case 56:case 57:d.N=b-49;d.ua=a.ea;break;case -12:case -13:case 65:case 68:Zc(a);break;case 69:if(a.j===0){a.j=3;for(const l of e)ed(a,
l,!1)}break;case 70:a.Pa.Hb();break;case 80:a.world&&(a.u=!0);break;case 81:d=d.H[d.N];if(e.has(17)||d.c&&--d.c.amount<=0)d.c=null;break;case -11:case -10:case 83:case 87:ad(a);break;case 84:if(a.j===0){a.j=2;for(const l of e)ed(a,l,!1)}break;case 112:a.Ea=!a.Ea;break;case 114:a.Xa=!a.Xa;case 116:case 122:case 123:break;default:return!1}}else{if(!e.delete(b))return!1;switch(b){case -15:case -14:case 16:case 32:$c(a);break;case -12:case -13:case 65:case 68:Zc(a);break;case -11:case -10:case 83:case 87:ad(a);
break;case -18:case -19:bd(a);break;case -17:case -16:cd(a)}}a.qb=[...e].join();return!0},fd=(a,b)=>(b=b.startsWith("~")?a+S(b.slice(1)):S(b),isNaN(b)?a:b),hd=(a,b)=>{var c=a.g,e=a.world;if(b)if(b.charAt(0)==="/"){b=b.slice(1).split(" ");const d=b.shift();switch(d){case "clear":a.T=[];break;case "clearinv":for(const g of c.H)g.c=null;Z(a,"Inventar geleert",!0);break;case "gamemode":case "gm":b=S(b[0]);!isNaN(b)&&b>=0&&b<3&&b%1===0?(c.l=b,Z(a,"Spielmodus gesetzt auf: "+b,!0)):Z(a,"Spielmodus muss in 0..2 sein!");
break;case "give":if(b.length===0){Z(a,"/give <id> [Anzahl]\n"+Ab.join(" "));break}e=Ab.indexOf((b[0]||"").toLowerCase());e=e>=0?e:S(b[0]);b=S(b[1]||1);!isNaN(e)&&e>0&&e<25&&e%1===0?!isNaN(b)&&b>0&&b%1===0?Z(a,cc(c.H,ac(e,b))?"Inventar ist voll!":`${"Items gegeben"} ${b} ${Bb[e]}`,!0):Z(a,"Anzahl muss mindestens 1 sein!"):Z(a,"Ung\u00fcltiger Blocktyp!");break;case "help":Z(a,"Befehle: clear, clearinv, gamemode, give, help, load, me, save, spawn, teleport, time, version");break;case "load":Ic(e,!0).then(()=>
{a.o.A=!0;Z(a,"Chunks geladen.",!0)});break;case "me":Z(a,c.name+" "+b.join(" "),!0);break;case "save":if(a.world.ra){Z(a,"Fehlende Berechtigung!");break}Ec(a.world,a.g);Z(a,"Spiel gespeichert.",!0);break;case "spawn":if(a.world.ra){Z(a,"Fehlende Berechtigung!");break}e.La=c.J;e.Ma=c.K;e.Na=c.L;Z(a,"Startpunkt aktualisiert.",!0);break;case "teleport":case "tp":b.length===0?(c.J=e.La,c.K=e.Ma,c.L=e.Na,a.o.A=!0,Z(a,"Zum Startpunkt teleportiert.",!0)):b.length===3?(Z(a,"Teleportiert zu"+` ${c.J=fd(c.J,
b[0])} ${c.K=fd(c.K,b[1])} ${c.L=fd(c.L,b[2])}`,!0),a.o.A=!0):Z(a,"Pech!");c.ka=0;c.la=0;c.ma=0;break;case "time":c=b[1];if(!c){Z(a,"Parameter fehlt!");break}if(c==="day")c=1E3;else if(c==="night")c=13E3;else if(isNaN(c=E(S(c))))break;switch(b[0]){case "add":c+=e.time;case "set":Kc(e,c);Z(a,"Zeit gesetzt auf: "+e.time,!0);break;default:Z(a,"Ung\u00fcltiger Befehl: time "+b[0])}break;case "version":Z(a,"minicraft 0.11.9");break;case "_w":V.Xb({type:b[0]==="m"?1:0});break;case "/exit":c.ab=0;Z(a,"Normaler Mausmodus.",
!0);break;case "/expand":a.g.Aa&&a.g.Ba?e=!0:(Z(a,"Auswahl erforderlich!"),e=!1);e&&(b[0]==="vert"?(c.Aa[1]=0,c.Ba[1]=63,Z(a,"Auswahl erweitert.",!0)):Z(a,'Nur "vert" wird unterst\u00fctzt!'));break;case "/pos1":case "/pos2":dd(a,[E(c.J),E(c.K),E(c.L)],d==="/pos2");break;case "/regen":if(a.world.ra){Z(a,"Fehlende Berechtigung!");break}Mc(e).then(()=>{a.o.A=!0;Z(a,"Chunk neu generiert.",!0)});break;case "/show":Z(a,`${"Erster"}: ${c.Aa?c.Aa.join(" "):"nichts"}, ${"Zweiter"}: ${c.Ba?c.Ba.join(" "):
"nichts"}`);break;case "/wand":c.ab=1;Z(a,"Auswahl mit Maustasten.",!0);break;default:Z(a,"Ung\u00fcltiger Befehl: "+d)}}else{const d=Z(a,`<${c.name}> `+b);Vc(a,b).then(g=>{g&&gd(a,d)})}},Z=(a,b,c=!1)=>{const e=++Uc;(a.T=a.T.slice(-49)).push({id:e,Jb:c,time:pa(),value:b});return e},gd=(a,b)=>{const c=a.T.findIndex(e=>e.id===b);c>=0&&a.T.splice(c,1)},dd=(a,b,c)=>{c?a.g.Ba=b:a.g.Aa=b;Z(a,`${c?"Zweiter Auswahlpunkt":"Erster Auswahlpunkt"}: ${b.join(" ")}`,!0)},Vc=(a,b)=>(hb(a.rb),a.rb=fb(Vc,5E3,a,null),
(b?R("/api/chat",Object.assign({},ub,{body:Na({msg:b})})):R("/api/chat")).then(c=>c.ok&&c.text()).then(c=>{if(c){c=c.split("\n").filter(Boolean);for(const e of c)e.startsWith("<")&&Z(a,e);return c.length>0}return!1}).catch(()=>!1)),id=({id:a,O:b})=>(y("div[className=bitmap]",{S:{backgroundImage:`url(${"/static/minicraft/"}textures/${b}.png)`,backgroundPositionY:100-a*100+"%"}}),null);
function jd({amount:a,l:b,id:c,O:e}){y("div[className=stack]",{title:Bb[c]+(b===1?` (${Ab[c]}, ${c})`:"")});return[B(id,{id:c,O:e}),a!==1&&C("div[className=amount]",{innerText:a})]}
function kd({g:a,O:b,va:c}){y("div[className=bar]",{ontouchstart:A(d=>{a.N=Number(d.target.closest("[data-slot]").dataset.slot);a.ua=d.timeStamp}),S:{opacity:J(.5,G(1,1-(c-a.ua-5E3)*5E-4))}});const e=a.l;return a.H.slice(0,9).map(({c:d},g)=>C("div",{D:{slot:g},F:{active:g===a.N}},[d&&B(jd,{amount:d.amount,data:d.data,l:e,id:d.id,O:b})]))}
function ld({Ub:a,O:b}){y("div[className=grid]",{onclick:({target:c})=>{(c=c.closest("[data-id]"))&&bc({c:ac(S(c.dataset.id)),filter:null,X:64},a)}});return Ab.map((c,e)=>e>0&&C("div",{D:{id:e}},[B(jd,{amount:1,data:null,l:1,id:e,O:b})]))}
function md({P:a,O:b}){const c=fa(()=>({c:null,filter:null,X:64})),e=a.g.l;y("div[className=menu overlay inventory]",fa(()=>({onclick:({target:d})=>{if(d.className==="menu overlay inventory")c.c?c.c=null:(a.j=0,a.u=!1,Wc(a));else if(d=d.closest("[data-slot]"))d=a.g.H[S(d.dataset.slot)],c.c?bc(c,d):d.c&&bc(d,c)},oncontextmenu:({target:d})=>{if(d.className==="menu overlay inventory")c.c?--c.c.amount<=0&&(c.c=null):(a.j=0,a.u=!1,Wc(a));else if(d=d.closest("[data-slot]"))d=a.g.H[S(d.dataset.slot)],c.c?
bc(c,d,1):d.c&&bc(d,c,za(d.c.amount/2))}})));return[C("div[className=window]",null,[C("h2[innerText=Inventar]"),e===1&&B(ld,{Ub:c,O:b}),C("div[className=grid]",null,a.g.H.map(({c:d},g)=>C("div",{D:{slot:g},F:{first:g<9}},[d&&B(jd,{amount:d.amount,data:d.data,l:e,id:d.id,O:b})])))]),c.c&&C("div[className=hand]",{S:{transform:`translate(${a.Cb}px, ${a.Db}px)`}},[B(jd,{amount:c.c.amount,data:c.c.data,l:0,id:c.c.id,O:b})])]}
const nd=({I:{Jb:a,time:b,value:c},va:e})=>(y(a?"div[className=minor]":"div",{innerText:c,S:{opacity:G(1,1-(e-b-4500)*.001)}}),null);function zd({T:a,va:b}){y("div[className=messages]");const c=b-5E3;return[oa(nd,a.slice(-10).filter(e=>e.time>c),{va:b})]}function Ad({I:a,pa:b,current:c}){y("button",{disabled:a.id===c,innerText:`${a.label} (${a.owner})`,onclick:()=>{b({V:a.id})}});return null}
function Bd({config:a,P:b,wa:c}){b&&z(()=>{Ec(b.world,b.g)});const e=V.pa,[d,g]=ka(!1),h=ca(()=>d?R("/static/minicraft/textures.json").then(zb).catch(()=>null):K.resolve(null),[d],null);y("div[className=menu overlay]");return[C("h1",{innerText:d?"Oberfl\u00e4chen":"Einstellungen"}),C("center",null,[C("button",{innerText:b&&!d?"Zur\u00fcck zum Spiel":"Zur\u00fcck",onclick:()=>{d?g(!1):b?(b.j=0,b.u=!1,Wc(b)):c(2)}})]),!d&&C("div[className=settings]",null,[C("button[innerText=Oberfl\u00e4chen...]",{onclick:()=>
{g(!0)}}),C("label[innerText=Aufl\u00f6sung:]",null,[C("input[type=range][min=1][max=100][step=1]",{value:101-a.$,onchange:l=>e({$:101-Number(l.target.value)})})]),C("label[innerText=Blickwinkel:]",null,[C("input[type=range][min=1][max=180][step=1]",{value:a.Oa,onchange:l=>e({Oa:Number(l.target.value)})})]),C("label[innerText=Sichtweite:]",null,[C("input[type=range][min=1][max=128][step=1]",{value:a.na,onchange:l=>e({na:Number(l.target.value)})})]),C("label[innerText=Pixelgruppierung:]",null,[C("input[type=range][min=1][max=8][step=1]",
{value:a.Ia,onchange:l=>e({Ia:Number(l.target.value)})})]),C("label[innerText=Mausempfindlichkeit:]",null,[C("input[type=range][min=1][max=15][step=1]",{value:a.Fa,onchange:l=>e({Fa:Number(l.target.value)})})]),C("button[innerText=Projektseite]",{onclick:()=>{open("//github.com/L3P3/minicraft")}})]),b&&!d&&C("center",null,[C("button[innerText=Welt verlassen]",{onclick:()=>{c(2)}})]),d&&C("div[className=settings]",null,[C("button[innerText=Einfarbig]",{disabled:a.V===0,onclick:()=>{e({V:0})}}),h&&
oa(Ad,h,{pa:e,current:a.V})])]}const Cd=({I:{Jb:a,value:b}})=>(y(a?"div[className=minor]":"div",{innerText:b}),null);
function Dd({P:a,T:b}){const c=A({history:null,input:null});y("div[className=menu overlay terminal]",{onclick:e=>{e.target!==c.input&&c.input.focus()}});z(e=>{e&&fb(()=>c.history.scrollTop=1E9,0)},[b.length&&b[b.length-1].id]);return[A(C("div[className=toolbar]",null,[C("button[innerText=\u274c]",{onclick:()=>{a.j=0;a.u=!1;Wc(a)}})])),C("div[className=history]",{R:A(e=>{c.history=e})},[oa(Cd,b)]),A(C("input[enterkeyhint=send][mozactionhint=send][name=message][required]",{onkeydown:e=>{const d=e.keyCode;
e=e.target;d===13?(hd(a,e.value),e.value=""):d===27&&(a.j=0,a.u=!1,Wc(a))},R:e=>{c.input=e;fb(()=>e.focus(),0)}}))]}const Ed=[["pick",-2],["up",-14],["down",-15],["E",69],["T",84],["F1",112],["F3",114],["...",27]],Fd=[["up",-10],["down",-11],["left",-12],["right",-13],["center",-1]],Gd=[["up",-16],["down",-17],["left",-18],["right",-19],["center",-3]];
function Hd({P:a}){const b=a.Z,c=([e,d])=>C("div",{D:{code:d},F:{button:!0,[e]:!0,active:b.has(d)}});y("div[className=touch]",A({ontouchstart:e=>{let {code:d}=e.target.dataset;if(d!=null&&ed(a,d=S(d),!0)){const g=e.changedTouches[0].identifier,h=l=>{l.changedTouches[0].identifier===g&&(kb("touchend",h),ed(a,d,!1))};jb("touchend",h)}return!1}}));return[C("div[className=top]",null,Ed.map(([e,d])=>C(`div[innerText=${e}]`,{D:{code:d},F:{button:!0,active:b.has(d)}}))),C("div[className=move]",null,Fd.map(c)),
C("div[className=move sec]",null,Gd.map(c))]}
function Id({frame:a,Y:b,state:c,wa:e,Pa:d}){const g=c.config,h=pa(),l=ra.pointerLockElement===a,f=fa(()=>Xc(a,d,c));z(()=>{Jd.add(f);const n=u=>{if(f.j!==0)return!0;ra.pointerLockElement===a?ed(f,-1-u.button,u.type==="mousedown"):Wc(f);return!1},q=u=>{if(ra.pointerLockElement===a){var t=f.config.Fa*ta/(J(f.cb,f.eb)*f.ta);tb&&(f.Mb=u.timeStamp);ec(f.g,f.fb=u.movementX*t,f.gb=-u.movementY*t)}else t=f.Gb.getBoundingClientRect(),f.Cb=u.clientX-t.left,f.Db=u.clientY-t.top},k=u=>{V.Va(!1);if(f.j===0&&
!f.u&&D.abs(u.deltaY)>5)return u=u.deltaY>0?-5:-4,ed(f,u,!0),ed(f,u,!1),!1},v={passive:!0};a.addEventListener("mousedown",n);a.addEventListener("mouseup",n);a.addEventListener("mousemove",q,v);a.addEventListener("wheel",k,v);return()=>{a.removeEventListener("mousedown",n);a.removeEventListener("mouseup",n);a.removeEventListener("mousemove",q,v);a.removeEventListener("wheel",k,v);hb(f.rb);ib(f.Vb);Ec(f.world,f.g);mc.delete(f.world.id);V.B({xb:[...mc.keys()]});var u=f.o;Pc.delete(u);ib(u.Sb);return Jd.delete(f)}});
z(()=>{f.config=g;f.o&&(f.o.A=!0);const n=f.world,q=za(Ha(f.config.na/16*2+2));n.M!==q&&Gc(n,f.g,q)},[g]);z((n,q,k)=>{f.ta=k||1;f.cb=J(1,n);f.eb=J(1,q);q=f.config.$;n=za(f.cb*f.ta/q);q=za(f.eb*f.ta/q);if(n!==f.Ja||q!==f.Ka)f.Ja=n,f.Ka=q,f.o&&(f.o.A=!0,Rc(f.o))},[a.offsetWidth,a.offsetHeight,qa.devicePixelRatio,g.$]);z(()=>{b&&ed(f,b.code,b.state)},[b]);z(n=>{n||f.u||f.j!==0||(f.j=1,tb&&f.fb|f.gb&&f.Mb>h-100&&(ec(f.g,-f.fb,-f.gb),f.fb=f.gb=0,f.o.A=!0));f.u=!n},[g.sa&&f.j===0||l]);z(n=>l&&n&&ra.exitPointerLock(),
[f.u||f.j!==0]);h===f.ea||Kd||(f.world&&(f.ea&&!f.u&&fc(f.g,h-f.ea),f.o&&Tc(f.o,h)),f.ea=h);ja();const r=A({ub:1});g.V&&(r.ub=g.V);return[C("canvas",{R:A(n=>f.o=Sc(f,n))}),f.Ea&&f.j!==2&&B(zd,{T:f.T,va:h}),f.o&&f.Xa&&C("div[className=diagnostics]",{innerText:f.o.Eb}),g.sa&&B(Hd,{P:f,qb:f.qb}),f.Ea&&f.j!==3&&f.g.l!==2&&B(kd,{g:f.g,O:r.ub,va:h}),f.j===3&&B(md,{P:f,O:r.ub,va:h}),f.j===1&&B(Bd,{config:g,P:f,wa:e}),f.j===2&&B(Dd,{P:f,T:f.T})]}
function Ld({I:a,$b:b,ac:c,ga:e}){y("div",{F:{selected:a===b},onclick:()=>{c(a.id)}});b=`${a.local?"L":"_"}${a.local&&a.remote?a.local>a.remote?">":a.local<a.remote?"<":"=":"_"}${a.remote?a.public?"R":"r":"_"}`;e===a.id&&(b=`[${b}]`);return[C("span",{innerText:`${b} ${a.label}`,title:a.account_name?"Besitzer: "+a.account_name:"Nur lokale Welt"}),C("span",{innerText:yb(J(a.local,a.remote),!0)})]}
function Md({state:{account:a,config:b,da:c,wb:e,ya:d,ga:g,Qa:h,xb:l},wa:f}){y("div[className=menu]");const [r,n]=ka(b.xa),q=r!==Sb?r:(n(Tb),Tb),k=fa(()=>h.find(p=>p.id===q)||null,[q,h]),[v,u]=ka(!1);k||u(!1);const [t,x]=ka(!1);l=!!k&&l.includes(q);return[C("h1[innerText=Welten]"),C("button[innerText=Aktualisieren][style=position:absolute;left:0;top:0;height:2rem][title=Liste neu laden]",{disabled:e||d||c!==null,onclick:Vb}),C("button[style=position:absolute;right:0;top:0;height:2rem]",{disabled:a.rank>
0,innerText:a.rank?a.label:"Anmelden",onclick:()=>{location.href="/account?redir=minicraft"}}),C("div[className=worlds]",null,[oa(Ld,h,{bc:Ka.now(),$b:k,ac:n,ga:g})]),C("center",null,[C("button[innerText=\u00d6ffnen]",{disabled:!k||l||k.local<2||k.remote>k.local,onclick:()=>{aa();V.pa({xa:k.id});f(0);ba()},title:k?l?"Die Welt ist schon ge\u00f6ffnet!":k.local<2?"Die Welt ist noch nicht heruntergeladen!":k.local<k.remote?"Die Welt wird noch geladen!":"Ausgew\u00e4hlte Welt betreten":"Keine Welt ausgew\u00e4hlt!"}),
C("button[innerText=Welt...]",{disabled:!k||v,onclick:()=>{u(!0)},title:k?l?"Die Welt ist schon ge\u00f6ffnet!":"Aktionen/Einstellungen zur Welt anzeigen":"Keine Welt ausgew\u00e4hlt!"})]),C("hr"),C("center",null,[C("button[innerText=Neue Welt]",{onclick:()=>{const p=sb("Name der neuen Welt:\n(max. 16 Zeichen)","Neue Welt");p&&(p.length>16?qb("Der Name ist zu lang!"):V.Pb({id:G(0,...b.worlds.map(F=>F.id))-1,label:p,mod_l:Ka.now(),mod_r:0}))}}),C("button[innerText=Einstellungen]",{onclick:()=>{f(1)}})]),
C("center",null,[C("small[innerText=Version 0.11.9 von L3P3]")]),v&&k&&C("div",{F:{"menu overlay advanced":!0,busy:t},onclick:p=>{p.target.className==="menu overlay advanced"&&u(!1)}},[C("div[className=window]",null,[C("h2",{innerText:`"${k.label}"`,title:k.id}),C("table",null,[!!k.account_name&&C("tr",null,[C("td[innerText=Besitzer:]"),C("td",{innerText:k.account_name})]),C("tr",null,[C("td[innerText=\u00c4nderung:]"),C("td",{innerText:yb(J(k.local,k.remote),!1)})])]),C("center",null,[C("button[innerText=Umbenennen]",
{disabled:t||l||!k.writable,onclick:()=>{const p=sb("Neuer Name der Welt:\n(max. 16 Zeichen)",k.label);!p||p===k.label||p.length>16||(k.local&&V.fa(k.id,{label:p}),k.remote&&(x(!0),R("/api/minicraft/world",Object.assign({},ub,{body:Na({what:"meta",world:k.id,label:p})})).then(zb).catch(F=>{qb("Fehler beim Bearbeiten der Welt: "+F.message)}).then(()=>{x(!1)})))},title:k.writable?l?"Die Welt ist schon ge\u00f6ffnet!":"Welt-Namen \u00e4ndern":"Fehlende Berechtigung!"}),C("button",{disabled:t||l||!k.local&&
!k.writable,innerText:k.local?"L\u00f6schen (lokal)":"L\u00f6schen",onclick:()=>{rb('Welt "'+k.label+'" wirklich l\u00f6schen?')&&(k.local?(Pb(k.id),V.Qb(k.id)):(x(!0),R("/api/minicraft/world",{method:"DELETE",headers:{"Content-Type":"application/json"},body:Na({what:"world",world:k.id})}).then(p=>(zb(p),aa(),n(null),u(!1),Vb(),x(!1),ba())).catch(p=>{qb("Fehler beim L\u00f6schen der Welt: "+p.message);x(!1)})))},title:l?"Die Welt ist schon ge\u00f6ffnet!":k.local||k.writable?"Welt l\u00f6schen":"Fehlende Berechtigung!"})]),
C("center",null,[C("button",{disabled:t||!k.remote||!k.writable,innerText:`${"\u00d6ffentlich"}: ${k.public?"Ja":"Nein"}`,onclick:()=>{x(!0);R("/api/minicraft/world",Object.assign({},ub,{body:Na({what:"meta",world:k.id,public:!k.public})})).then(p=>(p=zb(p),aa(),Vb(),x(!1),ba(),p)).catch(p=>{qb("Fehler beim Bearbeiten der Welt: "+p.message);x(!1)})},title:k.remote?k.writable?k.public?"Welt privat machen":"Welt ver\u00f6ffentlichen":"Fehlende Berechtigung!":"Die Welt ist nicht hochgeladen!"}),C("button",
{disabled:t||!T||l||k.local>0&&k.remote>0||!k.remote&&!a.rank,innerText:k.local?T&&k&&!k.remote?"Hochladen":"\u00dcbertragen":"Herunterladen",onclick:()=>{k.local?k.remote||V.fa(k.id,{mod_r:1}):V.Pb({id:k.id,label:k.label,mod_l:1,mod_r:k.remote})},title:T?k.local?k.remote?"Die Welt ist schon auf beiden Seiten vorhanden!":l?"Die Welt ist schon ge\u00f6ffnet!":a.rank?"Welt auf den Server hochladen":"Nicht angemeldet!":"Welt von Server herunterladen":"Liste wird noch geladen!"})])])])]}
function Nd({Y:a,state:b,Pa:c,hb:e}){const [d,g]=ka(2);z(()=>{c.Wb(d===0?b.Qa.find(l=>l.id===b.config.xa).label+" \u2013 minicraft":"minicraft")},[d]);const h=y("div[className=game]");return[(d===2||d===1)&&B(Md,{state:b,wa:g}),d===1&&B(Bd,{config:b.config,P:null,wa:g}),d===0&&B(Id,{frame:h,Y:a,state:b,wa:g,Pa:c,hb:e}),d===2&&b.da&&C("div[style=position:absolute;bottom:0;left:0;color:yellow]",{title:b.da},[C("span[innerText=Verbindungsfehler. ]"),C("button[innerText=Nochmal probieren]",{onclick:()=>
{V.B({da:null})}})])]}const Od="nwse-resize ns-resize nesw-resize ew-resize move ew-resize nesw-resize ns-resize nwse-resize".split(" ");let Pd=0;
const Qd={init:()=>Qd.sb({Wa:0,Da:0,height:0,Y:null,left:0,mode:Pd,title:"...",top:0,width:0},600,400),Hb:a=>Object.assign({},a,{mode:a.mode===0?1:0}),Tb:(a,b)=>a.Y&&a.Y.code===b.code&&a.Y.state===b.state?a:Object.assign({},a,{Y:b}),Lb:(a,b,c)=>Object.assign({},a,{left:J(0,G(b,U.aa-a.width)),top:J(0,G(c,U.ja-a.height))}),bb:(a,b)=>Object.assign({},a,b),sb:(a,b,c)=>Object.assign({},a,{Da:b=J(100,G(b,U.aa-a.left)),Wa:c=J(50,G(c,U.ja-a.top)),width:b,height:c}),Wb:(a,b)=>Object.assign({},a,{title:b})},
Rd=(a,b,c)=>{V.Yb(b);const e=c.target;if(e.className==="window borders"&&c.button===0){c.preventDefault();ra.activeElement.blur();var d,g;[d,g]=a;var h=c.clientX,l=c.clientY,f=h-d.left,r=l-d.top,n=f<8?0:f<d.width-8?1:2,q=r<8?0:r<d.height-8?1:2,k=n+q*3;e.style.willChange=k===4?"transform":"contents";V.B({cursor:Od[k]});var v=t=>{Kd=!0;aa();let x=t.clientX,p=t.clientY;a:if(k===4){if(t.type==="mouseup"){if(p<4){g.bb({left:0,top:0,width:U.aa,height:U.ja});break a}if(x<4){g.bb({left:0,top:0,width:za(U.aa/
2),height:U.ja});break a}if(x>U.aa-3){g.bb({left:za(U.aa/2),top:0,width:E(U.aa/2),height:U.ja});break a}}else if([t]=a,t.Da!==t.width||t.Wa!==t.height){g.sb(t.Da,t.Wa);const [F]=a;f=Aa(f*F.Da/t.width)}g.Lb(x-f,p-r)}else n!==0&&q!==0||g.Lb(n===0?(x=J(f,G(x,d.left+d.width-100+f)))-f:d.left,q===0?(p=J(r,G(p,d.top+d.height-50+r)))-r:d.top),g.sb(n===0?d.width+d.left+f-x:n===1?d.width:d.width-h+x,q===0?d.height+d.top+r-p:q===1?d.height:d.height-l+p);ba();Kd=!1},u=t=>{kb("mousemove",v,!0);kb("mouseup",u);
t.clientX===h&&t.clientY===l||v(t);V.B({cursor:null});e.style.willChange="auto"};jb("mousemove",v,!0);jb("mouseup",u)}},Sd=({height:a,left:b,mode:c,top:e,width:d},g)=>({F:{window:!0,borders:c===1},S:{display:c===2?"none":"block",height:c===0?"100%":a+"px",transform:c===0?"":`translate(${b}px, ${e}px)`,width:c===0?"100%":d+"px"},onmousedown:g}),Td=({title:a,hb:b})=>[C("div[className=window_title]",{innerText:a}),C("div[className=window_button]",{onclick:()=>V.Zb(b)})];
function Ud({I:{id:a,Kb:b,type:c},state:e}){Pd=b;const d=ha(Qd),[g,h]=d;z(()=>(Vd.set(a,h),()=>Vd.delete(a)));b=fa(()=>Rd.bind(null,d,a));y("div",fa(Sd,[g,b]));const l=ia(!0,!1);z((f,r)=>{l&&h.bb({left:J(0,G(g.left,f-g.width)),top:J(0,G(g.top,r-g.height)),width:G(f,J(100,g.Da,g.width)),height:G(r,J(50,g.Wa,g.height))})},[e.aa,e.ja]);return[c===1&&B(Nd,{Y:g.Y,state:e,Pa:h,hb:a}),g.mode!==0&&B(Td,{title:g.title,hb:a})]}const Jd=new ab,Vd=new bb;let Kd=!1,Wd=0,Xd=0;
function Yd(){[U,V]=ha($b);z(()=>{Ub(!0);let d=!1;onbeforeunload=onunload=onpagehide=onblur=()=>{if(!d){d=!0;for(const g of Jd)Ec(g.world,g.g);V.mb()}};onpageshow=onfocus=()=>{d=!1};onresize=()=>{Kd=!0;V.B({ja:qa.innerHeight,aa:qa.innerWidth});Kd=!1};gb(()=>(V.mb(),!Ja&&M("minicraft.lock",Ka.now())),500);jb("touchend",g=>{Wd=g.timeStamp},!0)});const a=A(d=>{if(d.target.tagName==="INPUT")return!0;Kd=!0;V.Va(!1);if(U.G.length>0){const g=Vd.get(U.G[U.G.length-1].id),h=d.type==="keydown";d.key!=="f"?
g.Tb({code:d.keyCode,state:h}):h&&g.Hb()}return Kd=!1}),b=A(()=>{V.Va(!0)}),c=A(d=>{d.timeStamp-Wd>999&&V.Va(!1)}),e=U.config.sa;z(()=>{e?(jb("mousedown",c,!0),jb("mouseup",c,!0),kb("touchstart",b,!0)):(kb("mousedown",c,!0),kb("mouseup",c,!0),jb("touchstart",b,!0))},[e]);z(Qc,[U.config.V]);z(()=>{hb(Xd);U.da||(Xd=fb(Zb))},[U.da,U.Qa]);y("",{onkeydown:a,onkeyup:a,oncontextmenu:xb,ondragstart:xb});return[oa(Ud,U.G,{state:U}),U.cursor&&C("div[className=cursormask]",{S:{cursor:U.cursor}})]}
function Zd(){close();return[C("h1[innerText=minicraft l\u00e4uft schon!]")]}if(window.SSR)na(Yd);else if(Ja){const a=new Ja("minicraft.lock"),b=fb(()=>Jb.then(()=>na(Yd)),100);a.addEventListener("message",c=>{c.data==="yes"?(hb(b),a.close(),na(Zd)):(a.postMessage("yes"),focus())});a.postMessage("anyone there?")}else{const a=S(L.getItem("minicraft.lock")),b=Ka.now()-1500;a>b?fb(()=>{na(S(L.getItem("minicraft.lock"))===a?Yd:Zd)},a-b):Jb.then(()=>na(Yd))};
