function m(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function g(h){h.done?d(h.value):Promise.resolve(h.value).then(b,c).then(g,e)}g(a.next())})}
const w=lui,y=w.defer,aa=w.defer_end,ba=w.hook_async,z=w.hook_dom,A=w.hook_effect,ea=w.hook_memo,fa=w.hook_model,ha=w.hook_prev,ia=w.hook_rerender,ja=w.hook_state,B=w.hook_static,ma=w.init,C=w.node,E=w.node_dom,na=w.node_map,oa=w.now,pa=window,qa=document,ra=navigator,F=Math,sa=F.PI,ta=sa*.5,wa=180/sa,xa=F.random,G=F.floor,ya=F.ceil,za=F.round,J=F.min,K=F.max,Aa=F.cos,Ba=F.sin,Fa=F.sqrt,Ga=F.log2,Ha=String.fromCharCode,Ia=pa.BroadcastChannel,Ja=Date,Ka=JSON,La=Promise,Ma=Ka.stringify,Na=Ka.parse,
L=localStorage,M=L.setItem.bind(L),Va=L.removeItem.bind(L),Wa=pa.indexedDB,N=fetch,Xa=Uint8Array,Ya=Uint32Array,Za=Set,$a=Map,O=Number,ab=Object,bb=ab.keys,cb=ab.entries,db=setTimeout,eb=setInterval,kb=clearTimeout,lb=clearInterval,mb=addEventListener,nb=removeEventListener,ob=alert,pb=confirm,qb=prompt,rb=ra.userAgent.includes("WebKit"),sb=a=>a*a,tb=()=>!1,ub=(a,b)=>{if(a<2)return"...";const c=new Ja;a=new Ja(a);var d=c-a;if(d<59E3)return za(d/1E3)+"s";if(d<3E6)return za(d/6E4)+"m";d=a.getFullYear();
const e=a.getMonth(),g=a.getDate();let h="";d<c.getFullYear()&&(h=d+"/");if(h||e<c.getMonth())h+=e+1+"/";if(h||g<c.getDate())h+=g;if(b)return h||"heute";h&&(h+="/");b=h+a.getHours()+":";a=a.getMinutes();a=G(a).toString().padStart(2,"0");return b+a},vb="air stone grass dirt cobble planks bedrock log leaves bricks wool sand gravel glass bookshelf obsidian stone_bricks sandstone lapis_block iron_block gold_block diamond_block emerald_block redstone_block quartz_block".split(" "),wb="Luft Stein Grasblock Erde Bruchstein Holzbretter Grundgestein Stamm Laub Ziegelsteine Wolle Sand Kies Glas B\u00fccherregal Obsidian Steinziegel Sandstein Lapislazuliblock Eisenblock Goldblock Diamantblock Smaragdblock Redstoneblock Quarzblock".split(" "),
xb=[0,8487297,4305266,4349313,8092539,5342114,7039851,3561583,4172910,6384533,15526888,10671324,8092798,16447200,4151672,1970708,8092539,9686227,9126695,15198183,5567485,14541182,7920469,662956,14936813];let P=null;
if(Wa){let a,b;(a=ra.storage)==null||(b=a.persist)==null||b.call(a);const c=Wa.open("minicraft",1);c.onupgradeneeded=d=>{d=d.target.result.createObjectStore("chunks",{keyPath:["world","coords"]});for(const e of bb(L))if(e.startsWith("minicraft.world.")){const [g,h]=e.substr(16).split(":");h!=="meta"&&(d.add({world:O(g),coords:h,data:L.getItem(e)}),Va(e))}};c.onsuccess=d=>{P=d.target.result}}
const Db=(a,b)=>m(function*(){if(!P)return L.getItem(`minicraft.world.${a}:${b}`);const c=P.transaction("chunks","readonly").objectStore("chunks").get([a,b]);return new La(d=>{c.onsuccess=()=>{let e;d((e=c.result)==null?void 0:e.data)}})}()),Fb=(a,b)=>{var c=Eb();return m(function*(){if(!P)return M(`minicraft.world.${a}:${b}`,c);const d=P.transaction("chunks","readwrite").objectStore("chunks").put({world:a,coords:b,data:c});return new La((e,g)=>{d.onsuccess=()=>{e()};d.onerror=()=>{g(d.error)}})}())},
Gb=(a,b)=>m(function*(){if(!P)return Va(`minicraft.world.${a}:${b}`);const c=P.transaction("chunks","readwrite").objectStore("chunks").delete([a,b]);return new La(d=>{c.onsuccess=()=>{d()}})}()),Hb=a=>m(function*(){const b=`minicraft.world.${a}:`;if(!P){const e={},g=b.length;for(const h of bb(L))h.startsWith(b)&&(e[h.substr(g)]=L.getItem(h));return e}const c=P.transaction("chunks","readonly").objectStore("chunks").openCursor(),d={meta:L.getItem(b+"meta")};return new La(e=>{c.onsuccess=()=>{const g=
c.result;g?(g.value.world===a&&(d[g.value.coords]=g.value.data),g.continue()):e(d)}})}()),Ib=(a,b)=>m(function*(){if(P){var c=P.transaction("chunks","readwrite"),d=c.objectStore("chunks");for(const [e,g]of cb(b))e!=="meta"?d.put({world:a,coords:e,data:g}):M(`minicraft.world.${a}:meta`,g);return new La((e,g)=>{c.oncomplete=()=>{e()};c.onerror=()=>{g(c.error)}})}for(const [e,g]of cb(b))M(`minicraft.world.${a}:${e}`,g);M("__margin",Array(257).join("x"));Va("__margin")}()),Jb=a=>{if(P){Va(`minicraft.world.${a}:meta`);
var b=P.transaction("chunks","readwrite").objectStore("chunks").openCursor();b.onsuccess=()=>{const c=b.result;c&&(c.value.world===a&&c.delete(),c.continue())}}else{const c=`minicraft.world.${a}:`;for(const d of bb(L))d.startsWith(c)&&Va(d)}},Kb=(a,b)=>m(function*(){if(P){M(`minicraft.world.${b}:meta`,L.getItem(`minicraft.world.${a}:meta`));Va(`minicraft.world.${a}:meta`);var c=P.transaction("chunks","readwrite").objectStore("chunks"),d=c.openCursor();return new La(l=>{d.onsuccess=()=>{const f=d.result;
f?(f.value.world===a&&(f.value.world=b,c.put(f.value)),f.continue()):l()}})}const e=`minicraft.world.${a}:`,g=e.length,h=`minicraft.world.${b}:`;for(const l of bb(L))if(l.startsWith(e)){const f=L.getItem(l);Va(l);M(h+l.substr(g),f)}}());let Lb=null,Mb=null,Nb=0,Ob=!1,Pb=null,Qb=0;
const Sb=()=>{U.za||(kb(Nb),V.A({yb:!0,za:!0}),Rb(!1))},Rb=a=>{m(function*(){Nb=db(V.A,5E3,{yb:!1});try{const b=yield N(`${"/api/minicraft/"}world?what=${a?"initia":"meta_al"}l`);if(!b.ok)throw Error("Verbindungsfehler.");const c=yield b.json();a?c.version_latest!=="0.11.7"?location.reload(!0):(Lb=c.worlds,V.A({account:c.account,za:!1,ca:Tb(U.config)})):(Lb=c,V.A({za:!1,ca:Tb(U.config)}))}catch(b){V.A({fa:"Fehler beim Laden der Weltenliste: "+b.message,za:!1})}}())},Ub=(a,b)=>K(b.local,b.remote)-
K(a.local,a.remote),Tb=a=>{const b=Lb?Lb.map(c=>({account_name:c.account_name,hash:c.hash,id:c.id,label:c.label,local:0,public:c.public,remote:c.modified,writable:c.writable})):[];for(const c of a.worlds)if(a=b.find(d=>d.id===c.id)){const d=a.local=c.mod_l,e=a.remote,g=c.mod_r;d>g&&e>g&&(pb('Konflikt! Die Welt "'+c.label+'" wurde sowohl hier als auch woanders ge\u00e4ndert.\nOK: Die vom Server \u00fcbernehmen ('+ub(e,!1)+") | Abbrechen: Die hier hochladen ("+ub(d,!1)+")")?(y(),V.ba(c.id,{mod_l:a.local=
g})):a.remote=g)}else c.mod_r>1&&Lb&&(ob('Die Welt "'+c.label+'" wurde auf dem Server nicht gefunden, ist also jetzt eine lokale!'),y(),V.ba(c.id,{mod_r:0})),b.push({account_name:"",hash:0,id:c.id,label:c.label,local:c.mod_l,public:!1,remote:c.mod_r===1?1:0,writable:!0});return Mb=b.sort(Ub)},Wb=()=>m(function*(){if(!Ob){Ob=!0;var a;try{for(;a=Mb.find(b=>b.local>0&&b.remote>0&&b.local!==b.remote);)yield Vb(a),V.A({Aa:null})}catch(b){V.A({fa:b.message,Aa:null})}Ob=!1}}()),Xb={method:"POST",headers:{"Content-Type":"application/json"}},
Vb=a=>m(function*(){const b=a.id;V.A({Aa:b});if(a.local<a.remote)try{var c=yield(yield N(`${"/static/minicraft/"}worlds/${a.hash}.json`)).json();yield Ib(b,c);y();V.ba(b,{mod_l:a.remote,mod_r:a.remote})}catch(d){if(d.name==="QuotaExceededError")ob("Der Speicherplatz reicht nicht!"),y(),V.zb(b),Jb(b);else throw Error("Fehler beim Herunterladen der Welt: "+d.message);}else if(a.writable)try{c=b;if(a.remote===1){const h=yield N("/api/minicraft/world",Object.assign({},Xb,{body:Ma({what:"meta",label:a.label})}));
if(!h.ok)throw Error(h.status===403?"Keine Berechtigung. Angemeldet?":"Verbindungsfehler.");c=(yield h.json()).id}const d=yield Hb(b),e=yield N("/api/minicraft/world",Object.assign({},Xb,{body:Ma({what:"data",world:c,data:d})}));if(!e.ok)throw Error(e.status===403?"Keine Berechtigung. Angemeldet?":"Verbindungsfehler.");const g=yield e.json();y();c===b?V.ba(b,{mod_l:g.modified,mod_r:g.modified}):(yield Kb(b,c),V.zb(b),V.xb({id:c,label:a.label,mod_l:g.modified,mod_r:g.modified}),Pb=b,Qb=c)}catch(d){throw y(),
V.ba(b,{mod_r:0}),Error("Fehler beim Hochladen der Welt: "+d.message);}else y(),V.ba(b,{mod_l:U.config.worlds.find(d=>d.id===b).mod_r})}());let W=Na(L.getItem("minicraft.config")||null);if(W&&W.worlds&&W.version.startsWith("0.9.")){const a=new Za(W.worlds.map(b=>"minicraft.world."+b.id));for(const b of bb(L))b.startsWith("minicraft.world.")&&!a.has(b.split(":",1)[0])&&Va(b)}
const Yb={init:()=>{let a=!1;var b={sa:!1,Ka:1,Ha:3,$:4,V:1,Qa:120,oa:64,ya:0,worlds:[]};if(W){let c=W.pixel_grouping;c!=null&&(b.Ka=c);(c=W.mouse_sensitivity)!=null&&(b.Ha=c);b.$=W.resolution_scaling;(c=W.textures)!=null?b.V=c:b.V=W.flag_textures?1:0;b.Qa=W.view_angle;b.oa=W.view_distance;(c=W.world_last)!=null&&(b.ya=c);(c=W.worlds)?b.worlds=c:L.getItem("minicraft.world.0:meta")&&(b.worlds[0]={id:0,label:(qb("Es wurde eine namenlose lokale Welt gefunden. Wie soll sie hei\u00dfen?","")||"Unbekannte Welt").substring(0,
16),mod_l:Ja.now(),mod_r:0},a=!0);W=null}b={account:{label:"",rank:0},config:b,pb:b,fa:null,cursor:null,ka:pa.innerHeight,aa:pa.innerWidth,B:[{id:0,Nb:0,type:1}],yb:!0,za:!0,Aa:null,ca:Tb(b),Ab:[]};return a?(b.pb=null,Yb.ob(b)):b},ob:a=>{const b=a.config;if(b===a.pb)return a;M("minicraft.config",Ma({version:"0.11.7",pixel_grouping:b.Ka,mouse_sensitivity:b.Ha,resolution_scaling:b.$,textures:b.V,view_angle:b.Qa,view_distance:b.oa,world_last:b.ya,worlds:b.worlds}));return Object.assign({},a,{pb:b})},
cc:(a,b)=>Yb.qa(a,b(a.config)),qa:(a,b)=>Object.assign({},a,{config:Object.assign({},a.config,b)}),Wa:(a,b)=>a.config.sa===b?a:Yb.qa(a,{sa:b}),A:(a,b)=>Object.assign({},a,b),Xb:(a,b)=>(qa.activeElement.blur(),Object.assign({},a,{B:[...a.B,Object.assign({},{id:K(-1,...a.B.map(c=>c.id))+1,Nb:1,type:0},b)]})),Zb:(a,b)=>Object.assign({},a,{B:a.B.filter(c=>c.id!==b)}),Yb:(a,b)=>a.B[a.B.length-1].id===b?a:Object.assign({},a,{B:[...a.B.filter(c=>c.id!==b),a.B.find(c=>c.id===b)]}),xb:(a,b)=>{b=Object.assign({},
a.config,{worlds:[...a.config.worlds,b]});return Object.assign({},a,{config:b,ca:Tb(b)})},zb:(a,b)=>{const c=Object.assign({},a.config,{worlds:a.config.worlds.filter(d=>d.id!==b)});return Object.assign({},a,{config:c,ca:Tb(c)})},ba:(a,b,c)=>{const d=Object.assign({},a.config,{worlds:a.config.worlds.map(e=>e.id===b?Object.assign({},e,c):e)});return Object.assign({},a,{config:d,ca:Tb(d)})}};let U,V;
const Zb=(a,b=1,c=null)=>({amount:b,data:c,id:a}),$b=(a,b,c=a.c.amount)=>{if(b.c)a.c.id===b.c.id?(c=J(c,b.X-b.c.amount),a.c.amount-=c,b.c.amount+=c,a.c.amount<=0&&(a.c=null)):!(a.c.amount<=c&&a.c.amount<=b.X&&b.c.amount<=a.X)||a.filter&&!a.filter(b.c.id)||b.filter&&!b.filter(a.c.id)||([b.c,a.c]=[a.c,b.c]);else if(!b.filter||b.filter(a.c.id))a.c.amount<=c&&a.c.amount<=b.X?[b.c,a.c]=[a.c,b.c]:(c=J(c,b.X),a.c.amount-=c,b.c=Zb(a.c.id,c),a.c.amount<=0&&(a.c=null))},ac=(a,b)=>{for(const c of a)if(c.c&&
c.c.id===b.id){const d=J(b.amount,c.X-c.c.amount);c.c.amount+=d;if((b.amount-=d)<=0)return null}for(const c of a)if(!c.c&&(!c.filter||c.filter(b.id)))if(a=J(b.amount,c.X),a<=b.amount){if(c.c=Zb(b.id,a),(b.amount-=a)<=0)return null}else return c.c=b,null;return b},bc=(a,b)=>({lb:0,Bb:0,mb:0,T:0,pa:0,Ba:0,ha:0,W:-1,ia:0,Ca:null,Da:null,l:1,Lb:20,G:Array(36).fill(null).map(()=>({c:null,filter:null,X:64})),bb:0,name:b.label||"Spieler",H:a.Na,J:a.Oa,K:a.Pa,Pb:0,Qb:0,M:0,va:0,la:0,ma:0,na:0}),dc=(a,b)=>
{b=J(5,b*.01);a.la-=a.la*.1*b;a.ma-=a.ma*.1*b;a.na-=a.na*.1*b;a.la+=(Aa(a.T)*a.lb+Ba(a.T)*a.mb)*b;a.ma+=a.Bb*b;a.na+=(-Ba(a.T)*a.lb+Aa(a.T)*a.mb)*b;cc(a,a.Pb*b*1.5,a.Qb*b*1.5);a.H+=a.la*b;a.J+=a.ma*b;a.K+=a.na*b},cc=(a,b,c)=>{a.T=(a.T+b+sa*100)%(sa*2);a.pa=K(-ta,J(ta,a.pa+c))},ec=a=>{a+=32;a>33&&a<39?a++:a>38&&a<44?a+=2:a>43&&a<127?a+=3:a>126&&a<55258?a+=37:a>55295&&(a+=8485);return Ha(a)},fc=a=>a-(a>63743?8517:a>159?69:a>46&&a<130?35:a>40&&a<46?34:a>34&&a<40?33:32),Eb=()=>{var a=hc;const b=a.length,
c=new $a,d=q=>{n=n<<1|q&1;++p===15&&(t+=ec(n),n=p=0)},e=()=>{for(let q=0;q<k;++q)d(0)},g=q=>{d(q);d(q>>1);d(q>>2);d(q>>3);d(q>>4);d(q>>5);d(q>>6);d(q>>7)},h=()=>{--u===0&&(u=1<<k++)},l=()=>{if(x)x=!1;else{let q=v.id;for(let D=0;D<k;D++)d(q>>D)}};let f=a[0],t="",n=0,p=2,k=2,u=2,r=2,v={id:r++,Ua:new $a},x=!0;g(f);c.set(f,v);for(let q=1;q<b;++q){const D=v.Ua.get(f=a[q]);D?v=D:(l(),c.has(f)||(h(),e(),g(f),c.set(f,{id:r++,Ua:new $a}),x=!0),v.Ua.set(f,{id:r++,Ua:new $a}),v=c.get(f),h())}l();c.has(f)||(h(),
e(),g(f));h();d(1);--k;e();return t+=ec(n<<15-p)},ic=a=>{var b=hc;if(!a)return null;const c=a.length,d=()=>{p+=(r>>--v&1)<<k++;v===0&&(v=15,r=fc(a.charCodeAt(u++)))};let e=[0,1],g=1,h=3,l=2,f=null;var t=null;let n=0,p=0;t=2;let k=0,u=0,r=fc(a.charCodeAt(u++)),v=15;for(;k<t;)d();if(p===1)return null;for(p=k=0;k<8;)d();f=[p];e[2]=f;for(b[n++]=p;u<=c;){t=l;for(p=k=0;k<t;)d();if(p===0){for(p=k=0;k<8;)d();e[h]=[p];p=h++;--g===0&&(g=1<<l++)}else if(p===1)return b;t=p<e.length?e[p]:f.concat(f[0]);for(let x=
0;x<t.length;x++)b[n++]=t[x];e[h++]=f.concat(t[0]);f=t;--g===0&&(g=1<<l++)}return null},jc=new $a,kc=new Ya(1024),hc=new Xa(kc.buffer),lc=new $a,mc=a=>{const b={da:null,Ta:null,busy:!1,ea:null,Va:null,Ea:0,ja:!U.ca.find(c=>c.id===a).writable,Za:0,$a:0,ab:0,id:a,Ia:0,Ja:0,L:0,Na:.5,Oa:8.5,Pa:.5,time:0,ub:0};jc.set(a,b);V.A({Ab:[...jc.keys()]});return b},nc=(a,b,c,d)=>c<0||c>63?0:a.da[(b<<a.L+4|d)<<6|c],zc=(a,b,c,d)=>{const e=a.L;a.da[(b<<e+4|d)<<6|c]=0;a.ea[(b>>4<<e|d>>4)<<2|c>>4].ra=!0},Ac=(a,b,c,
d,e)=>{const g=a.L,h=(b<<g+4|d)<<6|c;if(a.da[h]>0)return!1;a.da[h]=e;return a.ea[(b>>4<<g|d>>4)<<2|c>>4].ra=!0},Dc=(a,b,c)=>{const d=K(J(b.J,63),0)>>4,e=G(b.H)>>4;b=G(b.K)>>4;if(c||a.$a!==d||a.Ia+a.Za!==e||a.Ja+a.ab!==b)c=1<<a.L,a.$a=d,a.Ia=e-(a.Za=(65536+e)%c),a.Ja=b-(a.ab=(65536+b)%c),Bc(a);a.busy||Cc(a,!1)},Bc=a=>{const b=a.Za,c=a.$a,d=a.ab,e=a.L,g=`${e} ${b} ${d} ${c}`;let h=lc.get(g);if(h==null){const l=1<<e,f=sb(l*.5);lc.set(g,h=a.ea.map(({x:t,y:n,z:p},k)=>{let u=sb(t-b),r=sb(p-d),v=sb(t-b-
l),x=0,q=0;v<u&&(u=v,x=-l);(v=sb(t-b+l))<u&&(u=v,x=l);(v=sb(p-d-l))<r&&(r=v,q=-l);(v=sb(p-d+l))<r&&(r=v,q=l);return{qb:u+r+sb(n-c),Eb:k,Ia:x,Ja:q}}).filter(({qb:t})=>t<=f).sort((t,n)=>t.qb-n.qb))}a.Va=h;a.Ea=0},Fc=(a,b)=>{if(!a.ja){for(var c=b.G.map(({c:d})=>d&&[d.id,d.amount,d.data]);c.length>0&&c[c.length-1]===null;)c.pop();M(`minicraft.world.${a.id}:meta`,Ma({p:{h:b.Lb,i:c,m:b.l,p:[b.H,b.J,b.K,b.T,b.pa]},s:[a.Na,a.Oa,a.Pa],t:a.time,v:1}));La.all(a.ea.filter(d=>d.ra).map(d=>Ec(a,d)))}},Hc=(a,b)=>
{const c=L.getItem(`minicraft.world.${a.id}:meta`);if(c){const {p:d,s:e,t:g,v:h}=Na(c);h!=null&&(d.i.forEach((l,f)=>{l&&(b.G[f].c=Zb(l[0],l[1],l[2]))}),b.Lb=d.h,b.l=d.m,b.H=d.p[0],b.J=d.p[1],b.K=d.p[2],b.T=d.p[3],b.pa=d.p[4],a.Na=e[0],a.Oa=e[1],a.Pa=e[2],g!=null&&Gc(a,g))}},Gc=(a,b)=>{a.time=b%24E3;a.ub=(b+6E3)/24E3%1},Ic=a=>m(function*(){const b=a.ea[a.Va[a.Ea=0].Eb];var c=b.y;yield Gb(a.id,`${b.Sa}/${b.kb}`+(c>0?"/"+c:""));b.ra=!1;++b.Sa;return Cc(a,!1)}()),Ec=(a,b)=>{const c=a.Ta;var d=a.L;const e=
b.y,g=(256<<d)-256;for(let h=0,l=-1,f=((b.x<<d+4|b.z)<<6|e)<<2;h<16;++h){for(d=0;d<16;++d)kc[++l]=c[f],kc[++l]=c[++f],kc[++l]=c[++f],kc[++l]=c[++f],f+=13;f+=g}b.ra=!1;return Fb(a.id,`${b.Sa}/${b.kb}`+(e>0?"/"+e:""))},Cc=(a,b)=>m(function*(){const c=a.ea,d=a.Va,e=a.Ia,g=a.Ja,h=d.length;for(;a.Ea<h;){var l=d[a.Ea++],f=c[l.Eb],t=f.l,n=f.x;const r=f.y;var p=f.z,k=e+l.Ia+n;const v=g+l.Ja+p;if(!t||k!==f.Sa||v!==f.kb){f.l=a.busy=!0;l=f.ra&&Ec(a,f);var u=a.id;k=f.Sa=k;f=f.kb=v;f=ic(yield Db(u,`${k}/${f}`+
(r>0?"/"+r:"")));yield l;a.busy=!1;if(t||r===0||f){l=a.Ta;k=a.L;u=(256<<k)-256;n=((n<<k+4|p)<<6|r)<<2;if(f)for(let x=0,q=-1;x<16;++x){for(t=0;t<16;++t)l[n]=kc[++q],l[++n]=kc[++q],l[++n]=kc[++q],l[++n]=kc[++q],n+=13;n+=u}else for(p=0;p<16;++p){for(f=0;f<16;++f)l[n]=r>0?0:50397446,l[++n]=r>0?0:131843,t?(l[++n]=0,l[++n]=0,n+=13):n+=15;n+=u}if(!b)break}}}}());let Jc=null,Kc=null;
const Lc=new Za,Mc=a=>{if(a){const b=Kc=new Image;b.onload=()=>{if(Kc===b){var c=qa.createElement("canvas");c.width=16;c.height=416;c=c.getContext("2d");c.scale(1,-1);for(let d=0;d<26;++d)c.drawImage(b,0,d<<4,16,16,0,-(d<<4)-16,16,16);Jc=new Ya(c.getImageData(0,0,16,416).data.buffer);for(const d of Lc)d.U=!0;Kc=null}};b.src=`${"/static/minicraft/"}textures/${a}.png`}else Jc=null},Oc=(a,b)=>{const c={Rb:b,nb:b.getContext("2d",{alpha:!1,desynchronized:!0}),Cb:null,Db:null,Hb:"",U:!1,Ib:0,rb:0,Sb:eb(()=>
(c.Ib=c.rb,c.rb=0),1E3),O:a};Lc.add(c);Nc(c);return c},Pc=(a,b)=>{++a.rb;const c=a.nb;var d=a.Cb;const e=a.Db,g=a.O,h=g.config,l=g.Ga,f=g.g,t=g.La,n=g.Ma,p=g.world;var k=0;if(!g.u||a.U){a.U=!1;var u=h.Ka;const ld=h.oa;var r=f.T,v=f.pa;const md=f.ha,nd=f.ia,Oa=f.l;var x=f.H;k=f.J;var q=f.K;const od=l?f.W:-1,pd=p.da;var D=p.L;const qd=Jc!==null;var fb=1/t,ua=1/n;const ca=t>>1,ka=n>>1,oc=J(t,n),pc=oc>32,qc=Aa(r);r=Ba(r);const rc=Aa(-v);v=Ba(-v);var Ca=h.Qa/45;const rd=fb*(t<n?Ca*t*ua:Ca);fb=ua*(n<t?
Ca*n*fb:Ca);x+=65536;ua=k+65536;q+=65536;Ca=x%1;const sd=ua%1,td=q%1;D=4+D;const Da=(1<<D)-1;u=u<t?u:1;const ud=t-u;let sc=f.l===1?6:4,Pa=f.ha=f.ia=f.Ba=0,tc=0;f.W=-1;k=k<0||k>=64?0:nc(p,x&Da,ua&63,q&Da);if(Oa!==2&&k>0)f.ha=x&Da,f.W=ua&63,f.ia=q&Da,f.Ba=6,e.fill(xb[k]|4278190080);else{for(let Qa=0;Qa<n;++Qa){var gb=(ka-Qa)*fb;const uc=gb*rc-v;var yb=gb*v+rc;gb=yb*r;yb*=qc;let da=0,Ea=!1;var Ra=!1;a:for(let Q=0;Q<t;Q+=u)for(let X=Ra?1:0;X<u;++X){if(u<2)var H=Q;else if(Q===0)H=X===0?0:X===1?u:X-1,Ea=
X===1;else if(Q<ud)H=(Ea=X===1)?Q+u:Q+X-1;else{if((H=X===0?Q-1:Q+X)>=t)break a;Ea=!1}var R=(H-ca)*rd;Ra=gb+qc*R;const vc=yb-r*R,vd=tc;R=16757124;let hb=1,wc=ld,ib=0;Oa===2&&k>0&&(ib=xa()*10);for(let zb=0;zb<3;++zb){const S=(vd+zb)%3;let Y=vc;var I=td;S===0&&(Y=Ra,I=Ca);S===1&&(Y=uc,I=sd);var la=-1/Y;Y>0&&(I=1-I,la*=-1);const jb=Ra*la,va=uc*la;la*=vc;const xc=Fa(jb*jb+va*va+la*la);let Sa=x+jb*I-(S===0&Y<0|0),Ta=ua+va*I-(S===1&Y<0|0),Ua=q+la*I-(S===2&Y<0|0);I*=xc;for(let Ab,Bb,Cb,T;I<wc;Sa+=jb,Ta+=
va,Ua+=la,I+=xc)if(!(Oa===2&&I<ib))if(Ta<65536){if(va<0)break}else if(Ta>=65600){if(va>0)break}else if((T=pd[((Ab=Sa&Da)<<D|(Cb=Ua&Da))<<6|(Bb=Ta&63)])!==0){Oa!==2&&Qa===ka&&H===ca&&I<=sc&&(f.ha=Ab,f.W=Bb,f.ia=Cb,f.Ba=Y<0|S<<1,sc=I);if(qd){--T;S===1?T===6?T=25:T===13?T=4:T===1&&va>0&&(T=2):T===1&&(T=24);const yc=Jc[T<<8|((S===1?Ua:Ta)*16&15)<<4|(S===1?Sa:(Y>0?Sa-Ua:Ua-Sa)+65536)*16&15];if(yc>>>24===0)continue;R=yc&16777215}else R=xb[T];wc=I;hb=(S===0?.8:S===2?.6:Y>0?.4:1)+(Bb!==od||Ab!==md||Cb!==
nd?0:.2);tc=S;break}else Oa===2&&I<ib&&(ib=I)}R=4278190080|J((R>>16)*hb,255)<<16|J((R>>8&255)*hb,255)<<8|J((R&255)*hb,255);if(Ra=(Ea=Ea&&(Qa!==ka||H<ca||H>ca+u))&&da===R){if(u>6){e.fill(da,Pa+Q+1,Pa+Q+u+1);break}H=Pa+Q+1;e[H]=da;e[++H]=da;if(u<3)break;e[++H]=da;if(u<4)break;e[++H]=da;if(u<5)break;e[++H]=da;if(u<6)break;e[++H]=da;break}if(Ea||H===0)da=R;e[Pa+H]=R}Pa+=t}l&&!pc&&(e[t*ka+ca]^=16777215)}c.putImageData(d,0,0);l&&pc&&(d=J(ya(oc*.05),8),c.fillRect(ca-d,ka-1,d<<1,2),c.fillRect(ca-1,ka-d,2,
d-1),c.fillRect(ca-1,ka+1,2,d-1))}a.Hb=g.Ya?`minicraft ${"0.11.7"} ${G(a.Ib).toString().padStart(2,"\u00a0")} fps, T: ${G(p.ub*24).toString().padStart(2,"0")}:${G(p.ub*24%1*60).toString().padStart(2,"0")}; ${g.u&&b%1E3<500?"":p.time}
R: ${t}x${n} (x${h.$}), D: ${h.oa}, C: ${p.Ea}/${p.Va.length}, M: ${sb(1<<4+p.L)*64>>10}k
E: 0/0, M: ${f.l}, I: ${k}

Position: ${f.H.toFixed(2)} ${f.J.toFixed(2)} ${f.K.toFixed(2)}
Angle: ${(f.T*wa).toFixed(2)} ${(f.pa*wa).toFixed(2)}
Focus: ${f.W<0?"":f.ha+" "+f.W+" "+f.ia+" "+"WEBTSNI"[f.Ba]+": "+vb[nc(p,f.ha,f.W,f.ia)]}
Chunk abs: ${G(f.H)>>4} ${G(f.K)>>4} ${G(f.J)>>4} rel: ${p.Za} ${p.ab} ${p.$a}`:""},Nc=a=>{const b=a.Rb,c=a.O;a.Db=new Ya((a.Cb=a.nb.createImageData(b.width=c.La,b.height=c.Ma)).data.buffer);const d=c.La*c.config.$/c.ua,e=c.Ma*c.config.$/c.ua;b.style.width=d+"px";b.style.height=e+"px";b.style.left=za((c.fb-d)/2)+"px";b.style.top=za((c.gb-e)/2)+"px";a.nb.fillStyle="rgba(255,255,255,.5)"};let Qc=0;
const Tc=(a,b,{config:c,account:d})=>{const e=mc(c.ya),g=bc(e,d);Hc(e,g);const h={config:c,Fb:0,Gb:0,Ya:!1,Ga:!0,u:!0,Jb:a,ga:0,Z:new Za,sb:"",j:0,P:[],g,tb:null,o:null,ua:1,fb:1,gb:1,La:0,Ma:0,hb:0,Ob:0,ib:0,Vb:eb(()=>{var l;(l=h.u)||(Gc(e,e.time+1),Dc(e,g,!1),l=void 0);return l},50),Ra:b,world:e};Rc(h,null);Sc(h);return h},Uc=a=>{a.world.ja||(Fc(a.world,a.g),V.ba(a.world.id,{mod_l:Ja.now()}))},Sc=a=>{m(function*(){if(!a.config.sa)try{yield a.Jb.requestPointerLock()}catch(b){}}())},Vc=(a,b)=>a===
b?0:.1-a*.2,Wc=a=>{a.g.lb=Vc((a=a.Z).has(-12)||a.has(65),a.has(-13)||a.has(68))},Xc=a=>{a.g.Bb=Vc((a=a.Z).has(-15)||a.has(16),a.has(-14)||a.has(32))},Yc=a=>{a.g.mb=Vc((a=a.Z).has(-11)||a.has(83),a.has(-10)||a.has(87))},Zc=a=>{a.g.Pb=Vc(a.Z.has(-18),a.Z.has(-19))},$c=a=>{a.g.Qb=Vc(a.Z.has(-17),a.Z.has(-16))},bd=(a,b,c)=>{if(!a.world)return!1;const d=a.Z;var e=a.g;if(c){if(d.has(b))return!1;d.add(b);var g=e.ha,h=e.W;c=e.ia;switch(b){case -18:case -19:Zc(a);break;case -17:case -16:$c(a);break;case -1:!a.world.ja&&
e.l!==2&&h>=0&&(e.bb===0?e.l===0&&(b=nc(a.world,g,h,c),b===2?b=3:b===1&&(b=4),b===6||b!==8&&b!==13&&ac(e.G,Zb(b,1))!==null)||(zc(a.world,g,h,c),e.W=-1):ad(a,[g,h,c],!1));break;case -2:case 71:if(h>=0){const l=nc(a.world,g,h,c);c=e.G.slice(0,9);h=c.findIndex(f=>f.c!==null&&f.c.id===l);h>=0?e.M=h:e.l===1&&(c[e.M].c&&(c=c.findIndex(f=>f.c===null),c>=0&&(e.M=c)),e.G[e.M].c=Zb(l));e.va=a.ga}break;case -3:if(!a.world.ja&&e.l!==2&&h>=0)if(e.bb===0){if(b=e.G[e.M],b.c){switch(e.Ba){case 0:--g;break;case 1:++g;
break;case 2:--h;break;case 3:++h;break;case 4:--c;break;case 5:++c}h>=0&&h<64&&Ac(a.world,g&(1<<4+a.world.L)-1,h,c&(1<<4+a.world.L)-1,b.c.id)&&e.l!==1&&--b.c.amount<=0&&(b.c=null)}}else ad(a,[g,h,c],!0);break;case -4:e.M=(e.M+9-1)%9;e.va=a.ga;break;case -5:e.M=(e.M+1)%9;e.va=a.ga;break;case 27:a.j===0&&(a.u=!0,a.j=1);break;case -15:case -14:case 16:case 32:Xc(a);break;case 49:case 50:case 51:case 52:case 53:case 54:case 55:case 56:case 57:e.M=b-49;e.va=a.ga;break;case -12:case -13:case 65:case 68:Wc(a);
break;case 69:if(a.j===0){a.j=3;for(const l of d)bd(a,l,!1)}break;case 70:a.Ra.Kb();break;case 80:a.world&&(a.u=!0);break;case 81:e=e.G[e.M];if(d.has(17)||e.c&&--e.c.amount<=0)e.c=null;break;case -11:case -10:case 83:case 87:Yc(a);break;case 84:if(a.j===0){a.j=2;for(const l of d)bd(a,l,!1)}break;case 112:a.Ga=!a.Ga;break;case 114:a.Ya=!a.Ya;case 116:case 122:case 123:break;default:return!1}}else{if(!d.delete(b))return!1;switch(b){case -15:case -14:case 16:case 32:Xc(a);break;case -12:case -13:case 65:case 68:Wc(a);
break;case -11:case -10:case 83:case 87:Yc(a);break;case -18:case -19:Zc(a);break;case -17:case -16:$c(a)}}a.sb=[...d].join();return!0},cd=(a,b)=>(b=b.startsWith("~")?a+O(b.substr(1)):O(b),isNaN(b)?a:b),ed=(a,b)=>{var c=a.g,d=a.world;if(b)if(b.charAt(0)==="/"){b=b.substr(1).split(" ");const e=b.shift();switch(e){case "clear":a.P=[];break;case "clearinv":for(const g of c.G)g.c=null;Z(a,"Inventar geleert",!0);break;case "gamemode":case "gm":b=O(b[0]);!isNaN(b)&&b>=0&&b<3&&b%1===0?(c.l=b,Z(a,"Spielmodus gesetzt auf: "+
b,!0)):Z(a,"Spielmodus muss in 0..2 sein!");break;case "give":if(b.length===0){Z(a,"/give <id> [Anzahl]\n"+vb.join(" "));break}d=vb.indexOf((b[0]||"").toLowerCase());d=d>=0?d:O(b[0]);b=O(b[1]||1);!isNaN(d)&&d>0&&d<25&&d%1===0?!isNaN(b)&&b>0&&b%1===0?Z(a,ac(c.G,Zb(d,b))?"Inventar ist voll!":`${"Items gegeben"} ${b} ${wb[d]}`,!0):Z(a,"Anzahl muss mindestens 1 sein!"):Z(a,"Ung\u00fcltiger Blocktyp!");break;case "help":Z(a,"Befehle: clear, clearinv, gamemode, give, help, load, me, save, spawn, teleport, time, version");
break;case "load":Cc(d,!0).then(()=>{a.o.U=!0;Z(a,"Chunks geladen.",!0)});break;case "me":Z(a,c.name+" "+b.join(" "),!0);break;case "save":if(a.world.ja){Z(a,"Fehlende Berechtigung!");break}Uc(a);Z(a,"Spiel gespeichert.",!0);break;case "spawn":if(a.world.ja){Z(a,"Fehlende Berechtigung!");break}d.Na=c.H;d.Oa=c.J;d.Pa=c.K;Z(a,"Startpunkt aktualisiert.",!0);break;case "teleport":case "tp":b.length===0?(c.H=d.Na,c.J=d.Oa,c.K=d.Pa,a.o.U=!0,Z(a,"Zum Startpunkt teleportiert.",!0)):b.length===3?(Z(a,"Teleportiert zu"+
` ${c.H=cd(c.H,b[0])} ${c.J=cd(c.J,b[1])} ${c.K=cd(c.K,b[2])}`,!0),a.o.U=!0):Z(a,"Pech!");c.la=0;c.ma=0;c.na=0;break;case "time":c=b[1];if(!c){Z(a,"Parameter fehlt!");break}if(c==="day")c=1E3;else if(c==="night")c=13E3;else if(isNaN(c=G(O(c))))break;switch(b[0]){case "add":c+=d.time;case "set":Gc(d,c);Z(a,"Zeit gesetzt auf: "+d.time,!0);break;default:Z(a,"Ung\u00fcltiger Befehl: time "+b[0])}break;case "version":Z(a,"minicraft 0.11.7");break;case "_w":V.Xb({type:b[0]==="m"?1:0});break;case "/exit":c.bb=
0;Z(a,"Normaler Mausmodus.",!0);break;case "/expand":a.g.Ca&&a.g.Da?d=!0:(Z(a,"Auswahl erforderlich!"),d=!1);d&&(b[0]==="vert"?(c.Ca[1]=0,c.Da[1]=63,Z(a,"Auswahl erweitert.",!0)):Z(a,'Nur "vert" wird unterst\u00fctzt!'));break;case "/pos1":case "/pos2":ad(a,[G(c.H),G(c.J),G(c.K)],e==="/pos2");break;case "/regen":if(a.world.ja){Z(a,"Fehlende Berechtigung!");break}Ic(d).then(()=>{a.o.U=!0;Z(a,"Chunk neu generiert.",!0)});break;case "/show":Z(a,`${"Erster"}: ${c.Ca?c.Ca.join(" "):"nichts"}, ${"Zweiter"}: ${c.Da?
c.Da.join(" "):"nichts"}`);break;case "/wand":c.bb=1;Z(a,"Auswahl mit Maustasten.",!0);break;default:Z(a,"Ung\u00fcltiger Befehl: "+e)}}else{const e=Z(a,`<${c.name}> `+b);Rc(a,b).then(g=>{g&&dd(a,e)})}},Z=(a,b,c=!1)=>{const d=++Qc;(a.P=a.P.slice(-49)).push({id:d,Mb:c,time:oa(),value:b});return d},dd=(a,b)=>{const c=a.P.findIndex(d=>d.id===b);c>=0&&a.P.splice(c,1)},ad=(a,b,c)=>{c?a.g.Da=b:a.g.Ca=b;Z(a,`${c?"Zweiter Auswahlpunkt":"Erster Auswahlpunkt"}: ${b.join(" ")}`,!0)},Rc=(a,b)=>(kb(a.tb),(b?N("/api/chat",
{method:"POST",headers:{"Content-Type":"application/json"},body:Ma({msg:b})}):N("/api/chat")).then(c=>{if(c.ok)return c.text()}).then(c=>{if(c){c=c.split("\n").filter(Boolean);for(const d of c)d.startsWith("<")&&Z(a,d);return c.length>0}return!1}).catch(()=>!1).then(c=>{a.tb=db(Rc,5E3,a,null);return c})),fd=({id:a,N:b})=>(z("div[className=bitmap]",{S:{backgroundImage:`url(${"/static/minicraft/"}textures/${b}.png)`,backgroundPositionY:100-a*100+"%"}}),null);
function gd({amount:a,l:b,id:c,N:d}){z("div[className=stack]",{title:wb[c]+(b===1?` (${vb[c]}, ${c})`:"")});return[C(fd,{id:c,N:d}),a!==1&&E("div[className=amount]",{innerText:a})]}
function hd({g:a,N:b,wa:c}){z("div[className=bar]",{ontouchstart:B(e=>{a.M=Number(e.target.closest("[data-slot]").dataset.slot);a.va=e.timeStamp}),S:{opacity:K(.5,J(1,1-(c-a.va-5E3)*5E-4))}});const d=a.l;return a.G.slice(0,9).map(({c:e},g)=>E("div",{D:{slot:g},F:{active:g===a.M}},[e&&C(gd,{amount:e.amount,data:e.data,l:d,id:e.id,N:b})]))}
function id({Ub:a,N:b}){z("div[className=grid]",{onclick:({target:c})=>{(c=c.closest("[data-id]"))&&$b({c:Zb(O(c.dataset.id)),filter:null,X:64},a)}});return vb.map((c,d)=>d>0&&E("div",{D:{id:d}},[C(gd,{amount:1,data:null,l:1,id:d,N:b})]))}
function jd({O:a,N:b}){const c=ea(()=>({c:null,filter:null,X:64})),d=a.g.l;z("div[className=menu overlay inventory]",ea(()=>({onclick:({target:e})=>{if(e.className==="menu overlay inventory")c.c?c.c=null:(a.j=0,a.u=!1,Sc(a));else if(e=e.closest("[data-slot]"))e=a.g.G[O(e.dataset.slot)],c.c?$b(c,e):e.c&&$b(e,c)},oncontextmenu:({target:e})=>{if(e.className==="menu overlay inventory")c.c?--c.c.amount<=0&&(c.c=null):(a.j=0,a.u=!1,Sc(a));else if(e=e.closest("[data-slot]"))e=a.g.G[O(e.dataset.slot)],c.c?
$b(c,e,1):e.c&&$b(e,c,ya(e.c.amount/2))}})));return[E("div[className=window]",null,[E("h2[innerText=Inventar]"),d===1&&C(id,{Ub:c,N:b}),E("div[className=grid]",null,a.g.G.map(({c:e},g)=>E("div",{D:{slot:g},F:{first:g<9}},[e&&C(gd,{amount:e.amount,data:e.data,l:d,id:e.id,N:b})])))]),c.c&&E("div[className=hand]",{S:{transform:`translate(${a.Fb}px, ${a.Gb}px)`}},[C(gd,{amount:c.c.amount,data:c.c.data,l:0,id:c.c.id,N:b})])]}
const kd=({I:{Mb:a,time:b,value:c},wa:d})=>(z(a?"div[className=minor]":"div",{innerText:c,S:{opacity:J(1,1-(d-b-4500)*.001)}}),null);function wd({P:a,wa:b}){z("div[className=messages]");const c=b-5E3;return[na(kd,a.slice(-10).filter(d=>d.time>c),{wa:b})]}function xd({I:a,qa:b,current:c}){z("button",{disabled:a.id===c,innerText:`${a.label} (${a.owner})`,onclick:()=>{b({V:a.id})}});return null}
function yd({config:a,O:b,xa:c}){b&&A(()=>Uc(b));const d=V.qa,[e,g]=ja(!1),h=ba(()=>e?N("/static/minicraft/textures.json").then(l=>l.ok?l.json():null).catch(()=>null):La.resolve(null),[e],null);z("div[className=menu overlay]");return[E("h1",{innerText:e?"Oberfl\u00e4chen":"Einstellungen"}),E("center",null,[E("button",{innerText:b&&!e?"Zur\u00fcck zum Spiel":"Zur\u00fcck",onclick:()=>{e?g(!1):b?(b.j=0,b.u=!1,Sc(b)):c(2)}})]),!e&&E("div[className=settings]",null,[E("button[innerText=Oberfl\u00e4chen...]",
{onclick:()=>{g(!0)}}),E("label[innerText=Aufl\u00f6sung:]",null,[E("input[type=range][min=1][max=100][step=1]",{value:101-a.$,onchange:l=>d({$:101-Number(l.target.value)})})]),E("label[innerText=Blickwinkel:]",null,[E("input[type=range][min=1][max=180][step=1]",{value:a.Qa,onchange:l=>d({Qa:Number(l.target.value)})})]),E("label[innerText=Sichtweite:]",null,[E("input[type=range][min=1][max=128][step=1]",{value:a.oa,onchange:l=>d({oa:Number(l.target.value)})})]),E("label[innerText=Pixelgruppierung:]",
null,[E("input[type=range][min=1][max=8][step=1]",{value:a.Ka,onchange:l=>d({Ka:Number(l.target.value)})})]),E("label[innerText=Mausempfindlichkeit:]",null,[E("input[type=range][min=1][max=15][step=1]",{value:a.Ha,onchange:l=>d({Ha:Number(l.target.value)})})]),E("button[innerText=Projektseite]",{onclick:()=>{open("//github.com/L3P3/minicraft")}})]),b&&!e&&E("center",null,[E("button[innerText=Welt verlassen]",{onclick:()=>{c(2)}})]),e&&E("div[className=settings]",null,[E("button[innerText=Einfarbig]",
{disabled:a.V===0,onclick:()=>{d({V:0})}}),h&&na(xd,h,{qa:d,current:a.V})])]}const zd=({I:{Mb:a,value:b}})=>(z(a?"div[className=minor]":"div",{innerText:b}),null);
function Ad({O:a,P:b}){const c=B({history:null,input:null});z("div[className=menu overlay terminal]",{onclick:d=>{d.target!==c.input&&c.input.focus()}});A(d=>{d&&db(()=>c.history.scrollTop=1E9,0)},[b.length&&b[b.length-1].id]);return[B(E("div[className=toolbar]",null,[E("button[innerText=\u274c]",{onclick:()=>{a.j=0;a.u=!1;Sc(a)}})])),E("div[className=history]",{R:B(d=>{c.history=d})},[na(zd,b)]),B(E("input[enterkeyhint=send][mozactionhint=send][name=message][required]",{onkeydown:d=>{const e=d.keyCode;
d=d.target;e===13?(ed(a,d.value),d.value=""):e===27&&(a.j=0,a.u=!1,Sc(a))},R:d=>{c.input=d;db(()=>d.focus(),0)}}))]}const Bd=[["pick",-2],["up",-14],["down",-15],["E",69],["T",84],["F1",112],["F3",114],["...",27]],Cd=[["up",-10],["down",-11],["left",-12],["right",-13],["center",-1]],Dd=[["up",-16],["down",-17],["left",-18],["right",-19],["center",-3]];
function Ed({O:a}){const b=a.Z,c=([d,e])=>E("div",{D:{code:e},F:{button:!0,[d]:!0,active:b.has(e)}});z("div[className=touch]",B({ontouchstart:d=>{let {code:e}=d.target.dataset;if(e!=null&&bd(a,e=O(e),!0)){const g=d.changedTouches[0].identifier,h=l=>{l.changedTouches[0].identifier===g&&(nb("touchend",h),bd(a,e,!1))};mb("touchend",h)}return!1}}));return[E("div[className=top]",null,Bd.map(([d,e])=>E(`div[innerText=${d}]`,{D:{code:e},F:{button:!0,active:b.has(e)}}))),E("div[className=move]",null,Cd.map(c)),
E("div[className=move sec]",null,Dd.map(c))]}
function Fd({frame:a,Y:b,state:c,xa:d,Ra:e}){const g=c.config,h=oa(),l=qa.pointerLockElement===a,f=ea(()=>Tc(a,e,c));A(()=>{Gd.add(f);const n=r=>{if(f.j!==0)return!0;qa.pointerLockElement===a?bd(f,-1-r.button,r.type==="mousedown"):Sc(f);return!1},p=r=>{if(qa.pointerLockElement===a){var v=f.config.Ha*sa/(K(f.fb,f.gb)*f.ua);rb&&(f.Ob=r.timeStamp);cc(f.g,f.hb=r.movementX*v,f.ib=-r.movementY*v)}else v=f.Jb.getBoundingClientRect(),f.Fb=r.clientX-v.left,f.Gb=r.clientY-v.top},k=r=>{V.Wa(!1);if(f.j===0&&
!f.u&&F.abs(r.deltaY)>5)return r=r.deltaY>0?-5:-4,bd(f,r,!0),bd(f,r,!1),!1},u={passive:!0};a.addEventListener("mousedown",n);a.addEventListener("mouseup",n);a.addEventListener("mousemove",p,u);a.addEventListener("wheel",k,u);return()=>{a.removeEventListener("mousedown",n);a.removeEventListener("mouseup",n);a.removeEventListener("mousemove",p,u);a.removeEventListener("wheel",k,u);kb(f.tb);lb(f.Vb);Fc(f.world,f.g);jc.delete(f.world.id);V.A({Ab:[...jc.keys()]});var r=f.o;Lc.delete(r);lb(r.Sb);return Gd.delete(f)}});
A(()=>{f.config=g;f.o&&(f.o.U=!0);const n=f.world;var p=ya(Ga(f.config.oa/16*2+2));if(n.L!==p){var k=f.g;n.ea&&Fc(n,k);const u=1<<(n.L=p),r=n.ea=[];for(let v=0;v<u;++v)for(let x=0;x<u;++x)for(let q=0;q<4;++q)r.push({ra:!1,l:!1,x:v,y:q,z:x,Sa:0,kb:0});p=u<<p+12+2;n.da===null||n.da.length<p?n.Ta=new Ya((n.da=new Xa(p)).buffer):n.Ta.fill(0);Dc(n,k,!0)}},[g]);A((n,p,k)=>{f.ua=k||1;f.fb=K(1,n);f.gb=K(1,p);p=f.config.$;n=ya(f.fb*f.ua/p);p=ya(f.gb*f.ua/p);if(n!==f.La||p!==f.Ma)f.La=n,f.Ma=p,f.o&&(f.o.U=
!0,Nc(f.o))},[a.offsetWidth,a.offsetHeight,pa.devicePixelRatio,g.$]);A(()=>{b&&bd(f,b.code,b.state)},[b]);A(n=>{n||f.u||f.j!==0||(f.j=1,rb&&f.hb|f.ib&&f.Ob>h-100&&(cc(f.g,-f.hb,-f.ib),f.hb=f.ib=0,f.o.U=!0));f.u=!n},[g.sa&&f.j===0||l]);A(n=>l&&n&&qa.exitPointerLock(),[f.u||f.j!==0]);h===f.ga||Hd||(f.world&&(f.ga&&!f.u&&dc(f.g,h-f.ga),f.o&&Pc(f.o,h)),f.ga=h);ia();const t=B({wb:1});g.V&&(t.wb=g.V);return[E("canvas",{R:B(n=>f.o=Oc(f,n))}),f.Ga&&f.j!==2&&C(wd,{P:f.P,wa:h}),f.o&&f.Ya&&E("div[className=diagnostics]",
{innerText:f.o.Hb}),g.sa&&C(Ed,{O:f,sb:f.sb}),f.Ga&&f.j!==3&&f.g.l!==2&&C(hd,{g:f.g,N:t.wb,wa:h}),f.j===3&&C(jd,{O:f,N:t.wb,wa:h}),f.j===1&&C(yd,{config:g,O:f,xa:d}),f.j===2&&C(Ad,{O:f,P:f.P})]}
function Id({I:a,$b:b,ac:c,Aa:d}){z("div",{F:{selected:a===b},onclick:()=>{c(a.id)}});b=`${a.local?"L":"_"}${a.local&&a.remote?a.local>a.remote?">":a.local<a.remote?"<":"=":"_"}${a.remote?a.public?"R":"r":"_"}`;d===a.id&&(b=`[${b}]`);return[E("span",{innerText:`${b} ${a.label}`,title:a.account_name?"Besitzer: "+a.account_name:"Nur lokale Welt"}),E("span",{innerText:ub(K(a.local,a.remote),!0)})]}
function Jd({state:{account:a,config:b,fa:c,yb:d,za:e,Aa:g,ca:h,Ab:l},xa:f}){z("div[className=menu]");const [t,n]=ja(b.ya),p=t!==Pb?t:(n(Qb),Qb),k=ea(()=>h.find(q=>q.id===p)||null,[p,h]),[u,r]=ja(!1);k||r(!1);const [v,x]=ja(!1);l=!!k&&l.includes(p);return[E("h1[innerText=Welten]"),E("button[innerText=Aktualisieren][style=position:absolute;left:0;top:0;height:2rem][title=Liste neu laden]",{disabled:d||e||c!==null,onclick:Sb}),E("button[style=position:absolute;right:0;top:0;height:2rem]",{disabled:a.rank>
0,innerText:a.rank?a.label:"Anmelden",onclick:()=>{location.href="/account?redir=minicraft"}}),E("div[className=worlds]",null,[na(Id,h,{bc:Ja.now(),$b:k,ac:n,Aa:g})]),E("center",null,[E("button[innerText=\u00d6ffnen]",{disabled:!k||l||k.local<2||k.remote>k.local,onclick:()=>{y();V.qa({ya:k.id});f(0);aa()},title:k?l?"Die Welt ist schon ge\u00f6ffnet!":k.local<2?"Die Welt ist noch nicht heruntergeladen!":k.local<k.remote?"Die Welt wird noch geladen!":"Ausgew\u00e4hlte Welt betreten":"Keine Welt ausgew\u00e4hlt!"}),
E("button[innerText=Welt...]",{disabled:!k||u,onclick:()=>{r(!0)},title:k?l?"Die Welt ist schon ge\u00f6ffnet!":"Aktionen/Einstellungen zur Welt anzeigen":"Keine Welt ausgew\u00e4hlt!"})]),E("hr"),E("center",null,[E("button[innerText=Neue Welt]",{onclick:()=>{const q=qb("Name der neuen Welt:\n(max. 16 Zeichen)","Neue Welt");q&&(q.length>16?ob("Der Name ist zu lang!"):V.xb({id:J(0,...b.worlds.map(D=>D.id))-1,label:q,mod_l:Ja.now(),mod_r:0}))}}),E("button[innerText=Einstellungen]",{onclick:()=>{f(1)}})]),
E("center",null,[E("small[innerText=Version 0.11.7 von L3P3]")]),u&&k&&E("div",{F:{"menu overlay advanced":!0,busy:v},onclick:q=>{q.target.className==="menu overlay advanced"&&r(!1)}},[E("div[className=window]",null,[E("h2",{innerText:`"${k.label}"`,title:k.id}),E("table",null,[!!k.account_name&&E("tr",null,[E("td[innerText=Besitzer:]"),E("td",{innerText:k.account_name})]),E("tr",null,[E("td[innerText=\u00c4nderung:]"),E("td",{innerText:ub(K(k.local,k.remote),!1)})])]),E("center",null,[E("button[innerText=Umbenennen]",
{disabled:v||l||!k.writable,onclick:()=>{const q=qb("Neuer Name der Welt:\n(max. 16 Zeichen)",k.label);!q||q===k.label||q.length>16||(k.local&&V.ba(k.id,{label:q}),k.remote&&(x(!0),N("/api/minicraft/world",{method:"POST",headers:{"Content-Type":"application/json"},body:Ma({what:"meta",world:k.id,label:q})}).then(D=>{if(!D.ok)throw Error(D.status===403?"Keine Berechtigung. Angemeldet?":"Verbindungsfehler.");return D.json()}).catch(D=>{ob("Fehler beim Bearbeiten der Welt: "+D.message)}).then(()=>{x(!1)})))},
title:k.writable?l?"Die Welt ist schon ge\u00f6ffnet!":"Welt-Namen \u00e4ndern":"Fehlende Berechtigung!"}),E("button",{disabled:v||l||!k.local&&!k.writable,innerText:k.local?"L\u00f6schen (lokal)":"L\u00f6schen",onclick:()=>{pb('Welt "'+k.label+'" wirklich l\u00f6schen?')&&(k.local?(V.zb(k.id),Jb(k.id)):(x(!0),N("/api/minicraft/world",{method:"DELETE",headers:{"Content-Type":"application/json"},body:Ma({what:"world",world:k.id})}).then(q=>{if(!q.ok)throw Error(q.status===403?"Keine Berechtigung. Angemeldet?":
"Verbindungsfehler.");y();n(null);r(!1);Sb();x(!1);aa();return q.json()}).catch(q=>{ob("Fehler beim L\u00f6schen der Welt: "+q.message);x(!1)})))},title:l?"Die Welt ist schon ge\u00f6ffnet!":k.local||k.writable?"Welt l\u00f6schen":"Fehlende Berechtigung!"})]),E("center",null,[E("button",{disabled:v||!k.remote||!k.writable,innerText:`${"\u00d6ffentlich"}: ${k.public?"Ja":"Nein"}`,onclick:()=>{x(!0);N("/api/minicraft/world",{method:"POST",headers:{"Content-Type":"application/json"},body:Ma({what:"meta",
world:k.id,public:!k.public})}).then(q=>{if(!q.ok)throw Error(q.status===403?"Keine Berechtigung. Angemeldet?":"Verbindungsfehler.");y();Sb();x(!1);aa();return q.json()}).catch(q=>{ob("Fehler beim Bearbeiten der Welt: "+q.message);x(!1)})},title:k.remote?k.writable?k.public?"Welt privat machen":"Welt ver\u00f6ffentlichen":"Fehlende Berechtigung!":"Die Welt ist nicht hochgeladen!"}),E("button",{disabled:v||!Lb||l||k.local>0&&k.remote>0||!k.remote&&!a.rank,innerText:k.local?Lb&&k&&!k.remote?"Hochladen":
"\u00dcbertragen":"Herunterladen",onclick:()=>{k.local?k.remote||V.ba(k.id,{mod_r:1}):V.xb({id:k.id,label:k.label,mod_l:1,mod_r:k.remote})},title:Lb?k.local?k.remote?"Die Welt ist schon auf beiden Seiten vorhanden!":l?"Die Welt ist schon ge\u00f6ffnet!":a.rank?"Welt auf den Server hochladen":"Nicht angemeldet!":"Welt von Server herunterladen":"Liste wird noch geladen!"})])])])]}let Kd=0;
function Ld({Y:a,state:b,Ra:c,jb:d}){const [e,g]=ja(2);A(()=>{c.Wb(e===0?b.ca.find(l=>l.id===b.config.ya).label+" \u2013 minicraft":"minicraft")},[e]);A(()=>{kb(Kd);b.fa||(Kd=db(Wb))},[b.fa,b.ca]);const h=z("div[className=game]");return[(e===2||e===1)&&C(Jd,{state:b,xa:g}),e===1&&C(yd,{config:b.config,O:null,xa:g}),e===0&&C(Fd,{frame:h,Y:a,state:b,xa:g,Ra:c,jb:d}),e===2&&b.fa&&E("div[style=position:absolute;bottom:0;left:0;color:yellow]",{title:b.fa},[E("span[innerText=Verbindungsfehler. ]"),E("button[innerText=Nochmal probieren]",
{onclick:()=>{V.A({fa:null})}})])]}const Md="nwse-resize ns-resize nesw-resize ew-resize move ew-resize nesw-resize ns-resize nwse-resize".split(" ");let Nd=0;
const Od={init:()=>Od.ta({Xa:0,Fa:0,height:0,Y:null,left:0,mode:Nd,title:"...",top:0,width:0},600,400),Kb:a=>Object.assign({},a,{mode:a.mode===0?1:0}),Tb:(a,b)=>a.Y&&a.Y.code===b.code&&a.Y.state===b.state?a:Object.assign({},a,{Y:b}),cb:(a,b,c)=>Object.assign({},a,{left:K(0,J(b,U.aa-a.width)),top:K(0,J(c,U.ka-a.height))}),eb:(a,b)=>Object.assign({},a,b),ta:(a,b,c)=>Object.assign({},a,{Fa:b=K(100,J(b,U.aa-a.left)),Xa:c=K(50,J(c,U.ka-a.top)),width:b,height:c}),Wb:(a,b)=>Object.assign({},a,{title:b})},
Pd=(a,b,c)=>{V.Yb(b);const d=c.target;if(d.className==="window borders"&&c.button===0){c.preventDefault();d.style.willChange="transform";qa.activeElement.blur();var e,g;[e,g]=a;var h=c.clientX,l=c.clientY,f=h-e.left,t=l-e.top,n=(f<8?0:f<e.width-8?1:2)+(t<8?0:t<e.height-8?3:6);V.A({cursor:Md[n]});var p=u=>{Hd=!0;y();let r=u.clientX,v=u.clientY;switch(n){case 1:case 7:r=h;break;case 3:case 5:v=l}switch(n){case 0:case 3:case 6:r=K(f,J(r,e.left+e.width-100+f))}switch(n){case 0:case 1:case 2:v=K(t,J(v,
e.top+e.height-50+t))}switch(n){case 4:if(u.type==="mouseup"){if(v<4){g.eb({left:0,top:0,width:U.aa,height:U.ka});break}if(r<4){g.eb({left:0,top:0,width:ya(U.aa/2),height:U.ka});break}if(r>U.aa-3){g.eb({left:ya(U.aa/2),top:0,width:G(U.aa/2),height:U.ka});break}}else if([u]=a,u.Fa!==u.width||u.Xa!==u.height){g.ta(u.Fa,u.Xa);const [x]=a;f=za(f*x.Fa/u.width)}g.cb(r-f,v-t);break;case 0:case 1:case 3:g.cb(r-f,v-t);g.ta(e.left+e.width+f-r,e.top+e.height+t-v);break;case 2:g.cb(e.left,v-t);g.ta(e.width-h+
r,e.top+e.height+t-v);break;case 6:g.cb(r-f,e.top);g.ta(e.left+e.width+f-r,e.height-l+v);break;default:g.ta(e.width-h+r,e.height-l+v)}aa();Hd=!1},k=u=>{nb("mousemove",p,!0);nb("mouseup",k);u.clientX===h&&u.clientY===l||p(u);V.A({cursor:null});d.style.willChange="auto"};mb("mousemove",p,!0);mb("mouseup",k)}},Qd=({height:a,left:b,mode:c,top:d,width:e},g)=>({F:{window:!0,borders:c===1},S:{display:c===2?"none":"block",height:c===0?"100%":a+"px",transform:c===0?"":`translate(${b}px, ${d}px)`,width:c===
0?"100%":e+"px"},onmousedown:g}),Rd=({title:a,jb:b})=>[E("div[className=window_title]",{innerText:a}),E("div[className=window_button]",{onclick:()=>V.Zb(b)})];
function Sd({I:{id:a,Nb:b,type:c},state:d}){Nd=b;const e=fa(Od),[g,h]=e;A(()=>(Td.set(a,h),()=>Td.delete(a)));b=ea(()=>Pd.bind(null,e,a));z("div",ea(Qd,[g,b]));const l=ha(!0,!1);A((f,t)=>{l&&h.eb({left:K(0,J(g.left,f-g.width)),top:K(0,J(g.top,t-g.height)),width:J(f,K(100,g.Fa,g.width)),height:J(t,K(50,g.Xa,g.height))})},[d.aa,d.ka]);return[c===1&&C(Ld,{Y:g.Y,state:d,Ra:h,jb:a}),g.mode!==0&&C(Rd,{title:g.title,jb:a})]}const Gd=new Za,Td=new $a;let Hd=!1,Ud=0;
function Vd(){[U,V]=fa(Yb);A(()=>{Rb(!0);let e=!1;onbeforeunload=onunload=onpagehide=onblur=()=>{if(!e){e=!0;for(const g of Gd)Uc(g);V.ob()}};onpageshow=onfocus=()=>{e=!1};onresize=()=>{Hd=!0;V.A({ka:pa.innerHeight,aa:pa.innerWidth});Hd=!1};eb(()=>(V.ob(),!Ia&&M("minicraft.lock",Ja.now())),500);mb("touchend",g=>{Ud=g.timeStamp},!0)});const a=B(e=>{if(e.target.tagName==="INPUT")return!0;Hd=!0;V.Wa(!1);if(U.B.length>0){const g=Td.get(U.B[U.B.length-1].id),h=e.type==="keydown";e.key!=="f"?g.Tb({code:e.keyCode,
state:h}):h&&g.Kb()}return Hd=!1}),b=B(()=>{V.Wa(!0)}),c=B(e=>{e.timeStamp-Ud>999&&V.Wa(!1)}),d=U.config.sa;A(()=>{d?(mb("mousedown",c,!0),mb("mouseup",c,!0),nb("touchstart",b,!0)):(nb("mousedown",c,!0),nb("mouseup",c,!0),mb("touchstart",b,!0))},[d]);A(Mc,[U.config.V]);z("",{onkeydown:a,onkeyup:a,oncontextmenu:tb,ondragstart:tb});return[na(Sd,U.B,{state:U}),U.cursor&&E("div[className=cursormask]",{S:{cursor:U.cursor}})]}
function Wd(){close();return[E("h1[innerText=minicraft l\u00e4uft schon!]")]}if(window.SSR)ma(Vd);else if(Ia){const a=new Ia("minicraft.lock"),b=db(ma,100,Vd);a.addEventListener("message",c=>{c.data==="yes"?(kb(b),a.close(),ma(Wd)):(a.postMessage("yes"),focus())});a.postMessage("anyone there?")}else{const a=O(L.getItem("minicraft.lock")),b=Ja.now()-1E3;a<b?ma(Vd):db(()=>{ma(O(L.getItem("minicraft.lock"))===a?Vd:Wd)},a-b)};
