function m(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})}
var v=lui,ca=v.defer,da=v.defer_end,ea=v.hook_async,x=v.hook_dom,y=v.hook_effect,A=v.hook_memo,fa=v.hook_model,ha=v.hook_prev,ia=v.hook_rerender,ja=v.hook_state,oa=v.hook_static,pa=v.init,C=v.node,D=v.node_dom,qa=v.node_map,ra=v.now,E=window,sa=document,ta=navigator,F=Math,va=F.abs,wa=F.PI,xa=wa*.5,ya=180/wa,za=wa/360,Aa=F.random,G=F.floor,Da=F.ceil,Ea=F.round,H=F.min,I=F.max,Fa=F.cos,Ga=F.sin,Ha=F.sqrt,Ia=F.tan,Ja=F.log2,Ka=String.fromCharCode,La=E.visualViewport||null,Qa=E.BroadcastChannel,Ra=Date,
Sa=JSON,J=Promise,Ta=Sa.stringify,Ua=Sa.parse,L=localStorage,N=L.setItem.bind(L),Va=L.removeItem.bind(L),Za=E.indexedDB||null,O=fetch,$a=Array,ab=Uint8Array,bb=Uint32Array,cb=Set,db=Map,U=Number,eb=Object,fb=eb.keys,gb=eb.entries,hb=setTimeout,ib=setInterval,jb=clearTimeout,kb=addEventListener,lb=removeEventListener,mb=alert,nb=confirm,ob=prompt,vb=ta.userAgent.includes("WebKit"),wb={method:"POST",headers:{"Content-Type":"application/json"}},xb={behavior:"smooth",block:"center",container:"nearest"},
yb=(a,b)=>(a=G(a).toString(),a.length<2?b+a:a),zb=a=>a*a,Ab=()=>!1,Bb=(a,b)=>{if(a<2)return"...";var c=new Ra;a=new Ra(a);var d=c-a;if(d<59E3)return Ea(d/1E3)+"s";if(d<3E6)return Ea(d/6E4)+"m";d=a.getFullYear();var e=a.getMonth(),f=a.getDate(),g="";d<c.getFullYear()&&(g=d+"/");if(g||e<c.getMonth())g+=e+1+"/";if(g||f<c.getDate())g+=f;if(b)return g||"hoy";g&&(g+="/");return g+a.getHours()+":"+yb(a.getMinutes(),"0")},Cb=a=>{if(!a.ok)throw Error(a.status===403?"Falta de permisos. \u00bfSesi\u00f3n iniciada?":
"Error de conexi\u00f3n.");return a.json()},Db="air stone grass dirt cobble planks bedrock log leaves bricks wool sand gravel glass bookshelf obsidian stone_bricks sandstone lapis_block iron_block gold_block diamond_block emerald_block redstone_block quartz_block".split(" "),Eb="Aire;Piedra;Bloque de hierba;Tierra;Adoqu\u00edn;Tablones;Piedra base;Tronco;Hojas;Ladrillos;Lana;Arena;Grava;Cristal;Estanter\u00eda;Obsidiana;Ladrillos de piedra;Arenisca;Bloque de lapisl\u00e1zuli;Bloque de hierro;Bloque de oro;Bloque de diamante;Bloque de esmeralda;Bloque de redstone;Bloque de cuarzo".split(";"),
Fb=[0,8487297,4305266,4349313,8092539,5342114,7039851,3561583,4172910,6384533,15526888,10671324,8092798,16447200,4151672,1970708,8092539,9686227,9126695,15198183,5567485,14541182,7920469,662956,14936813],Wb=null,Xb=null,Yb=null,Zb=Za?new J(a=>{var b,c;(b=ta.storage)==null||(c=b.persist)==null||c.call(b);b=Za.open("minicraft",1);b.onupgradeneeded=d=>{d=d.target.result.createObjectStore("chunks",{keyPath:["world","coords"]});for(let e of fb(L))if(e.startsWith("minicraft.world.")){let [f,g]=e.slice(16).split(":",
2);g!=="meta"&&(d.add({world:U(f),coords:g,data:L.getItem(e)}),Va(e))}};b.onsuccess=d=>{Wb=d.target.result;a()}}):J.resolve(void 0),$b=Za?(a,b)=>new J(c=>{Xb||(Xb=Wb.transaction("chunks","readonly").objectStore("chunks"),J.resolve(void 0).then(()=>{Xb=null}));var d=Xb.get([a,b]);d.onsuccess=()=>{var e;return c((e=d.result)==null?void 0:e.data)}}):(a,b)=>{a=L.getItem(`minicraft.world.${a}:${b}`);return J.resolve(a)},ac=Za?(a,b,c)=>new J((d,e)=>{Yb||(Yb=Wb.transaction("chunks","readwrite").objectStore("chunks"),
J.resolve(void 0).then(()=>{Yb=null}));var f=Yb.put({world:a,coords:b,data:c});f.onsuccess=()=>d();f.onerror=()=>e(f.error)}):(a,b,c)=>(N(`minicraft.world.${a}:${b}`,c),J.resolve(void 0)),bc=Za?(a,b)=>new J((c,d)=>{Yb||(Yb=Wb.transaction("chunks","readwrite").objectStore("chunks"),J.resolve(void 0).then(()=>{Yb=null}));var e=Yb.delete([a,b]);e.onsuccess=()=>c();e.onerror=()=>d(e.error)}):(a,b)=>(Va(`minicraft.world.${a}:${b}`),J.resolve(void 0)),cc=Za?a=>new J(b=>{var c=L.getItem(`minicraft.world.${a}:meta`);
if(!c)return b({});var d=Wb.transaction("chunks","readonly").objectStore("chunks").openCursor(),e={meta:c};d.onsuccess=()=>{var f=d.result;f?(f.value.world===a&&(e[f.value.coords]=f.value.data),f.continue()):b(e)}}):a=>{a=`minicraft.world.${a}:`;var b=a.length,c={};for(let d of fb(L))d.startsWith(a)&&(c[d.slice(b)]=L.getItem(d));return J.resolve(c)},dc=Za?(a,b)=>new J((c,d)=>{var e=Wb.transaction("chunks","readwrite"),f=e.objectStore("chunks");for(let [g,l]of gb(b))g!=="meta"?f.put({world:a,coords:g,
data:l}):N(`minicraft.world.${a}:meta`,l);e.oncomplete=()=>c();e.onerror=()=>d(e.error)}):(a,b)=>m(function*(){for(let [c,d]of gb(b))N(`minicraft.world.${a}:${c}`,d);N("__margin",$a(257).join("x"));Va("__margin")}()),ec=Za?a=>{var b=Wb.transaction("chunks","readwrite").objectStore("chunks").openCursor();b.onsuccess=()=>{var c=b.result;c&&(c.value.world===a&&c.delete(),c.continue())};Va(`minicraft.world.${a}:meta`)}:a=>{a=`minicraft.world.${a}:`;for(let b of fb(L))b.startsWith(a)&&Va(b)},fc=Za?(a,
b)=>new J(c=>{var d=Wb.transaction("chunks","readwrite").objectStore("chunks"),e=d.openCursor();e.onsuccess=()=>{var f=e.result;f?(f.value.world===a&&(f.delete(),f.value.world=b,d.put(f.value)),f.continue()):c()};N(`minicraft.world.${b}:meta`,L.getItem(`minicraft.world.${a}:meta`));Va(`minicraft.world.${a}:meta`)}):(a,b)=>{a=`minicraft.world.${a}:`;var c=a.length;for(let d of fb(L))if(d.startsWith(a)){let e=L.getItem(d);Va(d);N(`minicraft.world.${b}:${d.slice(c)}`,e)}return J.resolve(void 0)},V=null,
hc=0,ic=null,kc=()=>{W.Ja||W.na!==null||(jb(hc),X.A({Ab:!0,Ja:!0}),jc(!1))},jc=a=>{m(function*(){hc=hb(X.A,5E3,{Ab:!1});try{let b=yield O(`/api/minicraft/world?what=${a?"initia":"meta_al"}l`),c=yield Cb(b);a?c.version_latest!=="0.13.3"?location.reload(!0):(V=c.worlds,X.A(Object.assign({},{account:c.account,Ja:!1},lc(W.config)))):(V=c,X.A(Object.assign({},{Ja:!1},lc(W.config))))}catch(b){X.A({ka:"Error al cargar la lista de mundos: "+b.message,Ja:!1})}}())},mc=(a,b)=>I(b.local,b.remote)-I(a.local,
a.remote),lc=a=>{var b=V?V.map(c=>({account_name:c.account_name,hash:c.hash,id:c.id,label:c.label,local:0,locked:c.locked,public:c.public,remote:c.modified,writable:c.writable})):[];for(let c of a.worlds){let d=b.find(e=>e.id===c.id);if(d){let e=d.local=c.mod_l,f=d.remote,g=c.mod_r;e>g&&f>g&&(nb('\u00a1Conflicto! El mundo "'+c.label+'" fue modificado aqu\u00ed y en otro lugar.\nAceptar: Tomar variante del servidor ('+Bb(f,!1)+") | Cancelar: Mantener variante local ("+Bb(e,!1)+")")?a=Object.assign({},
a,{worlds:a.worlds.map(l=>l.id===c.id?Object.assign({},l,{mod_l:d.local=g}):l)}):d.remote=g)}else c.mod_r>1&&V&&(mb('El mundo "'+c.label+'" no se encontr\u00f3 en el servidor, por lo que ahora es un mundo local.'),a=Object.assign({},a,{worlds:a.worlds.map(e=>e.id===c.id?Object.assign({},e,{mod_r:0}):e)})),b.push({account_name:"",hash:0,id:c.id,label:c.label,local:c.mod_l,locked:!1,public:!1,remote:c.mod_r===1?1:0,writable:!0})}return{config:a,Ya:b.sort(mc)}},oc=()=>m(function*(){if(W.na===null){var a;
try{for(;a=W.Ya.find(b=>b.local>0&&b.remote>0&&b.local!==b.remote);)yield nc(a);X.A({na:null})}catch(b){X.A({ka:b.message,na:null})}}}()),nc=a=>m(function*(){var b=a.id;X.A({na:b});if(a.local<a.remote)try{yield dc(b,yield Cb(yield O(`/static/minicraft/worlds/${a.hash}.json`))),X.ma(b,{mod_l:a.remote,mod_r:a.remote})}catch(c){if(c.name==="QuotaExceededError")mb("\u00a1Almacenamiento insuficiente!"),ec(b),X.Yb(b);else throw Error("Error al descargar el mundo: "+c.message);}else if(!a.writable||a.locked)X.ma(b,
{mod_l:a.remote});else{let c=b,d=null;try{let e=cc(b);if(a.remote===1){let g=yield Cb(yield O("/api/minicraft/world",Object.assign({},wb,{body:Ta({what:"meta",label:a.label})})));d=fc(b,c=g.id);ic=[b,c];X.ma(b,{id:c})}let f=yield Cb(yield O("/api/minicraft/world",Object.assign({},wb,{body:Ta({what:"data",world:c,data:yield e})})));a.remote===1?V.push(f):Object.assign(V.find(g=>g.id===b),f);X.ma(c,{mod_l:f.modified,mod_r:f.modified})}catch(e){throw X.ma(b,{mod_r:0}),Error("Error al subir el mundo: "+
e.message);}yield d}}()),Y=Ua(L.getItem("minicraft.config")||null);if(Y&&Y.worlds&&Y.version.startsWith("0.9.")){let a=new cb(Y.worlds.map(b=>"minicraft.world."+b.id));for(let b of fb(L))b.startsWith("minicraft.world.")&&!a.has(b.split(":",1)[0])&&Va(b)}
var pc={init:()=>{var a=!1,b={Ca:!1,ua:1,Da:3,$:4,V:1,Ha:120,ia:64,Ia:0,worlds:[]};if(Y){let c=Y.pixel_grouping;c!=null&&(b.ua=c);(c=Y.mouse_sensitivity)!=null&&(b.Da=c);b.$=Y.resolution_scaling;(c=Y.textures)!=null?b.V=c:b.V=Y.flag_textures?1:0;b.Ha=Y.view_angle;b.ia=Y.view_distance;(c=Y.world_last)!=null&&(b.Ia=c);(c=Y.worlds)?b.worlds=c:L.getItem("minicraft.world.0:meta")&&(b.worlds[0]={id:0,label:(ob("Se ha encontrado un mundo sin nombre. \u00bfC\u00f3mo deber\u00eda llamarse?","")||"Mundo desconocido").substring(0,
16),mod_l:Ra.now(),mod_r:0},a=!0);Y=null}b=Object.assign({},{account:{label:"",rank:0},config:b,rb:b,ka:null,cursor:null,ga:E.innerHeight,Y:E.innerWidth,ha:b.V,J:[{id:0,Rb:0,type:1}],Ab:!0,Ja:!0,na:null,Za:[]},lc(b));return a?(b.rb=null,pc.qb(b)):b},qb:a=>{var b=a.config;if(b===a.rb)return a;N("minicraft.config",Ta({version:"0.13.3",pixel_grouping:b.ua,mouse_sensitivity:b.Da,resolution_scaling:b.$,textures:b.V,view_angle:b.Ha,view_distance:b.ia,world_last:b.Ia,worlds:b.worlds}));return Object.assign({},
a,{rb:b})},sc:(a,b)=>pc.T(a,b(a.config)),T:(a,b)=>Object.assign({},a,{config:Object.assign({},a.config,b)}),bb:(a,b)=>a.config.Ca===b?a:pc.T(a,{Ca:b}),ec:(a,b,c)=>b===a.Y&&c===a.ga?a:Object.assign({},a,{Y:b,ga:c}),A:(a,b)=>Object.assign({},a,b),lc:(a,b)=>(sa.activeElement.blur(),Object.assign({},a,{J:[...a.J,Object.assign({},{id:I(-1,...a.J.map(c=>c.id))+1,Rb:1,type:0},b)]})),oc:(a,b)=>Object.assign({},a,{J:a.J.filter(c=>c.id!==b)}),mc:(a,b)=>a.J[a.J.length-1].id===b?a:Object.assign({},a,{J:[...a.J.filter(c=>
c.id!==b),a.J.find(c=>c.id===b)]}),Xb:(a,b)=>Object.assign({},a,lc(Object.assign({},a.config,{worlds:[...a.config.worlds,b]}))),Yb:(a,b)=>Object.assign({},a,lc(Object.assign({},a.config,{worlds:a.config.worlds.filter(c=>c.id!==b)}))),ma:(a,b,c)=>Object.assign({},a,lc(Object.assign({},a.config,{worlds:a.config.worlds.map(d=>d.id===b?Object.assign({},d,c):d)})))},W,X,qc=(a,b=1,c=null)=>({amount:b,data:c,id:a}),rc=(a,b,c=a.content.amount)=>{if(b.content)a.content.id===b.content.id?(c=H(c,b.ca-b.content.amount),
a.content.amount-=c,b.content.amount+=c,a.content.amount<=0&&(a.content=null)):!(a.content.amount<=c&&a.content.amount<=b.ca&&b.content.amount<=a.ca)||a.filter&&!a.filter(b.content.id)||b.filter&&!b.filter(a.content.id)||([b.content,a.content]=[a.content,b.content]);else if(!b.filter||b.filter(a.content.id))a.content.amount<=c&&a.content.amount<=b.ca?[b.content,a.content]=[a.content,b.content]:(c=H(c,b.ca),a.content.amount-=c,b.content=qc(a.content.id,c),a.content.amount<=0&&(a.content=null))},sc=
(a,b)=>{for(let c of a)if(c.content&&c.content.id===b.id){let d=H(b.amount,c.ca-c.content.amount);c.content.amount+=d;if((b.amount-=d)<=0)return null}for(let c of a)if(!c.content&&(!c.filter||c.filter(b.id)))if(a=H(b.amount,c.ca),a<=b.amount){if(c.content=qc(b.id,a),(b.amount-=a)<=0)return null}else return c.content=b,null;return b},tc=(a,b)=>({lb:0,Cb:0,mb:0,Z:0,Aa:0,Ka:0,pa:0,ba:-1,qa:0,La:null,Ma:null,u:1,Pb:20,L:$a(36).fill(null).map(()=>({content:null,filter:null,ca:64})),fb:0,name:b.label||
"Jugador",M:a.Ua,N:a.Va,O:a.Wa,Ub:0,Vb:0,P:0,Fa:0,va:0,wa:0,xa:0}),vc=(a,b)=>{b=H(5,b*.01);a.va-=a.va*.1*b;a.wa-=a.wa*.1*b;a.xa-=a.xa*.1*b;a.va+=(Fa(a.Z)*a.lb+Ga(a.Z)*a.mb)*b;a.wa+=a.Cb*b;a.xa+=(-Ga(a.Z)*a.lb+Fa(a.Z)*a.mb)*b;uc(a,a.Ub*b*1.5,a.Vb*b*1.5);a.M+=a.va*b;a.N+=a.wa*b;a.O+=a.xa*b},uc=(a,b,c)=>{a.Z=(a.Z+b+wa*100)%(wa*2);a.Aa=I(-xa,H(xa,a.Aa+c))},wc=a=>{a+=32;a>33&&a<39?a++:a>38&&a<44?a+=2:a>43&&a<127?a+=3:a>126&&a<55258?a+=37:a>55295&&(a+=8485);return Ka(a)},xc=a=>a-(a>63743?8517:a>159?69:
a>46&&a<130?35:a>40&&a<46?34:a>34&&a<40?33:32),zc=()=>{var a=yc,b=a.length,c=new db,d=t=>{k=k<<1|t&1;++p===15&&(q+=wc(k),k=p=0)},e=()=>{for(let t=0;t<r;++t)d(0)},f=t=>{d(t);d(t>>1);d(t>>2);d(t>>3);d(t>>4);d(t>>5);d(t>>6);d(t>>7)},g=()=>{--n===0&&(n=1<<r++)},l=()=>{if(u)u=!1;else{let t=w.id;for(let z=0;z<r;z++)d(t>>z)}},h=a[0],q="",k=0,p=2,r=2,n=2,B=2,w={id:B++,ab:new db},u=!0;f(h);c.set(h,w);for(let t=1;t<b;++t){let z=w.ab.get(h=a[t]);z?w=z:(l(),c.has(h)||(g(),e(),f(h),c.set(h,{id:B++,ab:new db}),
u=!0),w.ab.set(h,{id:B++,ab:new db}),w=c.get(h),g())}l();c.has(h)||(g(),e(),f(h));g();d(1);--r;e();return q+=wc(k<<15-p)},Ac=a=>{var b=yc;if(!a)return!1;var c=a.length,d=()=>{p+=(B>>--w&1)<<r++;w===0&&(w=15,B=xc(a.charCodeAt(n++)))},e=[0,1],f=1,g=3,l=2,h=null,q=null,k=0,p=0;q=2;for(var r=0,n=0,B=xc(a.charCodeAt(n++)),w=15;r<q;)d();if(p===1)return!1;for(p=r=0;r<8;)d();h=[p];e[2]=h;for(b[k++]=p;n<=c;){q=l;for(p=r=0;r<q;)d();if(p===0){for(p=r=0;r<8;)d();e[g]=[p];p=g++;--f===0&&(f=1<<l++)}else if(p===
1)return!0;q=p<e.length?e[p]:h.concat(h[0]);for(let u=0;u<q.length;u++)b[k++]=q[u];e[g++]=h.concat(q[0]);h=q;--f===0&&(f=1<<l++)}return!1},Bc=new db,Cc=new bb(1024),yc=new ab(Cc.buffer),Dc=a=>{var b=W.Ya.find(c=>c.id===a);b={ja:null,$a:null,da:null,Ba:null,Na:0,$b:[],X:!1,o:!1,ra:!b.writable||b.locked,Jb:0,Kb:0,Lb:0,id:a,Qa:0,Ra:0,Wb:0,U:0,Ua:.5,Va:8.5,Wa:.5,time:0,yb:0};Bc.set(a,b);X.A({Za:[...Bc.keys()]});return b},Ec=(a,b,c,d)=>c<0||c>63?0:a.ja[(b<<a.U+4|d)<<6|c],Fc=(a,b,c,d)=>{var e=a.U,f=a.da[(b>>
4<<e|d>>4)<<2|c>>4];f.sa||(a.ja[(b<<e+4|d)<<6|c]=0,f.o=f.ta=!0)},Mc=(a,b,c,d,e)=>{var f=a.U,g=a.da[(b>>4<<f|d>>4)<<2|c>>4];b=(b<<f+4|d)<<6|c;return g.sa||a.ja[b]!==0?!1:(a.ja[b]=e,g.o=g.ta=!0)},Pc=(a,b,c)=>{m(function*(){a.da&&(yield Nc(a,b,!0));var d=1<<(a.U=c),e=a.da=[];for(let f=0;f<d;++f)for(let g=0;g<d;++g)for(let l=0;l<4;++l)e.push({o:!1,sa:!1,ta:!1,x:f,y:l,z:g,oa:f+1,za:0});d<<=c+12+2;a.ja===null||a.ja.length<d?a.$a=new bb((a.ja=new ab(d)).buffer):a.$a.fill(0);Oc(a,b,!0)}())},Oc=(a,b,c)=>{var d=
I(H(b.N,63),0)>>4,e=G(b.M)>>4,f=G(b.O)>>4;if(c||a.Kb!==d||a.Qa+a.Jb!==e||a.Ra+a.Lb!==f){c=a.da;b=1<<a.U;var g=b-1;let l=a.Jb=e&g;g=a.Lb=f&g;let h=b>>1,q=I(h-2,8),k=a.Ba=[];a.Na=0;a.Kb=d;a.Qa=e-l;a.Ra=f-g;for(let p=0,r=c.length;p<r;++p){let {x:n,y:B,z:w}=c[p];e=va(n-l);f=0;e>h&&(e=b-e,f=n<l?b:-b);if(e>q)continue;let u=va(w-g),t=0;u>h&&(u=b-u,t=w<g?b:-b);u>q||k.push({Ib:e*e+u*u+zb(B-d),pb:p,Qa:f,Ra:t})}k.sort((p,r)=>p.Ib-r.Ib)}a.X||Qc(a,!1)},Nc=(a,b,c)=>m(function*(){if(!(!c&&a.X||a.ra)&&a.o){a.X=!0;
a.o=!1;for(var d=Ra.now(),e=b.L.map(({content:f})=>f&&[f.id,f.amount,f.data]);e.length>0&&e[e.length-1]===null;)e.pop();N(`minicraft.world.${a.id}:meta`,Ta({p:{h:b.Pb,i:e,m:b.u,p:[b.M,b.N,b.O,b.Z,b.Aa]},s:[a.Ua,a.Va,a.Wa],t:a.time,v:1}));e=null;for(let f of a.da)f.o&&(e=Rc(a,f));yield e;X.ma(a.id,{mod_l:d});a.X=!1}}()),Tc=(a,b)=>{var c=Ua(L.getItem(`minicraft.world.${a.id}:meta`));if(c){let d=c.p,e=c.s,f=c.t;c.v!=null&&(d.i.forEach((g,l)=>{g&&(b.L[l].content=qc(g[0],g[1],g[2]))}),b.Pb=d.h,b.u=a.ra?
2:d.m,b.M=d.p[0],b.N=d.p[1],b.O=d.p[2],b.Z=d.p[3],b.Aa=d.p[4],a.Ua=e[0],a.Va=e[1],a.Wa=e[2],f!=null&&Sc(a,f))}},Sc=(a,b)=>{a.time=b%24E3;a.yb=(b+6E3)/24E3%1},Uc=(a,b,c)=>`${a}/${b}`+(c>0?"/"+c:""),Wc=a=>m(function*(){a.X=!0;var b=a.da[a.Ba[0].pb];yield bc(a.id,Uc(b.oa,b.za,b.y));b.oa++;a.Na=0;return Vc(a)}()),Rc=(a,b)=>m(function*(){++a.Wb;var c=a.$a,d=a.U,e=b.y,f=(256<<d)-256;for(let g=0,l=-1,h=((b.x<<d+4|b.z)<<6|e)<<2;g<16;++g){for(d=0;d<16;++d)Cc[++l]=c[h],Cc[++l]=c[++h],Cc[++l]=c[++h],Cc[++l]=
c[++h],h+=13;h+=f}b.o=!1;yield ac(a.id,Uc(b.oa,b.za,e),zc());--a.Wb}()),Vc=a=>m(function*(){a.X=!0;yield Qc(a,!0);a.X=!1}()),Qc=(a,b)=>m(function*(){for(var c=a.$a,d=a.da,e=a.Ba,f=a.$b,g=a.Qa,l=a.Ra,h=a.U,q=null,k=null,p=e.length;a.Na<p;){var r=e[a.Na++];let n=d[r.pb],B=n.y,w=g+r.Qa+n.x;r=l+r.Ra+n.z;if(w!==n.oa||r!==n.za){let u={Fb:n,data:"nope",oa:w,za:r};n.sa&&(q=f.findIndex(t=>t.Fb===n),f.splice(q,1));n.sa=!0;f.push(u);n.o&&(k=Rc(a,n));q=$b(a.id,Uc(n.oa=w,n.za=r,B)).then(t=>{u.data=t});if(!b&&
f.length>5)break}}b&&(yield q);for(d=0;f.length>0&&f[0].data!=="nope";){let {Fb:n,data:B,oa:w,za:u}=f.shift();if(n.sa&&n.oa===w&&n.za===u)if(n.sa=!1,e=(256<<h)-256,l=n.y,g=((n.x<<h+4|n.z)<<6|l)<<2,Ac(B)){n.ta=!0;for(let t=0,z=-1;t<16;++t){for(l=0;l<16;++l)c[g]=Cc[++z],c[++g]=Cc[++z],c[++g]=Cc[++z],c[++g]=Cc[++z],g+=13;g+=e}}else if(l===0)for(n.ta=!0,l=0;l<16;++l){for(p=0;p<16;++p)c[g]=50397446,c[++g]=131843,c[++g]=0,c[++g]=0,g+=13;g+=e}else if(n.ta)for(n.ta=!1,l=0;l<16;++l){for(p=0;p<16;++p)c[g]=
0,c[++g]=0,c[++g]=0,c[++g]=0,g+=13;g+=e}if(!b&&++d>5)break}b&&(yield k)}()),Xc=null,Yc=0,Zc=new cb,$c=a=>{if(a){let b=new Image;b.onload=()=>{if(W.ha===a){var c=sa.createElement("canvas");c.width=16;c.height=416;c=c.getContext("2d");c.scale(1,-1);for(let d=0;d<26;++d)c.drawImage(b,0,d<<4,16,16,0,-(d<<4)-16,16,16);Xc=new bb(c.getImageData(0,0,16,416).data.buffer);for(let d of Zc)d.o=!0;Yc=a;X.A({ha:0})}};b.onerror=()=>{W.ha===a&&(alert("\u00a1Error al cargar la superficie!"),ca(),X.T({V:Yc}),X.A({ha:0}),
da())};b.src=`/static/minicraft/textures/${a}.png`}else Xc=null},bd=(a,b)=>{var c={Zb:b,ob:b.getContext("2d",{alpha:!1,desynchronized:!0}),Db:null,Eb:null,sb:"",o:!1,Mb:0,tb:0,ac:ib(()=>(c.Mb=c.tb,c.tb=0),1E3),K:a};Zc.add(c);ad(c);return c},cd=(a,b)=>{++a.tb;var c=a.ob,d=a.Db,e=a.Eb,f=a.K,g=f.config,l=f.Pa,h=f.j,q=f.Sa,k=f.Ta,p=f.world,r=0;if(!f.G||a.o){a.o=!1;r=g.ua;let Bd=g.ia;var n=h.Z,B=h.Aa;let Cd=h.pa,Dd=h.qa,pb=h.u,qb=h.M,Ma=h.N,rb=h.O,Ed=l?h.ba:-1,Fd=p.ja;var w=p.U;let Gd=Xc!==null;var u=
1/q,t=1/k,z=q>>1,P=k>>1;let Gc=H(q,k),Hc=Gc>32,Ic=Fa(n);n=Ga(n);let Jc=Fa(-B);B=Ga(-B);var ua=2*Ia(g.Ha*za);let Hd=u*(q<k?ua*q*t:ua);u=t*(k<q?ua*k*u:ua);t=G(qb);ua=G(Ma);let Gb=G(rb);w=4+w;let Na=(1<<w)-1,Q=r<q?r:1,Id=q-Q,Kc=h.u===1?6:4,Wa=h.pa=h.qa=h.Ka=0;h.ba=-1;r=Ma<0||Ma>=64?0:Ec(p,t&Na,ua&63,Gb&Na);if(pb!==2&&r>0)h.pa=t&Na,h.ba=ua&63,h.qa=Gb&Na,h.Ka=6,e.fill(Fb[r]|4278190080);else{for(let Xa=0;Xa<k;++Xa){var sb=(P-Xa)*u;let Hb=sb*Jc-B;var Ib=sb*B+Jc;sb=Ib*n;Ib*=Ic;let ka=0,Oa=!1;var Ba=!1;a:for(let S=
0;S<q;S+=Q)for(let aa=Ba?1:0;aa<Q;++aa){if(Q<2)var K=S;else if(S===0)K=aa===0?0:aa===1?Q:aa-1,Oa=aa===1;else if(S<Id)K=(Oa=aa===1)?S+Q:S+aa-1;else{if((K=aa===0?S-1:S+aa)>=q)break a;Oa=!1}var T=(K-z)*Hd,la=sb+T*Ic,ma=Ib-T*n;T=16757124;Ba=1;let Jb=0;pb===2&&r>0&&(Jb=Aa()*Aa()*10);var Ca=1/Ha(la*la+Hb*Hb+ma*ma);la*=Ca;let na=Hb*Ca;ma*=Ca;Ca=la>0?1:la<0?-1:0;let Kb=na>0?1:na<0?-1:0,Lb=ma>0?1:ma<0?-1:0,Mb=Ca===0?1/0:Ca/la,Nb=Kb===0?1/0:Kb/na,Ob=Lb===0?1/0:Lb/ma,tb=t,Pa=ua,ub=Gb,Lc=la<0?(qb-tb)*Mb:(tb-
qb+1)*Mb,Pb=na<0?(Ma-Pa)*Nb:(Pa-Ma+1)*Nb,Qb=ma<0?(rb-ub)*Ob:(ub-rb+1)*Ob;for(;;){let ba=0,Ya=la;var M=Lc;Pb<M&&(ba=1,Ya=na,M=Pb);Qb<M&&(ba=2,Ya=ma,M=Qb);if(M>=Bd)break;ba===0?(tb+=Ca,Lc+=Mb):ba===1?(Pa+=Kb,Pb+=Nb):(ub+=Lb,Qb+=Ob);if(Pa<0){if(na>0)continue;break}if(Pa>=64){if(na<0)continue;break}let Rb=tb&Na,Sb=Pa&63,Tb=ub&Na,R=Fd[(Rb<<w|Tb)<<6|Sb];if(pb===2&&M<Jb)R===0&&(Jb=0);else if(R!==0){pb!==2&&Xa===P&&K===z&&M<=Kc&&(h.pa=Rb,h.ba=Sb,h.qa=Tb,h.Ka=Ya<0|ba<<1,Kc=M);if(Gd){--R;ba===1?R===6?R=25:
R===13?R=4:R===1&&na>0&&(R=2):R===1&&(R=24);let Ub=qb+la*M,Vb=rb+ma*M;M=Xc[R<<8|(G((ba===1?Vb:Ma+na*M)*16)&15)<<4|G((ba===1?Ub:Ya>0?Ub-Vb:Vb-Ub)*16)&15];if(M>>>24===0)continue;T=M&16777215}else T=Fb[R];Ba=(ba===0?.8:ba===2?.6:Ya>0?.4:1)+(Sb!==Ed||Rb!==Cd||Tb!==Dd?0:.2);break}}T=4278190080|H((T>>16)*Ba,255)<<16|H((T>>8&255)*Ba,255)<<8|H((T&255)*Ba,255);if(Ba=(Oa=Oa&&(Xa!==P||K<z||K>z+Q))&&ka===T){if(Q>6){e.fill(ka,Wa+S+1,Wa+S+Q+1);break}K=Wa+S+1;e[K]=ka;e[++K]=ka;if(Q<3)break;e[++K]=ka;if(Q<4)break;
e[++K]=ka;if(Q<5)break;e[++K]=ka;if(Q<6)break;e[++K]=ka;break}if(Oa||K===0)ka=T;e[Wa+K]=T}Wa+=q}l&&!Hc&&(e[q*P+z]^=16777215)}c.putImageData(d,0,0);l&&Hc&&(d=H(Da(Gc*.05),8),c.fillRect(z-d,P-1,d<<1,2),c.fillRect(z-1,P-d,2,d-1),c.fillRect(z-1,P+1,2,d-1))}Oc(p,h,!1);f.eb?(c=G(h.N)>>4,z=c>=0&&c<4&&p.Ba&&p.da[p.Ba[0].pb],P=[],z&&(z.o&&P.push("modified"),z.sa&&P.push("loading"),z.ta||P.push("empty")),a.sb=`minicraft 0.13.3 ${yb(a.Mb,"\u00a0")} fps, T: ${yb(p.yb*24,"0")}:${yb(p.yb*24%1*60,"0")}; ${f.G&&
b%1E3<500?"":p.time}${p.X?" busy":""}
R: ${q}x${k} (x${g.$}), D: ${g.ia}, C: ${p.Na}/${p.Ba.length}, M: ${zb(1<<4+p.U)*64>>10}k
E: 0/0, M: ${h.u}, I: ${r}

Position: ${h.M.toFixed(2)} ${h.N.toFixed(2)} ${h.O.toFixed(2)}
Angle: ${(h.Z*ya).toFixed(2)} ${(h.Aa*ya).toFixed(2)}
Focus: ${h.ba<0?"":"("+h.pa+" "+h.ba+" "+h.qa+") "+"WEBTSNI"[h.Ka]+": "+Db[Ec(p,h.pa,h.ba,h.qa)]}
Chunk abs: (${G(h.M)>>4} ${G(h.O)>>4} ${c}) ${z?"rel: ("+z.x+" "+z.z+" "+z.y+") "+P.join(" "):"void"}`):a.sb=""},ad=a=>{var b=a.Zb,c=a.K;a.Eb=new bb((a.Db=a.ob.createImageData(b.width=c.Sa,b.height=c.Ta)).data.buffer);var d=c.Sa*c.config.$/c.Ea,e=c.Ta*c.config.$/c.Ea;b.style.width=d+"px";b.style.height=e+"px";b.style.left=Ea((c.hb-d)/2)+"px";b.style.top=Ea((c.ib-e)/2)+"px";a.ob.fillStyle="rgba(255,255,255,.5)"},dd=0,gd=(a,b,{config:c,account:d})=>{var e=Dc(c.Ia);d=tc(e,d);Tc(e,d);var f={config:c,
Gb:0,Hb:0,eb:!1,Pa:!0,G:!0,Nb:a,la:0,fa:new cb,ub:"",l:0,messages:[],j:d,wb:null,B:null,Ea:1,hb:1,ib:1,Sa:0,Ta:0,jb:0,Tb:0,kb:0,jc:ib(()=>{var g;(g=f.G)||(e.o=!0,Sc(e,e.time+1),g=void 0);return g},50),Xa:b,world:e};ed(f,null);fd(f);return f},fd=a=>{m(function*(){if(!a.config.Ca)try{yield a.Nb.requestPointerLock()}catch(b){}}())},hd=(a,b)=>a===b?0:.1-a*.2,id=a=>{a.j.lb=hd((a=a.fa).has(-12)||a.has(65),a.has(-13)||a.has(68))},jd=a=>{a.j.Cb=hd((a=a.fa).has(-15)||a.has(16),a.has(-14)||a.has(32))},kd=a=>
{a.j.mb=hd((a=a.fa).has(-11)||a.has(83),a.has(-10)||a.has(87))},ld=a=>{a.j.Ub=hd(a.fa.has(-18),a.fa.has(-19))},md=a=>{a.j.Vb=hd(a.fa.has(-17),a.fa.has(-16))},od=(a,b,c)=>{if(!a.world)return!1;var d=a.fa,e=a.j;if(c){if(d.has(b))return!1;d.add(b);var f=e.pa,g=e.ba;c=e.qa;switch(b){case -18:case -19:ld(a);break;case -17:case -16:md(a);break;case -1:!a.world.ra&&e.u!==2&&g>=0&&(e.fb===0?e.u===0&&(b=Ec(a.world,f,g,c),b===2?b=3:b===1&&(b=4),b===15||b===6||b!==8&&b!==13&&sc(e.L,qc(b,1))!==null)||(Fc(a.world,
f,g,c),e.ba=-1):nd(a,[f,g,c],!1));break;case -2:case 71:if(g>=0){let l=Ec(a.world,f,g,c);c=e.L.slice(0,9);g=c.findIndex(h=>h.content!==null&&h.content.id===l);g>=0?e.P=g:e.u===1&&(c[e.P].content&&(c=c.findIndex(h=>h.content===null),c>=0&&(e.P=c)),e.L[e.P].content=qc(l));e.Fa=a.la}break;case -3:if(!a.world.ra&&e.u!==2&&g>=0)if(e.fb===0){if(b=e.L[e.P],b.content){switch(e.Ka){case 0:--f;break;case 1:++f;break;case 2:--g;break;case 3:++g;break;case 4:--c;break;case 5:++c}g>=0&&g<64&&Mc(a.world,f&(1<<
4+a.world.U)-1,g,c&(1<<4+a.world.U)-1,b.content.id)&&e.u!==1&&--b.content.amount<=0&&(b.content=null)}}else nd(a,[f,g,c],!0);break;case -4:e.P=(e.P+9-1)%9;e.Fa=a.la;break;case -5:e.P=(e.P+1)%9;e.Fa=a.la;break;case 27:a.l===0&&(a.G=!0,a.l=1);break;case -15:case -14:case 16:case 32:jd(a);break;case 49:case 50:case 51:case 52:case 53:case 54:case 55:case 56:case 57:e.P=b-49;e.Fa=a.la;break;case -12:case -13:case 65:case 68:id(a);break;case 69:if(a.l===0){a.l=3;for(let l of d)od(a,l,!1)}break;case 70:a.Xa.Ob();
break;case 80:a.world&&(a.G=!0);break;case 81:e=e.L[e.P];if(d.has(17)||e.content&&--e.content.amount<=0)e.content=null;break;case -11:case -10:case 83:case 87:kd(a);break;case 84:if(a.l===0){a.l=2;for(let l of d)od(a,l,!1)}break;case 112:a.Pa=!a.Pa;break;case 114:a.eb=!a.eb;case 116:case 122:case 123:break;default:return!1}}else{if(!d.delete(b))return!1;switch(b){case -15:case -14:case 16:case 32:jd(a);break;case -12:case -13:case 65:case 68:id(a);break;case -11:case -10:case 83:case 87:kd(a);break;
case -18:case -19:ld(a);break;case -17:case -16:md(a)}}a.ub=[...d].join();return!0},pd=(a,b)=>(b=b.startsWith("~")?a+U(b.slice(1)):U(b),isNaN(b)?a:b),rd=(a,b)=>{var c=a.j,d=a.world;if(b)if(b.charAt(0)==="/"){b=b.slice(1).split(" ");let e=b.shift();switch(e){case "clear":a.messages=[];break;case "clearinv":for(let f of c.L)f.content=null;Z(a,"Inventario vaciado.",!0);break;case "gamemode":case "gm":b=U(b[0]);!isNaN(b)&&b>=0&&b<3&&b%1===0?(c.u=b,Z(a,"Modo de juego establecido: "+b,!0)):Z(a,"\u00a1El modo de juego debe estar entre 0 y 2!");
break;case "give":if(b.length===0){Z(a,"/give <id> [Cantidad]\n"+Db.join(" "));break}d=Db.indexOf((b[0]||"").toLowerCase());d=d>=0?d:U(b[0]);b=U(b[1]||1);!isNaN(d)&&d>0&&d<25&&d%1===0?!isNaN(b)&&b>0&&b%1===0?Z(a,sc(c.L,qc(d,b))?"\u00a1El inventario est\u00e1 lleno!":`Se han dado ${b} ${Eb[d]}`,!0):Z(a,"\u00a1La cantidad debe ser al menos 1!"):Z(a,"\u00a1Tipo de bloque no v\u00e1lido!");break;case "help":Z(a,"Comandos: clear, clearinv, gamemode, give, help, load, me, save, spawn, teleport, time, version, view_distance");
break;case "load":if(d.X){Z(a,"\u00a1Sin permisos!");break}Vc(d).then(()=>{a.B.o=!0;Z(a,"Chunks cargados.",!0)});break;case "me":Z(a,c.name+" "+b.join(" "),!0);break;case "save":if(a.world.ra||d.X){Z(a,"\u00a1Sin permisos!");break}Nc(a.world,a.j,!1);Z(a,"Juego guardado.",!0);break;case "spawn":if(a.world.ra){Z(a,"\u00a1Sin permisos!");break}d.Ua=c.M;d.Va=c.N;d.Wa=c.O;Z(a,"Punto de aparici\u00f3n actualizado.",!0);break;case "teleport":case "tp":b.length===0?(c.M=d.Ua,c.N=d.Va,c.O=d.Wa,a.B.o=!0,Z(a,
"Teletransportado al punto de aparici\u00f3n.",!0)):b.length===3?(Z(a,`Teletransportado a ${c.M=pd(c.M,b[0])} ${c.N=pd(c.N,b[1])} ${c.O=pd(c.O,b[2])}`,!0),a.B.o=!0):Z(a,"\u00a1Mala suerte!");c.va=0;c.wa=0;c.xa=0;break;case "time":c=b[1];if(!c){Z(a,"\u00a1Falta par\u00e1metro!");break}if(c==="day")c=1E3;else if(c==="night")c=13E3;else if(isNaN(c=G(U(c))))break;switch(b[0]){case "add":c+=d.time;case "set":Sc(d,c);Z(a,"Hora establecida: "+d.time,!0);break;default:Z(a,"Comando desconocido: time "+b[0])}break;
case "view_distance":case "vd":c=U(b[0]);if(isNaN(c)||c<0)break;X.T({ia:c});Z(a,"Distancia de visi\u00f3n: "+c,!0);break;case "version":Z(a,"minicraft 0.13.3");break;case "_w":X.lc({type:b[0]==="m"?1:0});break;case "/exit":c.fb=0;Z(a,"Modo de rat\u00f3n normal.",!0);break;case "/expand":a.j.La&&a.j.Ma?d=!0:(Z(a,"\u00a1Se requiere selecci\u00f3n!"),d=!1);d&&(b[0]==="vert"?(c.La[1]=0,c.Ma[1]=63,Z(a,"Selecci\u00f3n ampliada.",!0)):Z(a,'\u00a1Solo se admite "vert"!'));break;case "/pos1":case "/pos2":nd(a,
[G(c.M),G(c.N),G(c.O)],e==="/pos2");break;case "/regen":if(a.world.ra||d.X){Z(a,"\u00a1Sin permisos!");break}Wc(d).then(()=>{a.B.o=!0;Z(a,"Chunk regenerado.",!0)});break;case "/show":Z(a,`Principal: ${c.La?c.La.join(" "):"ninguno"}, Secundario: ${c.Ma?c.Ma.join(" "):"ninguno"}`);break;case "/wand":c.fb=1;Z(a,"Selecci\u00f3n usando los botones del rat\u00f3n.",!0);break;default:Z(a,"Comando desconocido: "+e)}}else{let e=Z(a,`<${c.name}> `+b);ed(a,b).then(f=>{f&&qd(a,e)})}},Z=(a,b,c=!1)=>{var d=++dd;
(a.messages=a.messages.slice(-49)).push({id:d,Qb:c,time:ra(),value:b});return d},qd=(a,b)=>{var c=a.messages.findIndex(d=>d.id===b);c>=0&&a.messages.splice(c,1)},nd=(a,b,c)=>{c?a.j.Ma=b:a.j.La=b;Z(a,`${c?"Punto secundario":"Punto principal"}: ${b.join(" ")}`,!0)},ed=(a,b)=>(jb(a.wb),a.wb=hb(ed,5E3,a,null),(b?O("/api/chat",Object.assign({},wb,{body:Ta({msg:b})})):O("/api/chat")).then(c=>c.ok&&c.text()).then(c=>{if(c){c=c.split("\n").filter(Boolean);for(let d of c)d.startsWith("<")&&Z(a,d);return c.length>
0}return!1}).catch(()=>!1)),sd=({id:a,W:b})=>(x("div[className=bitmap]",{S:{backgroundImage:`url(/static/minicraft/textures/${b}.png)`,backgroundPositionY:100-a*100+"%"}}),null);function td({amount:a,u:b,id:c,W:d}){x("div[className=stack]",{title:Eb[c]+(b===1?` (${Db[c]}, ${c})`:"")});return[C(sd,{id:c,W:d}),a!==1&&D("div[className=amount]",{innerText:a})]}
function ud({j:a,W:b,Ga:c,H:d}){x("table[className=bar]",{ontouchstart:oa(g=>{a.P=Number(g.target.closest("[data-slot]").dataset.slot);a.Fa=g.timeStamp}),S:{left:I(0,d/2-180)+"px",opacity:I(.5,H(1,1-(c-a.Fa-5E3)*5E-4))}});var e=A(g=>({height:g=g-8+"px",width:g}),[H(d/9,40)]),f=a.u;return[D("tr",null,a.L.slice(0,9).map(({content:g},l)=>D("td",{D:{slot:l},F:{active:l===a.P},S:e},[g&&C(td,{amount:g.amount,data:g.data,u:f,id:g.id,W:b}),!g&&D("div[className=stack]")])))]}
var vd=$a(4).fill(null).map((a,b)=>$a(9).fill(null).map((c,d)=>b*9+d));vd.push(vd.shift());function wd({fc:a,W:b,hc:c}){x("table",{onclick:({target:e})=>{e.className==="bitmap"&&rc({content:qc(U(e.parentElement.parentElement.dataset.id)),filter:null,ca:64},a);return!1}});var d=0;return $a(3).fill(null).map(()=>D("tr",null,$a(9).fill(null).map(()=>++d<25&&D("td",{D:{id:d},S:c},[C(td,{amount:1,data:null,u:1,id:d,W:b})]))))}
var xd={fontSize:"",height:"32px",width:"32px"},yd={fontSize:"75%",height:"16px",width:"16px"};
function zd({K:a,W:b,ya:c,H:d}){var e=A(()=>({content:null,filter:null,ca:64})),f=a.j.u;x("div[className=menu]",A(()=>({onclick:({target:h})=>{if(h.className==="menu")e.content?e.content=null:(a.l=0,a.G=!1,fd(a));else if(h.parentElement.className==="stack"&&h.parentElement.parentElement.dataset.slot||h.tagName==="TD")h=a.j.L[U((h.tagName==="TD"?h:h.parentElement.parentElement).dataset.slot)],e.content?rc(e,h):h.content&&rc(h,e)},oncontextmenu:({target:h})=>{if(h.className==="menu")e.content?--e.content.amount<=
0&&(e.content=null):(a.l=0,a.G=!1,fd(a));else if(h.parentElement.className==="stack"&&h.parentElement.parentElement.dataset.slot||h.tagName==="TD")h=a.j.L[U((h.tagName==="TD"?h:h.parentElement.parentElement).dataset.slot)],e.content?rc(e,h,1):h.content&&rc(h,e,Da(h.content.amount/2))}})));var g,l;[g,l]=A(()=>{var h=H(d,c)<400;return[{left:`${d/2-(h?96:168)}px`,top:`${c/2-(h?91:147)}px`},h?yd:xd]},[c,d]);return[D("div[className=window]",{S:g},[D("h2[innerText=Inventario]"),f===1&&C(wd,{fc:e,W:b,hc:l}),
D("table",null,vd.map((h,q)=>D(q<3?"tr":"tr[className=last]",null,h.map(k=>D("td",{D:A(()=>({slot:k})),S:l},[(k=a.j.L[k].content)&&C(td,{amount:k.amount,data:k.data,u:f,id:k.id,W:b})])))))]),e.content&&D("div[className=hand]",{S:{left:a.Gb+"px",top:a.Hb+"px"}},[C(td,{amount:e.content.amount,data:e.content.data,u:0,id:e.content.id,W:b})])]}
function Ad({I:{Qb:a,time:b,value:c},Ga:d}){b=H(1,1-(d-b-4500)*.001);x(a?"div[className=minor]":"div",{S:{opacity:b}});return[D("div[className=backdrop]"),D("span",{innerText:c})]}function Jd({messages:a,Ga:b}){x("div[className=messages]");return[qa(Ad,a.slice(-10).filter(c=>c.time>b-5E3),{Ga:b})]}function Kd({I:a,current:b,ha:c}){x("tr");return[D("td",null,[D("button",{disabled:a.id===b||c>0,innerText:`${a.label} (${a.owner})`,onclick:()=>{ca();X.T({V:a.id});X.A({ha:a.id});da()}})])]}
function Ld({K:a,state:{config:b,ha:c},aa:d}){a&&y(()=>{Nc(a.world,a.j,!1)});var e,f;[e,f]=ja(!1);var g=ea(()=>e?O("/static/minicraft/textures.json").then(Cb).catch(()=>null):J.resolve(null),[e],null);x("div[className=menu]");return[D("h1",{innerText:e?"Superficies":"Ajustes"}),D("div[className=row]",null,[D("button",{innerText:a&&!e?"Volver al juego":"Volver",onclick:()=>{e?f(!1):a?(a.l=0,a.G=!1,fd(a)):d(2)}})]),!e&&D("table[className=settings]",null,[D("tr",null,[D("td",null,[D("button[innerText=Superficies...]",
{onclick:()=>{f(!0)}})]),D("td",null,[D("label[htmlFor=setting-resolution]",{innerText:`Resoluci\u00f3n: 1:${b.$}\n`}),D("input[id=setting-resolution][type=range][min=1][max=20][step=1]",{value:21-b.$,onchange:l=>X.T({$:21-Number(l.target.value)})})])]),D("tr",null,[D("td",null,[D("label[htmlFor=setting-view-angle]",{innerText:`\u00c1ngulo de visi\u00f3n: ${b.Ha}\n`}),D("input[id=setting-view-angle][type=range][min=1][max=180][step=1]",{value:b.Ha,onchange:l=>X.T({Ha:Number(l.target.value)})})]),
D("td",null,[D("label[htmlFor=setting-view-distance]",{innerText:`Distancia de visi\u00f3n: ${b.ia}\n`}),D("input[id=setting-view-distance][type=range][min=16][max=128][step=16]",{value:b.ia,onchange:l=>X.T({ia:Number(l.target.value)})})])]),D("tr",null,[D("td",null,[D("label[htmlFor=setting-pixel-grouping]",{innerText:`Agrupaci\u00f3n de p\u00edxeles: ${b.ua===1?"Desactivado":b.ua}\n`}),D("input[id=setting-pixel-grouping][type=range][min=1][max=8][step=1]",{value:b.ua,onchange:l=>X.T({ua:Number(l.target.value)})})]),
D("td",null,[D("label[htmlFor=setting-mouse-sensitivity]",{innerText:`Sensibilidad del rat\u00f3n: ${b.Da}\n`}),D("input[id=setting-mouse-sensitivity][type=range][min=1][max=15][step=1]",{value:b.Da,onchange:l=>X.T({Da:Number(l.target.value)})})])]),D("tr",null,[D("td",null,[D("button[innerText=Versi\u00f3n 0.13.3][title=P\u00e1gina del proyecto]",{onclick:()=>{open("//github.com/L3P3/minicraft")}})])])]),a&&!e&&D("div[className=row]",null,[D("button[innerText=Salir del mundo]",{onclick:()=>{d(2)}})]),
e&&D("table[className=settings]",null,[D("tr",null,[D("td",null,[D("button[innerText=Liso]",{disabled:b.V===0,onclick:()=>{ca();X.T({V:0});X.A({ha:0});da()}})])]),g&&qa(Kd,g,{current:b.V,ha:c})]),e&&g&&D("div[className=row]",null,[D("button[innerText=A\u00f1adir superficie]",{onclick:()=>{open("//l3p3.de/svr/minicraft/textures.html")}})])]}
var Md=({K:a,dc:b,H:c})=>[D("div[className=toolbar]",null,[D("button[innerText=\u274c]",{onclick:()=>{a.l=0;a.G=!1;fd(a)}})]),D("input[autocomplete=off][enterkeyhint=send][mozactionhint=send][name=message][required]",{onkeydown:d=>{var e=d.keyCode;d=d.target;e===13?(rd(a,d.value),d.value=""):e===27&&(a.l=0,a.G=!1,fd(a))},R:d=>{b.input=d;hb(()=>d.focus(),0)},S:{width:`${c-40}px`}})],Nd=({I:{Qb:a,value:b}})=>(x(a?"div[className=minor]":"div",{innerText:b}),null);
function Od({K:a,messages:b,H:c}){var d=oa({history:null,input:null});x("div[className=menu terminal]",{onclick:e=>{e.target!==d.input&&d.input.focus()}});y(e=>{e&&hb(()=>d.history.scrollTop=1E9,0)},[b.length&&b[b.length-1].id]);return[D("div[className=history]",{R:oa(e=>{d.history=e})},[qa(Nd,b)]),C(Md,{K:a,dc:d,H:c})]}var Pd=[["pick",-2],["up",-14],["down",-15],["E",69],["T",84],["F1",112],["F3",114],["...",27]],Qd=[D("div")];
function Rd({K:a,H:b}){var c=a.fa;x("div[className=touch]",oa({ontouchstart:l=>{var h=l.target.dataset.code||l.target.parentElement.dataset.code;if(h!=null&&od(a,h=U(h),!0)){let q=l.changedTouches[0].identifier,k=p=>{p.changedTouches[0].identifier===q&&(lb("touchend",k),od(a,h,!1))};kb("touchend",k)}return!1}}));var d,e;[d,e]=A(l=>[{height:l-8+"px"},{width:l+="px",height:l}],[H(Ea(b/10),40)]);var f,g;[f,g]=A(()=>{var l=b>300?"14px":"0",h=b>300?"2px":"0",q=b>650?l:"40px";return[{borderSpacing:h,bottom:q,
left:l},{borderSpacing:h,bottom:q,right:l}]},[b]);return[D("div[className=top]",null,Pd.map(([l,h])=>D(`div[innerText=${l}]`,{D:{code:h},F:{button:!0,active:c.has(h)}}))),D("table[className=move]",{S:f},[D("tr",null,[D("td"),D("td",{D:{code:-10},F:{"button up":!0,active:c.has(-10)},S:e},Qd)]),D("tr",null,[D("td",{D:{code:-12},F:{"button left":!0,active:c.has(-12)},S:e},Qd),D("td",null,[D("div",{D:{code:-1},F:{"button center":!0,active:c.has(-1)},S:d},Qd)]),D("td",{D:{code:-13},F:{"button right":!0,
active:c.has(-13)},S:e},Qd)]),D("tr",null,[D("td"),D("td",{D:{code:-11},F:{"button down":!0,active:c.has(-11)},S:e},Qd)])]),D("table[className=move]",{S:g},[D("tr",null,[D("td"),D("td",{D:{code:-16},F:{"button up":!0,active:c.has(-16)},S:e},Qd)]),D("tr",null,[D("td",{D:{code:-18},F:{"button left":!0,active:c.has(-18)},S:e},Qd),D("td",null,[D("div",{D:{code:-3},F:{"button center":!0,active:c.has(-3)},S:d},Qd)]),D("td",{D:{code:-19},F:{"button right":!0,active:c.has(-19)},S:e},Qd)]),D("tr",null,[D("td"),
D("td",{D:{code:-17},F:{"button down":!0,active:c.has(-17)},S:e},Qd)])])]}function Sd({model:a}){var b=x("canvas");a.B=bd(a,b);return null}
function Td({frame:a,ea:b,state:c,aa:d,ya:e,H:f,Xa:g}){var l=c.config,h=ra(),q=sa.pointerLockElement===a,k=A(()=>gd(a,g,c));y(()=>{Ud.add(k);var r=u=>{if(k.l!==0)return!0;sa.pointerLockElement===a?od(k,-1-u.button,u.type==="mousedown"):fd(k);return!1},n=u=>{if(sa.pointerLockElement===a){var t=k.config.Da*wa/(I(k.hb,k.ib)*k.Ea);vb&&(k.Tb=u.timeStamp);uc(k.j,k.jb=u.movementX*t,k.kb=-u.movementY*t)}else t=k.Nb.getBoundingClientRect(),k.Gb=u.clientX-t.left,k.Hb=u.clientY-t.top},B=u=>{X.bb(!1);if(k.l===
0&&!k.G&&va(u.deltaY)>5)return u=u.deltaY>0?-5:-4,od(k,u,!0),od(k,u,!1),!1},w={passive:!0};a.addEventListener("mousedown",r);a.addEventListener("mouseup",r);a.addEventListener("mousemove",n,w);a.addEventListener("wheel",B,w);return()=>{a.removeEventListener("mousedown",r);a.removeEventListener("mouseup",r);a.removeEventListener("mousemove",n,w);a.removeEventListener("wheel",B,w);jb(k.wb);jb(k.jc);Nc(k.world,k.j,!0);Bc.delete(k.world.id);X.A({Za:[...Bc.keys()]});var u=k.B;Zc.delete(u);jb(u.ac);return Ud.delete(k)}});
y(()=>{k.config=l;k.B&&(k.B.o=!0);var r=k.world,n=Da(Ja(k.config.ia/16*2+2));r.U!==n&&Pc(r,k.j,n)},[l]);y((r,n,B)=>{k.Ea=B||1;k.hb=I(1,r);k.ib=I(1,n);n=k.config.$;r=Da(k.hb*k.Ea/n);n=Da(k.ib*k.Ea/n);if(r!==k.Sa||n!==k.Ta)k.Sa=r,k.Ta=n,k.B&&(k.B.o=!0,ad(k.B))},[a.offsetWidth,a.offsetHeight,E.devicePixelRatio,l.$]);y(()=>{b&&od(k,b.code,b.state)},[b]);y(r=>{r||k.G||k.l!==0||(k.l=1,vb&&k.jb|k.kb&&k.Tb>h-100&&(uc(k.j,-k.jb,-k.kb),k.jb=k.kb=0,k.B.o=!0));k.G=!r},[l.Ca&&k.l===0||q]);y(r=>q&&r&&sa.exitPointerLock(),
[k.G||k.l!==0]);h===k.la||Vd||(k.world&&(k.la&&!k.G&&vc(k.j,h-k.la),k.B&&cd(k.B,h)),k.la=h);ia();var p=oa({zb:1});l.V&&(p.zb=l.V);return[C(Sd,{model:k}),k.Pa&&k.l!==2&&k.messages.length>0&&k.messages[k.messages.length-1].time>h-5E3&&C(Jd,{messages:k.messages,Ga:h}),k.B&&k.eb&&D("div[className=diagnostics]",{innerText:k.B.sb}),l.Ca&&C(Rd,{K:k,ub:k.ub,H:f}),k.Pa&&k.l!==3&&k.j.u!==2&&C(ud,{j:k.j,W:p.zb,Ga:h,H:f}),(k.l===1||k.l===2||k.l===3)&&D("div[className=backdrop]"),k.l===3&&C(zd,{K:k,W:p.zb,Ga:h,
ya:e,H:f}),k.l===1&&C(Ld,{K:k,state:c,aa:d}),k.l===2&&C(Od,{K:k,messages:k.messages,H:f})]}
var Wd=({account:a,busy:b,nb:c,cc:d,aa:e,world:f,Bb:g})=>(x("div"),[D("button[innerText=Entrar]",{disabled:b||d||f.local<2||f.remote>f.local,onclick:()=>{ca();X.T({Ia:f.id});e(0);da()},title:d?"\u00a1El mundo ya est\u00e1 abierto!":f.local<2?"\u00a1El mundo a\u00fan no se ha descargado!":f.local<f.remote?"\u00a1El mundo a\u00fan se est\u00e1 cargando!":"Entrar al mundo seleccionado"}),D("button",{disabled:b||!V||d||f.local>0&&f.remote>0||!f.remote&&!a.rank,innerText:f.local?V&&f&&!f.remote?"Subir":
"Transferir":"Descargar",onclick:()=>{f.local?f.remote||X.ma(f.id,{mod_r:1}):X.Xb({id:f.id,label:f.label,mod_l:1,mod_r:f.remote})},title:V?f.local?f.remote?"\u00a1El mundo est\u00e1 presente en ambos lados!":d?"\u00a1El mundo ya est\u00e1 abierto!":a.rank?"Subir mundo al servidor":"\u00a1Sesi\u00f3n no iniciada!":"Descargar mundo del servidor":"\u00a1La lista se est\u00e1 cargando!"}),D("button[innerText=Renombrar]",{disabled:b||d||!f.writable,onclick:()=>{var l=ob("Nueva etiqueta del mundo:\n(m\u00e1x. 16 caracteres)",
f.label);!l||l===f.label||l.length>16||(f.local&&X.ma(f.id,{label:l}),f.remote&&(c(!0),O("/api/minicraft/world",Object.assign({},wb,{body:Ta({what:"meta",world:f.id,label:l})})).then(Cb).catch(h=>{mb("Error al editar el mundo: "+h.message)}).then(()=>{c(!1)})))},title:f.writable?d?"\u00a1El mundo ya est\u00e1 abierto!":"Cambiar nombre del mundo":"\u00a1Sin permisos!"}),D("button",{disabled:b||!f.remote||!f.writable,innerText:`Bloqueado: ${f.locked?"S\u00ed":"No"}`,onclick:()=>{c(!0);O("/api/minicraft/world",
Object.assign({},wb,{body:Ta({what:"meta",world:f.id,locked:!f.locked})})).then(l=>(l=Cb(l),ca(),kc(),c(!1),da(),l)).catch(l=>{mb("Error al editar el mundo: "+l.message);c(!1)})},title:f.remote?f.writable?f.locked?"Desbloquear mundo":"Bloquear mundo":"\u00a1Sin permisos!":"\u00a1El mundo no se ha subido!"}),D("button",{disabled:b||!f.remote||!f.writable,innerText:`P\u00fablico: ${f.public?"S\u00ed":"No"}`,onclick:()=>{c(!0);O("/api/minicraft/world",Object.assign({},wb,{body:Ta({what:"meta",world:f.id,
public:!f.public})})).then(l=>(l=Cb(l),ca(),kc(),c(!1),da(),l)).catch(l=>{mb("Error al editar el mundo: "+l.message);c(!1)})},title:f.remote?f.writable?f.public?"Despublicar mundo":"Publicar mundo":"\u00a1Sin permisos!":"\u00a1El mundo no se ha subido!"}),D("button",{disabled:b||d||!f.local&&!f.writable,innerText:f.local?"Eliminar (local)":"Eliminar",onclick:()=>{nb('\u00bfRealmente deseas eliminar el mundo "'+f.label+'"?')&&(f.local?(ec(f.id),X.Yb(f.id)):(c(!0),O("/api/minicraft/world",{method:"DELETE",
headers:{"Content-Type":"application/json"},body:Ta({what:"world",world:f.id})}).then(l=>(Cb(l),ca(),g(null),kc(),c(!1),da())).catch(l=>{mb("Error al eliminar el mundo: "+l.message);c(!1)})))},title:d?"\u00a1El mundo ya est\u00e1 abierto!":f.local||f.writable?"Eliminar mundo":"\u00a1Sin permisos!"})]),Xd=a=>{a.scrollIntoView(xb)},Yd=(a,b)=>{a&&hb(Xd,0,b)};
function Zd({I:a,account:b,busy:c,nb:d,aa:e,qc:f,Bb:g,na:l,Za:h}){f=a===f;var q=x("tr",{F:{selected:f},onclick:()=>{g(a.id)}});y(Yd,[f,q]);return[D("td[style=width:0]",{innerText:`${a.local?"L":"_"}${a.local&&a.remote?a.local>a.remote?">":a.local<a.remote?"<":"=":"_"}${a.remote?a.public?"R":"r":"_"}`,S:{color:l===a.id?"yellow":a.local!==a.remote&&a.local&&a.remote?"red":""}}),D("td",{innerText:a.label,title:a.id},[f&&C(Wd,{account:b,busy:c,nb:d,cc:h.includes(a.id),aa:e,world:a,Bb:g})]),D("td[style=width:0]",
null,[D("div[title=Modificado]",{innerText:Bb(I(a.local,a.remote),!0)}),f&&D("div",{innerText:a.account_name?a.account_name:"-",title:a.account_name?"Propietario":"Solo un mundo local"})])]}
function $d({state:{account:a,config:b,ka:c,Ab:d,Ja:e,na:f,Ya:g,Za:l},view:h,aa:q,ya:k,H:p}){var r,n;[r,n]=ja(b.Ia);y(()=>{ic&&r===ic[0]&&n(ic[1])},[ic]);var B=A(()=>g.find(t=>t.id===r)||null,[r,g]),w,u;[w,u]=ja(!1);x("div",{F:{menu:!0,blurred:h===1}});return[D("button[innerText=Ajustes][style=position:absolute]",{onclick:()=>{q(1)}}),D("button[style=position:absolute;right:0]",{disabled:a.rank>0,innerText:a.rank?a.label:"Iniciar sesi\u00f3n",onclick:()=>{location.href="/account?redir=minicraft"}}),
D("h1[innerText=Mundos]"),D("div[className=row]",null,[D("button[innerText=Actualizar][title=Recargar lista]",{disabled:d||e||c!==null,onclick:kc}),D("button[innerText=Nuevo mundo]",{onclick:()=>{var t=ob("Etiqueta del nuevo mundo:\n(m\u00e1x. 16 caracteres)","Nuevo mundo");t&&(t.length>16?mb("\u00a1El nombre es demasiado largo!"):X.Xb({id:H(0,...b.worlds.map(z=>z.id))-1,label:t,mod_l:Ra.now(),mod_r:0}))}})]),D("div[className=worlds]",{S:{height:`${I(100,k-140)}px`,width:`${H(480,p-16)}px`}},[D("table[cellSpacing=0]",
null,[qa(Zd,g,{rc:Ra.now(),account:a,busy:w,nb:u,aa:q,qc:B,Bb:n,na:f,Za:l})])])]}
function ae({ea:a,state:b,ya:c,H:d,Xa:e}){var f,g;[f,g]=ja(2);y(()=>{e.kc(f===0?b.Ya.find(h=>h.id===b.config.Ia).label+" \u2013 minicraft":"minicraft")},[f]);var l=x("div[className=game]");return[(f===2||f===1)&&C($d,{state:b,view:f,aa:g,ya:c,H:d}),f===1&&D("div[className=backdrop]"),f===1&&C(Ld,{K:null,state:b,aa:g}),f===0&&C(Td,{frame:l,ea:a,state:b,aa:g,ya:c,H:d,Xa:e}),f===2&&b.ka&&D("div[style=position:absolute;bottom:0;left:0;color:yellow]",{title:b.ka},[D("span[innerText=Error de conexi\u00f3n. ]"),
D("button[innerText=Reintentar]",{onclick:()=>{X.A({ka:null})}})])]}
var be="nwse-resize ns-resize nesw-resize ew-resize move ew-resize nesw-resize ns-resize nwse-resize".split(" "),ce={init:(a,b)=>ce.xb({cb:0,Oa:0,height:0,ea:null,left:0,mode:b,title:"...",top:0,width:0},600,400),Ob:a=>Object.assign({},a,{mode:a.mode===0?1:0}),bc:(a,b)=>a.ea&&a.ea.code===b.code&&a.ea.state===b.state?a:Object.assign({},a,{ea:b}),Sb:(a,b,c)=>Object.assign({},a,{left:I(0,H(b,W.Y-a.width)),top:I(0,H(c,W.ga-a.height))}),gb:(a,b)=>Object.assign({},a,b),xb:(a,b,c)=>Object.assign({},a,{Oa:b=
I(100,H(b,W.Y-a.left)),cb:c=I(50,H(c,W.ga-a.top)),width:b,height:c}),kc:(a,b)=>Object.assign({},a,{title:b})},de=(a,b,c)=>{X.mc(b);var d=c.target;if(d.className==="window_title")d=d.parentElement;else if(c.button!==0||d.className!=="window borders")return;c.preventDefault();sa.activeElement.blur();var e,f;[e,f]=a;var g=c.clientX,l=c.clientY,h=g-e.left,q=l-e.top,k=h<8?0:h<e.width-8?1:2,p=q<8?0:q<e.height-8?1:2,r=k+p*3;d.style.willChange=r===4?"left,top":"contents";X.A({cursor:be[r]});var n=w=>{Vd=
!0;ca();var u=w.clientX,t=w.clientY;a:if(r===4){if(w.type==="mouseup"){if(t<4){f.gb({left:0,top:0,width:W.Y,height:W.ga});break a}if(u<4){f.gb({left:0,top:0,width:Da(W.Y/2),height:W.ga});break a}if(u>W.Y-3){f.gb({left:Da(W.Y/2),top:0,width:G(W.Y/2),height:W.ga});break a}}else if([w]=a,w.Oa!==w.width||w.cb!==w.height){f.xb(w.Oa,w.cb);let [z]=a;h=Ea(h*z.Oa/w.width)}f.Sb(u-h,t-q)}else k!==0&&p!==0||f.Sb(k===0?(u=I(h,H(u,e.left+e.width-100+h)))-h:e.left,p===0?(t=I(q,H(t,e.top+e.height-50+q)))-q:e.top),
f.xb(k===0?e.width+e.left+h-u:k===1?e.width:e.width-g+u,p===0?e.height+e.top+q-t:p===1?e.height:e.height-l+t);da();Vd=!1},B=w=>{lb("mousemove",n,!0);lb("mouseup",B);X.A({cursor:null});n(w);d.style.willChange="auto"};kb("mousemove",n,!0);kb("mouseup",B)},ee=({height:a,left:b,mode:c,top:d,width:e},f)=>({F:{window:!0,borders:c===1},onmousedown:f,S:{display:c===2?"none":"block",left:c===0?"0":b-1+"px",top:c===0?"0":d-1+"px",height:c===0?"100%":a-40+"px",width:c===0?"100%":e-16+"px"}}),fe=({title:a,width:b,
nc:c})=>[D("div[className=window_title]",{innerText:a,S:{width:`${b-40}px`}}),D("div[className=window_button]",{onclick:()=>X.oc(c)})];
function ge({I:{id:a,Rb:b,type:c},state:d}){var e=fa(ce,b),f,g;[f,g]=e;y(()=>(he.set(a,g),()=>he.delete(a)));b=A(()=>de.bind(null,e,a));x("div",A(ee,[f,b]));var l=ha(!0,!1);y((q,k)=>{l&&g.gb({left:I(0,H(f.left,q-f.width)),top:I(0,H(f.top,k-f.height)),width:H(q,I(100,f.Oa,f.width)),height:H(k,I(50,f.cb,f.height))})},[d.Y,d.ga]);b=f.mode===0?d.Y:f.width-16;var h=f.mode===0?d.ga:f.height-40;return[c===1&&C(ae,{ea:f.ea,state:d,ya:h,H:b,Xa:g}),f.mode!==0&&C(fe,{title:f.title,width:f.width,nc:a})]}
var Ud=new cb,he=new db,Vd=!1,ie=0,je=0,ke=()=>{X.bb(!0)},le=a=>{a.timeStamp-ie>999&&X.bb(!1)};
function me(){[W,X]=fa(pc);y(()=>{jc(!0);var b=!1;E.onunload=onbeforeunload=onpagehide=onblur=()=>{if(!b){b=!0;for(let d of Ud)Nc(d.world,d.j,!0);X.qb()}};onpageshow=onfocus=()=>(b=!1,onresize());E.onorientationchange=onresize=()=>{Vd=!0;X.ec(La?La.width:E.innerWidth,La?La.height:E.innerHeight);Vd=!1};ib(()=>(onresize(),X.qb(),!Qa&&L.getItem("minicraft.lock_requested")&&(Va("minicraft.lock_requested"),N("minicraft.lock",Ra.now()))),200);kb("touchend",d=>{ie=d.timeStamp},!0);var c=d=>{var e=d.type===
"keydown";if(e&&d.target.tagName==="INPUT")return!0;Vd=!0;X.bb(!1);if(W.J.length>0){let f=he.get(W.J[W.J.length-1].id);d.key!=="f"?f.bc({code:d.keyCode,state:e}):e&&f.Ob()}return Vd=!1};eb.assign(sa.body,{style:"background:green",onkeydown:c,onkeyup:c,oncontextmenu:Ab,ondragstart:Ab})});var a=W.config.Ca;y(()=>{a?(kb("mousedown",le,!0),kb("mouseup",le,!0),lb("touchstart",ke,!0)):(lb("mousedown",le,!0),lb("mouseup",le,!0),kb("touchstart",ke,!0))},[a]);y($c,[W.config.V]);y(()=>{jb(je);W.ka||(je=hb(oc))},
[W.ka,W.Ya]);return[qa(ge,W.J,{state:W}),W.cursor&&D("div[className=cursormask]",{S:{cursor:W.cursor}})]}function ne(){close();return[D("h1[innerText=\u00a1minicraft ya se est\u00e1 ejecutando!]")]}
if(Qa){let a=new Qa("minicraft.lock"),b=hb(()=>Zb.then(()=>pa(me)),100);a.addEventListener("message",c=>{c.data==="yes"?(jb(b),a.close(),pa(ne)):(a.postMessage("yes"),focus())});a.postMessage("anyone there?")}else{N("minicraft.lock_requested","1");let a=Ra.now(),b=0,c=ib(()=>{U(L.getItem("minicraft.lock"))>a?(jb(c),pa(ne)):++b>4&&(jb(c),Zb.then(()=>pa(me)))},250)};

//# sourceMappingURL=app-es.js.map
