function m(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(k){k.done?d(k.value):Promise.resolve(k.value).then(b,c).then(f,e)}f(a.next())})}
var v=lui,aa=v.defer,ba=v.defer_end,ca=v.hook_async,y=v.hook_dom,z=v.hook_effect,A=v.hook_memo,da=v.hook_model,ha=v.hook_prev,ia=v.hook_rerender,ja=v.hook_state,ka=v.hook_static,la=v.init,B=v.node,C=v.node_dom,ma=v.node_map,na=v.now,qa=window,ra=document,sa=navigator,D=Math,ta=D.PI,ua=ta*.5,va=180/ta,wa=D.random,E=D.floor,xa=D.ceil,ya=D.round,F=D.min,G=D.max,Ba=D.cos,Ca=D.sin,Da=D.sqrt,Ea=D.log2,Fa=String.fromCharCode,Ga=qa.BroadcastChannel,Ha=Date,La=JSON,J=Promise,Ma=La.stringify,Na=La.parse,K=
localStorage,Oa=K.setItem.bind(K),Pa=K.removeItem.bind(K),Qa=qa.indexedDB||null,M=fetch,Ra=Array,Sa=Uint8Array,Ta=Uint32Array,ab=Set,bb=Map,N=Number,cb=Object,db=cb.keys,eb=cb.entries,fb=setTimeout,gb=setInterval,hb=clearTimeout,ib=clearInterval,jb=addEventListener,kb=removeEventListener,lb=alert,rb=confirm,sb=prompt,tb=sa.userAgent.includes("WebKit"),ub={method:"POST",headers:{"Content-Type":"application/json"}},vb={behavior:"smooth",block:"center",container:"nearest"},wb=(a,b)=>(a=E(a).toString(),
a.length<2?b+a:a),xb=a=>a*a,yb=()=>!1,zb=(a,b)=>{if(a<2)return"...";var c=new Ha;a=new Ha(a);var d=c-a;if(d<59E3)return ya(d/1E3)+"s";if(d<3E6)return ya(d/6E4)+"m";d=a.getFullYear();var e=a.getMonth(),f=a.getDate(),k="";d<c.getFullYear()&&(k=d+"/");if(k||e<c.getMonth())k+=e+1+"/";if(k||f<c.getDate())k+=f;if(b)return k||"today";k&&(k+="/");return k+a.getHours()+":"+wb(a.getMinutes(),"0")},Ab=a=>{if(!a.ok)throw Error(a.status===403?"Missing permission. Logged in?":"Connection error.");return a.json()},
Gb="air stone grass dirt cobble planks bedrock log leaves bricks wool sand gravel glass bookshelf obsidian stone_bricks sandstone lapis_block iron_block gold_block diamond_block emerald_block redstone_block quartz_block".split(" "),Hb=[0,8487297,4305266,4349313,8092539,5342114,7039851,3561583,4172910,6384533,15526888,10671324,8092798,16447200,4151672,1970708,8092539,9686227,9126695,15198183,5567485,14541182,7920469,662956,14936813],Ib=null,Jb=Qa?new J(a=>{var b,c;(b=sa.storage)==null||(c=b.persist)==
null||c.call(b);b=Qa.open("minicraft",1);b.onupgradeneeded=d=>{d=d.target.result.createObjectStore("chunks",{keyPath:["world","coords"]});for(let e of db(K))if(e.startsWith("minicraft.world.")){let [f,k]=e.slice(16).split(":",2);k!=="meta"&&(d.add({world:N(f),coords:k,data:K.getItem(e)}),Pa(e))}};b.onsuccess=d=>{Ib=d.target.result;a()}}):J.resolve(void 0),Kb=Qa?(a,b)=>new J(c=>{var d=Ib.transaction("chunks","readonly").objectStore("chunks").get([a,b]);d.onsuccess=()=>{var e;return c((e=d.result)==
null?void 0:e.data)}}):(a,b)=>{a=K.getItem(`minicraft.world.${a}:${b}`);return J.resolve(a)},Lb=Qa?(a,b,c)=>new J((d,e)=>{var f=Ib.transaction("chunks","readwrite").objectStore("chunks").put({world:a,coords:b,data:c});f.onsuccess=()=>d();f.onerror=()=>e(f.error)}):(a,b,c)=>(Oa(`minicraft.world.${a}:${b}`,c),J.resolve(void 0)),Mb=Qa?(a,b)=>new J((c,d)=>{var e=Ib.transaction("chunks","readwrite").objectStore("chunks").delete([a,b]);e.onsuccess=()=>c();e.onerror=()=>d(e.error)}):(a,b)=>(Pa(`minicraft.world.${a}:${b}`),
J.resolve(void 0)),Nb=Qa?a=>new J(b=>{var c=K.getItem(`minicraft.world.${a}:meta`);if(!c)return b({});var d=Ib.transaction("chunks","readonly").objectStore("chunks").openCursor(),e={meta:c};d.onsuccess=()=>{var f=d.result;f?(f.value.world===a&&(e[f.value.coords]=f.value.data),f.continue()):b(e)}}):a=>{a=`minicraft.world.${a}:`;var b=a.length,c={};for(let d of db(K))d.startsWith(a)&&(c[d.slice(b)]=K.getItem(d));return J.resolve(c)},Ob=Qa?(a,b)=>new J((c,d)=>{var e=Ib.transaction("chunks","readwrite"),
f=e.objectStore("chunks");for(let [k,l]of eb(b))k!=="meta"?f.put({world:a,coords:k,data:l}):Oa(`minicraft.world.${a}:meta`,l);e.oncomplete=()=>c();e.onerror=()=>d(e.error)}):(a,b)=>m(function*(){for(let [c,d]of eb(b))Oa(`minicraft.world.${a}:${c}`,d);Oa("__margin",Ra(257).join("x"));Pa("__margin")}()),Pb=Qa?a=>{var b=Ib.transaction("chunks","readwrite").objectStore("chunks").openCursor();b.onsuccess=()=>{var c=b.result;c&&(c.value.world===a&&c.delete(),c.continue())};Pa(`minicraft.world.${a}:meta`)}:
a=>{a=`minicraft.world.${a}:`;for(let b of db(K))b.startsWith(a)&&Pa(b)},Qb=Qa?(a,b)=>new J(c=>{var d=Ib.transaction("chunks","readwrite").objectStore("chunks"),e=d.openCursor();e.onsuccess=()=>{var f=e.result;f?(f.value.world===a&&(f.delete(),f.value.world=b,d.put(f.value)),f.continue()):c()};Oa(`minicraft.world.${b}:meta`,K.getItem(`minicraft.world.${a}:meta`));Pa(`minicraft.world.${a}:meta`)}):(a,b)=>{a=`minicraft.world.${a}:`;var c=a.length;for(let d of db(K))if(d.startsWith(a)){let e=K.getItem(d);
Pa(d);Oa(`minicraft.world.${b}:${d.slice(c)}`,e)}return J.resolve(void 0)},S=null,Rb=0,Sb=null,Ub=()=>{T.Ea||T.ma!==null||(hb(Rb),U.o({Ab:!0,Ea:!0}),Tb(!1))},Tb=a=>{m(function*(){Rb=fb(U.o,5E3,{Ab:!1});try{let b=yield M(`/api/minicraft/world?what=${a?"initia":"meta_al"}l`),c=yield Ab(b);a?c.version_latest!=="0.12.0"?location.reload(!0):(S=c.worlds,U.o(Object.assign({},{account:c.account,Ea:!1},Vb(T.config)))):(S=c,U.o(Object.assign({},{Ea:!1},Vb(T.config))))}catch(b){U.o({ha:"Error while loading world list: "+
b.message,Ea:!1})}}())},Wb=(a,b)=>G(b.local,b.remote)-G(a.local,a.remote),Vb=a=>{var b=S?S.map(c=>({account_name:c.account_name,hash:c.hash,id:c.id,label:c.label,local:0,public:c.public,remote:c.modified,writable:c.writable})):[];for(let c of a.worlds){let d=b.find(e=>e.id===c.id);if(d){let e=d.local=c.mod_l,f=d.remote,k=c.mod_r;e>k&&f>k&&(rb('Conflict! The world "'+c.label+'" was modified here and somewhere else.\nOK: Take variant from server ('+zb(f,!1)+") | Cancel: Keep local variant ("+zb(e,!1)+
")")?a=Object.assign({},a,{worlds:a.worlds.map(l=>l.id===c.id?Object.assign({},l,{mod_l:d.local=k}):l)}):d.remote=k)}else c.mod_r>1&&S&&(lb('The world "'+c.label+'" was not found on the server, so it is a local world now.'),a=Object.assign({},a,{worlds:a.worlds.map(e=>e.id===c.id?Object.assign({},e,{mod_r:0}):e)})),b.push({account_name:"",hash:0,id:c.id,label:c.label,local:c.mod_l,public:!1,remote:c.mod_r===1?1:0,writable:!0})}return{config:a,Ta:b.sort(Wb)}},Yb=()=>m(function*(){if(T.ma===null){var a;
try{for(;a=T.Ta.find(b=>b.local>0&&b.remote>0&&b.local!==b.remote);)yield Xb(a);U.o({ma:null})}catch(b){U.o({ha:b.message,ma:null})}}}()),Xb=a=>m(function*(){var b=a.id;U.o({ma:b});if(a.local<a.remote)try{yield Ob(b,yield Ab(yield M(`/static/minicraft/worlds/${a.hash}.json`))),U.la(b,{mod_l:a.remote,mod_r:a.remote})}catch(c){if(c.name==="QuotaExceededError")lb("Insufficient storage!"),Pb(b),U.Ub(b);else throw Error("Error while downloading world: "+c.message);}else if(a.writable){let c=b,d=null;try{let e=
Nb(b);if(a.remote===1){let k=yield Ab(yield M("/api/minicraft/world",Object.assign({},ub,{body:Ma({what:"meta",label:a.label})})));d=Qb(b,c=k.id);Sb=[b,c];U.la(b,{id:c})}let f=yield Ab(yield M("/api/minicraft/world",Object.assign({},ub,{body:Ma({what:"data",world:c,data:yield e})})));a.remote===1?S.push(f):Object.assign(S.find(k=>k.id===b),f);U.la(c,{mod_l:f.modified,mod_r:f.modified})}catch(e){throw U.la(b,{mod_r:0}),Error("Error while uploading world: "+e.message);}yield d}else U.la(b,{mod_l:a.remote})}()),
V=Na(K.getItem("minicraft.config")||null);if(V&&V.worlds&&V.version.startsWith("0.9.")){let a=new ab(V.worlds.map(b=>"minicraft.world."+b.id));for(let b of db(K))b.startsWith("minicraft.world.")&&!a.has(b.split(":",1)[0])&&Pa(b)}
var Zb={init:()=>{var a=!1,b={xa:!1,pa:1,ya:3,Y:4,U:1,Ca:120,ka:64,Da:0,worlds:[]};if(V){let c=V.pixel_grouping;c!=null&&(b.pa=c);(c=V.mouse_sensitivity)!=null&&(b.ya=c);b.Y=V.resolution_scaling;(c=V.textures)!=null?b.U=c:b.U=V.flag_textures?1:0;b.Ca=V.view_angle;b.ka=V.view_distance;(c=V.world_last)!=null&&(b.Da=c);(c=V.worlds)?b.worlds=c:K.getItem("minicraft.world.0:meta")&&(b.worlds[0]={id:0,label:(sb("There was an unnamed world found. How should it be called?","")||"Unknown world").substring(0,
16),mod_l:Ha.now(),mod_r:0},a=!0);V=null}b=Object.assign({},{account:{label:"",rank:0},config:b,rb:b,ha:null,cursor:null,ja:qa.innerHeight,Z:qa.innerWidth,ea:b.U,J:[{id:0,Ob:0,type:1}],Ab:!0,Ea:!0,ma:null,Ua:[]},Vb(b));return a?(b.rb=null,Zb.qb(b)):b},qb:a=>{var b=a.config;if(b===a.rb)return a;Oa("minicraft.config",Ma({version:"0.12.0",pixel_grouping:b.pa,mouse_sensitivity:b.ya,resolution_scaling:b.Y,textures:b.U,view_angle:b.Ca,view_distance:b.ka,world_last:b.Da,worlds:b.worlds}));return Object.assign({},
a,{rb:b})},lc:(a,b)=>Zb.W(a,b(a.config)),W:(a,b)=>Object.assign({},a,{config:Object.assign({},a.config,b)}),Za:(a,b)=>a.config.xa===b?a:Zb.W(a,{xa:b}),o:(a,b)=>Object.assign({},a,b),dc:(a,b)=>(ra.activeElement.blur(),Object.assign({},a,{J:[...a.J,Object.assign({},{id:G(-1,...a.J.map(c=>c.id))+1,Ob:1,type:0},b)]})),hc:(a,b)=>Object.assign({},a,{J:a.J.filter(c=>c.id!==b)}),ec:(a,b)=>a.J[a.J.length-1].id===b?a:Object.assign({},a,{J:[...a.J.filter(c=>c.id!==b),a.J.find(c=>c.id===b)]}),Tb:(a,b)=>Object.assign({},
a,Vb(Object.assign({},a.config,{worlds:[...a.config.worlds,b]}))),Ub:(a,b)=>Object.assign({},a,Vb(Object.assign({},a.config,{worlds:a.config.worlds.filter(c=>c.id!==b)}))),la:(a,b,c)=>Object.assign({},a,Vb(Object.assign({},a.config,{worlds:a.config.worlds.map(d=>d.id===b?Object.assign({},d,c):d)})))},T,U,$b=(a,b=1,c=null)=>({amount:b,data:c,id:a}),ac=(a,b,c=a.content.amount)=>{if(b.content)a.content.id===b.content.id?(c=F(c,b.ba-b.content.amount),a.content.amount-=c,b.content.amount+=c,a.content.amount<=
0&&(a.content=null)):!(a.content.amount<=c&&a.content.amount<=b.ba&&b.content.amount<=a.ba)||a.filter&&!a.filter(b.content.id)||b.filter&&!b.filter(a.content.id)||([b.content,a.content]=[a.content,b.content]);else if(!b.filter||b.filter(a.content.id))a.content.amount<=c&&a.content.amount<=b.ba?[b.content,a.content]=[a.content,b.content]:(c=F(c,b.ba),a.content.amount-=c,b.content=$b(a.content.id,c),a.content.amount<=0&&(a.content=null))},bc=(a,b)=>{for(let c of a)if(c.content&&c.content.id===b.id){let d=
F(b.amount,c.ba-c.content.amount);c.content.amount+=d;if((b.amount-=d)<=0)return null}for(let c of a)if(!c.content&&(!c.filter||c.filter(b.id)))if(a=F(b.amount,c.ba),a<=b.amount){if(c.content=$b(b.id,a),(b.amount-=a)<=0)return null}else return c.content=b,null;return b},cc=(a,b)=>({mb:0,Cb:0,nb:0,X:0,ua:0,Fa:0,na:0,aa:-1,oa:0,Ga:null,Ha:null,l:1,Mb:20,L:Ra(36).fill(null).map(()=>({content:null,filter:null,ba:64})),fb:0,name:b.label||"Player",M:a.Pa,N:a.Qa,O:a.Ra,Rb:0,Sb:0,T:0,Aa:0,qa:0,ra:0,sa:0}),
ec=(a,b)=>{b=F(5,b*.01);a.qa-=a.qa*.1*b;a.ra-=a.ra*.1*b;a.sa-=a.sa*.1*b;a.qa+=(Ba(a.X)*a.mb+Ca(a.X)*a.nb)*b;a.ra+=a.Cb*b;a.sa+=(-Ca(a.X)*a.mb+Ba(a.X)*a.nb)*b;dc(a,a.Rb*b*1.5,a.Sb*b*1.5);a.M+=a.qa*b;a.N+=a.ra*b;a.O+=a.sa*b},dc=(a,b,c)=>{a.X=(a.X+b+ta*100)%(ta*2);a.ua=G(-ua,F(ua,a.ua+c))},fc=a=>{a+=32;a>33&&a<39?a++:a>38&&a<44?a+=2:a>43&&a<127?a+=3:a>126&&a<55258?a+=37:a>55295&&(a+=8485);return Fa(a)},hc=a=>a-(a>63743?8517:a>159?69:a>46&&a<130?35:a>40&&a<46?34:a>34&&a<40?33:32),jc=()=>{var a=ic,b=a.length,
c=new bb,d=t=>{h=h<<1|t&1;++r===15&&(n+=fc(h),h=r=0)},e=()=>{for(let t=0;t<p;++t)d(0)},f=t=>{d(t);d(t>>1);d(t>>2);d(t>>3);d(t>>4);d(t>>5);d(t>>6);d(t>>7)},k=()=>{--q===0&&(q=1<<p++)},l=()=>{if(w)w=!1;else{let t=u.id;for(let L=0;L<p;L++)d(t>>L)}},g=a[0],n="",h=0,r=2,p=2,q=2,x=2,u={id:x++,Xa:new bb},w=!0;f(g);c.set(g,u);for(let t=1;t<b;++t){let L=u.Xa.get(g=a[t]);L?u=L:(l(),c.has(g)||(k(),e(),f(g),c.set(g,{id:x++,Xa:new bb}),w=!0),u.Xa.set(g,{id:x++,Xa:new bb}),u=c.get(g),k())}l();c.has(g)||(k(),e(),
f(g));k();d(1);--p;e();return n+=fc(h<<15-r)},kc=a=>{var b=ic;if(!a)return null;var c=a.length,d=()=>{r+=(x>>--u&1)<<p++;u===0&&(u=15,x=hc(a.charCodeAt(q++)))},e=[0,1],f=1,k=3,l=2,g=null,n=null,h=0,r=0;n=2;for(var p=0,q=0,x=hc(a.charCodeAt(q++)),u=15;p<n;)d();if(r===1)return null;for(r=p=0;p<8;)d();g=[r];e[2]=g;for(b[h++]=r;q<=c;){n=l;for(r=p=0;p<n;)d();if(r===0){for(r=p=0;p<8;)d();e[k]=[r];r=k++;--f===0&&(f=1<<l++)}else if(r===1)return b;n=r<e.length?e[r]:g.concat(g[0]);for(let w=0;w<n.length;w++)b[h++]=
n[w];e[k++]=g.concat(n[0]);g=n;--f===0&&(f=1<<l++)}return null},lc=new bb,mc=new Ta(1024),ic=new Sa(mc.buffer),nc=new bb,oc=a=>{var b={fa:null,Wa:null,busy:!1,ga:null,Ya:null,Ia:0,G:!1,wa:!T.Ta.find(c=>c.id===a).writable,bb:0,cb:0,eb:0,id:a,La:0,Ma:0,P:0,Pa:.5,Qa:8.5,Ra:.5,time:0,yb:0};lc.set(a,b);U.o({Ua:[...lc.keys()]});return b},Ac=(a,b,c,d)=>c<0||c>63?0:a.fa[(b<<a.P+4|d)<<6|c],Bc=(a,b,c,d)=>{var e=a.P;a.fa[(b<<e+4|d)<<6|c]=0;a.ga[(b>>4<<e|d>>4)<<2|c>>4].va=!0},Cc=(a,b,c,d,e)=>{var f=a.P,k=(b<<
f+4|d)<<6|c;if(a.fa[k]>0)return!1;a.fa[k]=e;return a.ga[(b>>4<<f|d>>4)<<2|c>>4].va=!0},Fc=(a,b,c)=>{m(function*(){a.ga&&(yield Dc(a,b));var d=1<<(a.P=c),e=a.ga=[];for(let f=0;f<d;++f)for(let k=0;k<d;++k)for(let l=0;l<4;++l)e.push({va:!1,loaded:!1,x:f,y:l,z:k,Va:0,lb:0});d<<=c+12+2;a.fa===null||a.fa.length<d?a.Wa=new Ta((a.fa=new Sa(d)).buffer):a.Wa.fill(0);Ec(a,b,!0)}())},Ec=(a,b,c)=>{var d=G(F(b.N,63),0)>>4,e=E(b.M)>>4;b=E(b.O)>>4;if(c||a.cb!==d||a.La+a.bb!==e||a.Ma+a.eb!==b)c=1<<a.P,a.cb=d,a.La=
e-(a.bb=(65536+e)%c),a.Ma=b-(a.eb=(65536+b)%c),Gc(a);a.busy||Hc(a,!1)},Gc=a=>{var b=a.bb,c=a.cb,d=a.eb,e=a.P,f=`${e} ${b} ${d} ${c}`,k=nc.get(f);if(k==null){let l=1<<e,g=xb(l*.5);nc.set(f,k=a.ga.map(({x:n,y:h,z:r},p)=>{var q=xb(n-b),x=xb(r-d),u=xb(n-b-l),w=0,t=0;u<q&&(q=u,w=-l);(u=xb(n-b+l))<q&&(q=u,w=l);(u=xb(r-d-l))<x&&(x=u,t=-l);(u=xb(r-d+l))<x&&(x=u,t=l);return{sb:q+x+xb(h-c),Fb:p,La:w,Ma:t}}).filter(({sb:n})=>n<=g).sort((n,h)=>n.sb-h.sb))}a.Ya=k;a.Ia=0},Dc=(a,b)=>m(function*(){if(!a.wa&&a.G){a.G=
!1;for(var c=Ha.now(),d=b.L.map(({content:e})=>e&&[e.id,e.amount,e.data]);d.length>0&&d[d.length-1]===null;)d.pop();Oa(`minicraft.world.${a.id}:meta`,Ma({p:{h:b.Mb,i:d,m:b.l,p:[b.M,b.N,b.O,b.X,b.ua]},s:[a.Pa,a.Qa,a.Ra],t:a.time,v:1}));yield J.all(a.ga.filter(e=>e.va).map(e=>Ic(a,e)));U.la(a.id,{mod_l:c})}}()),Kc=(a,b)=>{var c=Na(K.getItem(`minicraft.world.${a.id}:meta`));if(c){let d=c.p,e=c.s,f=c.t;c.v!=null&&(d.i.forEach((k,l)=>{k&&(b.L[l].content=$b(k[0],k[1],k[2]))}),b.Mb=d.h,b.l=d.m,b.M=d.p[0],
b.N=d.p[1],b.O=d.p[2],b.X=d.p[3],b.ua=d.p[4],a.Pa=e[0],a.Qa=e[1],a.Ra=e[2],f!=null&&Jc(a,f))}},Jc=(a,b)=>{a.time=b%24E3;a.yb=(b+6E3)/24E3%1},Lc=a=>m(function*(){var b=a.ga[a.Ya[a.Ia=0].Fb],c=b.y;yield Mb(a.id,`${b.Va}/${b.lb}`+(c>0?"/"+c:""));b.va=!1;++b.Va;return Hc(a,!1)}()),Ic=(a,b)=>{var c=a.Wa,d=a.P,e=b.y,f=(256<<d)-256;for(let k=0,l=-1,g=((b.x<<d+4|b.z)<<6|e)<<2;k<16;++k){for(d=0;d<16;++d)mc[++l]=c[g],mc[++l]=c[++g],mc[++l]=c[++g],mc[++l]=c[++g],g+=13;g+=f}b.va=!1;return Lb(a.id,`${b.Va}/${b.lb}`+
(e>0?"/"+e:""),jc())},Hc=(a,b)=>m(function*(){for(var c=a.ga,d=a.Ya,e=a.La,f=a.Ma,k=d.length;a.Ia<k;){var l=d[a.Ia++],g=c[l.Fb],n=g.loaded,h=g.x;let x=g.y;var r=g.z,p=e+l.La+h;let u=f+l.Ma+r;if(!n||p!==g.Va||u!==g.lb){g.loaded=a.busy=!0;l=g.va&&Ic(a,g);var q=a.id;p=g.Va=p;g=g.lb=u;g=kc(yield Kb(q,`${p}/${g}`+(x>0?"/"+x:"")));yield l;a.busy=!1;if(n||x===0||g){l=a.Wa;p=a.P;q=(256<<p)-256;h=((h<<p+4|r)<<6|x)<<2;if(g)for(let w=0,t=-1;w<16;++w){for(n=0;n<16;++n)l[h]=mc[++t],l[++h]=mc[++t],l[++h]=mc[++t],
l[++h]=mc[++t],h+=13;h+=q}else for(r=0;r<16;++r){for(g=0;g<16;++g)l[h]=x>0?0:50397446,l[++h]=x>0?0:131843,n?(l[++h]=0,l[++h]=0,h+=13):h+=15;h+=q}if(!b)break}}}}()),Mc=null,Nc=0,Oc=new ab,Pc=a=>{if(a){let b=new Image;b.onload=()=>{if(T.ea===a){var c=ra.createElement("canvas");c.width=16;c.height=416;c=c.getContext("2d");c.scale(1,-1);for(let d=0;d<26;++d)c.drawImage(b,0,d<<4,16,16,0,-(d<<4)-16,16,16);Mc=new Ta(c.getImageData(0,0,16,416).data.buffer);for(let d of Oc)d.G=!0;Nc=a;U.o({ea:0})}};b.onerror=
()=>{T.ea===a&&(alert("Error while loading surface!"),aa(),U.W({U:Nc}),U.o({ea:0}),ba())};b.src=`/static/minicraft/textures/${a}.png`}else Mc=null},Rc=(a,b)=>{var c={Vb:b,pb:b.getContext("2d",{alpha:!1,desynchronized:!0}),Db:null,Eb:null,Ib:"",G:!1,Jb:0,tb:0,Wb:gb(()=>(c.Jb=c.tb,c.tb=0),1E3),K:a};Oc.add(c);Qc(c);return c},Sc=(a,b)=>{++a.tb;var c=a.pb,d=a.Db,e=a.Eb,f=a.K,k=f.config,l=f.Ka,g=f.g,n=f.Na,h=f.Oa,r=f.world,p=0;if(!f.A||a.G){a.G=!1;var q=k.pa;let od=k.ka;var x=g.X,u=g.ua;let pd=g.na,qd=
g.oa,Ua=g.l;var w=g.M;p=g.N;var t=g.O;let rd=l?g.aa:-1,sd=r.fa;var L=r.P;let td=Mc!==null;var mb=1/n,za=1/h;let ea=n>>1,oa=h>>1,pc=F(n,h),qc=pc>32,rc=Ba(x);x=Ca(x);let sc=Ba(-u);u=Ca(-u);var Ia=k.Ca/45;let ud=mb*(n<h?Ia*n*za:Ia);mb=za*(h<n?Ia*h*mb:Ia);w+=65536;za=p+65536;t+=65536;Ia=w%1;let vd=za%1,wd=t%1;L=4+L;let Ja=(1<<L)-1;q=q<n?q:1;let xd=n-q,tc=g.l===1?6:4,Va=g.na=g.oa=g.Fa=0,uc=0;g.aa=-1;p=p<0||p>=64?0:Ac(r,w&Ja,za&63,t&Ja);if(Ua!==2&&p>0)g.na=w&Ja,g.aa=za&63,g.oa=t&Ja,g.Fa=6,e.fill(Hb[p]|
4278190080);else{for(let Wa=0;Wa<h;++Wa){var nb=(oa-Wa)*mb;let vc=nb*sc-u;var Bb=nb*u+sc;nb=Bb*x;Bb*=rc;let fa=0,Ka=!1;var Xa=!1;a:for(let O=0;O<n;O+=q)for(let W=Xa?1:0;W<q;++W){if(q<2)var H=O;else if(O===0)H=W===0?0:W===1?q:W-1,Ka=W===1;else if(O<xd)H=(Ka=W===1)?O+q:O+W-1;else{if((H=W===0?O-1:O+W)>=n)break a;Ka=!1}var P=(H-ea)*ud;Xa=nb+rc*P;let wc=Bb-x*P,yd=uc;P=16757124;let ob=1,xc=od,pb=0;Ua===2&&p>0&&(pb=wa()*10);for(let Cb=0;Cb<3;++Cb){let Q=(yd+Cb)%3,X=wc;var I=wd;Q===0&&(X=Xa,I=Ia);Q===1&&
(X=vc,I=vd);var pa=-1/X;X>0&&(I=1-I,pa*=-1);let qb=Xa*pa,Aa=vc*pa;pa*=wc;let yc=Da(qb*qb+Aa*Aa+pa*pa),Ya=w+qb*I-(Q===0&X<0|0),Za=za+Aa*I-(Q===1&X<0|0),$a=t+pa*I-(Q===2&X<0|0);I*=yc;for(let Db,Eb,Fb,R;I<xc;Ya+=qb,Za+=Aa,$a+=pa,I+=yc)if(!(Ua===2&&I<pb))if(Za<65536){if(Aa<0)break}else if(Za>=65600){if(Aa>0)break}else if((R=sd[((Db=Ya&Ja)<<L|(Fb=$a&Ja))<<6|(Eb=Za&63)])!==0){Ua!==2&&Wa===oa&&H===ea&&I<=tc&&(g.na=Db,g.aa=Eb,g.oa=Fb,g.Fa=X<0|Q<<1,tc=I);if(td){--R;Q===1?R===6?R=25:R===13?R=4:R===1&&Aa>0&&
(R=2):R===1&&(R=24);let zc=Mc[R<<8|((Q===1?$a:Za)*16&15)<<4|(Q===1?Ya:(X>0?Ya-$a:$a-Ya)+65536)*16&15];if(zc>>>24===0)continue;P=zc&16777215}else P=Hb[R];xc=I;ob=(Q===0?.8:Q===2?.6:X>0?.4:1)+(Eb!==rd||Db!==pd||Fb!==qd?0:.2);uc=Q;break}else Ua===2&&I<pb&&(pb=I)}P=4278190080|F((P>>16)*ob,255)<<16|F((P>>8&255)*ob,255)<<8|F((P&255)*ob,255);if(Xa=(Ka=Ka&&(Wa!==oa||H<ea||H>ea+q))&&fa===P){if(q>6){e.fill(fa,Va+O+1,Va+O+q+1);break}H=Va+O+1;e[H]=fa;e[++H]=fa;if(q<3)break;e[++H]=fa;if(q<4)break;e[++H]=fa;if(q<
5)break;e[++H]=fa;if(q<6)break;e[++H]=fa;break}if(Ka||H===0)fa=P;e[Va+H]=P}Va+=n}l&&!qc&&(e[n*oa+ea]^=16777215)}c.putImageData(d,0,0);l&&qc&&(d=F(xa(pc*.05),8),c.fillRect(ea-d,oa-1,d<<1,2),c.fillRect(ea-1,oa-d,2,d-1),c.fillRect(ea-1,oa+1,2,d-1))}a.Ib=f.ab?`minicraft 0.12.0 ${wb(a.Jb,"\u00a0")} fps, T: ${wb(r.yb*24,"0")}:${wb(r.yb*24%1*60,"0")}; ${f.A&&b%1E3<500?"":r.time}
R: ${n}x${h} (x${k.Y}), D: ${k.ka}, C: ${r.Ia}/${r.Ya.length}, M: ${xb(1<<4+r.P)*64>>10}k
E: 0/0, M: ${g.l}, I: ${p}

Position: ${g.M.toFixed(2)} ${g.N.toFixed(2)} ${g.O.toFixed(2)}
Angle: ${(g.X*va).toFixed(2)} ${(g.ua*va).toFixed(2)}
Focus: ${g.aa<0?"":g.na+" "+g.aa+" "+g.oa+" "+"WEBTSNI"[g.Fa]+": "+Gb[Ac(r,g.na,g.aa,g.oa)]}
Chunk abs: ${E(g.M)>>4} ${E(g.O)>>4} ${E(g.N)>>4} rel: ${r.bb} ${r.eb} ${r.cb}`:""},Qc=a=>{var b=a.Vb,c=a.K;a.Eb=new Ta((a.Db=a.pb.createImageData(b.width=c.Na,b.height=c.Oa)).data.buffer);var d=c.Na*c.config.Y/c.za,e=c.Oa*c.config.Y/c.za;b.style.width=d+"px";b.style.height=e+"px";b.style.left=ya((c.hb-d)/2)+"px";b.style.top=ya((c.ib-e)/2)+"px";a.pb.fillStyle="rgba(255,255,255,.5)"},Tc=0,Wc=(a,b,{config:c,account:d})=>{var e=oc(c.Da),f=cc(e,d);Kc(e,f);var k={config:c,Gb:0,Hb:0,ab:!1,Ka:!0,A:!0,Kb:a,
ia:0,da:new ab,ub:"",j:0,H:[],g:f,wb:null,u:null,za:1,hb:1,ib:1,Na:0,Oa:0,jb:0,Qb:0,kb:0,bc:gb(()=>{var l;(l=k.A)||(e.G=!0,Jc(e,e.time+1),Ec(e,f,!1),l=void 0);return l},50),Sa:b,world:e};Uc(k,null);Vc(k);return k},Vc=a=>{m(function*(){if(!a.config.xa)try{yield a.Kb.requestPointerLock()}catch(b){}}())},Xc=(a,b)=>a===b?0:.1-a*.2,Yc=a=>{a.g.mb=Xc((a=a.da).has(-12)||a.has(65),a.has(-13)||a.has(68))},Zc=a=>{a.g.Cb=Xc((a=a.da).has(-15)||a.has(16),a.has(-14)||a.has(32))},$c=a=>{a.g.nb=Xc((a=a.da).has(-11)||
a.has(83),a.has(-10)||a.has(87))},ad=a=>{a.g.Rb=Xc(a.da.has(-18),a.da.has(-19))},bd=a=>{a.g.Sb=Xc(a.da.has(-17),a.da.has(-16))},dd=(a,b,c)=>{if(!a.world)return!1;var d=a.da,e=a.g;if(c){if(d.has(b))return!1;d.add(b);var f=e.na,k=e.aa;c=e.oa;switch(b){case -18:case -19:ad(a);break;case -17:case -16:bd(a);break;case -1:!a.world.wa&&e.l!==2&&k>=0&&(e.fb===0?e.l===0&&(b=Ac(a.world,f,k,c),b===2?b=3:b===1&&(b=4),b===15||b===6||b!==8&&b!==13&&bc(e.L,$b(b,1))!==null)||(Bc(a.world,f,k,c),e.aa=-1):cd(a,[f,k,
c],!1));break;case -2:case 71:if(k>=0){let l=Ac(a.world,f,k,c);c=e.L.slice(0,9);k=c.findIndex(g=>g.content!==null&&g.content.id===l);k>=0?e.T=k:e.l===1&&(c[e.T].content&&(c=c.findIndex(g=>g.content===null),c>=0&&(e.T=c)),e.L[e.T].content=$b(l));e.Aa=a.ia}break;case -3:if(!a.world.wa&&e.l!==2&&k>=0)if(e.fb===0){if(b=e.L[e.T],b.content){switch(e.Fa){case 0:--f;break;case 1:++f;break;case 2:--k;break;case 3:++k;break;case 4:--c;break;case 5:++c}k>=0&&k<64&&Cc(a.world,f&(1<<4+a.world.P)-1,k,c&(1<<4+a.world.P)-
1,b.content.id)&&e.l!==1&&--b.content.amount<=0&&(b.content=null)}}else cd(a,[f,k,c],!0);break;case -4:e.T=(e.T+9-1)%9;e.Aa=a.ia;break;case -5:e.T=(e.T+1)%9;e.Aa=a.ia;break;case 27:a.j===0&&(a.A=!0,a.j=1);break;case -15:case -14:case 16:case 32:Zc(a);break;case 49:case 50:case 51:case 52:case 53:case 54:case 55:case 56:case 57:e.T=b-49;e.Aa=a.ia;break;case -12:case -13:case 65:case 68:Yc(a);break;case 69:if(a.j===0){a.j=3;for(let l of d)dd(a,l,!1)}break;case 70:a.Sa.Lb();break;case 80:a.world&&(a.A=
!0);break;case 81:e=e.L[e.T];if(d.has(17)||e.content&&--e.content.amount<=0)e.content=null;break;case -11:case -10:case 83:case 87:$c(a);break;case 84:if(a.j===0){a.j=2;for(let l of d)dd(a,l,!1)}break;case 112:a.Ka=!a.Ka;break;case 114:a.ab=!a.ab;case 116:case 122:case 123:break;default:return!1}}else{if(!d.delete(b))return!1;switch(b){case -15:case -14:case 16:case 32:Zc(a);break;case -12:case -13:case 65:case 68:Yc(a);break;case -11:case -10:case 83:case 87:$c(a);break;case -18:case -19:ad(a);break;
case -17:case -16:bd(a)}}a.ub=[...d].join();return!0},ed=(a,b)=>(b=b.startsWith("~")?a+N(b.slice(1)):N(b),isNaN(b)?a:b),gd=(a,b)=>{var c=a.g,d=a.world;if(b)if(b.charAt(0)==="/"){b=b.slice(1).split(" ");let e=b.shift();switch(e){case "clear":a.H=[];break;case "clearinv":for(let f of c.L)f.content=null;Y(a,"Inventory cleared.",!0);break;case "gamemode":case "gm":b=N(b[0]);!isNaN(b)&&b>=0&&b<3&&b%1===0?(c.l=b,Y(a,"Game mode set to: "+b,!0)):Y(a,"Game mode must be in 0..2!");break;case "give":if(b.length===
0){Y(a,"/give <id> [Amount]\n"+Gb.join(" "));break}d=Gb.indexOf((b[0]||"").toLowerCase());d=d>=0?d:N(b[0]);b=N(b[1]||1);!isNaN(d)&&d>0&&d<25&&d%1===0?!isNaN(b)&&b>0&&b%1===0?Y(a,bc(c.L,$b(d,b))?"Inventory is full!":`Gave items ${b} ${Gb[d]}`,!0):Y(a,"Amount must be at least 1!"):Y(a,"Invalid block type!");break;case "help":Y(a,"Commands: clear, clearinv, gamemode, give, help, load, me, save, spawn, teleport, time, version");break;case "load":Hc(d,!0).then(()=>{a.u.G=!0;Y(a,"Chunks loaded.",!0)});
break;case "me":Y(a,c.name+" "+b.join(" "),!0);break;case "save":if(a.world.wa){Y(a,"No permission!");break}Dc(a.world,a.g);Y(a,"Game saved.",!0);break;case "spawn":if(a.world.wa){Y(a,"No permission!");break}d.Pa=c.M;d.Qa=c.N;d.Ra=c.O;Y(a,"Spawn updated.",!0);break;case "teleport":case "tp":b.length===0?(c.M=d.Pa,c.N=d.Qa,c.O=d.Ra,a.u.G=!0,Y(a,"Teleported to spawn.",!0)):b.length===3?(Y(a,`Teleported to ${c.M=ed(c.M,b[0])} ${c.N=ed(c.N,b[1])} ${c.O=ed(c.O,b[2])}`,!0),a.u.G=!0):Y(a,"Pitch!");c.qa=
0;c.ra=0;c.sa=0;break;case "time":c=b[1];if(!c){Y(a,"Parameter missing!");break}if(c==="day")c=1E3;else if(c==="night")c=13E3;else if(isNaN(c=E(N(c))))break;switch(b[0]){case "add":c+=d.time;case "set":Jc(d,c);Y(a,"Time set to: "+d.time,!0);break;default:Y(a,"Unknown command: time "+b[0])}break;case "version":Y(a,"minicraft 0.12.0");break;case "_w":U.dc({type:b[0]==="m"?1:0});break;case "/exit":c.fb=0;Y(a,"Normal mouse mode.",!0);break;case "/expand":a.g.Ga&&a.g.Ha?d=!0:(Y(a,"Selection required!"),
d=!1);d&&(b[0]==="vert"?(c.Ga[1]=0,c.Ha[1]=63,Y(a,"Expanded selection.",!0)):Y(a,'Only "vert" supported!'));break;case "/pos1":case "/pos2":cd(a,[E(c.M),E(c.N),E(c.O)],e==="/pos2");break;case "/regen":if(a.world.wa){Y(a,"No permission!");break}Lc(d).then(()=>{a.u.G=!0;Y(a,"Chunk regenerated.",!0)});break;case "/show":Y(a,`Primary: ${c.Ga?c.Ga.join(" "):"none"}, Secondary: ${c.Ha?c.Ha.join(" "):"none"}`);break;case "/wand":c.fb=1;Y(a,"Select using mouse buttons.",!0);break;default:Y(a,"Unknown command: "+
e)}}else{let e=Y(a,`<${c.name}> `+b);Uc(a,b).then(f=>{f&&fd(a,e)})}},Y=(a,b,c=!1)=>{var d=++Tc;(a.H=a.H.slice(-49)).push({id:d,Nb:c,time:na(),value:b});return d},fd=(a,b)=>{var c=a.H.findIndex(d=>d.id===b);c>=0&&a.H.splice(c,1)},cd=(a,b,c)=>{c?a.g.Ha=b:a.g.Ga=b;Y(a,`${c?"Secondary point":"Primary point"}: ${b.join(" ")}`,!0)},Uc=(a,b)=>(hb(a.wb),a.wb=fb(Uc,5E3,a,null),(b?M("/api/chat",Object.assign({},ub,{body:Ma({msg:b})})):M("/api/chat")).then(c=>c.ok&&c.text()).then(c=>{if(c){c=c.split("\n").filter(Boolean);
for(let d of c)d.startsWith("<")&&Y(a,d);return c.length>0}return!1}).catch(()=>!1)),hd=({id:a,V:b})=>(y("div[className=bitmap]",{S:{backgroundImage:`url(/static/minicraft/textures/${b}.png)`,backgroundPositionY:100-a*100+"%"}}),null);function id({amount:a,l:b,id:c,V:d}){y("div[className=stack]",{title:Gb[c]+(b===1?` (${c})`:"")});return[B(hd,{id:c,V:d}),a!==1&&C("div[className=amount]",{innerText:a})]}
function jd({g:a,V:b,Ba:c,B:d}){y("table[className=bar]",{ontouchstart:ka(k=>{a.T=Number(k.target.closest("[data-slot]").dataset.slot);a.Aa=k.timeStamp}),S:{left:G(0,d/2-180)+"px",opacity:G(.5,F(1,1-(c-a.Aa-5E3)*5E-4))}});var e=A(k=>({height:k=k-8+"px",width:k}),[F(d/9,40)]),f=a.l;return[C("tr",null,a.L.slice(0,9).map(({content:k},l)=>C("td",{D:{slot:l},F:{active:l===a.T},S:e},[k&&B(id,{amount:k.amount,data:k.data,l:f,id:k.id,V:b}),!k&&C("div[className=stack]")])))]}
var kd=Ra(4).fill(null).map((a,b)=>Ra(9).fill(null).map((c,d)=>b*9+d));kd.push(kd.shift());function ld({$b:a,V:b,ac:c}){y("table",{onclick:({target:e})=>{e.className==="bitmap"&&ac({content:$b(N(e.parentElement.parentElement.dataset.id)),filter:null,ba:64},a);return!1}});var d=0;return Ra(3).fill(null).map(()=>C("tr",null,Ra(9).fill(null).map(()=>++d<25&&C("td",{D:{id:d},S:c},[B(id,{amount:1,data:null,l:1,id:d,V:b})]))))}
var md={fontSize:"",height:"32px",width:"32px"},nd={fontSize:"75%",height:"16px",width:"16px"};
function zd({K:a,V:b,ta:c,B:d}){var e=A(()=>({content:null,filter:null,ba:64})),f=a.g.l;y("div[className=menu]",A(()=>({onclick:({target:g})=>{if(g.className==="menu")e.content?e.content=null:(a.j=0,a.A=!1,Vc(a));else if(g.parentElement.className==="stack"&&g.parentElement.parentElement.dataset.slot||g.tagName==="TD")g=a.g.L[N((g.tagName==="TD"?g:g.parentElement.parentElement).dataset.slot)],e.content?ac(e,g):g.content&&ac(g,e)},oncontextmenu:({target:g})=>{if(g.className==="menu")e.content?--e.content.amount<=
0&&(e.content=null):(a.j=0,a.A=!1,Vc(a));else if(g.parentElement.className==="stack"&&g.parentElement.parentElement.dataset.slot||g.tagName==="TD")g=a.g.L[N((g.tagName==="TD"?g:g.parentElement.parentElement).dataset.slot)],e.content?ac(e,g,1):g.content&&ac(g,e,xa(g.content.amount/2))}})));var k,l;[k,l]=A(()=>{var g=F(d,c)<400;return[{left:`${d/2-(g?96:168)}px`,top:`${c/2-(g?91:147)}px`},g?nd:md]},[c,d]);return[C("div[className=window]",{S:k},[C("h2[innerText=Inventory]"),f===1&&B(ld,{$b:e,V:b,ac:l}),
C("table",null,kd.map((g,n)=>C(n<3?"tr":"tr[className=last]",null,g.map(h=>C("td",{D:A(()=>({slot:h})),S:l},[(h=a.g.L[h].content)&&B(id,{amount:h.amount,data:h.data,l:f,id:h.id,V:b})])))))]),e.content&&C("div[className=hand]",{S:{left:a.Gb+"px",top:a.Hb+"px"}},[B(id,{amount:e.content.amount,data:e.content.data,l:0,id:e.content.id,V:b})])]}
function Ad({I:{Nb:a,time:b,value:c},Ba:d}){b=F(1,1-(d-b-4500)*.001);y(a?"div[className=minor]":"div",{S:{opacity:b}});return[C("div[className=backdrop]"),C("span",{innerText:c})]}function Bd({H:a,Ba:b}){y("div[className=messages]");return[ma(Ad,a.slice(-10).filter(c=>c.time>b-5E3),{Ba:b})]}function Cd({I:a,current:b,ea:c}){y("tr");return[C("td",null,[C("button",{disabled:a.id===b||c>0,innerText:`${a.label} (${a.owner})`,onclick:()=>{aa();U.W({U:a.id});U.o({ea:a.id});ba()}})])]}
function Dd({K:a,state:{config:b,ea:c},$:d}){a&&z(()=>{Dc(a.world,a.g)});var e,f;[e,f]=ja(!1);var k=ca(()=>e?M("/static/minicraft/textures.json").then(Ab).catch(()=>null):J.resolve(null),[e],null);y("div[className=menu]");return[C("h1",{innerText:e?"Surfaces":"Settings"}),C("div[className=row]",null,[C("button",{innerText:a&&!e?"Back to game":"Back",onclick:()=>{e?f(!1):a?(a.j=0,a.A=!1,Vc(a)):d(2)}})]),!e&&C("table[className=settings]",null,[C("tr",null,[C("td",null,[C("button[innerText=Surfaces...]",
{onclick:()=>{f(!0)}})]),C("td",null,[C("label[htmlFor=setting-resolution]",{innerText:`Resolution: 1:${b.Y}\n`}),C("input[id=setting-resolution][type=range][min=1][max=20][step=1]",{value:21-b.Y,onchange:l=>U.W({Y:21-Number(l.target.value)})})])]),C("tr",null,[C("td",null,[C("label[htmlFor=setting-view-angle]",{innerText:`View angle: ${b.Ca}\n`}),C("input[id=setting-view-angle][type=range][min=1][max=180][step=1]",{value:b.Ca,onchange:l=>U.W({Ca:Number(l.target.value)})})]),C("td",null,[C("label[htmlFor=setting-view-distance]",
{innerText:`View distance: ${b.ka}\n`}),C("input[id=setting-view-distance][type=range][min=16][max=128][step=16]",{value:b.ka,onchange:l=>U.W({ka:Number(l.target.value)})})])]),C("tr",null,[C("td",null,[C("label[htmlFor=setting-pixel-grouping]",{innerText:`Pixel grouping: ${b.pa===1?"Disabled":b.pa}\n`}),C("input[id=setting-pixel-grouping][type=range][min=1][max=8][step=1]",{value:b.pa,onchange:l=>U.W({pa:Number(l.target.value)})})]),C("td",null,[C("label[htmlFor=setting-mouse-sensitivity]",{innerText:`Mouse sensitivity: ${b.ya}\n`}),
C("input[id=setting-mouse-sensitivity][type=range][min=1][max=15][step=1]",{value:b.ya,onchange:l=>U.W({ya:Number(l.target.value)})})])]),C("tr",null,[C("td",null,[C("button[innerText=Version 0.12.0][title=Project page]",{onclick:()=>{open("//github.com/L3P3/minicraft")}})])])]),a&&!e&&C("div[className=row]",null,[C("button[innerText=Leave world]",{onclick:()=>{d(2)}})]),e&&C("table[className=settings]",null,[C("tr",null,[C("td",null,[C("button[innerText=Plain]",{disabled:b.U===0,onclick:()=>{aa();
U.W({U:0});U.o({ea:0});ba()}})])]),k&&ma(Cd,k,{current:b.U,ea:c})]),e&&k&&C("div[className=row]",null,[C("button[innerText=Add surface]",{onclick:()=>{open("//l3p3.de/svr/minicraft/textures.html")}})])]}
var Ed=({K:a,Zb:b,B:c})=>[C("div[className=toolbar]",null,[C("button[innerText=\u274c]",{onclick:()=>{a.j=0;a.A=!1;Vc(a)}})]),C("input[autocomplete=off][enterkeyhint=send][mozactionhint=send][name=message][required]",{onkeydown:d=>{var e=d.keyCode;d=d.target;e===13?(gd(a,d.value),d.value=""):e===27&&(a.j=0,a.A=!1,Vc(a))},R:d=>{b.input=d;fb(()=>d.focus(),0)},S:{width:`${c-40}px`}})],Fd=({I:{Nb:a,value:b}})=>(y(a?"div[className=minor]":"div",{innerText:b}),null);
function Gd({K:a,H:b,B:c}){var d=ka({history:null,input:null});y("div[className=menu terminal]",{onclick:e=>{e.target!==d.input&&d.input.focus()}});z(e=>{e&&fb(()=>d.history.scrollTop=1E9,0)},[b.length&&b[b.length-1].id]);return[C("div[className=history]",{R:ka(e=>{d.history=e})},[ma(Fd,b)]),B(Ed,{K:a,Zb:d,B:c})]}var Hd=[["pick",-2],["up",-14],["down",-15],["E",69],["T",84],["F1",112],["F3",114],["...",27]],Z=[C("div")];
function Id({K:a,B:b}){var c=a.da;y("div[className=touch]",ka({ontouchstart:l=>{var g=l.target.dataset.code||l.target.parentElement.dataset.code;if(g!=null&&dd(a,g=N(g),!0)){let n=l.changedTouches[0].identifier,h=r=>{r.changedTouches[0].identifier===n&&(kb("touchend",h),dd(a,g,!1))};jb("touchend",h)}return!1}}));var d,e;[d,e]=A(l=>[{height:l-8+"px"},{width:l+="px",height:l}],[F(ya(b/10),40)]);var f,k;[f,k]=A(()=>{var l=b>300?"14px":"0",g=b>300?"2px":"0",n=b>650?l:"40px";return[{borderSpacing:g,bottom:n,
left:l},{borderSpacing:g,bottom:n,right:l}]},[b]);return[C("div[className=top]",null,Hd.map(([l,g])=>C(`div[innerText=${l}]`,{D:{code:g},F:{button:!0,active:c.has(g)}}))),C("table[className=move]",{S:f},[C("tr",null,[C("td"),C("td",{D:{code:-10},F:{"button up":!0,active:c.has(-10)},S:e},Z)]),C("tr",null,[C("td",{D:{code:-12},F:{"button left":!0,active:c.has(-12)},S:e},Z),C("td",null,[C("div",{D:{code:-1},F:{"button center":!0,active:c.has(-1)},S:d},Z)]),C("td",{D:{code:-13},F:{"button right":!0,active:c.has(-13)},
S:e},Z)]),C("tr",null,[C("td"),C("td",{D:{code:-11},F:{"button down":!0,active:c.has(-11)},S:e},Z)])]),C("table[className=move]",{S:k},[C("tr",null,[C("td"),C("td",{D:{code:-16},F:{"button up":!0,active:c.has(-16)},S:e},Z)]),C("tr",null,[C("td",{D:{code:-18},F:{"button left":!0,active:c.has(-18)},S:e},Z),C("td",null,[C("div",{D:{code:-3},F:{"button center":!0,active:c.has(-3)},S:d},Z)]),C("td",{D:{code:-19},F:{"button right":!0,active:c.has(-19)},S:e},Z)]),C("tr",null,[C("td"),C("td",{D:{code:-17},
F:{"button down":!0,active:c.has(-17)},S:e},Z)])])]}function Jd({model:a}){var b=y("canvas");a.u=Rc(a,b);return null}
function Kd({frame:a,ca:b,state:c,$:d,ta:e,B:f,Sa:k}){var l=c.config,g=na(),n=ra.pointerLockElement===a,h=A(()=>Wc(a,k,c));z(()=>{Ld.add(h);var p=w=>{if(h.j!==0)return!0;ra.pointerLockElement===a?dd(h,-1-w.button,w.type==="mousedown"):Vc(h);return!1},q=w=>{if(ra.pointerLockElement===a){var t=h.config.ya*ta/(G(h.hb,h.ib)*h.za);tb&&(h.Qb=w.timeStamp);dc(h.g,h.jb=w.movementX*t,h.kb=-w.movementY*t)}else t=h.Kb.getBoundingClientRect(),h.Gb=w.clientX-t.left,h.Hb=w.clientY-t.top},x=w=>{U.Za(!1);if(h.j===
0&&!h.A&&D.abs(w.deltaY)>5)return w=w.deltaY>0?-5:-4,dd(h,w,!0),dd(h,w,!1),!1},u={passive:!0};a.addEventListener("mousedown",p);a.addEventListener("mouseup",p);a.addEventListener("mousemove",q,u);a.addEventListener("wheel",x,u);return()=>{a.removeEventListener("mousedown",p);a.removeEventListener("mouseup",p);a.removeEventListener("mousemove",q,u);a.removeEventListener("wheel",x,u);hb(h.wb);ib(h.bc);Dc(h.world,h.g);lc.delete(h.world.id);U.o({Ua:[...lc.keys()]});var w=h.u;Oc.delete(w);ib(w.Wb);return Ld.delete(h)}});
z(()=>{h.config=l;h.u&&(h.u.G=!0);var p=h.world,q=xa(Ea(h.config.ka/16*2+2));p.P!==q&&Fc(p,h.g,q)},[l]);z((p,q,x)=>{h.za=x||1;h.hb=G(1,p);h.ib=G(1,q);q=h.config.Y;p=xa(h.hb*h.za/q);q=xa(h.ib*h.za/q);if(p!==h.Na||q!==h.Oa)h.Na=p,h.Oa=q,h.u&&(h.u.G=!0,Qc(h.u))},[a.offsetWidth,a.offsetHeight,qa.devicePixelRatio,l.Y]);z(()=>{b&&dd(h,b.code,b.state)},[b]);z(p=>{p||h.A||h.j!==0||(h.j=1,tb&&h.jb|h.kb&&h.Qb>g-100&&(dc(h.g,-h.jb,-h.kb),h.jb=h.kb=0,h.u.G=!0));h.A=!p},[l.xa&&h.j===0||n]);z(p=>n&&p&&ra.exitPointerLock(),
[h.A||h.j!==0]);g===h.ia||Md||(h.world&&(h.ia&&!h.A&&ec(h.g,g-h.ia),h.u&&Sc(h.u,g)),h.ia=g);ia();var r=ka({zb:1});l.U&&(r.zb=l.U);return[B(Jd,{model:h}),h.Ka&&h.j!==2&&h.H.length>0&&h.H[h.H.length-1].time>g-5E3&&B(Bd,{H:h.H,Ba:g}),h.u&&h.ab&&C("div[className=diagnostics]",{innerText:h.u.Ib}),l.xa&&B(Id,{K:h,ub:h.ub,B:f}),h.Ka&&h.j!==3&&h.g.l!==2&&B(jd,{g:h.g,V:r.zb,Ba:g,B:f}),(h.j===1||h.j===2||h.j===3)&&C("div[className=backdrop]"),h.j===3&&B(zd,{K:h,V:r.zb,Ba:g,ta:e,B:f}),h.j===1&&B(Dd,{K:h,state:c,
$:d}),h.j===2&&B(Gd,{K:h,H:h.H,B:f})]}
var Nd=({account:a,busy:b,ob:c,Yb:d,$:e,world:f,Bb:k})=>(y("div"),[C("button[innerText=Enter]",{disabled:b||d||f.local<2||f.remote>f.local,onclick:()=>{aa();U.W({Da:f.id});e(0);ba()},title:d?"The world is already opened!":f.local<2?"The world is not downloaded yet!":f.local<f.remote?"The world is still loading!":"Enter selected world"}),C("button",{disabled:b||!S||d||f.local>0&&f.remote>0||!f.remote&&!a.rank,innerText:f.local?S&&f&&!f.remote?"Upload":"Transfer":"Download",onclick:()=>{f.local?f.remote||
U.la(f.id,{mod_r:1}):U.Tb({id:f.id,label:f.label,mod_l:1,mod_r:f.remote})},title:S?f.local?f.remote?"The world is present on both sides!":d?"The world is already opened!":a.rank?"Upload world to server":"Not logged in!":"Download world from server":"List is loading!"}),C("button[innerText=Rename]",{disabled:b||d||!f.writable,onclick:()=>{var l=sb("World's new label:\n(max. 16 characters)",f.label);!l||l===f.label||l.length>16||(f.local&&U.la(f.id,{label:l}),f.remote&&(c(!0),M("/api/minicraft/world",
Object.assign({},ub,{body:Ma({what:"meta",world:f.id,label:l})})).then(Ab).catch(g=>{lb("Error while editing world: "+g.message)}).then(()=>{c(!1)})))},title:f.writable?d?"The world is already opened!":"Change world name":"No permission!"}),C("button",{disabled:b||!f.remote||!f.writable,innerText:`Public: ${f.public?"Yes":"No"}`,onclick:()=>{c(!0);M("/api/minicraft/world",Object.assign({},ub,{body:Ma({what:"meta",world:f.id,public:!f.public})})).then(l=>(l=Ab(l),aa(),Ub(),c(!1),ba(),l)).catch(l=>
{lb("Error while editing world: "+l.message);c(!1)})},title:f.remote?f.writable?f.public?"Unpublish world":"Publish world":"No permission!":"The world is not uploaded!"}),C("button",{disabled:b||d||!f.local&&!f.writable,innerText:f.local?"Delete (local)":"Delete",onclick:()=>{rb('Really delete world "'+f.label+'"?')&&(f.local?(Pb(f.id),U.Ub(f.id)):(c(!0),M("/api/minicraft/world",{method:"DELETE",headers:{"Content-Type":"application/json"},body:Ma({what:"world",world:f.id})}).then(l=>(Ab(l),aa(),k(null),
Ub(),c(!1),ba())).catch(l=>{lb("Error while deleting world: "+l.message);c(!1)})))},title:d?"The world is already opened!":f.local||f.writable?"Delete world":"No permission!"})]),Od=a=>{a.scrollIntoView(vb)},Pd=(a,b)=>{a&&fb(Od,0,b)};
function Qd({I:a,account:b,busy:c,ob:d,$:e,jc:f,Bb:k,ma:l,Ua:g}){f=a===f;var n=y("tr",{F:{selected:f},onclick:()=>{k(a.id)}});z(Pd,[f,n]);return[C("td[style=width:0]",{innerText:`${a.local?"L":"_"}${a.local&&a.remote?a.local>a.remote?">":a.local<a.remote?"<":"=":"_"}${a.remote?a.public?"R":"r":"_"}`,S:{color:l===a.id?"yellow":a.local!==a.remote&&a.local&&a.remote?"red":""}}),C("td",{innerText:a.label,title:a.id},[f&&B(Nd,{account:b,busy:c,ob:d,Yb:g.includes(a.id),$:e,world:a,Bb:k})]),C("td[style=width:0]",
null,[C("div[title=Modified]",{innerText:zb(G(a.local,a.remote),!0)}),f&&C("div",{innerText:a.account_name?a.account_name:"-",title:a.account_name?"Owner":"Just a local world"})])]}
function Rd({state:{account:a,config:b,ha:c,Ab:d,Ea:e,ma:f,Ta:k,Ua:l},view:g,$:n,ta:h,B:r}){var p,q;[p,q]=ja(b.Da);z(()=>{Sb&&p===Sb[0]&&q(Sb[1])},[Sb]);var x=A(()=>k.find(t=>t.id===p)||null,[p,k]),u,w;[u,w]=ja(!1);y("div",{F:{menu:!0,blurred:g===1}});return[C("button[innerText=Settings][style=position:absolute]",{onclick:()=>{n(1)}}),C("button[style=position:absolute;right:0]",{disabled:a.rank>0,innerText:a.rank?a.label:"Login",onclick:()=>{location.href="/account?redir=minicraft"}}),C("h1[innerText=Worlds]"),
C("div[className=row]",null,[C("button[innerText=Refresh][title=Reload list]",{disabled:d||e||c!==null,onclick:Ub}),C("button[innerText=New world]",{onclick:()=>{var t=sb("New world's label:\n(max. 16 characters)","New world");t&&(t.length>16?lb("Name is too long!"):U.Tb({id:F(0,...b.worlds.map(L=>L.id))-1,label:t,mod_l:Ha.now(),mod_r:0}))}})]),C("div[className=worlds]",{S:{height:`${G(100,h-140)}px`,width:`${F(480,r-16)}px`}},[C("table[cellSpacing=0]",null,[ma(Qd,k,{kc:Ha.now(),account:a,busy:u,
ob:w,$:n,jc:x,Bb:q,ma:f,Ua:l})])])]}
function Sd({ca:a,state:b,ta:c,B:d,Sa:e}){var f,k;[f,k]=ja(2);z(()=>{e.cc(f===0?b.Ta.find(g=>g.id===b.config.Da).label+" \u2013 minicraft":"minicraft")},[f]);var l=y("div[className=game]");return[(f===2||f===1)&&B(Rd,{state:b,view:f,$:k,ta:c,B:d}),f===1&&C("div[className=backdrop]"),f===1&&B(Dd,{K:null,state:b,$:k}),f===0&&B(Kd,{frame:l,ca:a,state:b,$:k,ta:c,B:d,Sa:e}),f===2&&b.ha&&C("div[style=position:absolute;bottom:0;left:0;color:yellow]",{title:b.ha},[C("span[innerText=Connection error. ]"),C("button[innerText=Retry]",
{onclick:()=>{U.o({ha:null})}})])]}
var Td="nwse-resize ns-resize nesw-resize ew-resize move ew-resize nesw-resize ns-resize nwse-resize".split(" "),Ud=0,Vd={init:()=>Vd.xb({$a:0,Ja:0,height:0,ca:null,left:0,mode:Ud,title:"...",top:0,width:0},600,400),Lb:a=>Object.assign({},a,{mode:a.mode===0?1:0}),Xb:(a,b)=>a.ca&&a.ca.code===b.code&&a.ca.state===b.state?a:Object.assign({},a,{ca:b}),Pb:(a,b,c)=>Object.assign({},a,{left:G(0,F(b,T.Z-a.width)),top:G(0,F(c,T.ja-a.height))}),gb:(a,b)=>Object.assign({},a,b),xb:(a,b,c)=>Object.assign({},a,
{Ja:b=G(100,F(b,T.Z-a.left)),$a:c=G(50,F(c,T.ja-a.top)),width:b,height:c}),cc:(a,b)=>Object.assign({},a,{title:b})},Wd=(a,b,c)=>{U.ec(b);var d=c.target;if(c.button===0&&(d.className==="window borders"||d.className==="window_title")){c.preventDefault();ra.activeElement.blur();var e,f;[e,f]=a;var k=c.clientX,l=c.clientY,g=k-e.left,n=l-e.top,h=g<8?0:g<e.width-8?1:2,r=n<8?0:n<e.height-8?1:2,p=h+r*3;d.style.willChange=p===4?"left,top":"contents";U.o({cursor:Td[p]});var q=u=>{Md=!0;aa();var w=u.clientX,
t=u.clientY;a:if(p===4){if(u.type==="mouseup"){if(t<4){f.gb({left:0,top:0,width:T.Z,height:T.ja});break a}if(w<4){f.gb({left:0,top:0,width:xa(T.Z/2),height:T.ja});break a}if(w>T.Z-3){f.gb({left:xa(T.Z/2),top:0,width:E(T.Z/2),height:T.ja});break a}}else if([u]=a,u.Ja!==u.width||u.$a!==u.height){f.xb(u.Ja,u.$a);let [L]=a;g=ya(g*L.Ja/u.width)}f.Pb(w-g,t-n)}else h!==0&&r!==0||f.Pb(h===0?(w=G(g,F(w,e.left+e.width-100+g)))-g:e.left,r===0?(t=G(n,F(t,e.top+e.height-50+n)))-n:e.top),f.xb(h===0?e.width+e.left+
g-w:h===1?e.width:e.width-k+w,r===0?e.height+e.top+n-t:r===1?e.height:e.height-l+t);ba();Md=!1},x=u=>{kb("mousemove",q,!0);kb("mouseup",x);u.clientX===k&&u.clientY===l||q(u);U.o({cursor:null});d.style.willChange="auto"};jb("mousemove",q,!0);jb("mouseup",x)}},Xd=({height:a,left:b,mode:c,top:d,width:e},f)=>({F:{window:!0,borders:c===1},onmousedown:f,S:{display:c===2?"none":"block",left:c===0?"0":b-1+"px",top:c===0?"0":d-1+"px",height:c===0?"100%":a-40+"px",width:c===0?"100%":e-16+"px"}}),Yd=({title:a,
width:b,fc:c})=>[C("div[className=window_title]",{innerText:a,S:{width:`${b-40}px`}}),C("div[className=window_button]",{onclick:()=>U.hc(c)})];
function Zd({I:{id:a,Ob:b,type:c},state:d}){Ud=b;var e=da(Vd),f,k;[f,k]=e;z(()=>($d.set(a,k),()=>$d.delete(a)));b=A(()=>Wd.bind(null,e,a));y("div",A(Xd,[f,b]));var l=ha(!0,!1);z((n,h)=>{l&&k.gb({left:G(0,F(f.left,n-f.width)),top:G(0,F(f.top,h-f.height)),width:F(n,G(100,f.Ja,f.width)),height:F(h,G(50,f.$a,f.height))})},[d.Z,d.ja]);b=f.mode===0?d.Z:f.width-16;var g=f.mode===0?d.ja:f.height-40;return[c===1&&B(Sd,{ca:f.ca,state:d,ta:g,B:b,Sa:k}),f.mode!==0&&B(Yd,{title:f.title,width:f.width,fc:a})]}
var Ld=new ab,$d=new bb,Md=!1,ae=0,be=0;
function ce(){[T,U]=da(Zb);z(()=>{Tb(!0);var e=!1;onbeforeunload=onunload=onpagehide=onblur=()=>{if(!e){e=!0;for(let f of Ld)Dc(f.world,f.g);U.qb()}};onpageshow=onfocus=()=>{e=!1};onresize=()=>{Md=!0;U.o({ja:qa.innerHeight,Z:qa.innerWidth});Md=!1};gb(()=>(U.qb(),!Ga&&Oa("minicraft.lock",Ha.now())),500);jb("touchend",f=>{ae=f.timeStamp},!0)});var a=ka(e=>{var f=e.type==="keydown";if(f&&e.target.tagName==="INPUT")return!0;Md=!0;U.Za(!1);if(T.J.length>0){let k=$d.get(T.J[T.J.length-1].id);e.key!=="f"?
k.Xb({code:e.keyCode,state:f}):f&&k.Lb()}return Md=!1}),b=ka(()=>{U.Za(!0)}),c=ka(e=>{e.timeStamp-ae>999&&U.Za(!1)}),d=T.config.xa;z(()=>{d?(jb("mousedown",c,!0),jb("mouseup",c,!0),kb("touchstart",b,!0)):(kb("mousedown",c,!0),kb("mouseup",c,!0),jb("touchstart",b,!0))},[d]);z(Pc,[T.config.U]);z(()=>{hb(be);T.ha||(be=fb(Yb))},[T.ha,T.Ta]);y("",{onkeydown:a,onkeyup:a,oncontextmenu:yb,ondragstart:yb});return[ma(Zd,T.J,{state:T}),T.cursor&&C("div[className=cursormask]",{S:{cursor:T.cursor}})]}
function de(){close();return[C("h1[innerText=minicraft already running!]")]}if(Ga){let a=new Ga("minicraft.lock"),b=fb(()=>Jb.then(()=>la(ce)),100);a.addEventListener("message",c=>{c.data==="yes"?(hb(b),a.close(),la(de)):(a.postMessage("yes"),focus())});a.postMessage("anyone there?")}else{let a=N(K.getItem("minicraft.lock")),b=Ha.now()-1500;a>b?fb(()=>{la(N(K.getItem("minicraft.lock"))===a?ce:de)},a-b):Jb.then(()=>la(ce))};

//# sourceMappingURL=app-en.js.map
