function m(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})}
var v=lui,ca=v.defer,da=v.defer_end,ea=v.hook_async,x=v.hook_dom,y=v.hook_effect,z=v.hook_memo,fa=v.hook_model,ha=v.hook_prev,ia=v.hook_rerender,ja=v.hook_state,la=v.hook_static,ma=v.init,B=v.node,C=v.node_dom,na=v.node_map,oa=v.now,pa=window,qa=document,sa=navigator,D=Math,ta=D.abs,ua=D.PI,va=ua*.5,wa=180/ua,xa=D.random,F=D.floor,ya=D.ceil,Ba=D.round,H=D.min,I=D.max,Ca=D.cos,Da=D.sin,Ea=D.sqrt,Fa=D.log2,Ga=String.fromCharCode,Ha=pa.BroadcastChannel,Ia=Date,Ma=JSON,J=Promise,Na=Ma.stringify,Oa=Ma.parse,
M=localStorage,O=M.setItem.bind(M),Pa=M.removeItem.bind(M),Qa=pa.indexedDB||null,P=fetch,Ra=Array,Sa=Uint8Array,$a=Uint32Array,ab=Set,bb=Map,U=Number,cb=Object,db=cb.keys,eb=cb.entries,fb=setTimeout,gb=setInterval,hb=clearTimeout,ib=addEventListener,jb=removeEventListener,kb=alert,lb=confirm,mb=prompt,nb=sa.userAgent.includes("WebKit"),ob={method:"POST",headers:{"Content-Type":"application/json"}},ub={behavior:"smooth",block:"center",container:"nearest"},vb=(a,b)=>(a=F(a).toString(),a.length<2?b+
a:a),wb=a=>a*a,xb=()=>!1,yb=(a,b)=>{if(a<2)return"...";var c=new Ia;a=new Ia(a);var d=c-a;if(d<59E3)return Ba(d/1E3)+"s";if(d<3E6)return Ba(d/6E4)+"m";d=a.getFullYear();var e=a.getMonth(),f=a.getDate(),g="";d<c.getFullYear()&&(g=d+"/");if(g||e<c.getMonth())g+=e+1+"/";if(g||f<c.getDate())g+=f;if(b)return g||"hoy";g&&(g+="/");return g+a.getHours()+":"+vb(a.getMinutes(),"0")},zb=a=>{if(!a.ok)throw Error(a.status===403?"Falta de permisos. \u00bfSesi\u00f3n iniciada?":"Error de conexi\u00f3n.");return a.json()},
Ab="air stone grass dirt cobble planks bedrock log leaves bricks wool sand gravel glass bookshelf obsidian stone_bricks sandstone lapis_block iron_block gold_block diamond_block emerald_block redstone_block quartz_block".split(" "),Bb="Aire;Piedra;Bloque de hierba;Tierra;Adoqu\u00edn;Tablones;Piedra base;Tronco;Hojas;Ladrillos;Lana;Arena;Grava;Cristal;Estanter\u00eda;Obsidiana;Ladrillos de piedra;Arenisca;Bloque de lapisl\u00e1zuli;Bloque de hierro;Bloque de oro;Bloque de diamante;Bloque de esmeralda;Bloque de redstone;Bloque de cuarzo".split(";"),
Cb=[0,8487297,4305266,4349313,8092539,5342114,7039851,3561583,4172910,6384533,15526888,10671324,8092798,16447200,4151672,1970708,8092539,9686227,9126695,15198183,5567485,14541182,7920469,662956,14936813],Db=null,Eb=null,Kb=null,Lb=Qa?new J(a=>{var b,c;(b=sa.storage)==null||(c=b.persist)==null||c.call(b);b=Qa.open("minicraft",1);b.onupgradeneeded=d=>{d=d.target.result.createObjectStore("chunks",{keyPath:["world","coords"]});for(let e of db(M))if(e.startsWith("minicraft.world.")){let [f,g]=e.slice(16).split(":",
2);g!=="meta"&&(d.add({world:U(f),coords:g,data:M.getItem(e)}),Pa(e))}};b.onsuccess=d=>{Db=d.target.result;a()}}):J.resolve(void 0),Mb=Qa?(a,b)=>new J(c=>{Eb||(Eb=Db.transaction("chunks","readonly").objectStore("chunks"),J.resolve(void 0).then(()=>{Eb=null}));var d=Eb.get([a,b]);d.onsuccess=()=>{var e;return c((e=d.result)==null?void 0:e.data)}}):(a,b)=>{a=M.getItem(`minicraft.world.${a}:${b}`);return J.resolve(a)},Nb=Qa?(a,b,c)=>new J((d,e)=>{Kb||(Kb=Db.transaction("chunks","readwrite").objectStore("chunks"),
J.resolve(void 0).then(()=>{Kb=null}));var f=Kb.put({world:a,coords:b,data:c});f.onsuccess=()=>d();f.onerror=()=>e(f.error)}):(a,b,c)=>(O(`minicraft.world.${a}:${b}`,c),J.resolve(void 0)),Ob=Qa?(a,b)=>new J((c,d)=>{Kb||(Kb=Db.transaction("chunks","readwrite").objectStore("chunks"),J.resolve(void 0).then(()=>{Kb=null}));var e=Kb.delete([a,b]);e.onsuccess=()=>c();e.onerror=()=>d(e.error)}):(a,b)=>(Pa(`minicraft.world.${a}:${b}`),J.resolve(void 0)),Pb=Qa?a=>new J(b=>{var c=M.getItem(`minicraft.world.${a}:meta`);
if(!c)return b({});var d=Db.transaction("chunks","readonly").objectStore("chunks").openCursor(),e={meta:c};d.onsuccess=()=>{var f=d.result;f?(f.value.world===a&&(e[f.value.coords]=f.value.data),f.continue()):b(e)}}):a=>{a=`minicraft.world.${a}:`;var b=a.length,c={};for(let d of db(M))d.startsWith(a)&&(c[d.slice(b)]=M.getItem(d));return J.resolve(c)},Qb=Qa?(a,b)=>new J((c,d)=>{var e=Db.transaction("chunks","readwrite"),f=e.objectStore("chunks");for(let [g,l]of eb(b))g!=="meta"?f.put({world:a,coords:g,
data:l}):O(`minicraft.world.${a}:meta`,l);e.oncomplete=()=>c();e.onerror=()=>d(e.error)}):(a,b)=>m(function*(){for(let [c,d]of eb(b))O(`minicraft.world.${a}:${c}`,d);O("__margin",Ra(257).join("x"));Pa("__margin")}()),Rb=Qa?a=>{var b=Db.transaction("chunks","readwrite").objectStore("chunks").openCursor();b.onsuccess=()=>{var c=b.result;c&&(c.value.world===a&&c.delete(),c.continue())};Pa(`minicraft.world.${a}:meta`)}:a=>{a=`minicraft.world.${a}:`;for(let b of db(M))b.startsWith(a)&&Pa(b)},Sb=Qa?(a,
b)=>new J(c=>{var d=Db.transaction("chunks","readwrite").objectStore("chunks"),e=d.openCursor();e.onsuccess=()=>{var f=e.result;f?(f.value.world===a&&(f.delete(),f.value.world=b,d.put(f.value)),f.continue()):c()};O(`minicraft.world.${b}:meta`,M.getItem(`minicraft.world.${a}:meta`));Pa(`minicraft.world.${a}:meta`)}):(a,b)=>{a=`minicraft.world.${a}:`;var c=a.length;for(let d of db(M))if(d.startsWith(a)){let e=M.getItem(d);Pa(d);O(`minicraft.world.${b}:${d.slice(c)}`,e)}return J.resolve(void 0)},V=null,
Tb=0,Ub=null,Wb=()=>{W.Ka||W.oa!==null||(hb(Tb),X.A({Bb:!0,Ka:!0}),Vb(!1))},Vb=a=>{m(function*(){Tb=fb(X.A,5E3,{Bb:!1});try{let b=yield P(`/api/minicraft/world?what=${a?"initia":"meta_al"}l`),c=yield zb(b);a?c.version_latest!=="0.13.1"?location.reload(!0):(V=c.worlds,X.A(Object.assign({},{account:c.account,Ka:!1},Xb(W.config)))):(V=c,X.A(Object.assign({},{Ka:!1},Xb(W.config))))}catch(b){X.A({ja:"Error al cargar la lista de mundos: "+b.message,Ka:!1})}}())},Yb=(a,b)=>I(b.local,b.remote)-I(a.local,
a.remote),Xb=a=>{var b=V?V.map(c=>({account_name:c.account_name,hash:c.hash,id:c.id,label:c.label,local:0,locked:c.locked,public:c.public,remote:c.modified,writable:c.writable})):[];for(let c of a.worlds){let d=b.find(e=>e.id===c.id);if(d){let e=d.local=c.mod_l,f=d.remote,g=c.mod_r;e>g&&f>g&&(lb('\u00a1Conflicto! El mundo "'+c.label+'" fue modificado aqu\u00ed y en otro lugar.\nAceptar: Tomar variante del servidor ('+yb(f,!1)+") | Cancelar: Mantener variante local ("+yb(e,!1)+")")?a=Object.assign({},
a,{worlds:a.worlds.map(l=>l.id===c.id?Object.assign({},l,{mod_l:d.local=g}):l)}):d.remote=g)}else c.mod_r>1&&V&&(kb('El mundo "'+c.label+'" no se encontr\u00f3 en el servidor, por lo que ahora es un mundo local.'),a=Object.assign({},a,{worlds:a.worlds.map(e=>e.id===c.id?Object.assign({},e,{mod_r:0}):e)})),b.push({account_name:"",hash:0,id:c.id,label:c.label,local:c.mod_l,locked:!1,public:!1,remote:c.mod_r===1?1:0,writable:!0})}return{config:a,Za:b.sort(Yb)}},$b=()=>m(function*(){if(W.oa===null){var a;
try{for(;a=W.Za.find(b=>b.local>0&&b.remote>0&&b.local!==b.remote);)yield Zb(a);X.A({oa:null})}catch(b){X.A({ja:b.message,oa:null})}}}()),Zb=a=>m(function*(){var b=a.id;X.A({oa:b});if(a.local<a.remote)try{yield Qb(b,yield zb(yield P(`/static/minicraft/worlds/${a.hash}.json`))),X.na(b,{mod_l:a.remote,mod_r:a.remote})}catch(c){if(c.name==="QuotaExceededError")kb("\u00a1Almacenamiento insuficiente!"),Rb(b),X.Zb(b);else throw Error("Error al descargar el mundo: "+c.message);}else if(!a.writable||a.locked)X.na(b,
{mod_l:a.remote});else{let c=b,d=null;try{let e=Pb(b);if(a.remote===1){let g=yield zb(yield P("/api/minicraft/world",Object.assign({},ob,{body:Na({what:"meta",label:a.label})})));d=Sb(b,c=g.id);Ub=[b,c];X.na(b,{id:c})}let f=yield zb(yield P("/api/minicraft/world",Object.assign({},ob,{body:Na({what:"data",world:c,data:yield e})})));a.remote===1?V.push(f):Object.assign(V.find(g=>g.id===b),f);X.na(c,{mod_l:f.modified,mod_r:f.modified})}catch(e){throw X.na(b,{mod_r:0}),Error("Error al subir el mundo: "+
e.message);}yield d}}()),Y=Oa(M.getItem("minicraft.config")||null);if(Y&&Y.worlds&&Y.version.startsWith("0.9.")){let a=new ab(Y.worlds.map(b=>"minicraft.world."+b.id));for(let b of db(M))b.startsWith("minicraft.world.")&&!a.has(b.split(":",1)[0])&&Pa(b)}
var ac={init:()=>{var a=!1,b={Da:!1,ua:1,Ea:3,$:4,V:1,Ia:120,ma:64,Ja:0,worlds:[]};if(Y){let c=Y.pixel_grouping;c!=null&&(b.ua=c);(c=Y.mouse_sensitivity)!=null&&(b.Ea=c);b.$=Y.resolution_scaling;(c=Y.textures)!=null?b.V=c:b.V=Y.flag_textures?1:0;b.Ia=Y.view_angle;b.ma=Y.view_distance;(c=Y.world_last)!=null&&(b.Ja=c);(c=Y.worlds)?b.worlds=c:M.getItem("minicraft.world.0:meta")&&(b.worlds[0]={id:0,label:(mb("Se ha encontrado un mundo sin nombre. \u00bfC\u00f3mo deber\u00eda llamarse?","")||"Mundo desconocido").substring(0,
16),mod_l:Ia.now(),mod_r:0},a=!0);Y=null}b=Object.assign({},{account:{label:"",rank:0},config:b,sb:b,ja:null,cursor:null,la:pa.innerHeight,aa:pa.innerWidth,ha:b.V,K:[{id:0,Sb:0,type:1}],Bb:!0,Ka:!0,oa:null,$a:[]},Xb(b));return a?(b.sb=null,ac.rb(b)):b},rb:a=>{var b=a.config;if(b===a.sb)return a;O("minicraft.config",Na({version:"0.13.1",pixel_grouping:b.ua,mouse_sensitivity:b.Ea,resolution_scaling:b.$,textures:b.V,view_angle:b.Ia,view_distance:b.ma,world_last:b.Ja,worlds:b.worlds}));return Object.assign({},
a,{sb:b})},sc:(a,b)=>ac.X(a,b(a.config)),X:(a,b)=>Object.assign({},a,{config:Object.assign({},a.config,b)}),cb:(a,b)=>a.config.Da===b?a:ac.X(a,{Da:b}),A:(a,b)=>Object.assign({},a,b),lc:(a,b)=>(qa.activeElement.blur(),Object.assign({},a,{K:[...a.K,Object.assign({},{id:I(-1,...a.K.map(c=>c.id))+1,Sb:1,type:0},b)]})),oc:(a,b)=>Object.assign({},a,{K:a.K.filter(c=>c.id!==b)}),mc:(a,b)=>a.K[a.K.length-1].id===b?a:Object.assign({},a,{K:[...a.K.filter(c=>c.id!==b),a.K.find(c=>c.id===b)]}),Yb:(a,b)=>Object.assign({},
a,Xb(Object.assign({},a.config,{worlds:[...a.config.worlds,b]}))),Zb:(a,b)=>Object.assign({},a,Xb(Object.assign({},a.config,{worlds:a.config.worlds.filter(c=>c.id!==b)}))),na:(a,b,c)=>Object.assign({},a,Xb(Object.assign({},a.config,{worlds:a.config.worlds.map(d=>d.id===b?Object.assign({},d,c):d)})))},W,X,bc=(a,b=1,c=null)=>({amount:b,data:c,id:a}),cc=(a,b,c=a.content.amount)=>{if(b.content)a.content.id===b.content.id?(c=H(c,b.da-b.content.amount),a.content.amount-=c,b.content.amount+=c,a.content.amount<=
0&&(a.content=null)):!(a.content.amount<=c&&a.content.amount<=b.da&&b.content.amount<=a.da)||a.filter&&!a.filter(b.content.id)||b.filter&&!b.filter(a.content.id)||([b.content,a.content]=[a.content,b.content]);else if(!b.filter||b.filter(a.content.id))a.content.amount<=c&&a.content.amount<=b.da?[b.content,a.content]=[a.content,b.content]:(c=H(c,b.da),a.content.amount-=c,b.content=bc(a.content.id,c),a.content.amount<=0&&(a.content=null))},dc=(a,b)=>{for(let c of a)if(c.content&&c.content.id===b.id){let d=
H(b.amount,c.da-c.content.amount);c.content.amount+=d;if((b.amount-=d)<=0)return null}for(let c of a)if(!c.content&&(!c.filter||c.filter(b.id)))if(a=H(b.amount,c.da),a<=b.amount){if(c.content=bc(b.id,a),(b.amount-=a)<=0)return null}else return c.content=b,null;return b},ec=(a,b)=>({mb:0,Db:0,nb:0,Z:0,Aa:0,La:0,qa:0,ca:-1,ra:0,Ma:null,Na:null,u:1,Qb:20,M:Ra(36).fill(null).map(()=>({content:null,filter:null,da:64})),gb:0,name:b.label||"Jugador",N:a.Va,O:a.Wa,P:a.Xa,Vb:0,Wb:0,T:0,Ga:0,va:0,wa:0,xa:0}),
hc=(a,b)=>{b=H(5,b*.01);a.va-=a.va*.1*b;a.wa-=a.wa*.1*b;a.xa-=a.xa*.1*b;a.va+=(Ca(a.Z)*a.mb+Da(a.Z)*a.nb)*b;a.wa+=a.Db*b;a.xa+=(-Da(a.Z)*a.mb+Ca(a.Z)*a.nb)*b;fc(a,a.Vb*b*1.5,a.Wb*b*1.5);a.N+=a.va*b;a.O+=a.wa*b;a.P+=a.xa*b},fc=(a,b,c)=>{a.Z=(a.Z+b+ua*100)%(ua*2);a.Aa=I(-va,H(va,a.Aa+c))},ic=a=>{a+=32;a>33&&a<39?a++:a>38&&a<44?a+=2:a>43&&a<127?a+=3:a>126&&a<55258?a+=37:a>55295&&(a+=8485);return Ga(a)},jc=a=>a-(a>63743?8517:a>159?69:a>46&&a<130?35:a>40&&a<46?34:a>34&&a<40?33:32),lc=()=>{var a=kc,b=a.length,
c=new bb,d=t=>{k=k<<1|t&1;++p===15&&(r+=ic(k),k=p=0)},e=()=>{for(let t=0;t<q;++t)d(0)},f=t=>{d(t);d(t>>1);d(t>>2);d(t>>3);d(t>>4);d(t>>5);d(t>>6);d(t>>7)},g=()=>{--n===0&&(n=1<<q++)},l=()=>{if(u)u=!1;else{let t=w.id;for(let E=0;E<q;E++)d(t>>E)}},h=a[0],r="",k=0,p=2,q=2,n=2,A=2,w={id:A++,bb:new bb},u=!0;f(h);c.set(h,w);for(let t=1;t<b;++t){let E=w.bb.get(h=a[t]);E?w=E:(l(),c.has(h)||(g(),e(),f(h),c.set(h,{id:A++,bb:new bb}),u=!0),w.bb.set(h,{id:A++,bb:new bb}),w=c.get(h),g())}l();c.has(h)||(g(),e(),
f(h));g();d(1);--q;e();return r+=ic(k<<15-p)},mc=a=>{var b=kc;if(!a)return!1;var c=a.length,d=()=>{p+=(A>>--w&1)<<q++;w===0&&(w=15,A=jc(a.charCodeAt(n++)))},e=[0,1],f=1,g=3,l=2,h=null,r=null,k=0,p=0;r=2;for(var q=0,n=0,A=jc(a.charCodeAt(n++)),w=15;q<r;)d();if(p===1)return!1;for(p=q=0;q<8;)d();h=[p];e[2]=h;for(b[k++]=p;n<=c;){r=l;for(p=q=0;q<r;)d();if(p===0){for(p=q=0;q<8;)d();e[g]=[p];p=g++;--f===0&&(f=1<<l++)}else if(p===1)return!0;r=p<e.length?e[p]:h.concat(h[0]);for(let u=0;u<r.length;u++)b[k++]=
r[u];e[g++]=h.concat(r[0]);h=r;--f===0&&(f=1<<l++)}return!1},nc=new bb,oc=new $a(1024),kc=new Sa(oc.buffer),pc=a=>{var b=W.Za.find(c=>c.id===a);b={ia:null,ab:null,ea:null,Ba:null,Oa:0,ac:[],Y:!1,o:!1,Ca:!b.writable||b.locked,Kb:0,Lb:0,Mb:0,id:a,Ra:0,Sa:0,Xb:0,U:0,Va:.5,Wa:8.5,Xa:.5,time:0,zb:0};nc.set(a,b);X.A({$a:[...nc.keys()]});return b},qc=(a,b,c,d)=>c<0||c>63?0:a.ia[(b<<a.U+4|d)<<6|c],rc=(a,b,c,d)=>{var e=a.U,f=a.ea[(b>>4<<e|d>>4)<<2|c>>4];f.sa||(a.ia[(b<<e+4|d)<<6|c]=0,f.o=f.ta=!0)},sc=(a,b,
c,d,e)=>{var f=a.U,g=a.ea[(b>>4<<f|d>>4)<<2|c>>4];b=(b<<f+4|d)<<6|c;return g.sa||a.ia[b]!==0?!1:(a.ia[b]=e,g.o=g.ta=!0)},Gc=(a,b,c)=>{m(function*(){a.ea&&(yield Ec(a,b,!0));var d=1<<(a.U=c),e=a.ea=[];for(let f=0;f<d;++f)for(let g=0;g<d;++g)for(let l=0;l<4;++l)e.push({o:!1,sa:!1,ta:!1,x:f,y:l,z:g,pa:f+1,za:0});d<<=c+12+2;a.ia===null||a.ia.length<d?a.ab=new $a((a.ia=new Sa(d)).buffer):a.ab.fill(0);Fc(a,b,!0)}())},Fc=(a,b,c)=>{var d=I(H(b.O,63),0)>>4,e=F(b.N)>>4,f=F(b.P)>>4;if(c||a.Lb!==d||a.Ra+a.Kb!==
e||a.Sa+a.Mb!==f){c=a.ea;b=1<<a.U;let g=a.Kb=(65536+e)%b,l=a.Mb=(65536+f)%b,h=b>>1,r=I(h-2,8),k=a.Ba=[];a.Oa=0;a.Lb=d;a.Ra=e-g;a.Sa=f-l;for(let p=0,q=c.length;p<q;++p){let {x:n,y:A,z:w}=c[p];e=ta(n-g);f=0;e>h&&(e=b-e,f=n<g?b:-b);if(e>r)continue;let u=ta(w-l),t=0;u>h&&(u=b-u,t=w<l?b:-b);u>r||k.push({Jb:e*e+u*u+wb(A-d),qb:p,Ra:f,Sa:t})}k.sort((p,q)=>p.Jb-q.Jb)}a.Y||Hc(a,!1)},Ec=(a,b,c)=>m(function*(){if(!(!c&&a.Y||a.Ca)&&a.o){a.Y=!0;a.o=!1;for(var d=Ia.now(),e=b.M.map(({content:f})=>f&&[f.id,f.amount,
f.data]);e.length>0&&e[e.length-1]===null;)e.pop();O(`minicraft.world.${a.id}:meta`,Na({p:{h:b.Qb,i:e,m:b.u,p:[b.N,b.O,b.P,b.Z,b.Aa]},s:[a.Va,a.Wa,a.Xa],t:a.time,v:1}));e=null;for(let f of a.ea)f.o&&(e=Ic(a,f));yield e;X.na(a.id,{mod_l:d});a.Y=!1}}()),Kc=(a,b)=>{var c=Oa(M.getItem(`minicraft.world.${a.id}:meta`));if(c){let d=c.p,e=c.s,f=c.t;c.v!=null&&(d.i.forEach((g,l)=>{g&&(b.M[l].content=bc(g[0],g[1],g[2]))}),b.Qb=d.h,b.u=d.m,b.N=d.p[0],b.O=d.p[1],b.P=d.p[2],b.Z=d.p[3],b.Aa=d.p[4],a.Va=e[0],a.Wa=
e[1],a.Xa=e[2],f!=null&&Jc(a,f))}},Jc=(a,b)=>{a.time=b%24E3;a.zb=(b+6E3)/24E3%1},Lc=(a,b,c)=>`${a}/${b}`+(c>0?"/"+c:""),Nc=a=>m(function*(){a.Y=!0;var b=a.ea[a.Ba[0].qb];yield Ob(a.id,Lc(b.pa,b.za,b.y));b.pa++;a.Oa=0;return Mc(a)}()),Ic=(a,b)=>m(function*(){++a.Xb;var c=a.ab,d=a.U,e=b.y,f=(256<<d)-256;for(let g=0,l=-1,h=((b.x<<d+4|b.z)<<6|e)<<2;g<16;++g){for(d=0;d<16;++d)oc[++l]=c[h],oc[++l]=c[++h],oc[++l]=c[++h],oc[++l]=c[++h],h+=13;h+=f}b.o=!1;yield Nb(a.id,Lc(b.pa,b.za,e),lc());--a.Xb}()),Mc=a=>
m(function*(){a.Y=!0;yield Hc(a,!0);a.Y=!1}()),Hc=(a,b)=>m(function*(){for(var c=a.ab,d=a.ea,e=a.Ba,f=a.ac,g=a.Ra,l=a.Sa,h=a.U,r=null,k=null,p=e.length;a.Oa<p;){var q=e[a.Oa++];let n=d[q.qb],A=n.y,w=g+q.Ra+n.x;q=l+q.Sa+n.z;if(w!==n.pa||q!==n.za){let u={Gb:n,data:"nope",pa:w,za:q};n.sa&&(r=f.findIndex(t=>t.Gb===n),f.splice(r,1));n.sa=!0;f.push(u);n.o&&(k=Ic(a,n));r=Mb(a.id,Lc(n.pa=w,n.za=q,A)).then(t=>{u.data=t});if(!b&&f.length>5)break}}b&&(yield r);for(d=0;f.length>0&&f[0].data!=="nope";){let {Gb:n,
data:A,pa:w,za:u}=f.shift();if(n.sa&&n.pa===w&&n.za===u)if(n.sa=!1,e=(256<<h)-256,l=n.y,g=((n.x<<h+4|n.z)<<6|l)<<2,mc(A)){n.ta=!0;for(let t=0,E=-1;t<16;++t){for(l=0;l<16;++l)c[g]=oc[++E],c[++g]=oc[++E],c[++g]=oc[++E],c[++g]=oc[++E],g+=13;g+=e}}else if(l===0)for(n.ta=!0,l=0;l<16;++l){for(p=0;p<16;++p)c[g]=50397446,c[++g]=131843,c[++g]=0,c[++g]=0,g+=13;g+=e}else if(n.ta)for(n.ta=!1,l=0;l<16;++l){for(p=0;p<16;++p)c[g]=0,c[++g]=0,c[++g]=0,c[++g]=0,g+=13;g+=e}if(!b&&++d>5)break}b&&(yield k)}()),Oc=null,
Pc=0,Qc=new ab,Rc=a=>{if(a){let b=new Image;b.onload=()=>{if(W.ha===a){var c=qa.createElement("canvas");c.width=16;c.height=416;c=c.getContext("2d");c.scale(1,-1);for(let d=0;d<26;++d)c.drawImage(b,0,d<<4,16,16,0,-(d<<4)-16,16,16);Oc=new $a(c.getImageData(0,0,16,416).data.buffer);for(let d of Qc)d.o=!0;Pc=a;X.A({ha:0})}};b.onerror=()=>{W.ha===a&&(alert("\u00a1Error al cargar la superficie!"),ca(),X.X({V:Pc}),X.A({ha:0}),da())};b.src=`/static/minicraft/textures/${a}.png`}else Oc=null},Tc=(a,b)=>{var c=
{$b:b,pb:b.getContext("2d",{alpha:!1,desynchronized:!0}),Eb:null,Fb:null,tb:"",o:!1,Nb:0,ub:0,bc:gb(()=>(c.Nb=c.ub,c.ub=0),1E3),L:a};Qc.add(c);Sc(c);return c},Uc=(a,b)=>{++a.ub;var c=a.pb,d=a.Eb,e=a.Fb,f=a.L,g=f.config,l=f.Qa,h=f.j,r=f.Ta,k=f.Ua,p=f.world,q=0;if(!f.G||a.o){a.o=!1;var n=g.ua;let sd=g.ma;var A=h.Z,w=h.Aa;let td=h.qa,ud=h.ra,Ta=h.u;var u=h.N;q=h.O;var t=h.P;let vd=l?h.ca:-1,wd=p.ia;var E=p.U;let xd=Oc!==null;var pb=1/r,za=1/k,G=r>>1,N=k>>1;let tc=H(r,k),uc=tc>32,vc=Ca(A);A=Da(A);let wc=
Ca(-w);w=Da(-w);var Ja=g.Ia/45;let yd=pb*(r<k?Ja*r*za:Ja);pb=za*(k<r?Ja*k*pb:Ja);u+=65536;za=q+65536;t+=65536;Ja=u%1;let zd=za%1,Ad=t%1;E=4+E;let Ka=(1<<E)-1;n=n<r?n:1;let Bd=r-n,xc=h.u===1?6:4,Ua=h.qa=h.ra=h.La=0,yc=0;h.ca=-1;q=q<0||q>=64?0:qc(p,u&Ka,za&63,t&Ka);if(Ta!==2&&q>0)h.qa=u&Ka,h.ca=za&63,h.ra=t&Ka,h.La=6,e.fill(Cb[q]|4278190080);else{for(let Va=0;Va<k;++Va){var qb=(N-Va)*pb;let zc=qb*wc-w;var Fb=qb*w+wc;qb=Fb*A;Fb*=vc;let ka=0,La=!1;var Wa=!1;a:for(let Q=0;Q<r;Q+=n)for(let aa=Wa?1:0;aa<
n;++aa){if(n<2)var K=Q;else if(Q===0)K=aa===0?0:aa===1?n:aa-1,La=aa===1;else if(Q<Bd)K=(La=aa===1)?Q+n:Q+aa-1;else{if((K=aa===0?Q-1:Q+aa)>=r)break a;La=!1}var R=(K-G)*yd;Wa=qb+vc*R;let Ac=Fb-A*R,Cd=yc;R=16757124;let rb=1,Bc=sd,sb=0;Ta===2&&q>0&&(sb=xa()*10);for(let Gb=0;Gb<3;++Gb){let S=(Cd+Gb)%3,ba=Ac;var L=Ad;S===0&&(ba=Wa,L=Ja);S===1&&(ba=zc,L=zd);var ra=-1/ba;ba>0&&(L=1-L,ra*=-1);let tb=Wa*ra,Aa=zc*ra;ra*=Ac;let Cc=Ea(tb*tb+Aa*Aa+ra*ra),Xa=u+tb*L-(S===0&ba<0|0),Ya=za+Aa*L-(S===1&ba<0|0),Za=t+
ra*L-(S===2&ba<0|0);L*=Cc;for(let Hb,Ib,Jb,T;L<Bc;Xa+=tb,Ya+=Aa,Za+=ra,L+=Cc)if(!(Ta===2&&L<sb))if(Ya<65536){if(Aa<0)break}else if(Ya>=65600){if(Aa>0)break}else if((T=wd[((Hb=Xa&Ka)<<E|(Jb=Za&Ka))<<6|(Ib=Ya&63)])!==0){Ta!==2&&Va===N&&K===G&&L<=xc&&(h.qa=Hb,h.ca=Ib,h.ra=Jb,h.La=ba<0|S<<1,xc=L);if(xd){--T;S===1?T===6?T=25:T===13?T=4:T===1&&Aa>0&&(T=2):T===1&&(T=24);let Dc=Oc[T<<8|((S===1?Za:Ya)*16&15)<<4|(S===1?Xa:(ba>0?Xa-Za:Za-Xa)+65536)*16&15];if(Dc>>>24===0)continue;R=Dc&16777215}else R=Cb[T];Bc=
L;rb=(S===0?.8:S===2?.6:ba>0?.4:1)+(Ib!==vd||Hb!==td||Jb!==ud?0:.2);yc=S;break}else Ta===2&&L<sb&&(sb=L)}R=4278190080|H((R>>16)*rb,255)<<16|H((R>>8&255)*rb,255)<<8|H((R&255)*rb,255);if(Wa=(La=La&&(Va!==N||K<G||K>G+n))&&ka===R){if(n>6){e.fill(ka,Ua+Q+1,Ua+Q+n+1);break}K=Ua+Q+1;e[K]=ka;e[++K]=ka;if(n<3)break;e[++K]=ka;if(n<4)break;e[++K]=ka;if(n<5)break;e[++K]=ka;if(n<6)break;e[++K]=ka;break}if(La||K===0)ka=R;e[Ua+K]=R}Ua+=r}l&&!uc&&(e[r*N+G]^=16777215)}c.putImageData(d,0,0);l&&uc&&(d=H(ya(tc*.05),
8),c.fillRect(G-d,N-1,d<<1,2),c.fillRect(G-1,N-d,2,d-1),c.fillRect(G-1,N+1,2,d-1))}Fc(p,h,!1);f.fb?(c=F(h.O)>>4,G=c>=0&&c<4&&p.Ba&&p.ea[p.Ba[0].qb],N=[],G&&(G.o&&N.push("modified"),G.sa&&N.push("loading"),G.ta||N.push("empty")),a.tb=`minicraft 0.13.1 ${vb(a.Nb,"\u00a0")} fps, T: ${vb(p.zb*24,"0")}:${vb(p.zb*24%1*60,"0")}; ${f.G&&b%1E3<500?"":p.time}${p.Y?" busy":""}
R: ${r}x${k} (x${g.$}), D: ${g.ma}, C: ${p.Oa}/${p.Ba.length}, M: ${wb(1<<4+p.U)*64>>10}k
E: 0/0, M: ${h.u}, I: ${q}

Position: ${h.N.toFixed(2)} ${h.O.toFixed(2)} ${h.P.toFixed(2)}
Angle: ${(h.Z*wa).toFixed(2)} ${(h.Aa*wa).toFixed(2)}
Focus: ${h.ca<0?"":"("+h.qa+" "+h.ca+" "+h.ra+") "+"WEBTSNI"[h.La]+": "+Ab[qc(p,h.qa,h.ca,h.ra)]}
Chunk abs: (${F(h.N)>>4} ${F(h.P)>>4} ${c}) ${G?"rel: ("+G.x+" "+G.z+" "+G.y+") "+N.join(" "):"void"}`):a.tb=""},Sc=a=>{var b=a.$b,c=a.L;a.Fb=new $a((a.Eb=a.pb.createImageData(b.width=c.Ta,b.height=c.Ua)).data.buffer);var d=c.Ta*c.config.$/c.Fa,e=c.Ua*c.config.$/c.Fa;b.style.width=d+"px";b.style.height=e+"px";b.style.left=Ba((c.ib-d)/2)+"px";b.style.top=Ba((c.jb-e)/2)+"px";a.pb.fillStyle="rgba(255,255,255,.5)"},Vc=0,Yc=(a,b,{config:c,account:d})=>{var e=pc(c.Ja);d=ec(e,d);Kc(e,d);var f={config:c,
Hb:0,Ib:0,fb:!1,Qa:!0,G:!0,Ob:a,ka:0,ga:new ab,wb:"",l:0,J:[],j:d,xb:null,B:null,Fa:1,ib:1,jb:1,Ta:0,Ua:0,kb:0,Ub:0,lb:0,jc:gb(()=>{var g;(g=f.G)||(e.o=!0,Jc(e,e.time+1),g=void 0);return g},50),Ya:b,world:e};Wc(f,null);Xc(f);return f},Xc=a=>{m(function*(){if(!a.config.Da)try{yield a.Ob.requestPointerLock()}catch(b){}}())},Zc=(a,b)=>a===b?0:.1-a*.2,$c=a=>{a.j.mb=Zc((a=a.ga).has(-12)||a.has(65),a.has(-13)||a.has(68))},ad=a=>{a.j.Db=Zc((a=a.ga).has(-15)||a.has(16),a.has(-14)||a.has(32))},bd=a=>{a.j.nb=
Zc((a=a.ga).has(-11)||a.has(83),a.has(-10)||a.has(87))},cd=a=>{a.j.Vb=Zc(a.ga.has(-18),a.ga.has(-19))},dd=a=>{a.j.Wb=Zc(a.ga.has(-17),a.ga.has(-16))},fd=(a,b,c)=>{if(!a.world)return!1;var d=a.ga,e=a.j;if(c){if(d.has(b))return!1;d.add(b);var f=e.qa,g=e.ca;c=e.ra;switch(b){case -18:case -19:cd(a);break;case -17:case -16:dd(a);break;case -1:!a.world.Ca&&e.u!==2&&g>=0&&(e.gb===0?e.u===0&&(b=qc(a.world,f,g,c),b===2?b=3:b===1&&(b=4),b===15||b===6||b!==8&&b!==13&&dc(e.M,bc(b,1))!==null)||(rc(a.world,f,g,
c),e.ca=-1):ed(a,[f,g,c],!1));break;case -2:case 71:if(g>=0){let l=qc(a.world,f,g,c);c=e.M.slice(0,9);g=c.findIndex(h=>h.content!==null&&h.content.id===l);g>=0?e.T=g:e.u===1&&(c[e.T].content&&(c=c.findIndex(h=>h.content===null),c>=0&&(e.T=c)),e.M[e.T].content=bc(l));e.Ga=a.ka}break;case -3:if(!a.world.Ca&&e.u!==2&&g>=0)if(e.gb===0){if(b=e.M[e.T],b.content){switch(e.La){case 0:--f;break;case 1:++f;break;case 2:--g;break;case 3:++g;break;case 4:--c;break;case 5:++c}g>=0&&g<64&&sc(a.world,f&(1<<4+a.world.U)-
1,g,c&(1<<4+a.world.U)-1,b.content.id)&&e.u!==1&&--b.content.amount<=0&&(b.content=null)}}else ed(a,[f,g,c],!0);break;case -4:e.T=(e.T+9-1)%9;e.Ga=a.ka;break;case -5:e.T=(e.T+1)%9;e.Ga=a.ka;break;case 27:a.l===0&&(a.G=!0,a.l=1);break;case -15:case -14:case 16:case 32:ad(a);break;case 49:case 50:case 51:case 52:case 53:case 54:case 55:case 56:case 57:e.T=b-49;e.Ga=a.ka;break;case -12:case -13:case 65:case 68:$c(a);break;case 69:if(a.l===0){a.l=3;for(let l of d)fd(a,l,!1)}break;case 70:a.Ya.Pb();break;
case 80:a.world&&(a.G=!0);break;case 81:e=e.M[e.T];if(d.has(17)||e.content&&--e.content.amount<=0)e.content=null;break;case -11:case -10:case 83:case 87:bd(a);break;case 84:if(a.l===0){a.l=2;for(let l of d)fd(a,l,!1)}break;case 112:a.Qa=!a.Qa;break;case 114:a.fb=!a.fb;case 116:case 122:case 123:break;default:return!1}}else{if(!d.delete(b))return!1;switch(b){case -15:case -14:case 16:case 32:ad(a);break;case -12:case -13:case 65:case 68:$c(a);break;case -11:case -10:case 83:case 87:bd(a);break;case -18:case -19:cd(a);
break;case -17:case -16:dd(a)}}a.wb=[...d].join();return!0},gd=(a,b)=>(b=b.startsWith("~")?a+U(b.slice(1)):U(b),isNaN(b)?a:b),id=(a,b)=>{var c=a.j,d=a.world;if(b)if(b.charAt(0)==="/"){b=b.slice(1).split(" ");let e=b.shift();switch(e){case "clear":a.J=[];break;case "clearinv":for(let f of c.M)f.content=null;Z(a,"Inventario vaciado.",!0);break;case "gamemode":case "gm":b=U(b[0]);!isNaN(b)&&b>=0&&b<3&&b%1===0?(c.u=b,Z(a,"Modo de juego establecido: "+b,!0)):Z(a,"\u00a1El modo de juego debe estar entre 0 y 2!");
break;case "give":if(b.length===0){Z(a,"/give <id> [Cantidad]\n"+Ab.join(" "));break}d=Ab.indexOf((b[0]||"").toLowerCase());d=d>=0?d:U(b[0]);b=U(b[1]||1);!isNaN(d)&&d>0&&d<25&&d%1===0?!isNaN(b)&&b>0&&b%1===0?Z(a,dc(c.M,bc(d,b))?"\u00a1El inventario est\u00e1 lleno!":`Se han dado ${b} ${Bb[d]}`,!0):Z(a,"\u00a1La cantidad debe ser al menos 1!"):Z(a,"\u00a1Tipo de bloque no v\u00e1lido!");break;case "help":Z(a,"Comandos: clear, clearinv, gamemode, give, help, load, me, save, spawn, teleport, time, version");
break;case "load":if(d.Y){Z(a,"\u00a1Sin permisos!");break}Mc(d).then(()=>{a.B.o=!0;Z(a,"Chunks cargados.",!0)});break;case "me":Z(a,c.name+" "+b.join(" "),!0);break;case "save":if(a.world.Ca||d.Y){Z(a,"\u00a1Sin permisos!");break}Ec(a.world,a.j,!1);Z(a,"Juego guardado.",!0);break;case "spawn":if(a.world.Ca){Z(a,"\u00a1Sin permisos!");break}d.Va=c.N;d.Wa=c.O;d.Xa=c.P;Z(a,"Punto de aparici\u00f3n actualizado.",!0);break;case "teleport":case "tp":b.length===0?(c.N=d.Va,c.O=d.Wa,c.P=d.Xa,a.B.o=!0,Z(a,
"Teletransportado al punto de aparici\u00f3n.",!0)):b.length===3?(Z(a,`Teletransportado a ${c.N=gd(c.N,b[0])} ${c.O=gd(c.O,b[1])} ${c.P=gd(c.P,b[2])}`,!0),a.B.o=!0):Z(a,"\u00a1Mala suerte!");c.va=0;c.wa=0;c.xa=0;break;case "time":c=b[1];if(!c){Z(a,"\u00a1Falta par\u00e1metro!");break}if(c==="day")c=1E3;else if(c==="night")c=13E3;else if(isNaN(c=F(U(c))))break;switch(b[0]){case "add":c+=d.time;case "set":Jc(d,c);Z(a,"Hora establecida: "+d.time,!0);break;default:Z(a,"Comando desconocido: time "+b[0])}break;
case "version":Z(a,"minicraft 0.13.1");break;case "_w":X.lc({type:b[0]==="m"?1:0});break;case "/exit":c.gb=0;Z(a,"Modo de rat\u00f3n normal.",!0);break;case "/expand":a.j.Ma&&a.j.Na?d=!0:(Z(a,"\u00a1Se requiere selecci\u00f3n!"),d=!1);d&&(b[0]==="vert"?(c.Ma[1]=0,c.Na[1]=63,Z(a,"Selecci\u00f3n ampliada.",!0)):Z(a,'\u00a1Solo se admite "vert"!'));break;case "/pos1":case "/pos2":ed(a,[F(c.N),F(c.O),F(c.P)],e==="/pos2");break;case "/regen":if(a.world.Ca||d.Y){Z(a,"\u00a1Sin permisos!");break}Nc(d).then(()=>
{a.B.o=!0;Z(a,"Chunk regenerado.",!0)});break;case "/show":Z(a,`Principal: ${c.Ma?c.Ma.join(" "):"ninguno"}, Secundario: ${c.Na?c.Na.join(" "):"ninguno"}`);break;case "/wand":c.gb=1;Z(a,"Selecci\u00f3n usando los botones del rat\u00f3n.",!0);break;default:Z(a,"Comando desconocido: "+e)}}else{let e=Z(a,`<${c.name}> `+b);Wc(a,b).then(f=>{f&&hd(a,e)})}},Z=(a,b,c=!1)=>{var d=++Vc;(a.J=a.J.slice(-49)).push({id:d,Rb:c,time:oa(),value:b});return d},hd=(a,b)=>{var c=a.J.findIndex(d=>d.id===b);c>=0&&a.J.splice(c,
1)},ed=(a,b,c)=>{c?a.j.Na=b:a.j.Ma=b;Z(a,`${c?"Punto secundario":"Punto principal"}: ${b.join(" ")}`,!0)},Wc=(a,b)=>(hb(a.xb),a.xb=fb(Wc,5E3,a,null),(b?P("/api/chat",Object.assign({},ob,{body:Na({msg:b})})):P("/api/chat")).then(c=>c.ok&&c.text()).then(c=>{if(c){c=c.split("\n").filter(Boolean);for(let d of c)d.startsWith("<")&&Z(a,d);return c.length>0}return!1}).catch(()=>!1)),jd=({id:a,W:b})=>(x("div[className=bitmap]",{S:{backgroundImage:`url(/static/minicraft/textures/${b}.png)`,backgroundPositionY:100-
a*100+"%"}}),null);function kd({amount:a,u:b,id:c,W:d}){x("div[className=stack]",{title:Bb[c]+(b===1?` (${Ab[c]}, ${c})`:"")});return[B(jd,{id:c,W:d}),a!==1&&C("div[className=amount]",{innerText:a})]}
function ld({j:a,W:b,Ha:c,H:d}){x("table[className=bar]",{ontouchstart:la(g=>{a.T=Number(g.target.closest("[data-slot]").dataset.slot);a.Ga=g.timeStamp}),S:{left:I(0,d/2-180)+"px",opacity:I(.5,H(1,1-(c-a.Ga-5E3)*5E-4))}});var e=z(g=>({height:g=g-8+"px",width:g}),[H(d/9,40)]),f=a.u;return[C("tr",null,a.M.slice(0,9).map(({content:g},l)=>C("td",{D:{slot:l},F:{active:l===a.T},S:e},[g&&B(kd,{amount:g.amount,data:g.data,u:f,id:g.id,W:b}),!g&&C("div[className=stack]")])))]}
var md=Ra(4).fill(null).map((a,b)=>Ra(9).fill(null).map((c,d)=>b*9+d));md.push(md.shift());function nd({fc:a,W:b,hc:c}){x("table",{onclick:({target:e})=>{e.className==="bitmap"&&cc({content:bc(U(e.parentElement.parentElement.dataset.id)),filter:null,da:64},a);return!1}});var d=0;return Ra(3).fill(null).map(()=>C("tr",null,Ra(9).fill(null).map(()=>++d<25&&C("td",{D:{id:d},S:c},[B(kd,{amount:1,data:null,u:1,id:d,W:b})]))))}
var od={fontSize:"",height:"32px",width:"32px"},pd={fontSize:"75%",height:"16px",width:"16px"};
function qd({L:a,W:b,ya:c,H:d}){var e=z(()=>({content:null,filter:null,da:64})),f=a.j.u;x("div[className=menu]",z(()=>({onclick:({target:h})=>{if(h.className==="menu")e.content?e.content=null:(a.l=0,a.G=!1,Xc(a));else if(h.parentElement.className==="stack"&&h.parentElement.parentElement.dataset.slot||h.tagName==="TD")h=a.j.M[U((h.tagName==="TD"?h:h.parentElement.parentElement).dataset.slot)],e.content?cc(e,h):h.content&&cc(h,e)},oncontextmenu:({target:h})=>{if(h.className==="menu")e.content?--e.content.amount<=
0&&(e.content=null):(a.l=0,a.G=!1,Xc(a));else if(h.parentElement.className==="stack"&&h.parentElement.parentElement.dataset.slot||h.tagName==="TD")h=a.j.M[U((h.tagName==="TD"?h:h.parentElement.parentElement).dataset.slot)],e.content?cc(e,h,1):h.content&&cc(h,e,ya(h.content.amount/2))}})));var g,l;[g,l]=z(()=>{var h=H(d,c)<400;return[{left:`${d/2-(h?96:168)}px`,top:`${c/2-(h?91:147)}px`},h?pd:od]},[c,d]);return[C("div[className=window]",{S:g},[C("h2[innerText=Inventario]"),f===1&&B(nd,{fc:e,W:b,hc:l}),
C("table",null,md.map((h,r)=>C(r<3?"tr":"tr[className=last]",null,h.map(k=>C("td",{D:z(()=>({slot:k})),S:l},[(k=a.j.M[k].content)&&B(kd,{amount:k.amount,data:k.data,u:f,id:k.id,W:b})])))))]),e.content&&C("div[className=hand]",{S:{left:a.Hb+"px",top:a.Ib+"px"}},[B(kd,{amount:e.content.amount,data:e.content.data,u:0,id:e.content.id,W:b})])]}
function rd({I:{Rb:a,time:b,value:c},Ha:d}){b=H(1,1-(d-b-4500)*.001);x(a?"div[className=minor]":"div",{S:{opacity:b}});return[C("div[className=backdrop]"),C("span",{innerText:c})]}function Dd({J:a,Ha:b}){x("div[className=messages]");return[na(rd,a.slice(-10).filter(c=>c.time>b-5E3),{Ha:b})]}function Ed({I:a,current:b,ha:c}){x("tr");return[C("td",null,[C("button",{disabled:a.id===b||c>0,innerText:`${a.label} (${a.owner})`,onclick:()=>{ca();X.X({V:a.id});X.A({ha:a.id});da()}})])]}
function Fd({L:a,state:{config:b,ha:c},ba:d}){a&&y(()=>{Ec(a.world,a.j,!1)});var e,f;[e,f]=ja(!1);var g=ea(()=>e?P("/static/minicraft/textures.json").then(zb).catch(()=>null):J.resolve(null),[e],null);x("div[className=menu]");return[C("h1",{innerText:e?"Superficies":"Ajustes"}),C("div[className=row]",null,[C("button",{innerText:a&&!e?"Volver al juego":"Volver",onclick:()=>{e?f(!1):a?(a.l=0,a.G=!1,Xc(a)):d(2)}})]),!e&&C("table[className=settings]",null,[C("tr",null,[C("td",null,[C("button[innerText=Superficies...]",
{onclick:()=>{f(!0)}})]),C("td",null,[C("label[htmlFor=setting-resolution]",{innerText:`Resoluci\u00f3n: 1:${b.$}\n`}),C("input[id=setting-resolution][type=range][min=1][max=20][step=1]",{value:21-b.$,onchange:l=>X.X({$:21-Number(l.target.value)})})])]),C("tr",null,[C("td",null,[C("label[htmlFor=setting-view-angle]",{innerText:`\u00c1ngulo de visi\u00f3n: ${b.Ia}\n`}),C("input[id=setting-view-angle][type=range][min=1][max=180][step=1]",{value:b.Ia,onchange:l=>X.X({Ia:Number(l.target.value)})})]),
C("td",null,[C("label[htmlFor=setting-view-distance]",{innerText:`Distancia de visi\u00f3n: ${b.ma}\n`}),C("input[id=setting-view-distance][type=range][min=16][max=128][step=16]",{value:b.ma,onchange:l=>X.X({ma:Number(l.target.value)})})])]),C("tr",null,[C("td",null,[C("label[htmlFor=setting-pixel-grouping]",{innerText:`Agrupaci\u00f3n de p\u00edxeles: ${b.ua===1?"Desactivado":b.ua}\n`}),C("input[id=setting-pixel-grouping][type=range][min=1][max=8][step=1]",{value:b.ua,onchange:l=>X.X({ua:Number(l.target.value)})})]),
C("td",null,[C("label[htmlFor=setting-mouse-sensitivity]",{innerText:`Sensibilidad del rat\u00f3n: ${b.Ea}\n`}),C("input[id=setting-mouse-sensitivity][type=range][min=1][max=15][step=1]",{value:b.Ea,onchange:l=>X.X({Ea:Number(l.target.value)})})])]),C("tr",null,[C("td",null,[C("button[innerText=Versi\u00f3n 0.13.1][title=P\u00e1gina del proyecto]",{onclick:()=>{open("//github.com/L3P3/minicraft")}})])])]),a&&!e&&C("div[className=row]",null,[C("button[innerText=Salir del mundo]",{onclick:()=>{d(2)}})]),
e&&C("table[className=settings]",null,[C("tr",null,[C("td",null,[C("button[innerText=Liso]",{disabled:b.V===0,onclick:()=>{ca();X.X({V:0});X.A({ha:0});da()}})])]),g&&na(Ed,g,{current:b.V,ha:c})]),e&&g&&C("div[className=row]",null,[C("button[innerText=A\u00f1adir superficie]",{onclick:()=>{open("//l3p3.de/svr/minicraft/textures.html")}})])]}
var Gd=({L:a,ec:b,H:c})=>[C("div[className=toolbar]",null,[C("button[innerText=\u274c]",{onclick:()=>{a.l=0;a.G=!1;Xc(a)}})]),C("input[autocomplete=off][enterkeyhint=send][mozactionhint=send][name=message][required]",{onkeydown:d=>{var e=d.keyCode;d=d.target;e===13?(id(a,d.value),d.value=""):e===27&&(a.l=0,a.G=!1,Xc(a))},R:d=>{b.input=d;fb(()=>d.focus(),0)},S:{width:`${c-40}px`}})],Hd=({I:{Rb:a,value:b}})=>(x(a?"div[className=minor]":"div",{innerText:b}),null);
function Id({L:a,J:b,H:c}){var d=la({history:null,input:null});x("div[className=menu terminal]",{onclick:e=>{e.target!==d.input&&d.input.focus()}});y(e=>{e&&fb(()=>d.history.scrollTop=1E9,0)},[b.length&&b[b.length-1].id]);return[C("div[className=history]",{R:la(e=>{d.history=e})},[na(Hd,b)]),B(Gd,{L:a,ec:d,H:c})]}var Jd=[["pick",-2],["up",-14],["down",-15],["E",69],["T",84],["F1",112],["F3",114],["...",27]],Kd=[C("div")];
function Ld({L:a,H:b}){var c=a.ga;x("div[className=touch]",la({ontouchstart:l=>{var h=l.target.dataset.code||l.target.parentElement.dataset.code;if(h!=null&&fd(a,h=U(h),!0)){let r=l.changedTouches[0].identifier,k=p=>{p.changedTouches[0].identifier===r&&(jb("touchend",k),fd(a,h,!1))};ib("touchend",k)}return!1}}));var d,e;[d,e]=z(l=>[{height:l-8+"px"},{width:l+="px",height:l}],[H(Ba(b/10),40)]);var f,g;[f,g]=z(()=>{var l=b>300?"14px":"0",h=b>300?"2px":"0",r=b>650?l:"40px";return[{borderSpacing:h,bottom:r,
left:l},{borderSpacing:h,bottom:r,right:l}]},[b]);return[C("div[className=top]",null,Jd.map(([l,h])=>C(`div[innerText=${l}]`,{D:{code:h},F:{button:!0,active:c.has(h)}}))),C("table[className=move]",{S:f},[C("tr",null,[C("td"),C("td",{D:{code:-10},F:{"button up":!0,active:c.has(-10)},S:e},Kd)]),C("tr",null,[C("td",{D:{code:-12},F:{"button left":!0,active:c.has(-12)},S:e},Kd),C("td",null,[C("div",{D:{code:-1},F:{"button center":!0,active:c.has(-1)},S:d},Kd)]),C("td",{D:{code:-13},F:{"button right":!0,
active:c.has(-13)},S:e},Kd)]),C("tr",null,[C("td"),C("td",{D:{code:-11},F:{"button down":!0,active:c.has(-11)},S:e},Kd)])]),C("table[className=move]",{S:g},[C("tr",null,[C("td"),C("td",{D:{code:-16},F:{"button up":!0,active:c.has(-16)},S:e},Kd)]),C("tr",null,[C("td",{D:{code:-18},F:{"button left":!0,active:c.has(-18)},S:e},Kd),C("td",null,[C("div",{D:{code:-3},F:{"button center":!0,active:c.has(-3)},S:d},Kd)]),C("td",{D:{code:-19},F:{"button right":!0,active:c.has(-19)},S:e},Kd)]),C("tr",null,[C("td"),
C("td",{D:{code:-17},F:{"button down":!0,active:c.has(-17)},S:e},Kd)])])]}function Md({model:a}){var b=x("canvas");a.B=Tc(a,b);return null}
function Nd({frame:a,fa:b,state:c,ba:d,ya:e,H:f,Ya:g}){var l=c.config,h=oa(),r=qa.pointerLockElement===a,k=z(()=>Yc(a,g,c));y(()=>{Od.add(k);var q=u=>{if(k.l!==0)return!0;qa.pointerLockElement===a?fd(k,-1-u.button,u.type==="mousedown"):Xc(k);return!1},n=u=>{if(qa.pointerLockElement===a){var t=k.config.Ea*ua/(I(k.ib,k.jb)*k.Fa);nb&&(k.Ub=u.timeStamp);fc(k.j,k.kb=u.movementX*t,k.lb=-u.movementY*t)}else t=k.Ob.getBoundingClientRect(),k.Hb=u.clientX-t.left,k.Ib=u.clientY-t.top},A=u=>{X.cb(!1);if(k.l===
0&&!k.G&&ta(u.deltaY)>5)return u=u.deltaY>0?-5:-4,fd(k,u,!0),fd(k,u,!1),!1},w={passive:!0};a.addEventListener("mousedown",q);a.addEventListener("mouseup",q);a.addEventListener("mousemove",n,w);a.addEventListener("wheel",A,w);return()=>{a.removeEventListener("mousedown",q);a.removeEventListener("mouseup",q);a.removeEventListener("mousemove",n,w);a.removeEventListener("wheel",A,w);hb(k.xb);hb(k.jc);Ec(k.world,k.j,!0);nc.delete(k.world.id);X.A({$a:[...nc.keys()]});var u=k.B;Qc.delete(u);hb(u.bc);return Od.delete(k)}});
y(()=>{k.config=l;k.B&&(k.B.o=!0);var q=k.world,n=ya(Fa(k.config.ma/16*2+2));q.U!==n&&Gc(q,k.j,n)},[l]);y((q,n,A)=>{k.Fa=A||1;k.ib=I(1,q);k.jb=I(1,n);n=k.config.$;q=ya(k.ib*k.Fa/n);n=ya(k.jb*k.Fa/n);if(q!==k.Ta||n!==k.Ua)k.Ta=q,k.Ua=n,k.B&&(k.B.o=!0,Sc(k.B))},[a.offsetWidth,a.offsetHeight,pa.devicePixelRatio,l.$]);y(()=>{b&&fd(k,b.code,b.state)},[b]);y(q=>{q||k.G||k.l!==0||(k.l=1,nb&&k.kb|k.lb&&k.Ub>h-100&&(fc(k.j,-k.kb,-k.lb),k.kb=k.lb=0,k.B.o=!0));k.G=!q},[l.Da&&k.l===0||r]);y(q=>r&&q&&qa.exitPointerLock(),
[k.G||k.l!==0]);h===k.ka||Pd||(k.world&&(k.ka&&!k.G&&hc(k.j,h-k.ka),k.B&&Uc(k.B,h)),k.ka=h);ia();var p=la({Ab:1});l.V&&(p.Ab=l.V);return[B(Md,{model:k}),k.Qa&&k.l!==2&&k.J.length>0&&k.J[k.J.length-1].time>h-5E3&&B(Dd,{J:k.J,Ha:h}),k.B&&k.fb&&C("div[className=diagnostics]",{innerText:k.B.tb}),l.Da&&B(Ld,{L:k,wb:k.wb,H:f}),k.Qa&&k.l!==3&&k.j.u!==2&&B(ld,{j:k.j,W:p.Ab,Ha:h,H:f}),(k.l===1||k.l===2||k.l===3)&&C("div[className=backdrop]"),k.l===3&&B(qd,{L:k,W:p.Ab,Ha:h,ya:e,H:f}),k.l===1&&B(Fd,{L:k,state:c,
ba:d}),k.l===2&&B(Id,{L:k,J:k.J,H:f})]}
var Qd=({account:a,busy:b,ob:c,dc:d,ba:e,world:f,Cb:g})=>(x("div"),[C("button[innerText=Entrar]",{disabled:b||d||f.local<2||f.remote>f.local,onclick:()=>{ca();X.X({Ja:f.id});e(0);da()},title:d?"\u00a1El mundo ya est\u00e1 abierto!":f.local<2?"\u00a1El mundo a\u00fan no se ha descargado!":f.local<f.remote?"\u00a1El mundo a\u00fan se est\u00e1 cargando!":"Entrar al mundo seleccionado"}),C("button",{disabled:b||!V||d||f.local>0&&f.remote>0||!f.remote&&!a.rank,innerText:f.local?V&&f&&!f.remote?"Subir":
"Transferir":"Descargar",onclick:()=>{f.local?f.remote||X.na(f.id,{mod_r:1}):X.Yb({id:f.id,label:f.label,mod_l:1,mod_r:f.remote})},title:V?f.local?f.remote?"\u00a1El mundo est\u00e1 presente en ambos lados!":d?"\u00a1El mundo ya est\u00e1 abierto!":a.rank?"Subir mundo al servidor":"\u00a1Sesi\u00f3n no iniciada!":"Descargar mundo del servidor":"\u00a1La lista se est\u00e1 cargando!"}),C("button[innerText=Renombrar]",{disabled:b||d||!f.writable,onclick:()=>{var l=mb("Nueva etiqueta del mundo:\n(m\u00e1x. 16 caracteres)",
f.label);!l||l===f.label||l.length>16||(f.local&&X.na(f.id,{label:l}),f.remote&&(c(!0),P("/api/minicraft/world",Object.assign({},ob,{body:Na({what:"meta",world:f.id,label:l})})).then(zb).catch(h=>{kb("Error al editar el mundo: "+h.message)}).then(()=>{c(!1)})))},title:f.writable?d?"\u00a1El mundo ya est\u00e1 abierto!":"Cambiar nombre del mundo":"\u00a1Sin permisos!"}),C("button",{disabled:b||!f.remote||!f.writable,innerText:`Bloqueado: ${f.locked?"S\u00ed":"No"}`,onclick:()=>{c(!0);P("/api/minicraft/world",
Object.assign({},ob,{body:Na({what:"meta",world:f.id,locked:!f.locked})})).then(l=>(l=zb(l),ca(),Wb(),c(!1),da(),l)).catch(l=>{kb("Error al editar el mundo: "+l.message);c(!1)})},title:f.remote?f.writable?f.locked?"Desbloquear mundo":"Bloquear mundo":"\u00a1Sin permisos!":"\u00a1El mundo no se ha subido!"}),C("button",{disabled:b||!f.remote||!f.writable,innerText:`P\u00fablico: ${f.public?"S\u00ed":"No"}`,onclick:()=>{c(!0);P("/api/minicraft/world",Object.assign({},ob,{body:Na({what:"meta",world:f.id,
public:!f.public})})).then(l=>(l=zb(l),ca(),Wb(),c(!1),da(),l)).catch(l=>{kb("Error al editar el mundo: "+l.message);c(!1)})},title:f.remote?f.writable?f.public?"Despublicar mundo":"Publicar mundo":"\u00a1Sin permisos!":"\u00a1El mundo no se ha subido!"}),C("button",{disabled:b||d||!f.local&&!f.writable,innerText:f.local?"Eliminar (local)":"Eliminar",onclick:()=>{lb('\u00bfRealmente deseas eliminar el mundo "'+f.label+'"?')&&(f.local?(Rb(f.id),X.Zb(f.id)):(c(!0),P("/api/minicraft/world",{method:"DELETE",
headers:{"Content-Type":"application/json"},body:Na({what:"world",world:f.id})}).then(l=>(zb(l),ca(),g(null),Wb(),c(!1),da())).catch(l=>{kb("Error al eliminar el mundo: "+l.message);c(!1)})))},title:d?"\u00a1El mundo ya est\u00e1 abierto!":f.local||f.writable?"Eliminar mundo":"\u00a1Sin permisos!"})]),Rd=a=>{a.scrollIntoView(ub)},Sd=(a,b)=>{a&&fb(Rd,0,b)};
function Td({I:a,account:b,busy:c,ob:d,ba:e,qc:f,Cb:g,oa:l,$a:h}){f=a===f;var r=x("tr",{F:{selected:f},onclick:()=>{g(a.id)}});y(Sd,[f,r]);return[C("td[style=width:0]",{innerText:`${a.local?"L":"_"}${a.local&&a.remote?a.local>a.remote?">":a.local<a.remote?"<":"=":"_"}${a.remote?a.public?"R":"r":"_"}`,S:{color:l===a.id?"yellow":a.local!==a.remote&&a.local&&a.remote?"red":""}}),C("td",{innerText:a.label,title:a.id},[f&&B(Qd,{account:b,busy:c,ob:d,dc:h.includes(a.id),ba:e,world:a,Cb:g})]),C("td[style=width:0]",
null,[C("div[title=Modificado]",{innerText:yb(I(a.local,a.remote),!0)}),f&&C("div",{innerText:a.account_name?a.account_name:"-",title:a.account_name?"Propietario":"Solo un mundo local"})])]}
function Ud({state:{account:a,config:b,ja:c,Bb:d,Ka:e,oa:f,Za:g,$a:l},view:h,ba:r,ya:k,H:p}){var q,n;[q,n]=ja(b.Ja);y(()=>{Ub&&q===Ub[0]&&n(Ub[1])},[Ub]);var A=z(()=>g.find(t=>t.id===q)||null,[q,g]),w,u;[w,u]=ja(!1);x("div",{F:{menu:!0,blurred:h===1}});return[C("button[innerText=Ajustes][style=position:absolute]",{onclick:()=>{r(1)}}),C("button[style=position:absolute;right:0]",{disabled:a.rank>0,innerText:a.rank?a.label:"Iniciar sesi\u00f3n",onclick:()=>{location.href="/account?redir=minicraft"}}),
C("h1[innerText=Mundos]"),C("div[className=row]",null,[C("button[innerText=Actualizar][title=Recargar lista]",{disabled:d||e||c!==null,onclick:Wb}),C("button[innerText=Nuevo mundo]",{onclick:()=>{var t=mb("Etiqueta del nuevo mundo:\n(m\u00e1x. 16 caracteres)","Nuevo mundo");t&&(t.length>16?kb("\u00a1El nombre es demasiado largo!"):X.Yb({id:H(0,...b.worlds.map(E=>E.id))-1,label:t,mod_l:Ia.now(),mod_r:0}))}})]),C("div[className=worlds]",{S:{height:`${I(100,k-140)}px`,width:`${H(480,p-16)}px`}},[C("table[cellSpacing=0]",
null,[na(Td,g,{rc:Ia.now(),account:a,busy:w,ob:u,ba:r,qc:A,Cb:n,oa:f,$a:l})])])]}
function Vd({fa:a,state:b,ya:c,H:d,Ya:e}){var f,g;[f,g]=ja(2);y(()=>{e.kc(f===0?b.Za.find(h=>h.id===b.config.Ja).label+" \u2013 minicraft":"minicraft")},[f]);var l=x("div[className=game]");return[(f===2||f===1)&&B(Ud,{state:b,view:f,ba:g,ya:c,H:d}),f===1&&C("div[className=backdrop]"),f===1&&B(Fd,{L:null,state:b,ba:g}),f===0&&B(Nd,{frame:l,fa:a,state:b,ba:g,ya:c,H:d,Ya:e}),f===2&&b.ja&&C("div[style=position:absolute;bottom:0;left:0;color:yellow]",{title:b.ja},[C("span[innerText=Error de conexi\u00f3n. ]"),
C("button[innerText=Reintentar]",{onclick:()=>{X.A({ja:null})}})])]}
var Wd="nwse-resize ns-resize nesw-resize ew-resize move ew-resize nesw-resize ns-resize nwse-resize".split(" "),Xd={init:(a,b)=>Xd.yb({eb:0,Pa:0,height:0,fa:null,left:0,mode:b,title:"...",top:0,width:0},600,400),Pb:a=>Object.assign({},a,{mode:a.mode===0?1:0}),cc:(a,b)=>a.fa&&a.fa.code===b.code&&a.fa.state===b.state?a:Object.assign({},a,{fa:b}),Tb:(a,b,c)=>Object.assign({},a,{left:I(0,H(b,W.aa-a.width)),top:I(0,H(c,W.la-a.height))}),hb:(a,b)=>Object.assign({},a,b),yb:(a,b,c)=>Object.assign({},a,{Pa:b=
I(100,H(b,W.aa-a.left)),eb:c=I(50,H(c,W.la-a.top)),width:b,height:c}),kc:(a,b)=>Object.assign({},a,{title:b})},Yd=(a,b,c)=>{X.mc(b);var d=c.target;if(d.className==="window_title")d=d.parentElement;else if(c.button!==0||d.className!=="window borders")return;c.preventDefault();qa.activeElement.blur();var e,f;[e,f]=a;var g=c.clientX,l=c.clientY,h=g-e.left,r=l-e.top,k=h<8?0:h<e.width-8?1:2,p=r<8?0:r<e.height-8?1:2,q=k+p*3;d.style.willChange=q===4?"left,top":"contents";X.A({cursor:Wd[q]});var n=w=>{Pd=
!0;ca();var u=w.clientX,t=w.clientY;a:if(q===4){if(w.type==="mouseup"){if(t<4){f.hb({left:0,top:0,width:W.aa,height:W.la});break a}if(u<4){f.hb({left:0,top:0,width:ya(W.aa/2),height:W.la});break a}if(u>W.aa-3){f.hb({left:ya(W.aa/2),top:0,width:F(W.aa/2),height:W.la});break a}}else if([w]=a,w.Pa!==w.width||w.eb!==w.height){f.yb(w.Pa,w.eb);let [E]=a;h=Ba(h*E.Pa/w.width)}f.Tb(u-h,t-r)}else k!==0&&p!==0||f.Tb(k===0?(u=I(h,H(u,e.left+e.width-100+h)))-h:e.left,p===0?(t=I(r,H(t,e.top+e.height-50+r)))-r:
e.top),f.yb(k===0?e.width+e.left+h-u:k===1?e.width:e.width-g+u,p===0?e.height+e.top+r-t:p===1?e.height:e.height-l+t);da();Pd=!1},A=w=>{jb("mousemove",n,!0);jb("mouseup",A);X.A({cursor:null});n(w);d.style.willChange="auto"};ib("mousemove",n,!0);ib("mouseup",A)},Zd=({height:a,left:b,mode:c,top:d,width:e},f)=>({F:{window:!0,borders:c===1},onmousedown:f,S:{display:c===2?"none":"block",left:c===0?"0":b-1+"px",top:c===0?"0":d-1+"px",height:c===0?"100%":a-40+"px",width:c===0?"100%":e-16+"px"}}),$d=({title:a,
width:b,nc:c})=>[C("div[className=window_title]",{innerText:a,S:{width:`${b-40}px`}}),C("div[className=window_button]",{onclick:()=>X.oc(c)})];
function ae({I:{id:a,Sb:b,type:c},state:d}){var e=fa(Xd,b),f,g;[f,g]=e;y(()=>(be.set(a,g),()=>be.delete(a)));b=z(()=>Yd.bind(null,e,a));x("div",z(Zd,[f,b]));var l=ha(!0,!1);y((r,k)=>{l&&g.hb({left:I(0,H(f.left,r-f.width)),top:I(0,H(f.top,k-f.height)),width:H(r,I(100,f.Pa,f.width)),height:H(k,I(50,f.eb,f.height))})},[d.aa,d.la]);b=f.mode===0?d.aa:f.width-16;var h=f.mode===0?d.la:f.height-40;return[c===1&&B(Vd,{fa:f.fa,state:d,ya:h,H:b,Ya:g}),f.mode!==0&&B($d,{title:f.title,width:f.width,nc:a})]}
var Od=new ab,be=new bb,Pd=!1,ce=0,de=0,ee=()=>{X.cb(!0)},fe=a=>{a.timeStamp-ce>999&&X.cb(!1)};
function ge(){[W,X]=fa(ac);y(()=>{Vb(!0);var b=!1;onbeforeunload=onunload=onpagehide=onblur=()=>{if(!b){b=!0;for(let d of Od)Ec(d.world,d.j,!0);X.rb()}};onpageshow=onfocus=()=>{b=!1};onresize=()=>{Pd=!0;X.A({la:pa.innerHeight,aa:pa.innerWidth});Pd=!1};gb(()=>(X.rb(),!Ha&&M.getItem("minicraft.lock_requested")&&(Pa("minicraft.lock_requested"),O("minicraft.lock",Ia.now()))),200);ib("touchend",d=>{ce=d.timeStamp},!0);var c=d=>{var e=d.type==="keydown";if(e&&d.target.tagName==="INPUT")return!0;Pd=!0;X.cb(!1);
if(W.K.length>0){let f=be.get(W.K[W.K.length-1].id);d.key!=="f"?f.cc({code:d.keyCode,state:e}):e&&f.Pb()}return Pd=!1};cb.assign(qa.body,{style:"background:green",onkeydown:c,onkeyup:c,oncontextmenu:xb,ondragstart:xb})});var a=W.config.Da;y(()=>{a?(ib("mousedown",fe,!0),ib("mouseup",fe,!0),jb("touchstart",ee,!0)):(jb("mousedown",fe,!0),jb("mouseup",fe,!0),ib("touchstart",ee,!0))},[a]);y(Rc,[W.config.V]);y(()=>{hb(de);W.ja||(de=fb($b))},[W.ja,W.Za]);return[na(ae,W.K,{state:W}),W.cursor&&C("div[className=cursormask]",
{S:{cursor:W.cursor}})]}function he(){close();return[C("h1[innerText=\u00a1minicraft ya se est\u00e1 ejecutando!]")]}if(Ha){let a=new Ha("minicraft.lock"),b=fb(()=>Lb.then(()=>ma(ge)),100);a.addEventListener("message",c=>{c.data==="yes"?(hb(b),a.close(),ma(he)):(a.postMessage("yes"),focus())});a.postMessage("anyone there?")}else{O("minicraft.lock_requested","1");let a=Ia.now(),b=0,c=gb(()=>{U(M.getItem("minicraft.lock"))>a?(hb(c),ma(he)):++b>4&&(hb(c),Lb.then(()=>ma(ge)))},250)};

//# sourceMappingURL=app-es.js.map
