function m(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})}
var t=lui,aa=t.defer,ca=t.defer_end,da=t.hook_async,x=t.hook_dom,y=t.hook_effect,A=t.hook_memo,ea=t.hook_model,fa=t.hook_prev,ha=t.hook_rerender,ia=t.hook_state,ja=t.hook_static,ka=t.init,B=t.node,C=t.node_dom,qa=t.node_map,ra=t.now,D=window,sa=document,ta=navigator,F=Math,ua=F.abs,va=F.PI,xa=va*.5,ya=180/va,za=va/360,Aa=F.random,H=F.floor,Ba=F.ceil,Ca=F.round,I=F.min,J=F.max,Ea=F.cos,Fa=F.sin,Ga=F.sqrt,Ha=F.tan,Ia=F.log2,Ja=String.fromCharCode,Ka=D.visualViewport||null,La=D.BroadcastChannel,Qa=Date,
Ra=JSON,K=Promise,Sa=Ra.stringify,Ta=Ra.parse,L=localStorage,O=L.setItem.bind(L),Ua=L.removeItem.bind(L),Va=D.indexedDB||null,P=fetch,Wa=Array,Xa=Uint8Array,eb=Uint32Array,fb=Set,gb=Map,U=Number,hb=Object,ib=hb.keys,jb=hb.entries,kb=setTimeout,lb=setInterval,mb=clearTimeout,nb=addEventListener,ob=removeEventListener,pb=alert,qb=confirm,rb=prompt,sb=ta.userAgent.includes("WebKit"),yb={method:"POST",headers:{"Content-Type":"application/json"}},zb={behavior:"smooth",block:"center",container:"nearest"},
Ab=(a,b)=>(a=H(a).toString(),a.length<2?b+a:a),Bb=a=>a*a,Cb=()=>!1,Db=(a,b)=>{if(a<2)return"...";var c=new Qa;a=new Qa(a);var d=c-a;if(d<59E3)return Ca(d/1E3)+"s";if(d<3E6)return Ca(d/6E4)+"m";d=a.getFullYear();var e=a.getMonth(),f=a.getDate(),g="";d<c.getFullYear()&&(g=d+"/");if(g||e<c.getMonth())g+=e+1+"/";if(g||f<c.getDate())g+=f;if(b)return g||"today";g&&(g+="/");return g+a.getHours()+":"+Ab(a.getMinutes(),"0")},Eb=a=>{if(!a.ok)throw Error(a.status===403?"Missing permission. Logged in?":"Connection error.");
return a.json()},Fb="air stone grass dirt cobble planks bedrock log leaves bricks wool sand gravel glass bookshelf obsidian stone_bricks sandstone lapis_block iron_block gold_block diamond_block emerald_block redstone_block quartz_block mirror_block".split(" "),Gb=[0,8487297,4305266,4349313,8092539,5342114,7039851,3561583,4172910,6384533,15526888,10671324,8092798,16447200,4151672,1970708,8092539,9686227,9126695,15198183,5567485,14541182,7920469,662956,14936813,0],Hb=null,Ib=null,ac=null,bc=Va?new K(a=>
{var b,c;(b=ta.storage)==null||(c=b.persist)==null||c.call(b);b=Va.open("minicraft",1);b.onupgradeneeded=d=>{d=d.target.result.createObjectStore("chunks",{keyPath:["world","coords"]});for(let e of ib(L))if(e.startsWith("minicraft.world.")){let [f,g]=e.slice(16).split(":",2);g!=="meta"&&(d.add({world:U(f),coords:g,data:L.getItem(e)}),Ua(e))}};b.onsuccess=d=>{Hb=d.target.result;a()}}):K.resolve(void 0),cc=Va?(a,b)=>new K(c=>{Ib||(Ib=Hb.transaction("chunks","readonly").objectStore("chunks"),K.resolve(void 0).then(()=>
{Ib=null}));var d=Ib.get([a,b]);d.onsuccess=()=>{var e;return c((e=d.result)==null?void 0:e.data)}}):(a,b)=>{a=L.getItem(`minicraft.world.${a}:${b}`);return K.resolve(a)},dc=Va?(a,b,c)=>new K((d,e)=>{ac||(ac=Hb.transaction("chunks","readwrite").objectStore("chunks"),K.resolve(void 0).then(()=>{ac=null}));var f=ac.put({world:a,coords:b,data:c});f.onsuccess=()=>d();f.onerror=()=>e(f.error)}):(a,b,c)=>(O(`minicraft.world.${a}:${b}`,c),K.resolve(void 0)),ec=Va?(a,b)=>new K((c,d)=>{ac||(ac=Hb.transaction("chunks",
"readwrite").objectStore("chunks"),K.resolve(void 0).then(()=>{ac=null}));var e=ac.delete([a,b]);e.onsuccess=()=>c();e.onerror=()=>d(e.error)}):(a,b)=>(Ua(`minicraft.world.${a}:${b}`),K.resolve(void 0)),fc=Va?a=>new K(b=>{var c=L.getItem(`minicraft.world.${a}:meta`);if(!c)return b({});var d=Hb.transaction("chunks","readonly").objectStore("chunks").openCursor(),e={meta:c};d.onsuccess=()=>{var f=d.result;f?(f.value.world===a&&(e[f.value.coords]=f.value.data),f.continue()):b(e)}}):a=>{a=`minicraft.world.${a}:`;
var b=a.length,c={};for(let d of ib(L))d.startsWith(a)&&(c[d.slice(b)]=L.getItem(d));return K.resolve(c)},hc=Va?(a,b)=>new K((c,d)=>{var e=Hb.transaction("chunks","readwrite"),f=e.objectStore("chunks");for(let [g,l]of jb(b))g!=="meta"?f.put({world:a,coords:g,data:l}):O(`minicraft.world.${a}:meta`,l);e.oncomplete=()=>c();e.onerror=()=>d(e.error)}):(a,b)=>m(function*(){for(let [c,d]of jb(b))O(`minicraft.world.${a}:${c}`,d);O("__margin",Wa(257).join("x"));Ua("__margin")}()),ic=Va?a=>{var b=Hb.transaction("chunks",
"readwrite").objectStore("chunks").openCursor();b.onsuccess=()=>{var c=b.result;c&&(c.value.world===a&&c.delete(),c.continue())};Ua(`minicraft.world.${a}:meta`)}:a=>{a=`minicraft.world.${a}:`;for(let b of ib(L))b.startsWith(a)&&Ua(b)},jc=Va?(a,b)=>new K(c=>{var d=Hb.transaction("chunks","readwrite").objectStore("chunks"),e=d.openCursor();e.onsuccess=()=>{var f=e.result;f?(f.value.world===a&&(f.delete(),f.value.world=b,d.put(f.value)),f.continue()):c()};O(`minicraft.world.${b}:meta`,L.getItem(`minicraft.world.${a}:meta`));
Ua(`minicraft.world.${a}:meta`)}):(a,b)=>{a=`minicraft.world.${a}:`;var c=a.length;for(let d of ib(L))if(d.startsWith(a)){let e=L.getItem(d);Ua(d);O(`minicraft.world.${b}:${d.slice(c)}`,e)}return K.resolve(void 0)},kc=null,lc=0,mc=null,oc=()=>{V.La||V.na!==null||(mb(lc),W.A({Cb:!0,La:!0}),nc(!1))},nc=a=>{m(function*(){lc=kb(W.A,5E3,{Cb:!1});try{let b=yield P(`/api/minicraft/world?what=${a?"initia":"meta_al"}l`),c=yield Eb(b);a?c.version_latest!=="0.14.0"?location.reload(!0):(kc=c.worlds,W.A(Object.assign({},
{account:c.account,La:!1},pc(V.config)))):(kc=c,W.A(Object.assign({},{La:!1},pc(V.config))))}catch(b){W.A({ka:"Error while loading world list: "+b.message,La:!1})}}())},qc=(a,b)=>J(b.local,b.remote)-J(a.local,a.remote),pc=a=>{var b=kc?kc.map(c=>({account_name:c.account_name,hash:c.hash,id:c.id,label:c.label,local:0,locked:c.locked,public:c.public,remote:c.modified,writable:c.writable})):[];for(let c of a.worlds){let d=b.find(e=>e.id===c.id);if(d){let e=d.local=c.mod_l,f=d.remote,g=c.mod_r;e>g&&f>
g&&(qb('Conflict! The world "'+c.label+'" was modified here and somewhere else.\nOK: Take variant from server ('+Db(f,!1)+") | Cancel: Keep local variant ("+Db(e,!1)+")")?a=Object.assign({},a,{worlds:a.worlds.map(l=>l.id===c.id?Object.assign({},l,{mod_l:d.local=g}):l)}):d.remote=g)}else c.mod_r>1&&kc&&(pb('The world "'+c.label+'" was not found on the server, so it is a local world now.'),a=Object.assign({},a,{worlds:a.worlds.map(e=>e.id===c.id?Object.assign({},e,{mod_r:0}):e)})),b.push({account_name:"",
hash:0,id:c.id,label:c.label,local:c.mod_l,locked:!1,public:!1,remote:c.mod_r===1?1:0,writable:!0})}return{config:a,$a:b.sort(qc)}},sc=()=>m(function*(){if(V.na===null){var a;try{for(;a=V.$a.find(b=>b.local>0&&b.remote>0&&b.local!==b.remote);)yield rc(a);W.A({na:null})}catch(b){W.A({ka:b.message,na:null})}}}()),rc=a=>m(function*(){var b=a.id;W.A({na:b});if(a.local<a.remote)try{yield hc(b,yield Eb(yield P(`/static/minicraft/worlds/${a.hash}.json`))),W.ma(b,{mod_l:a.remote,mod_r:a.remote})}catch(c){if(c.name===
"QuotaExceededError")pb("Insufficient storage!"),ic(b),W.$b(b);else throw Error("Error while downloading world: "+c.message);}else if(!a.writable||a.locked)W.ma(b,{mod_l:a.remote});else{let c=b,d=null;try{let e=fc(b);if(a.remote===1){let g=yield Eb(yield P("/api/minicraft/world",Object.assign({},yb,{body:Sa({what:"meta",label:a.label})})));d=jc(b,c=g.id);mc=[b,c];W.ma(b,{id:c})}let f=yield Eb(yield P("/api/minicraft/world",Object.assign({},yb,{body:Sa({what:"data",world:c,data:yield e})})));a.remote===
1?kc.push(f):Object.assign(kc.find(g=>g.id===b),f);W.ma(c,{mod_l:f.modified,mod_r:f.modified})}catch(e){throw W.ma(b,{mod_r:0}),Error("Error while uploading world: "+e.message);}yield d}}()),Y=Ta(L.getItem("minicraft.config")||null);if(Y&&Y.worlds&&Y.version.startsWith("0.9.")){let a=new fb(Y.worlds.map(b=>"minicraft.world."+b.id));for(let b of ib(L))b.startsWith("minicraft.world.")&&!a.has(b.split(":",1)[0])&&Ua(b)}
var tc={init:()=>{var a=!1,b={Ca:!1,Da:!1,Ea:!1,ua:1,Fa:3,$:4,V:1,Ja:120,ia:64,Ka:0,worlds:[]};if(Y){let c=Y.pixel_grouping;c!=null&&(b.ua=c);(c=Y.flag_blocks_dimming)!=null&&(b.Ca=c);(c=Y.flag_glass_clear)!=null&&(b.Da=c);(c=Y.mouse_sensitivity)!=null&&(b.Fa=c);b.$=Y.resolution_scaling;(c=Y.textures)!=null?b.V=c:b.V=Y.flag_textures?1:0;b.Ja=Y.view_angle;b.ia=Y.view_distance;(c=Y.world_last)!=null&&(b.Ka=c);(c=Y.worlds)?b.worlds=c:L.getItem("minicraft.world.0:meta")&&(b.worlds[0]={id:0,label:(rb("There was an unnamed world found. How should it be called?",
"")||"Unknown world").substring(0,16),mod_l:Qa.now(),mod_r:0},a=!0);Y=null}b=Object.assign({},{account:{label:"",rank:0},config:b,ub:b,ka:null,cursor:null,ga:D.innerHeight,Y:D.innerWidth,ha:b.V,K:[{id:0,Tb:0,type:1}],Cb:!0,La:!0,na:null,ab:[]},pc(b));return a?(b.ub=null,tc.tb(b)):b},tb:a=>{var b=a.config;if(b===a.ub)return a;O("minicraft.config",Sa({version:"0.14.0",flag_blocks_dimming:b.Ca,flag_glass_clear:b.Da,pixel_grouping:b.ua,mouse_sensitivity:b.Fa,resolution_scaling:b.$,textures:b.V,view_angle:b.Ja,
view_distance:b.ia,world_last:b.Ka,worlds:b.worlds}));return Object.assign({},a,{ub:b})},uc:(a,b)=>tc.J(a,b(a.config)),J:(a,b)=>Object.assign({},a,{config:Object.assign({},a.config,b)}),eb:(a,b)=>a.config.Ea===b?a:tc.J(a,{Ea:b}),hc:(a,b,c)=>b===a.Y&&c===a.ga?a:Object.assign({},a,{Y:b,ga:c}),A:(a,b)=>Object.assign({},a,b),nc:(a,b)=>(sa.activeElement.blur(),Object.assign({},a,{K:[...a.K,Object.assign({},{id:J(-1,...a.K.map(c=>c.id))+1,Tb:1,type:0},b)]})),rc:(a,b)=>Object.assign({},a,{K:a.K.filter(c=>
c.id!==b)}),oc:(a,b)=>a.K[a.K.length-1].id===b?a:Object.assign({},a,{K:[...a.K.filter(c=>c.id!==b),a.K.find(c=>c.id===b)]}),Zb:(a,b)=>Object.assign({},a,pc(Object.assign({},a.config,{worlds:[...a.config.worlds,b]}))),$b:(a,b)=>Object.assign({},a,pc(Object.assign({},a.config,{worlds:a.config.worlds.filter(c=>c.id!==b)}))),ma:(a,b,c)=>Object.assign({},a,pc(Object.assign({},a.config,{worlds:a.config.worlds.map(d=>d.id===b?Object.assign({},d,c):d)})))},V,W,uc=(a,b=1,c=null)=>({amount:b,data:c,id:a}),
vc=(a,b,c=a.content.amount)=>{if(b.content)a.content.id===b.content.id?(c=I(c,b.ca-b.content.amount),a.content.amount-=c,b.content.amount+=c,a.content.amount<=0&&(a.content=null)):!(a.content.amount<=c&&a.content.amount<=b.ca&&b.content.amount<=a.ca)||a.filter&&!a.filter(b.content.id)||b.filter&&!b.filter(a.content.id)||([b.content,a.content]=[a.content,b.content]);else if(!b.filter||b.filter(a.content.id))a.content.amount<=c&&a.content.amount<=b.ca?[b.content,a.content]=[a.content,b.content]:(c=
I(c,b.ca),a.content.amount-=c,b.content=uc(a.content.id,c),a.content.amount<=0&&(a.content=null))},wc=(a,b)=>{for(let c of a)if(c.content&&c.content.id===b.id){let d=I(b.amount,c.ca-c.content.amount);c.content.amount+=d;if((b.amount-=d)<=0)return null}for(let c of a)if(!c.content&&(!c.filter||c.filter(b.id)))if(a=I(b.amount,c.ca),a<=b.amount){if(c.content=uc(b.id,a),(b.amount-=a)<=0)return null}else return c.content=b,null;return b},xc=(a,b)=>({ob:0,Eb:0,pb:0,Z:0,Aa:0,Ma:0,pa:0,ba:-1,qa:0,Na:null,
Oa:null,u:1,Rb:20,M:Wa(36).fill(null).map(()=>({content:null,filter:null,ca:64})),hb:0,name:b.label||"Player",N:a.Wa,O:a.Xa,P:a.Ya,Wb:0,Xb:0,T:0,Ha:0,va:0,wa:0,xa:0}),zc=(a,b)=>{b=I(5,b*.01);a.va-=a.va*.1*b;a.wa-=a.wa*.1*b;a.xa-=a.xa*.1*b;a.va+=(Ea(a.Z)*a.ob+Fa(a.Z)*a.pb)*b;a.wa+=a.Eb*b;a.xa+=(-Fa(a.Z)*a.ob+Ea(a.Z)*a.pb)*b;yc(a,a.Wb*b*1.5,a.Xb*b*1.5);a.N+=a.va*b;a.O+=a.wa*b;a.P+=a.xa*b},yc=(a,b,c)=>{a.Z=(a.Z+b+va*100)%(va*2);a.Aa=J(-xa,I(xa,a.Aa+c))},Ac=a=>{a+=32;a>33&&a<39?a++:a>38&&a<44?a+=2:a>
43&&a<127?a+=3:a>126&&a<55258?a+=37:a>55295&&(a+=8485);return Ja(a)},Bc=a=>a-(a>63743?8517:a>159?69:a>46&&a<130?35:a>40&&a<46?34:a>34&&a<40?33:32),Dc=()=>{var a=Cc,b=a.length,c=new gb,d=u=>{k=k<<1|u&1;++n===15&&(q+=Ac(k),k=n=0)},e=()=>{for(let u=0;u<r;++u)d(0)},f=u=>{d(u);d(u>>1);d(u>>2);d(u>>3);d(u>>4);d(u>>5);d(u>>6);d(u>>7)},g=()=>{--p===0&&(p=1<<r++)},l=()=>{if(v)v=!1;else{let u=w.id;for(let G=0;G<r;G++)d(u>>G)}},h=a[0],q="",k=0,n=2,r=2,p=2,z=2,w={id:z++,cb:new gb},v=!0;f(h);c.set(h,w);for(let u=
1;u<b;++u){let G=w.cb.get(h=a[u]);G?w=G:(l(),c.has(h)||(g(),e(),f(h),c.set(h,{id:z++,cb:new gb}),v=!0),w.cb.set(h,{id:z++,cb:new gb}),w=c.get(h),g())}l();c.has(h)||(g(),e(),f(h));g();d(1);--r;e();return q+=Ac(k<<15-n)},Ec=a=>{var b=Cc;if(!a)return!1;var c=a.length,d=()=>{n+=(z>>--w&1)<<r++;w===0&&(w=15,z=Bc(a.charCodeAt(p++)))},e=[0,1],f=1,g=3,l=2,h=null,q=null,k=0,n=0;q=2;for(var r=0,p=0,z=Bc(a.charCodeAt(p++)),w=15;r<q;)d();if(n===1)return!1;for(n=r=0;r<8;)d();h=[n];e[2]=h;for(b[k++]=n;p<=c;){q=
l;for(n=r=0;r<q;)d();if(n===0){for(n=r=0;r<8;)d();e[g]=[n];n=g++;--f===0&&(f=1<<l++)}else if(n===1)return!0;q=n<e.length?e[n]:h.concat(h[0]);for(let v=0;v<q.length;v++)b[k++]=q[v];e[g++]=h.concat(q[0]);h=q;--f===0&&(f=1<<l++)}return!1},Fc=new gb,Gc=new eb(1024),Cc=new Xa(Gc.buffer),Hc=a=>{var b=V.$a.find(c=>c.id===a);b={ja:null,bb:null,da:null,Ba:null,Pa:0,bc:[],X:!1,o:!1,ra:!b.writable||b.locked,Lb:0,Mb:0,Nb:0,id:a,Sa:0,Ta:0,Yb:0,U:0,Wa:.5,Xa:8.5,Ya:.5,time:0,nb:0};Fc.set(a,b);W.A({ab:[...Fc.keys()]});
return b},Ic=(a,b,c,d)=>c<0||c>63?0:a.ja[(b<<a.U+4|d)<<6|c],Jc=(a,b,c,d)=>{var e=a.U,f=a.da[(b>>4<<e|d>>4)<<2|c>>4];f.sa||(a.ja[(b<<e+4|d)<<6|c]=0,f.o=f.ta=!0)},Kc=(a,b,c,d,e)=>{var f=a.U,g=a.da[(b>>4<<f|d>>4)<<2|c>>4];b=(b<<f+4|d)<<6|c;return g.sa||a.ja[b]!==0?!1:(a.ja[b]=e,g.o=g.ta=!0)},fd=(a,b,c)=>{m(function*(){a.da&&(yield dd(a,b,!0));var d=1<<(a.U=c),e=a.da=[];for(let f=0;f<d;++f)for(let g=0;g<d;++g)for(let l=0;l<4;++l)e.push({o:!1,sa:!1,ta:!1,x:f,y:l,z:g,oa:f+1,za:0});d<<=c+12+2;a.ja===null||
a.ja.length<d?a.bb=new eb((a.ja=new Xa(d)).buffer):a.bb.fill(0);ed(a,b,!0)}())},ed=(a,b,c)=>{var d=J(I(b.O,63),0)>>4,e=H(b.N)>>4,f=H(b.P)>>4;if(c||a.Mb!==d||a.Sa+a.Lb!==e||a.Ta+a.Nb!==f){c=a.da;b=1<<a.U;var g=b-1;let l=a.Lb=e&g;g=a.Nb=f&g;let h=b>>1,q=J(h-2,8),k=a.Ba=[];a.Pa=0;a.Mb=d;a.Sa=e-l;a.Ta=f-g;for(let n=0,r=c.length;n<r;++n){let {x:p,y:z,z:w}=c[n];e=ua(p-l);f=0;e>h&&(e=b-e,f=p<l?b:-b);if(e>q)continue;let v=ua(w-g),u=0;v>h&&(v=b-v,u=w<g?b:-b);v>q||k.push({Kb:e*e+v*v+Bb(z-d),sb:n,Sa:f,Ta:u})}k.sort((n,
r)=>n.Kb-r.Kb)}a.X||gd(a,!1)},dd=(a,b,c)=>m(function*(){if(!(!c&&a.X||a.ra)&&a.o){a.X=!0;a.o=!1;for(var d=Qa.now(),e=b.M.map(({content:f})=>f&&[f.id,f.amount,f.data]);e.length>0&&e[e.length-1]===null;)e.pop();O(`minicraft.world.${a.id}:meta`,Sa({p:{h:b.Rb,i:e,m:b.u,p:[b.N,b.O,b.P,b.Z,b.Aa]},s:[a.Wa,a.Xa,a.Ya],t:a.time,v:1}));e=null;for(let f of a.da)f.o&&(e=hd(a,f));yield e;W.ma(a.id,{mod_l:d});a.X=!1}}()),jd=(a,b)=>{var c=Ta(L.getItem(`minicraft.world.${a.id}:meta`));if(c){let d=c.p,e=c.s,f=c.t;
c.v!=null&&(d.i.forEach((g,l)=>{g&&(b.M[l].content=uc(g[0],g[1],g[2]))}),b.Rb=d.h,b.u=a.ra?2:d.m,b.N=d.p[0],b.O=d.p[1],b.P=d.p[2],b.Z=d.p[3],b.Aa=d.p[4],a.Wa=e[0],a.Xa=e[1],a.Ya=e[2],f!=null&&id(a,f))}},id=(a,b)=>{a.time=b%24E3;a.nb=(b+6E3)/24E3%1},kd=(a,b,c)=>`${a}/${b}`+(c>0?"/"+c:""),md=a=>m(function*(){a.X=!0;var b=a.da[a.Ba[0].sb];yield ec(a.id,kd(b.oa,b.za,b.y));b.oa++;a.Pa=0;return ld(a)}()),hd=(a,b)=>m(function*(){++a.Yb;var c=a.bb,d=a.U,e=b.y,f=(256<<d)-256;for(let g=0,l=-1,h=((b.x<<d+4|
b.z)<<6|e)<<2;g<16;++g){for(d=0;d<16;++d)Gc[++l]=c[h],Gc[++l]=c[++h],Gc[++l]=c[++h],Gc[++l]=c[++h],h+=13;h+=f}b.o=!1;yield dc(a.id,kd(b.oa,b.za,e),Dc());--a.Yb}()),ld=a=>m(function*(){a.X=!0;yield gd(a,!0);a.X=!1}()),gd=(a,b)=>m(function*(){for(var c=a.bb,d=a.da,e=a.Ba,f=a.bc,g=a.Sa,l=a.Ta,h=a.U,q=null,k=null,n=e.length;a.Pa<n;){var r=e[a.Pa++];let p=d[r.sb],z=p.y,w=g+r.Sa+p.x;r=l+r.Ta+p.z;if(w!==p.oa||r!==p.za){let v={Hb:p,data:"nope",oa:w,za:r};p.sa&&(q=f.findIndex(u=>u.Hb===p),f.splice(q,1));p.sa=
!0;f.push(v);p.o&&(k=hd(a,p));q=cc(a.id,kd(p.oa=w,p.za=r,z)).then(u=>{v.data=u});if(!b&&f.length>5)break}}b&&(yield q);for(d=0;f.length>0&&f[0].data!=="nope";){let {Hb:p,data:z,oa:w,za:v}=f.shift();if(p.sa&&p.oa===w&&p.za===v)if(p.sa=!1,e=(256<<h)-256,l=p.y,g=((p.x<<h+4|p.z)<<6|l)<<2,Ec(z)){p.ta=!0;for(let u=0,G=-1;u<16;++u){for(l=0;l<16;++l)c[g]=Gc[++G],c[++g]=Gc[++G],c[++g]=Gc[++G],c[++g]=Gc[++G],g+=13;g+=e}}else if(l===0)for(p.ta=!0,l=0;l<16;++l){for(n=0;n<16;++n)c[g]=50397446,c[++g]=131843,c[++g]=
0,c[++g]=0,g+=13;g+=e}else if(p.ta)for(p.ta=!1,l=0;l<16;++l){for(n=0;n<16;++n)c[g]=0,c[++g]=0,c[++g]=0,c[++g]=0,g+=13;g+=e}if(!b&&++d>5)break}b&&(yield k)}()),nd=null,od=0,pd=new fb,qd=a=>{if(a){let b=new Image;b.onload=()=>{if(V.ha===a){var c=sa.createElement("canvas");c.width=16;c.height=416;c=c.getContext("2d");c.scale(1,-1);for(let d=0;d<26;++d)c.drawImage(b,0,d<<4,16,16,0,-(d<<4)-16,16,16);nd=new eb(c.getImageData(0,0,16,416).data.buffer);for(let d of pd)d.o=!0;od=a;W.A({ha:0})}};b.onerror=()=>
{V.ha===a&&(alert("Error while loading surface!"),aa(),W.J({V:od}),W.A({ha:0}),ca())};b.src=`/static/minicraft/textures/${a}.png`}else nd=null},sd=(a,b)=>{var c={ac:b,rb:b.getContext("2d",{alpha:!1,desynchronized:!0}),Fb:null,Gb:null,wb:"",o:!1,Ob:0,xb:0,cc:lb(()=>(c.Ob=c.xb,c.xb=0),1E3),L:a};pd.add(c);rd(c);return c},td=(a,b)=>{++a.xb;var c=a.rb,d=a.Fb,e=a.Gb,f=a.L,g=f.config,l=f.Ra,h=f.j,q=f.Ua,k=f.Va,n=f.world,r=0;if(!f.G||a.o){a.o=!1;let p=g.Ca,z=g.Da,w=g.ua,v=g.ia,u=h.Z,G=h.Aa,Sd=h.pa,Td=h.qa,
tb=h.u,ub=h.N,Ma=h.O,vb=h.P,Ud=l?h.ba:-1,Vd=n.ja,Wd=n.U,Xd=n.nb,Yd=nd!==null,Lc=1/q,Mc=1/k,la=q>>1,wa=k>>1,Nc=I(q,k),Oc=Nc>32,Pc=Ea(u),Qc=Fa(u),Rc=Ea(-G),Sc=Fa(-G),wb=2*Ha(g.Ja*za),Zd=Lc*(q<k?wb*q*Mc:wb),$d=Mc*(k<q?wb*k*Lc:wb),Jb=H(ub),Kb=H(Ma),Lb=H(vb),Tc=4+Wd,Na=(1<<Tc)-1,Q=w<q?w:1,ae=q-Q,xb=1-.9*J(0,Ea(Xd*za*720)),be=Ca(255*xb)<<16|Ca(177*xb)<<8|Ca(132*xb),Uc=h.u===1?6:4,Ya=h.pa=h.qa=h.Ma=0;h.ba=-1;r=Ma<0||Ma>=64?0:Ic(n,Jb&Na,Kb&63,Lb&Na);if(tb!==2&&r>0)h.pa=Jb&Na,h.ba=Kb&63,h.qa=Lb&Na,h.Ma=6,
e.fill(Gb[r]|4278190080);else{for(let R=0;R<k;++R){let Vc=(wa-R)*$d,Mb=Vc*Rc-Sc,Wc=Vc*Sc+Rc,ce=Wc*Qc,de=Wc*Pc,X,ma=0,Oa=!1,Xc=!1;a:for(let S=0;S<q;S+=Q)for(let ba=Xc?1:0;ba<Q;++ba){if(Q<2)X=S;else if(S===0)X=ba===0?0:ba===1?Q:ba-1,Oa=ba===1;else if(S<ae)X=(Oa=ba===1)?S+Q:S+ba-1;else{if((X=ba===0?S-1:S+ba)>=q)break a;Oa=!1}let Yc=(X-la)*Zd,Nb=ce+Yc*Pc,Ob=de-Yc*Qc,na=be,Pa=1,Pb=0;tb===2&&r>0&&(Pb=Aa()*Aa()*10);let Qb=1/Ga(Nb*Nb+Mb*Mb+Ob*Ob),oa=Nb*Qb,T=Mb*Qb,pa=Ob*Qb,Za=oa>0?1:oa<0?-1:0,$a=T>0?1:T<0?
-1:0,ab=pa>0?1:pa<0?-1:0,Rb=Za===0?1/0:Za/oa,Sb=$a===0?1/0:$a/T,Tb=ab===0?1/0:ab/pa,bb=Jb,Da=Kb,cb=Lb,Zc=oa<0?(ub-bb)*Rb:(bb-ub+1)*Rb,Ub=T<0?(Ma-Da)*Sb:(Da-Ma+1)*Sb,Vb=pa<0?(vb-cb)*Tb:(cb-vb+1)*Tb,$c=ub,ad=Ma,bd=vb;for(;;){let E=0,db=oa,N=Zc;Ub<N&&(E=1,db=T,N=Ub);Vb<N&&(E=2,db=pa,N=Vb);if(N>=v)break;E===0?(bb+=Za,Zc+=Rb):E===1?(Da+=$a,Ub+=Sb):(cb+=ab,Vb+=Tb);if(Da<0){if(T>0)continue;break}if(Da>=64){if(T<0)continue;break}let Wb=bb&Na,Xb=Da&63,Yb=cb&Na,M=Vd[(Wb<<Tc|Yb)<<6|Xb];if(tb===2&&N<Pb)M===0&&
(Pb=0);else if(M!==0)if(tb!==2&&R===wa&&X===la&&N<=Uc&&(h.pa=Wb,h.ba=Xb,h.qa=Yb,h.Ma=db<0|E<<1,Uc=N),z&&M===13||M===25)Pa*=.9,M===13&&(X^R)&1||(E===0?($c+=2*oa*N,oa=-oa,bb+=Za=-Za):E===1?(ad+=2*T*N,T=-T,Da+=$a=-$a):(bd+=2*pa*N,pa=-pa,cb+=ab=-ab));else{if(Yd){--M;E===1?M===6?M=25:M===13?M=4:M===1&&T>0&&(M=2):M===1&&(M=24);let Zb=$c+oa*N,$b=bd+pa*N,cd=nd[M<<8|(H((E===1?$b:ad+T*N)*16)&15)<<4|H((E===1?Zb:db>0?Zb-$b:$b-Zb)*16)&15];if(cd>>>24===0)continue;na=cd&16777215}else na=Gb[M];Pa*=(E===0?.8:E===
2?.6:db>0?.4:1)+(Xb!==Ud||Wb!==Sd||Yb!==Td?0:.2);p&&(Pa*=xb);break}}na=4278190080|I((na>>16)*Pa,255)<<16|I((na>>8&255)*Pa,255)<<8|I((na&255)*Pa,255);if(Xc=(Oa=Oa&&(R!==wa||X<la||X>la+Q))&&ma===na){if(Q>6){e.fill(ma,Ya+S+1,Ya+S+Q+1);break}let E=Ya+S+1;e[E]=ma;e[++E]=ma;if(Q<3)break;e[++E]=ma;if(Q<4)break;e[++E]=ma;if(Q<5)break;e[++E]=ma;if(Q<6)break;e[++E]=ma;break}if(Oa||X===0)ma=na;e[Ya+X]=na}Ya+=q}l&&!Oc&&(e[q*wa+la]^=16777215)}c.putImageData(d,0,0);if(l&&Oc){let R=I(Ba(Nc*.05),8);c.fillRect(la-
R,wa-1,R<<1,2);c.fillRect(la-1,wa-R,2,R-1);c.fillRect(la-1,wa+1,2,R-1)}}ed(n,h,!1);if(f.gb){let p=H(h.O)>>4,z=p>=0&&p<4&&n.Ba&&n.da[n.Ba[0].sb],w=[];z&&(z.o&&w.push("modified"),z.sa&&w.push("loading"),z.ta||w.push("empty"));a.wb=`minicraft 0.14.0 ${Ab(a.Ob,"\u00a0")} fps, T: ${Ab(n.nb*24,"0")}:${Ab(n.nb*24%1*60,"0")}; ${f.G&&b%1E3<500?"":n.time}${n.X?" busy":""}
R: ${q}x${k} (x${g.$}), D: ${g.ia}, C: ${n.Pa}/${n.Ba.length}, M: ${Bb(1<<4+n.U)*64>>10}k
E: 0/0, M: ${h.u}, I: ${r}

Position: ${h.N.toFixed(2)} ${h.O.toFixed(2)} ${h.P.toFixed(2)}
Angle: ${(h.Z*ya).toFixed(2)} ${(h.Aa*ya).toFixed(2)}
Focus: ${h.ba<0?"":"("+h.pa+" "+h.ba+" "+h.qa+") "+"WEBTSNI"[h.Ma]+": "+Fb[Ic(n,h.pa,h.ba,h.qa)]}
Chunk abs: (${H(h.N)>>4} ${H(h.P)>>4} ${p}) ${z?"rel: ("+z.x+" "+z.z+" "+z.y+") "+w.join(" "):"void"}`}else a.wb=""},rd=a=>{var b=a.ac,c=a.L;a.Gb=new eb((a.Fb=a.rb.createImageData(b.width=c.Ua,b.height=c.Va)).data.buffer);var d=c.Ua*c.config.$/c.Ga,e=c.Va*c.config.$/c.Ga;b.style.width=d+"px";b.style.height=e+"px";b.style.left=Ca((c.jb-d)/2)+"px";b.style.top=Ca((c.kb-e)/2)+"px";a.rb.fillStyle="rgba(255,255,255,.5)"},ud=0,xd=(a,b,{config:c,account:d})=>{var e=Hc(c.Ka);d=xc(e,d);jd(e,d);var f={config:c,
Ib:0,Jb:0,gb:!1,Ra:!0,G:!0,Pb:a,la:0,fa:new fb,yb:"",l:0,messages:[],j:d,zb:null,B:null,Ga:1,jb:1,kb:1,Ua:0,Va:0,lb:0,Vb:0,mb:0,lc:lb(()=>{var g;(g=f.G)||(e.o=!0,id(e,e.time+1),g=void 0);return g},50),Za:b,world:e};vd(f,null);wd(f);return f},wd=a=>{m(function*(){if(!a.config.Ea)try{yield a.Pb.requestPointerLock()}catch(b){}}())},yd=(a,b)=>a===b?0:.1-a*.2,zd=a=>{a.j.ob=yd((a=a.fa).has(-12)||a.has(65),a.has(-13)||a.has(68))},Ad=a=>{a.j.Eb=yd((a=a.fa).has(-15)||a.has(16),a.has(-14)||a.has(32))},Bd=a=>
{a.j.pb=yd((a=a.fa).has(-11)||a.has(83),a.has(-10)||a.has(87))},Cd=a=>{a.j.Wb=yd(a.fa.has(-18),a.fa.has(-19))},Dd=a=>{a.j.Xb=yd(a.fa.has(-17),a.fa.has(-16))},Fd=(a,b,c)=>{if(!a.world)return!1;var d=a.fa,e=a.j;if(c){if(d.has(b))return!1;d.add(b);var f=e.pa,g=e.ba;c=e.qa;switch(b){case -18:case -19:Cd(a);break;case -17:case -16:Dd(a);break;case -1:!a.world.ra&&e.u!==2&&g>=0&&(e.hb===0?e.u===0&&(b=Ic(a.world,f,g,c),b===2?b=3:b===1&&(b=4),b===15||b===6||b!==8&&b!==13&&wc(e.M,uc(b,1))!==null)||(Jc(a.world,
f,g,c),e.ba=-1):Ed(a,[f,g,c],!1));break;case -2:case 71:if(g>=0){let l=Ic(a.world,f,g,c);c=e.M.slice(0,9);g=c.findIndex(h=>h.content!==null&&h.content.id===l);g>=0?e.T=g:e.u===1&&(c[e.T].content&&(c=c.findIndex(h=>h.content===null),c>=0&&(e.T=c)),e.M[e.T].content=uc(l));e.Ha=a.la}break;case -3:if(!a.world.ra&&e.u!==2&&g>=0)if(e.hb===0){if(b=e.M[e.T],b.content){switch(e.Ma){case 0:--f;break;case 1:++f;break;case 2:--g;break;case 3:++g;break;case 4:--c;break;case 5:++c}g>=0&&g<64&&Kc(a.world,f&(1<<
4+a.world.U)-1,g,c&(1<<4+a.world.U)-1,b.content.id)&&e.u!==1&&--b.content.amount<=0&&(b.content=null)}}else Ed(a,[f,g,c],!0);break;case -4:e.T=(e.T+9-1)%9;e.Ha=a.la;break;case -5:e.T=(e.T+1)%9;e.Ha=a.la;break;case 27:a.l===0&&(a.G=!0,a.l=1);break;case -15:case -14:case 16:case 32:Ad(a);break;case 49:case 50:case 51:case 52:case 53:case 54:case 55:case 56:case 57:e.T=b-49;e.Ha=a.la;break;case -12:case -13:case 65:case 68:zd(a);break;case 69:if(a.l===0){a.l=3;for(let l of d)Fd(a,l,!1)}break;case 70:a.Za.Qb();
break;case 80:a.world&&(a.G=!0);break;case 81:e=e.M[e.T];if(d.has(17)||e.content&&--e.content.amount<=0)e.content=null;break;case -11:case -10:case 83:case 87:Bd(a);break;case 84:if(a.l===0){a.l=2;for(let l of d)Fd(a,l,!1)}break;case 112:a.Ra=!a.Ra;break;case 114:a.gb=!a.gb;case 116:case 122:case 123:break;default:return!1}}else{if(!d.delete(b))return!1;switch(b){case -15:case -14:case 16:case 32:Ad(a);break;case -12:case -13:case 65:case 68:zd(a);break;case -11:case -10:case 83:case 87:Bd(a);break;
case -18:case -19:Cd(a);break;case -17:case -16:Dd(a)}}a.yb=[...d].join();return!0},Gd=(a,b)=>(b=b.startsWith("~")?a+U(b.slice(1)):U(b),isNaN(b)?a:b),Id=(a,b)=>{var c=a.j,d=a.world;if(b)if(b.charAt(0)==="/"){b=b.slice(1).split(" ");let e=b.shift();switch(e){case "clear":a.messages=[];break;case "clearinv":for(let f of c.M)f.content=null;Z(a,"Inventory cleared.",!0);break;case "gamemode":case "gm":b=U(b[0]);!isNaN(b)&&b>=0&&b<3&&b%1===0?(c.u=b,Z(a,"Game mode set to: "+b,!0)):Z(a,"Game mode must be in 0..2!");
break;case "give":if(b.length===0){Z(a,"/give <id> [Amount]\n"+Fb.join(" "));break}d=Fb.indexOf((b[0]||"").toLowerCase());d=d>=0?d:U(b[0]);b=U(b[1]||1);!isNaN(d)&&d>0&&d<26&&d%1===0?!isNaN(b)&&b>0&&b%1===0?Z(a,wc(c.M,uc(d,b))?"Inventory is full!":`Gave items ${b} ${Fb[d]}`,!0):Z(a,"Amount must be at least 1!"):Z(a,"Invalid block type!");break;case "help":Z(a,"Commands: clear, clearinv, gamemode, give, help, load, me, save, spawn, teleport, time, version, view_distance");break;case "load":if(d.X){Z(a,
"No permission!");break}ld(d).then(()=>{a.B.o=!0;Z(a,"Chunks loaded.",!0)});break;case "me":Z(a,c.name+" "+b.join(" "),!0);break;case "save":if(a.world.ra||d.X){Z(a,"No permission!");break}dd(a.world,a.j,!1);Z(a,"Game saved.",!0);break;case "spawn":if(a.world.ra){Z(a,"No permission!");break}d.Wa=c.N;d.Xa=c.O;d.Ya=c.P;Z(a,"Spawn updated.",!0);break;case "teleport":case "tp":b.length===0?(c.N=d.Wa,c.O=d.Xa,c.P=d.Ya,a.B.o=!0,Z(a,"Teleported to spawn.",!0)):b.length===3?(Z(a,`Teleported to ${c.N=Gd(c.N,
b[0])} ${c.O=Gd(c.O,b[1])} ${c.P=Gd(c.P,b[2])}`,!0),a.B.o=!0):Z(a,"Pitch!");c.va=0;c.wa=0;c.xa=0;break;case "time":c=b[1];if(!c){Z(a,"Parameter missing!");break}if(c==="day")c=1E3;else if(c==="night")c=13E3;else if(isNaN(c=H(U(c))))break;switch(b[0]){case "add":c+=d.time;case "set":id(d,c);Z(a,"Time set to: "+d.time,!0);break;default:Z(a,"Unknown command: time "+b[0])}break;case "view_distance":case "vd":c=U(b[0]);if(isNaN(c)||c<0)break;W.J({ia:c});Z(a,"View distance: "+c,!0);break;case "version":Z(a,
"minicraft 0.14.0");break;case "_w":W.nc({type:b[0]==="m"?1:0});break;case "/exit":c.hb=0;Z(a,"Normal mouse mode.",!0);break;case "/expand":a.j.Na&&a.j.Oa?d=!0:(Z(a,"Selection required!"),d=!1);d&&(b[0]==="vert"?(c.Na[1]=0,c.Oa[1]=63,Z(a,"Expanded selection.",!0)):Z(a,'Only "vert" supported!'));break;case "/pos1":case "/pos2":Ed(a,[H(c.N),H(c.O),H(c.P)],e==="/pos2");break;case "/regen":if(a.world.ra||d.X){Z(a,"No permission!");break}md(d).then(()=>{a.B.o=!0;Z(a,"Chunk regenerated.",!0)});break;case "/show":Z(a,
`Primary: ${c.Na?c.Na.join(" "):"none"}, Secondary: ${c.Oa?c.Oa.join(" "):"none"}`);break;case "/wand":c.hb=1;Z(a,"Select using mouse buttons.",!0);break;default:Z(a,"Unknown command: "+e)}}else{let e=Z(a,`<${c.name}> `+b);vd(a,b).then(f=>{f&&Hd(a,e)})}},Z=(a,b,c=!1)=>{var d=++ud;(a.messages=a.messages.slice(-49)).push({id:d,Sb:c,time:ra(),value:b});return d},Hd=(a,b)=>{var c=a.messages.findIndex(d=>d.id===b);c>=0&&a.messages.splice(c,1)},Ed=(a,b,c)=>{c?a.j.Oa=b:a.j.Na=b;Z(a,`${c?"Secondary point":
"Primary point"}: ${b.join(" ")}`,!0)},vd=(a,b)=>(mb(a.zb),a.zb=kb(vd,5E3,a,null),(b?P("/api/chat",Object.assign({},yb,{body:Sa({msg:b})})):P("/api/chat")).then(c=>c.ok&&c.text()).then(c=>{if(c){c=c.split("\n").filter(Boolean);for(let d of c)d.startsWith("<")&&Z(a,d);return c.length>0}return!1}).catch(()=>!1)),Jd=({id:a,W:b})=>(x("div[className=bitmap]",{S:{backgroundImage:`url(/static/minicraft/textures/${b}.png)`,backgroundColor:a===25?"#84b1ff":"",backgroundPositionY:100-(a===25?13:a)*100+"%"}}),
null);function Kd({amount:a,u:b,id:c,W:d}){x("div[className=stack]",{title:Fb[c]+(b===1?` (${c})`:"")});return[B(Jd,{id:c,W:d}),a!==1&&C("div[className=amount]",{innerText:a})]}
function Ld({j:a,W:b,Ia:c,H:d}){x("table[className=bar]",{ontouchstart:ja(g=>{a.T=Number(g.target.closest("[data-slot]").dataset.slot);a.Ha=g.timeStamp}),S:{left:J(0,d/2-180)+"px",opacity:J(.5,I(1,1-(c-a.Ha-5E3)*5E-4))}});var e=A(g=>({height:g=g-8+"px",width:g}),[I(d/9,40)]),f=a.u;return[C("tr",null,a.M.slice(0,9).map(({content:g},l)=>C("td",{D:{slot:l},F:{active:l===a.T},S:e},[g&&B(Kd,{amount:g.amount,data:g.data,u:f,id:g.id,W:b}),!g&&C("div[className=stack]")])))]}
var Md=Wa(4).fill(null).map((a,b)=>Wa(9).fill(null).map((c,d)=>b*9+d));Md.push(Md.shift());function Nd({jc:a,W:b,kc:c}){x("table",{onclick:({target:e})=>{e.className==="bitmap"&&vc({content:uc(U(e.parentElement.parentElement.dataset.id)),filter:null,ca:64},a);return!1}});var d=0;return Wa(3).fill(null).map(()=>C("tr",null,Wa(9).fill(null).map(()=>++d<26&&C("td",{D:{id:d},S:c},[B(Kd,{amount:1,data:null,u:1,id:d,W:b})]))))}
var Od={fontSize:"",height:"32px",width:"32px"},Pd={fontSize:"75%",height:"16px",width:"16px"};
function Qd({L:a,W:b,ya:c,H:d}){var e=A(()=>({content:null,filter:null,ca:64})),f=a.j.u;x("div[className=menu]",A(()=>({onclick:({target:h})=>{if(h.className==="menu")e.content?e.content=null:(a.l=0,a.G=!1,wd(a));else if(h.parentElement.className==="stack"&&h.parentElement.parentElement.dataset.slot||h.tagName==="TD")h=a.j.M[U((h.tagName==="TD"?h:h.parentElement.parentElement).dataset.slot)],e.content?vc(e,h):h.content&&vc(h,e)},oncontextmenu:({target:h})=>{if(h.className==="menu")e.content?--e.content.amount<=
0&&(e.content=null):(a.l=0,a.G=!1,wd(a));else if(h.parentElement.className==="stack"&&h.parentElement.parentElement.dataset.slot||h.tagName==="TD")h=a.j.M[U((h.tagName==="TD"?h:h.parentElement.parentElement).dataset.slot)],e.content?vc(e,h,1):h.content&&vc(h,e,Ba(h.content.amount/2))}})));var g,l;[g,l]=A(()=>{var h=I(d,c)<400;return[{left:`${d/2-(h?96:168)}px`,top:`${c/2-(h?91:147)}px`},h?Pd:Od]},[c,d]);return[C("div[className=window]",{S:g},[C("h2[innerText=Inventory]"),f===1&&B(Nd,{jc:e,W:b,kc:l}),
C("table",null,Md.map((h,q)=>C(q<3?"tr":"tr[className=last]",null,h.map(k=>C("td",{D:A(()=>({slot:k})),S:l},[(k=a.j.M[k].content)&&B(Kd,{amount:k.amount,data:k.data,u:f,id:k.id,W:b})])))))]),e.content&&C("div[className=hand]",{S:{left:a.Ib+"px",top:a.Jb+"px"}},[B(Kd,{amount:e.content.amount,data:e.content.data,u:0,id:e.content.id,W:b})])]}
function Rd({I:{Sb:a,time:b,value:c},Ia:d}){b=I(1,1-(d-b-4500)*.001);x(a?"div[className=minor]":"div",{S:{opacity:b}});return[C("div[className=backdrop]"),C("span",{innerText:c})]}function ee({messages:a,Ia:b}){x("div[className=messages]");return[qa(Rd,a.slice(-10).filter(c=>c.time>b-5E3),{Ia:b})]}function fe({I:a,current:b,ha:c}){x("tr");return[C("td",null,[C("button",{disabled:a.id===b||c>0,innerText:`${a.label} (${a.owner})`,onclick:()=>{aa();W.J({V:a.id});W.A({ha:a.id});ca()}})])]}
function ge({L:a,state:{config:b,ha:c},aa:d}){a&&y(()=>{dd(a.world,a.j,!1)});var e,f;[e,f]=ia(!1);var g=da(()=>e?P("/static/minicraft/textures.json").then(Eb).catch(()=>null):K.resolve(null),[e],null);x("div[className=menu]");return[C("h1",{innerText:e?"Surfaces":"Settings"}),C("div[className=row]",null,[C("button",{innerText:a&&!e?"Back to game":"Back",onclick:()=>{e?f(!1):a?(a.l=0,a.G=!1,wd(a)):d(2)}})]),!e&&C("table[className=settings]",null,[C("tr",null,[C("td",null,[C("button[innerText=Surfaces...]",
{onclick:()=>{f(!0)}})]),C("td",null,[C("label[htmlFor=setting-resolution]",{innerText:`Resolution: 1:${b.$}\n`}),C("input[id=setting-resolution][type=range][min=1][max=20][step=1]",{value:21-b.$,onchange:l=>W.J({$:21-Number(l.target.value)})})])]),C("tr",null,[C("td",null,[C("label[htmlFor=setting-view-angle]",{innerText:`View angle: ${b.Ja}\n`}),C("input[id=setting-view-angle][type=range][min=1][max=180][step=1]",{value:b.Ja,onchange:l=>W.J({Ja:Number(l.target.value)})})]),C("td",null,[C("label[htmlFor=setting-view-distance]",
{innerText:`View distance: ${b.ia}\n`}),C("input[id=setting-view-distance][type=range][min=16][max=128][step=16]",{value:b.ia,onchange:l=>W.J({ia:Number(l.target.value)})})])]),C("tr",null,[C("td",null,[C("label[htmlFor=setting-pixel-grouping]",{innerText:`Pixel grouping: ${b.ua===1?"Disabled":b.ua}\n`}),C("input[id=setting-pixel-grouping][type=range][min=1][max=8][step=1]",{value:b.ua,onchange:l=>W.J({ua:Number(l.target.value)})})]),C("td",null,[C("label[htmlFor=setting-mouse-sensitivity]",{innerText:`Mouse sensitivity: ${b.Fa}\n`}),
C("input[id=setting-mouse-sensitivity][type=range][min=1][max=15][step=1]",{value:b.Fa,onchange:l=>W.J({Fa:Number(l.target.value)})})])]),C("tr",null,[C("td",null,[C("button",{innerText:`Dim blocks: ${b.Ca?"Enabled":"Disabled"}`,onclick:()=>{W.J({Ca:!b.Ca})}})]),C("td",null,[C("button",{innerText:`Clear glass: ${b.Da?"Enabled":"Disabled"}`,onclick:()=>{W.J({Da:!b.Da})}})])]),C("tr",null,[C("td",null,[C("button[innerText=Version 0.14.0][title=Project page]",{onclick:()=>{open("//github.com/L3P3/minicraft")}})])])]),
a&&!e&&C("div[className=row]",null,[C("button[innerText=Leave world]",{onclick:()=>{d(2)}})]),e&&C("table[className=settings]",null,[C("tr",null,[C("td",null,[C("button[innerText=Plain]",{disabled:b.V===0,onclick:()=>{aa();W.J({V:0});W.A({ha:0});ca()}})])]),g&&qa(fe,g,{current:b.V,ha:c})]),e&&g&&C("div[className=row]",null,[C("button[innerText=Add surface]",{onclick:()=>{open("//l3p3.de/svr/minicraft/textures.html")}})])]}
var he=({L:a,fc:b,H:c})=>[C("div[className=toolbar]",null,[C("button[innerText=\u274c]",{onclick:()=>{a.l=0;a.G=!1;wd(a)}})]),C("input[autocomplete=off][enterkeyhint=send][mozactionhint=send][name=message][required]",{onkeydown:d=>{var e=d.keyCode;d=d.target;e===13?(Id(a,d.value),d.value=""):e===27&&(a.l=0,a.G=!1,wd(a))},R:d=>{b.input=d;kb(()=>d.focus(),0)},S:{width:`${c-40}px`}})],ie=({I:{Sb:a,value:b}})=>(x(a?"div[className=minor]":"div",{innerText:b}),null);
function je({L:a,messages:b,H:c}){var d=ja({history:null,input:null});x("div[className=menu terminal]",{onclick:e=>{e.target!==d.input&&d.input.focus()}});y(e=>{e&&kb(()=>d.history.scrollTop=1E9,0)},[b.length&&b[b.length-1].id]);return[C("div[className=history]",{R:ja(e=>{d.history=e})},[qa(ie,b)]),B(he,{L:a,fc:d,H:c})]}var ke=[["pick",-2],["up",-14],["down",-15],["E",69],["T",84],["F1",112],["F3",114],["...",27]],le=[C("div")];
function me({L:a,H:b}){var c=a.fa;x("div[className=touch]",ja({ontouchstart:l=>{var h=l.target.dataset.code||l.target.parentElement.dataset.code;if(h!=null&&Fd(a,h=U(h),!0)){let q=l.changedTouches[0].identifier,k=n=>{n.changedTouches[0].identifier===q&&(ob("touchend",k),Fd(a,h,!1))};nb("touchend",k)}return!1}}));var d,e;[d,e]=A(l=>[{height:l-8+"px"},{width:l+="px",height:l}],[I(Ca(b/10),40)]);var f,g;[f,g]=A(()=>{var l=b>300?"14px":"0",h=b>300?"2px":"0",q=b>650?l:"40px";return[{borderSpacing:h,bottom:q,
left:l},{borderSpacing:h,bottom:q,right:l}]},[b]);return[C("div[className=top]",null,ke.map(([l,h])=>C(`div[innerText=${l}]`,{D:{code:h},F:{button:!0,active:c.has(h)}}))),C("table[className=move]",{S:f},[C("tr",null,[C("td"),C("td",{D:{code:-10},F:{"button up":!0,active:c.has(-10)},S:e},le)]),C("tr",null,[C("td",{D:{code:-12},F:{"button left":!0,active:c.has(-12)},S:e},le),C("td",null,[C("div",{D:{code:-1},F:{"button center":!0,active:c.has(-1)},S:d},le)]),C("td",{D:{code:-13},F:{"button right":!0,
active:c.has(-13)},S:e},le)]),C("tr",null,[C("td"),C("td",{D:{code:-11},F:{"button down":!0,active:c.has(-11)},S:e},le)])]),C("table[className=move]",{S:g},[C("tr",null,[C("td"),C("td",{D:{code:-16},F:{"button up":!0,active:c.has(-16)},S:e},le)]),C("tr",null,[C("td",{D:{code:-18},F:{"button left":!0,active:c.has(-18)},S:e},le),C("td",null,[C("div",{D:{code:-3},F:{"button center":!0,active:c.has(-3)},S:d},le)]),C("td",{D:{code:-19},F:{"button right":!0,active:c.has(-19)},S:e},le)]),C("tr",null,[C("td"),
C("td",{D:{code:-17},F:{"button down":!0,active:c.has(-17)},S:e},le)])])]}function ne({model:a}){var b=x("canvas");a.B=sd(a,b);return null}
function oe({frame:a,ea:b,state:c,aa:d,ya:e,H:f,Za:g}){var l=c.config,h=ra(),q=sa.pointerLockElement===a,k=A(()=>xd(a,g,c));y(()=>{pe.add(k);var r=v=>{if(k.l!==0)return!0;sa.pointerLockElement===a?Fd(k,-1-v.button,v.type==="mousedown"):wd(k);return!1},p=v=>{if(sa.pointerLockElement===a){var u=k.config.Fa*va/(J(k.jb,k.kb)*k.Ga);sb&&(k.Vb=v.timeStamp);yc(k.j,k.lb=v.movementX*u,k.mb=-v.movementY*u)}else u=k.Pb.getBoundingClientRect(),k.Ib=v.clientX-u.left,k.Jb=v.clientY-u.top},z=v=>{W.eb(!1);if(k.l===
0&&!k.G&&ua(v.deltaY)>5)return v=v.deltaY>0?-5:-4,Fd(k,v,!0),Fd(k,v,!1),!1},w={passive:!0};a.addEventListener("mousedown",r);a.addEventListener("mouseup",r);a.addEventListener("mousemove",p,w);a.addEventListener("wheel",z,w);return()=>{a.removeEventListener("mousedown",r);a.removeEventListener("mouseup",r);a.removeEventListener("mousemove",p,w);a.removeEventListener("wheel",z,w);mb(k.zb);mb(k.lc);dd(k.world,k.j,!0);Fc.delete(k.world.id);W.A({ab:[...Fc.keys()]});var v=k.B;pd.delete(v);mb(v.cc);return pe.delete(k)}});
y(()=>{k.config=l;k.B&&(k.B.o=!0);var r=k.world,p=Ba(Ia(k.config.ia/16*2+2));r.U!==p&&fd(r,k.j,p)},[l]);y((r,p,z)=>{k.Ga=z||1;k.jb=J(1,r);k.kb=J(1,p);p=k.config.$;r=Ba(k.jb*k.Ga/p);p=Ba(k.kb*k.Ga/p);if(r!==k.Ua||p!==k.Va)k.Ua=r,k.Va=p,k.B&&(k.B.o=!0,rd(k.B))},[a.offsetWidth,a.offsetHeight,D.devicePixelRatio,l.$]);y(()=>{b&&Fd(k,b.code,b.state)},[b]);y(r=>{r||k.G||k.l!==0||(k.l=1,sb&&k.lb|k.mb&&k.Vb>h-100&&(yc(k.j,-k.lb,-k.mb),k.lb=k.mb=0,k.B.o=!0));k.G=!r},[l.Ea&&k.l===0||q]);y(r=>q&&r&&sa.exitPointerLock(),
[k.G||k.l!==0]);h===k.la||qe||(k.world&&(k.la&&!k.G&&zc(k.j,h-k.la),k.B&&td(k.B,h)),k.la=h);ha();var n=ja({Bb:1});l.V&&(n.Bb=l.V);return[B(ne,{model:k}),k.Ra&&k.l!==2&&k.messages.length>0&&k.messages[k.messages.length-1].time>h-5E3&&B(ee,{messages:k.messages,Ia:h}),k.B&&k.gb&&C("div[className=diagnostics]",{innerText:k.B.wb}),l.Ea&&B(me,{L:k,yb:k.yb,H:f}),k.Ra&&k.l!==3&&k.j.u!==2&&B(Ld,{j:k.j,W:n.Bb,Ia:h,H:f}),(k.l===1||k.l===2||k.l===3)&&C("div[className=backdrop]"),k.l===3&&B(Qd,{L:k,W:n.Bb,Ia:h,
ya:e,H:f}),k.l===1&&B(ge,{L:k,state:c,aa:d}),k.l===2&&B(je,{L:k,messages:k.messages,H:f})]}
var re=({account:a,busy:b,qb:c,ec:d,aa:e,world:f,Db:g})=>(x("div"),[C("button[innerText=Enter]",{disabled:b||d||f.local<2||f.remote>f.local,onclick:()=>{aa();W.J({Ka:f.id});e(0);ca()},title:d?"The world is already opened!":f.local<2?"The world is not downloaded yet!":f.local<f.remote?"The world is still loading!":"Enter selected world"}),C("button",{disabled:b||!kc||d||f.local>0&&f.remote>0||!f.remote&&!a.rank,innerText:f.local?kc&&f&&!f.remote?"Upload":"Transfer":"Download",onclick:()=>{f.local?
f.remote||W.ma(f.id,{mod_r:1}):W.Zb({id:f.id,label:f.label,mod_l:1,mod_r:f.remote})},title:kc?f.local?f.remote?"The world is present on both sides!":d?"The world is already opened!":a.rank?"Upload world to server":"Not logged in!":"Download world from server":"List is loading!"}),C("button[innerText=Rename]",{disabled:b||d||!f.writable,onclick:()=>{var l=rb("World's new label:\n(max. 16 characters)",f.label);!l||l===f.label||l.length>16||(f.local&&W.ma(f.id,{label:l}),f.remote&&(c(!0),P("/api/minicraft/world",
Object.assign({},yb,{body:Sa({what:"meta",world:f.id,label:l})})).then(Eb).catch(h=>{pb("Error while editing world: "+h.message)}).then(()=>{c(!1)})))},title:f.writable?d?"The world is already opened!":"Change world name":"No permission!"}),C("button",{disabled:b||!f.remote||!f.writable,innerText:`Locked: ${f.locked?"Yes":"No"}`,onclick:()=>{c(!0);P("/api/minicraft/world",Object.assign({},yb,{body:Sa({what:"meta",world:f.id,locked:!f.locked})})).then(l=>(l=Eb(l),aa(),oc(),c(!1),ca(),l)).catch(l=>
{pb("Error while editing world: "+l.message);c(!1)})},title:f.remote?f.writable?f.locked?"Unlock world":"Lock world":"No permission!":"The world is not uploaded!"}),C("button",{disabled:b||!f.remote||!f.writable,innerText:`Public: ${f.public?"Yes":"No"}`,onclick:()=>{c(!0);P("/api/minicraft/world",Object.assign({},yb,{body:Sa({what:"meta",world:f.id,public:!f.public})})).then(l=>(l=Eb(l),aa(),oc(),c(!1),ca(),l)).catch(l=>{pb("Error while editing world: "+l.message);c(!1)})},title:f.remote?f.writable?
f.public?"Unpublish world":"Publish world":"No permission!":"The world is not uploaded!"}),C("button",{disabled:b||d||!f.local&&!f.writable,innerText:f.local?"Delete (local)":"Delete",onclick:()=>{qb('Really delete world "'+f.label+'"?')&&(f.local?(ic(f.id),W.$b(f.id)):(c(!0),P("/api/minicraft/world",{method:"DELETE",headers:{"Content-Type":"application/json"},body:Sa({what:"world",world:f.id})}).then(l=>(Eb(l),aa(),g(null),oc(),c(!1),ca())).catch(l=>{pb("Error while deleting world: "+l.message);
c(!1)})))},title:d?"The world is already opened!":f.local||f.writable?"Delete world":"No permission!"})]),se=a=>{a.scrollIntoView(zb)},te=(a,b)=>{a&&kb(se,0,b)};
function ue({I:a,account:b,busy:c,qb:d,aa:e,sc:f,Db:g,na:l,ab:h}){f=a===f;var q=x("tr",{F:{selected:f},onclick:()=>{g(a.id)}});y(te,[f,q]);return[C("td[style=width:0]",{innerText:`${a.local?"L":"_"}${a.local&&a.remote?a.local>a.remote?">":a.local<a.remote?"<":"=":"_"}${a.remote?a.public?"R":"r":"_"}`,S:{color:l===a.id?"yellow":a.local!==a.remote&&a.local&&a.remote?"red":""}}),C("td",{innerText:a.label,title:a.id},[f&&B(re,{account:b,busy:c,qb:d,ec:h.includes(a.id),aa:e,world:a,Db:g})]),C("td[style=width:0]",
null,[C("div[title=Modified]",{innerText:Db(J(a.local,a.remote),!0)}),f&&C("div",{innerText:a.account_name?a.account_name:"-",title:a.account_name?"Owner":"Just a local world"})])]}
function ve({state:{account:a,config:b,ka:c,Cb:d,La:e,na:f,$a:g,ab:l},view:h,aa:q,ya:k,H:n}){var r,p;[r,p]=ia(b.Ka);y(()=>{mc&&r===mc[0]&&p(mc[1])},[mc]);var z=A(()=>g.find(u=>u.id===r)||null,[r,g]),w,v;[w,v]=ia(!1);x("div",{F:{menu:!0,blurred:h===1}});return[C("button[innerText=Settings][style=position:absolute]",{onclick:()=>{q(1)}}),C("button[style=position:absolute;right:0]",{disabled:a.rank>0,innerText:a.rank?a.label:"Login",onclick:()=>{location.href="/account?redir=minicraft"}}),C("h1[innerText=Worlds]"),
C("div[className=row]",null,[C("button[innerText=Refresh][title=Reload list]",{disabled:d||e||c!==null,onclick:oc}),C("button[innerText=New world]",{onclick:()=>{var u=rb("New world's label:\n(max. 16 characters)","New world");u&&(u.length>16?pb("Name is too long!"):W.Zb({id:I(0,...b.worlds.map(G=>G.id))-1,label:u,mod_l:Qa.now(),mod_r:0}))}})]),C("div[className=worlds]",{S:{height:`${J(100,k-140)}px`,width:`${I(480,n-16)}px`}},[C("table[cellSpacing=0]",null,[qa(ue,g,{tc:Qa.now(),account:a,busy:w,
qb:v,aa:q,sc:z,Db:p,na:f,ab:l})])])]}
function we({ea:a,state:b,ya:c,H:d,Za:e}){var f,g;[f,g]=ia(2);y(()=>{e.mc(f===0?b.$a.find(h=>h.id===b.config.Ka).label+" \u2013 minicraft":"minicraft")},[f]);var l=x("div[className=game]");return[(f===2||f===1)&&B(ve,{state:b,view:f,aa:g,ya:c,H:d}),f===1&&C("div[className=backdrop]"),f===1&&B(ge,{L:null,state:b,aa:g}),f===0&&B(oe,{frame:l,ea:a,state:b,aa:g,ya:c,H:d,Za:e}),f===2&&b.ka&&C("div[style=position:absolute;bottom:0;left:0;color:yellow]",{title:b.ka},[C("span[innerText=Connection error. ]"),C("button[innerText=Retry]",
{onclick:()=>{W.A({ka:null})}})])]}
var xe="nwse-resize ns-resize nesw-resize ew-resize move ew-resize nesw-resize ns-resize nwse-resize".split(" "),ye={init:(a,b)=>ye.Ab({fb:0,Qa:0,height:0,ea:null,left:0,mode:b,title:"...",top:0,width:0},600,400),Qb:a=>Object.assign({},a,{mode:a.mode===0?1:0}),dc:(a,b)=>a.ea&&a.ea.code===b.code&&a.ea.state===b.state?a:Object.assign({},a,{ea:b}),Ub:(a,b,c)=>Object.assign({},a,{left:J(0,I(b,V.Y-a.width)),top:J(0,I(c,V.ga-a.height))}),ib:(a,b)=>Object.assign({},a,b),Ab:(a,b,c)=>Object.assign({},a,{Qa:b=
J(100,I(b,V.Y-a.left)),fb:c=J(50,I(c,V.ga-a.top)),width:b,height:c}),mc:(a,b)=>Object.assign({},a,{title:b})},ze=(a,b,c)=>{W.oc(b);var d=c.target;if(d.className==="window_title")d=d.parentElement;else if(c.button!==0||d.className!=="window borders")return;c.preventDefault();sa.activeElement.blur();var e,f;[e,f]=a;var g=c.clientX,l=c.clientY,h=g-e.left,q=l-e.top,k=h<8?0:h<e.width-8?1:2,n=q<8?0:q<e.height-8?1:2,r=k+n*3;d.style.willChange=r===4?"left,top":"contents";W.A({cursor:xe[r]});var p=w=>{qe=
!0;aa();var v=w.clientX,u=w.clientY;a:if(r===4){if(w.type==="mouseup"){if(u<4){f.ib({left:0,top:0,width:V.Y,height:V.ga});break a}if(v<4){f.ib({left:0,top:0,width:Ba(V.Y/2),height:V.ga});break a}if(v>V.Y-3){f.ib({left:Ba(V.Y/2),top:0,width:H(V.Y/2),height:V.ga});break a}}else if([w]=a,w.Qa!==w.width||w.fb!==w.height){f.Ab(w.Qa,w.fb);let [G]=a;h=Ca(h*G.Qa/w.width)}f.Ub(v-h,u-q)}else k!==0&&n!==0||f.Ub(k===0?(v=J(h,I(v,e.left+e.width-100+h)))-h:e.left,n===0?(u=J(q,I(u,e.top+e.height-50+q)))-q:e.top),
f.Ab(k===0?e.width+e.left+h-v:k===1?e.width:e.width-g+v,n===0?e.height+e.top+q-u:n===1?e.height:e.height-l+u);ca();qe=!1},z=w=>{ob("mousemove",p,!0);ob("mouseup",z);W.A({cursor:null});p(w);d.style.willChange="auto"};nb("mousemove",p,!0);nb("mouseup",z)},Ae=({height:a,left:b,mode:c,top:d,width:e},f)=>({F:{window:!0,borders:c===1},onmousedown:f,S:{display:c===2?"none":"block",left:c===0?"0":b-1+"px",top:c===0?"0":d-1+"px",height:c===0?"100%":a-40+"px",width:c===0?"100%":e-16+"px"}}),Be=({title:a,width:b,
qc:c})=>[C("div[className=window_title]",{innerText:a,S:{width:`${b-40}px`}}),C("div[className=window_button]",{onclick:()=>W.rc(c)})];
function Ce({I:{id:a,Tb:b,type:c},state:d}){var e=ea(ye,b),f,g;[f,g]=e;y(()=>(De.set(a,g),()=>De.delete(a)));b=A(()=>ze.bind(null,e,a));x("div",A(Ae,[f,b]));var l=fa(!0,!1);y((q,k)=>{l&&g.ib({left:J(0,I(f.left,q-f.width)),top:J(0,I(f.top,k-f.height)),width:I(q,J(100,f.Qa,f.width)),height:I(k,J(50,f.fb,f.height))})},[d.Y,d.ga]);b=f.mode===0?d.Y:f.width-16;var h=f.mode===0?d.ga:f.height-40;return[c===1&&B(we,{ea:f.ea,state:d,ya:h,H:b,Za:g}),f.mode!==0&&B(Be,{title:f.title,width:f.width,qc:a})]}
var pe=new fb,De=new gb,qe=!1,Ee=0,Fe=0,Ge=()=>{W.eb(!0)},He=a=>{a.timeStamp-Ee>999&&W.eb(!1)};
function Ie(){[V,W]=ea(tc);y(()=>{nc(!0);var b=!1;D.onunload=onbeforeunload=onpagehide=onblur=()=>{if(!b){b=!0;for(let d of pe)dd(d.world,d.j,!0);W.tb()}};onpageshow=onfocus=()=>(b=!1,onresize());D.onorientationchange=onresize=()=>{qe=!0;W.hc(Ka?Ka.width:D.innerWidth,Ka?Ka.height:D.innerHeight);qe=!1};lb(()=>(onresize(),W.tb(),!La&&L.getItem("minicraft.lock_requested")&&(Ua("minicraft.lock_requested"),O("minicraft.lock",Qa.now()))),200);nb("touchend",d=>{Ee=d.timeStamp},!0);var c=d=>{var e=d.type===
"keydown";if(e&&d.target.tagName==="INPUT")return!0;qe=!0;W.eb(!1);if(V.K.length>0){let f=De.get(V.K[V.K.length-1].id);d.key!=="f"?f.dc({code:d.keyCode,state:e}):e&&f.Qb()}return qe=!1};hb.assign(sa.body,{style:"background:green",onkeydown:c,onkeyup:c,oncontextmenu:Cb,ondragstart:Cb})});var a=V.config.Ea;y(()=>{a?(nb("mousedown",He,!0),nb("mouseup",He,!0),ob("touchstart",Ge,!0)):(ob("mousedown",He,!0),ob("mouseup",He,!0),nb("touchstart",Ge,!0))},[a]);y(qd,[V.config.V]);y(()=>{mb(Fe);V.ka||(Fe=kb(sc))},
[V.ka,V.$a]);return[qa(Ce,V.K,{state:V}),V.cursor&&C("div[className=cursormask]",{S:{cursor:V.cursor}})]}function Je(){close();return[C("h1[innerText=minicraft already running!]")]}
if(La){let a=new La("minicraft.lock"),b=kb(()=>bc.then(()=>ka(Ie)),100);a.addEventListener("message",c=>{c.data==="yes"?(mb(b),a.close(),ka(Je)):(a.postMessage("yes"),focus())});a.postMessage("anyone there?")}else{O("minicraft.lock_requested","1");let a=Qa.now(),b=0,c=lb(()=>{U(L.getItem("minicraft.lock"))>a?(mb(c),ka(Je)):++b>4&&(mb(c),bc.then(()=>ka(Ie)))},250)};

//# sourceMappingURL=app-en.js.map
