function aa(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,f){function l(m){m.done?d(m.value):Promise.resolve(m.value).then(b,c).then(l,f)}l(a.next())})}
const r=lui,ea=r.defer,fa=r.defer_end,ha=r.dom_define,ia=r.hook_async,A=r.hook_dom,D=r.hook_effect,ja=r.hook_memo,na=r.hook_model,oa=r.hook_rerender,pa=r.hook_state,E=r.hook_static,F=r.node,H=r.node_dom,qa=r.node_map,ra=r.now,sa=window,ta=document,J=Math,za=J.PI,Aa=.5*za,Ba=180/za,L=J.floor,Ca=J.ceil,Da=J.round,O=J.min,Ea=J.max,Fa=J.cos,Ga=J.sin,Ha=J.sqrt,Ma=J.log2,Na=String.fromCharCode,Oa=Date,Pa=JSON,Qa=Pa.stringify,Ra=Pa.parse,P=localStorage,Sa=P.setItem.bind(P),Ta=P.removeItem.bind(P),Ua=Uint8Array,
Va=Uint32Array,Wa=Map,Q=Number,Xa=Object,Ya=Xa.keys,Za=Xa.entries,$a=setTimeout,ab=setInterval,fb=clearTimeout,gb=clearInterval,S=a=>a*a,hb=()=>!1,ib=a=>{var b=new Oa;a=new Oa(a);var c=b-a;if(59E3>c)return Da(c/1E3)+"s";if(3E6>c)return Da(c/6E4)+"m";c=a.getFullYear();const d=a.getMonth(),f=a.getDate();let l="";c<b.getFullYear()&&(l=c+"/");if(l||d<b.getMonth())l+=d+1+"/";if(l||f<b.getDate())l+=f+"/";b=l+a.getHours()+":";a=a.getMinutes();a=L(a).toString().padStart(2,"0");return b+a},jb={init:()=>{let a=
!1;var b={ia:!0,ra:3,V:4,za:120,da:64,Ba:0,worlds:[]},c=P.getItem("minicraft.config");if(c){c=Ra(c);let d=c.flag_textures;null!=d&&(b.ia=d);null!=(d=c.mouse_sensitivity)&&(b.ra=d);b.V=c.resolution_scaling;b.za=c.view_angle;b.da=c.view_distance;null!=(d=c.world_last)&&(b.Ba=d);null!=(d=c.worlds)?b.worlds=d:P.getItem("minicraft.world.0:meta")&&(b.worlds[0]={id:0,label:(prompt("Es wurde eine namenlose lokale Welt gefunden. Wie soll sie hei\u00dfen?","")||"Unbekannte Welt").substring(0,16),mod_l:Date.now(),
mod_r:0},a=!0)}b={account:{label:"",rank:0},g:b,Ua:b};return a?(b.Ua=null,jb.Ta(b)):b},Ta:a=>{const b=a.g;if(b===a.Ua)return a;Sa("minicraft.config",Qa({version:"0.9.7",flag_textures:b.ia,mouse_sensitivity:b.ra,resolution_scaling:b.V,view_angle:b.za,view_distance:b.da,world_last:b.Ba,worlds:b.worlds}));return Object.assign({},a,{Ua:b})},ob:(a,b)=>Object.assign({},a,{account:b}),qb:(a,b)=>jb.Va(a,b(a.g)),Va:(a,b)=>Object.assign({},a,{g:Object.assign({},a.g,b)}),ab:(a,b)=>Object.assign({},a,{g:Object.assign({},
a.g,{worlds:[...a.g.worlds,b]})}),nb:(a,b)=>Object.assign({},a,{g:Object.assign({},a.g,{worlds:a.g.worlds.filter(c=>c.id!==b)})}),W:(a,b,c)=>Object.assign({},a,{g:Object.assign({},a.g,{worlds:a.g.worlds.map(d=>d.id===b?Object.assign({},d,c):d)})})},kb="air stone grass dirt cobble planks bedrock log leaves bricks wool sand gravel glass bookshelf obsidian stone_bricks sandstone lapis_block iron_block gold_block diamond_block emerald_block redstone_block quartz_block".split(" "),lb="Luft Stein Grasblock Erde Bruchstein Holzbretter Grundgestein Stamm Laub Ziegelsteine Wolle Sand Kies Glas B\u00fccherregal Obsidian Steinziegel Sandstein Lapislazuliblock Eisenblock Goldblock Diamantblock Smaragdblock Redstoneblock Quarzblock".split(" "),
mb=[0,8487297,4305266,4349313,8092539,5342114,7039851,3561583,4172910,6384533,15526888,10671324,8092798,16447200,4151672,1970708,8092539,9686227,9126695,15198183,5567485,14541182,7920469,662956,14936813],nb="WEBTSN".split(""),ob=(a,b=1,c=null)=>({amount:b,data:c,id:a}),pb=(a,b,c=a.content.amount)=>{if(b.content)a.content.id===b.content.id?(c=O(c,b.P-b.content.amount),a.content.amount-=c,b.content.amount+=c,0>=a.content.amount&&(a.content=null)):!(a.content.amount<=c&&a.content.amount<=b.P&&b.content.amount<=
a.P)||a.filter&&!a.filter(b.content.id)||b.filter&&!b.filter(a.content.id)||([b.content,a.content]=[a.content,b.content]);else if(!b.filter||b.filter(a.content.id))a.content.amount<=c&&a.content.amount<=b.P?[b.content,a.content]=[a.content,b.content]:(c=O(c,b.P),a.content.amount-=c,b.content=ob(a.content.id,c),0>=a.content.amount&&(a.content=null))},qb=(a,b)=>{for(const c of a)if(c.content&&c.content.id===b.id){const d=O(b.amount,c.P-c.content.amount);c.content.amount+=d;if(0>=(b.amount-=d))return null}for(const c of a)if(!c.content&&
(!c.filter||c.filter(b.id)))if(a=O(b.amount,c.P),a<=b.amount){if(c.content=ob(b.id,a),0>=(b.amount-=a))return null}else return c.content=b,null;return b},rb=(a,b)=>({Qa:0,bb:0,Ra:0,O:0,ea:0,Da:0,fa:0,X:-1,ga:0,ma:null,na:null,u:1,jb:20,G:Array(36).fill(null).map(()=>({content:null,filter:null,P:64})),La:0,name:b.label||"Spieler",H:a.wa,J:a.xa,K:a.ya,lb:0,mb:0,M:0,ka:0,aa:0,ba:0,ca:0}),sb=(a,b,c)=>{a.O=(a.O+b+100*za)%(2*za);a.ea=Ea(-Aa,O(Aa,a.ea+c))},tb=a=>{a+=32;33<a&&39>a?a++:38<a&&44>a?a+=2:43<
a&&127>a?a+=3:126<a&&55258>a?a+=37:55295<a&&(a+=8485);return Na(a)},ub=a=>a-(63743<a?8517:159<a?69:46<a&&130>a?35:40<a&&46>a?34:34<a&&40>a?33:32),wb=()=>{var a=vb;const b=a.length,c=new Wa,d=k=>{h=h<<1|k&1;15===++t&&(g+=tb(h),h=t=0)},f=()=>{for(let k=0;k<w;++k)d(0)},l=k=>{d(k);d(k>>1);d(k>>2);d(k>>3);d(k>>4);d(k>>5);d(k>>6);d(k>>7)},m=()=>{0===--v&&(v=1<<w++)},p=()=>{if(q)q=!1;else{let k=u.id;for(let x=0;x<w;x++)d(k>>x)}};let e=a[0],g="",h=0,t=2,w=2,v=2,n=2,u={id:n++,Fa:new Wa},q=!0;l(e);c.set(e,
u);for(let k=1;k<b;++k){const x=u.Fa.get(e=a[k]);x?u=x:(p(),c.has(e)||(m(),f(),l(e),c.set(e,{id:n++,Fa:new Wa}),q=!0),u.Fa.set(e,{id:n++,Fa:new Wa}),u=c.get(e),m())}p();c.has(e)||(m(),f(),l(e));m();d(1);--w;f();return g+=tb(h<<15-t)},xb=a=>{var b=vb;if(!a)return null;const c=a.length,d=()=>{t+=(n>>--u&1)<<w++;0===u&&(u=15,n=ub(a.charCodeAt(v++)))};let f=[0,1],l=1,m=3,p=2,e=null;var g=null;let h=0,t=0;g=2;let w=0,v=0,n=ub(a.charCodeAt(v++)),u=15;for(;w<g;)d();if(1===t)return null;for(t=w=0;8>w;)d();
e=[t];f[2]=e;for(b[h++]=t;v<=c;){g=p;for(t=w=0;w<g;)d();if(0===t){for(t=w=0;8>w;)d();f[m]=[t];t=m++;0===--l&&(l=1<<p++)}else if(1===t)return b;g=t<f.length?f[t]:e.concat(e[0]);for(let q=0;q<g.length;q++)b[h++]=g[q];f[m++]=e.concat(g[0]);e=g;0===--l&&(l=1<<p++)}return null},T=new Va(1024),vb=new Ua(T.buffer),yb=new Wa,zb=(a,b,c,d)=>0>c||63<c?0:a.Y[(b<<a.L+4|d)<<6|c],Ab=(a,b,c,d)=>{const f=a.L;a.Y[(b<<f+4|d)<<6|c]=0;a.Z[(b>>4<<f|d>>4)<<2|c>>4].ha=!0},Bb=(a,b,c,d,f)=>{const l=a.L,m=(b<<l+4|d)<<6|c;if(0<
a.Y[m])return!1;a.Y[m]=f;return a.Z[(b>>4<<l|d>>4)<<2|c>>4].ha=!0},Eb=(a,b,c)=>{const d=Ea(O(b.J,63),0)>>4,f=L(b.H)>>4;b=L(b.K)>>4;if(c||a.Ja!==d||a.sa+a.Ia!==f||a.ta+a.Ka!==b)c=1<<a.L,a.Ja=d,a.sa=f-(a.Ia=(65536+f)%c),a.ta=b-(a.Ka=(65536+b)%c),Cb(a);Db(a,!1)},Cb=a=>{const b=a.Ia,c=a.Ja,d=a.Ka,f=a.L,l=`${f} ${b} ${d} ${c}`;let m=yb.get(l);if(null==m){const p=1<<f,e=S(.5*p);yb.set(l,m=a.Z.map(({x:g,y:h,z:t},w)=>{let v=S(g-b),n=S(t-d),u=S(g-b-p),q=0,k=0;u<v&&(v=u,q=-p);(u=S(g-b+p))<v&&(v=u,q=p);(u=S(t-
d-p))<n&&(n=u,k=-p);(u=S(t-d+p))<n&&(n=u,k=p);return{Wa:v+n+S(h-c),eb:w,sa:q,ta:k}}).filter(({Wa:g})=>g<=e).sort((g,h)=>g.Wa-h.Wa))}a.Ga=m;a.oa=0},Gb=(a,b)=>{for(var c of a.Z)c.ha&&Fb(a,c);for(c=b.G.map(({content:d})=>d&&[d.id,d.amount,d.data]);0<c.length&&null===c[c.length-1];)c.pop();Sa(`minicraft.world.${a.id}:meta`,Qa({p:{h:b.jb,i:c,m:b.u,p:[b.H,b.J,b.K,b.O,b.ea]},s:[a.wa,a.xa,a.ya],v:1}))},Sb=(a,b)=>{const c=P.getItem(`minicraft.world.${a.id}:meta`);if(c){const {p:d,s:f,v:l}=Ra(c);null!=l&&(d.i.forEach((m,
p)=>{m&&(b.G[p].content=ob(m[0],m[1],m[2]))}),b.jb=d.h,b.u=d.m,b.H=d.p[0],b.J=d.p[1],b.K=d.p[2],b.O=d.p[3],b.ea=d.p[4],a.wa=f[0],a.xa=f[1],a.ya=f[2])}},Tb=(a,b,c,d)=>`minicraft.world.${a.id}:${b}/${c}`+(0<d?"/"+d:""),Ub=a=>{const b=a.Z[a.Ga[a.oa=0].eb];Ta(Tb(a,b.Ca,b.Pa,b.y));b.ha=!1;++b.Ca;Db(a,!1)},Fb=(a,b)=>{const c=a.Ea;var d=a.L;const f=b.y,l=(256<<d)-256;for(let m=0,p=-1,e=((b.x<<d+4|b.z)<<6|f)<<2;16>m;++m){for(d=0;16>d;++d)T[++p]=c[e],T[++p]=c[++e],T[++p]=c[++e],T[++p]=c[++e],e+=13;e+=l}Sa(Tb(a,
b.Ca,b.Pa,f),wb());b.ha=!1},Db=(a,b)=>{const c=a.Z,d=a.Ga,f=a.sa,l=a.ta,m=d.length;for(;a.oa<m;){var p=d[a.oa++],e=c[p.eb],g=e.loaded,h=e.x;const v=e.y;var t=e.z,w=f+p.sa+h;p=l+p.ta+t;if(!g||w!==e.Ca||p!==e.Pa)if(e.ha&&Fb(a,e),e.loaded=!0,p=xb(P.getItem(Tb(a,e.Ca=w,e.Pa=p,v))),g||0===v||p){e=a.Ea;const n=a.L;w=(256<<n)-256;h=((h<<n+4|t)<<6|v)<<2;if(p)for(let u=0,q=-1;16>u;++u){for(g=0;16>g;++g)e[h]=T[++q],e[++h]=T[++q],e[++h]=T[++q],e[++h]=T[++q],h+=13;h+=w}else for(t=0;16>t;++t){for(p=0;16>p;++p)e[h]=
0<v?0:50397446,e[++h]=0<v?0:131843,g?(e[++h]=0,e[++h]=0,h+=13):h+=15;h+=w}if(!b)break}}};let Vb=null,Wb=null,Xb=new Image;Xb.crossOrigin="anonymous";Xb.onload=()=>{const a=ta.createElement("canvas");a.width=16;a.height=416;const b=a.getContext("2d");b.drawImage(Xb,0,0);ha("tile","div[className=bitmap]",{S:{backgroundImage:`url(${a.toDataURL()})`}});Vb=new Va(b.getImageData(0,0,16,416).data.buffer);Wb&&Wb();Xb=Wb=null};Xb.src=ASSETS+"blocks.webp";
const Zb=(a,b)=>{const c={pb:b,Sa:b.getContext("2d",{alpha:!1,desynchronized:!0}),cb:null,hb:"",T:!1,ib:0,Xa:0,rb:ab(()=>(c.ib=c.Xa,c.Xa=0),1E3),o:a};null===Vb&&(Wb=()=>c.T=!0);Yb(c);return c},Yb=a=>{const b=a.pb,c=a.o;(a.cb=a.Sa.createImageData(b.width=c.ua,b.height=c.va)).data.fill(255);const d=c.ua*c.g.V/c.ja,f=c.va*c.g.V/c.ja;b.style.width=d+"px";b.style.height=f+"px";b.style.left=Da((c.Ma-d)/2)+"px";b.style.top=Da((c.Na-f)/2)+"px";a.Sa.fillStyle="rgba(255,255,255,.5)"};let $b=0;
const cc=(a,b,c,d)=>{const f={Y:null,Ea:null,Z:null,Ga:null,oa:0,A:!0,Ia:0,Ja:0,Ka:0,id:c.Ba,sa:0,ta:0,L:0,wa:.5,xa:8.5,ya:.5,time:0,Oa:0},l=rb(f,d);Sb(f,l);a={actions:a,g:c,fb:0,gb:0,Ha:!1,pa:!0,qa:!1,sb:b,$:0,U:new Set,Ya:"",l:0,N:[],j:l,Za:null,B:null,ja:1,Ma:1,Na:1,ua:0,va:0,ub:ab(()=>{f.A||(f.time=(f.time+1)%24E3,f.Oa=1/24E3*(f.Oa+6E3)%1,Eb(f,l,!1))},50),world:f};ac(a,null);bc(a);return a},dc=a=>{Gb(a.world,a.j);a.actions.W(a.world.id,{mod_l:Date.now()})},bc=a=>{aa(function*(){try{yield a.sb.requestPointerLock()}catch(b){}}())},
ec=(a,b)=>a===b?0:.1-.2*a,fc=a=>{a.j.Qa=ec((a=a.U).has(-12)||a.has(65),a.has(-13)||a.has(68))},gc=a=>{a.j.bb=ec((a=a.U).has(-15)||a.has(16),a.has(-14)||a.has(32))},hc=a=>{a.j.Ra=ec((a=a.U).has(-11)||a.has(83),a.has(-10)||a.has(87))},ic=a=>{a.j.lb=ec(a.U.has(-18),a.U.has(-19))},jc=a=>{a.j.mb=ec(a.U.has(-17),a.U.has(-16))},X=(a,b,c)=>{if(!a.world)return!1;const d=a.U;var f=a.j;if(c){if(d.has(b))return!1;d.add(b);var l=f.fa,m=f.X;c=f.ga;switch(b){case -18:case -19:ic(a);break;case -17:case -16:jc(a);
break;case -1:2!==f.u&&0<=m&&(0===f.La?0===f.u&&(b=zb(a.world,l,m,c),2===b?b=3:1===b&&(b=4),6===b||8!==b&&13!==b&&null!==qb(f.G,ob(b,1)))||(Ab(a.world,l,m,c),f.X=-1):kc(a,[l,m,c],!1));break;case -2:case 71:if(0<=m){const p=zb(a.world,l,m,c);c=f.G.slice(0,9);m=c.findIndex(e=>null!==e.content&&e.content.id===p);0<=m?f.M=m:1===f.u&&(c[f.M].content&&(c=c.findIndex(e=>null===e.content),0<=c&&(f.M=c)),f.G[f.M].content=ob(p));f.ka=a.$}break;case -3:if(2!==f.u&&0<=m)if(0===f.La){if(b=f.G[f.M],b.content){switch(f.Da){case 0:--l;
break;case 1:++l;break;case 2:--m;break;case 3:++m;break;case 4:--c;break;default:++c}0<=m&&64>m&&Bb(a.world,l&(1<<4+a.world.L)-1,m,c&(1<<4+a.world.L)-1,b.content.id)&&1!==f.u&&0>=--b.content.amount&&(b.content=null)}}else kc(a,[l,m,c],!0);break;case -4:f.M=(f.M+9-1)%9;f.ka=a.$;break;case -5:f.M=(f.M+1)%9;f.ka=a.$;break;case 27:0===a.l&&(a.world.A=!0,a.l=1);break;case -15:case -14:case 16:case 32:gc(a);break;case 49:case 50:case 51:case 52:case 53:case 54:case 55:case 56:case 57:f.M=b-49;f.ka=a.$;
break;case -12:case -13:case 65:case 68:fc(a);break;case 69:if(0===a.l){a.l=3;for(const p of d)X(a,p,!1)}break;case 80:a.world&&(a.world.A=!a.world.A);break;case 81:f=f.G[f.M];if(d.has(17)||f.content&&0>=--f.content.amount)f.content=null;break;case -11:case -10:case 83:case 87:hc(a);break;case 84:if(0===a.l){a.l=2;for(const p of d)X(a,p,!1)}break;case 112:a.pa=!a.pa;break;case 114:a.Ha=!a.Ha;break;default:return!1}}else{if(!d.delete(b))return!1;switch(b){case -15:case -14:case 16:case 32:gc(a);break;
case -12:case -13:case 65:case 68:fc(a);break;case -11:case -10:case 83:case 87:hc(a);break;case -18:case -19:ic(a);break;case -17:case -16:jc(a)}}a.Ya=[...d].join();return!0},lc=(a,b)=>(b=b.startsWith("~")?a+Q(b.substr(1)):Q(b),isNaN(b)?a:b),nc=(a,b)=>{const c=a.j;var d=a.world;if(b)if("/"===b.charAt(0)){b=b.substr(1).split(" ");const f=b.shift();switch(f){case "clear":a.N=[];break;case "clearinv":for(const l of c.G)l.content=null;Y(a,"Inventar geleert",!0);break;case "gamemode":case "gm":b=Q(b[0]);
!isNaN(b)&&0<=b&&3>b&&0===b%1?(c.u=b,Y(a,"Spielmodus gesetzt auf: "+b,!0)):Y(a,"Spielmodus muss in 0..2 sein!");break;case "give":if(0===b.length){Y(a,"/give <id> [Anzahl]\n"+kb.join(" "));break}d=kb.indexOf((b[0]||"").toLowerCase());d=0<=d?d:Q(b[0]);b=Q(b[1]||1);!isNaN(d)&&0<d&&25>d&&0===d%1?!isNaN(b)&&0<b&&0===b%1?Y(a,qb(c.G,ob(d,b))?"Inventar ist voll!":`${"Items gegeben"} ${b} ${lb[d]}`,!0):Y(a,"Anzahl muss mindestens 1 sein!"):Y(a,"Ung\u00fcltiger Blocktyp!");break;case "help":Y(a,"Befehle: clear, clearinv, gamemode, give, help, load, me, save, spawn, teleport, version");
break;case "load":Db(d,!0);a.B.T=!0;Y(a,"Chunks geladen.",!0);break;case "me":Y(a,c.name+" "+b.join(" "),!0);break;case "save":dc(a);Y(a,"Spiel gespeichert.",!0);break;case "smart":c.name="LFF5644";Y(a,"lff.smart: true",!0);break;case "spawn":d.wa=c.H;d.xa=c.J;d.ya=c.K;Y(a,"Startpunkt aktualisiert.",!0);break;case "teleport":case "tp":0===b.length?(c.H=d.wa,c.J=d.xa,c.K=d.ya,a.B.T=!0,Y(a,"Zum Startpunkt teleportiert.",!0)):3===b.length?(Y(a,"Teleportiert zu"+` ${c.H=lc(c.H,b[0])} ${c.J=lc(c.J,b[1])} ${c.K=
lc(c.K,b[2])}`,!0),a.B.T=!0):Y(a,"Pech!");c.aa=0;c.ba=0;c.ca=0;break;case "version":Y(a,"Minicraft 0.9.7");break;case "/exit":c.La=0;Y(a,"Normaler Mausmodus.",!0);break;case "/expand":a.j.ma&&a.j.na?d=!0:(Y(a,"Auswahl erforderlich!"),d=!1);d&&("vert"===b[0]?(c.ma[1]=0,c.na[1]=63,Y(a,"Auswahl erweitert.",!0)):Y(a,'Nur "vert" wird unterst\u00fctzt!'));break;case "/pos1":case "/pos2":kc(a,[L(c.H),L(c.J),L(c.K)],"/pos2"===f);break;case "/regen":Ub(d);Y(a,"Chunk neu generiert.",!0);a.B.T=!0;break;case "/show":Y(a,
`${"Erster"}: ${c.ma?c.ma.join(" "):"nichts"}, ${"Zweiter"}: ${c.na?c.na.join(" "):"nichts"}`);break;case "/wand":c.La=1;Y(a,"Auswahl mit Maustasten.",!0);break;default:Y(a,"Ung\u00fcltiger Befehl: "+f)}}else{const f=Y(a,`<${c.name}> `+b);ac(a,b).then(l=>{l&&mc(a,f)})}},Y=(a,b,c=!1)=>{const d=++$b;(a.N=a.N.slice(-49)).push({id:d,kb:c,time:ra(),value:b});return d},mc=(a,b)=>{const c=a.N.findIndex(d=>d.id===b);0<=c&&a.N.splice(c,1)},kc=(a,b,c)=>{c?a.j.na=b:a.j.ma=b;Y(a,`${c?"Zweiter Auswahlpunkt":"Erster Auswahlpunkt"}: ${b.join(" ")}`,
!0)},ac=(a,b)=>(fb(a.Za),(b?fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:Qa({msg:b})}):fetch("/api/chat")).then(c=>{if(c.ok)return c.text()}).then(c=>{if(c){c=c.split("\n").filter(Boolean);for(const d of c)d.startsWith("<")&&Y(a,d);return 0<c.length}return!1}).catch(()=>!1).then(c=>{a.Za=$a(()=>{ac(a,null)},5E3);return c})),oc=({id:a})=>(A("#tile",{S:{backgroundPositionY:`-${2*(a-1)}rem`}}),null);
function pc({amount:a,u:b,id:c}){A("div[className=stack]",{title:lb[c]+(1===b?` (${kb[c]}, ${c})`:"")});return[F(oc,{id:c}),1!==a&&H("div[className=amount]",{innerText:a})]}
function qc({j:a,la:b}){A("div[className=bar]",{ontouchstart:E(d=>{a.M=Number(d.target.closest("[data-slot]").dataset.slot);a.ka=d.timeStamp}),S:{opacity:Ea(.5,O(1,1-5E-4*(b-a.ka-5E3)))}});const c=a.u;return Vb&&a.G.slice(0,9).map(({content:d},f)=>H("div",{D:{slot:f},F:{active:f===a.M}},[d&&F(pc,{amount:d.amount,data:d.data,u:c,id:d.id})]))}
function rc({tb:a}){A("div[className=grid]",{onclick:({target:b})=>{(b=b.closest("[data-id]"))&&pb({content:ob(Q(b.dataset.id)),filter:null,P:64},a)}});return kb.map((b,c)=>0<c&&H("div",{D:{id:c}},[F(pc,{amount:1,data:null,u:1,id:c})]))}
function sc({o:a}){const b=ja(()=>({content:null,filter:null,P:64})),c=a.j.u;A("div[className=menu overlay inventory]",ja(()=>({onclick:({target:d})=>{if("menu overlay inventory"===d.className)b.content?b.content=null:(a.l=0,a.world.A=!1,bc(a));else if(d=d.closest("[data-slot]"))d=a.j.G[Q(d.dataset.slot)],b.content?pb(b,d):d.content&&pb(d,b)},oncontextmenu:({target:d})=>{if("menu overlay inventory"===d.className)b.content?0>=--b.content.amount&&(b.content=null):(a.l=0,bc(a));else if(d=d.closest("[data-slot]"))d=
a.j.G[Q(d.dataset.slot)],b.content?pb(b,d,1):d.content&&pb(d,b,Ca(d.content.amount/2))}})));return Vb&&[H("div[className=window]",null,[H("div[innerText=Inventar]"),1===c&&F(rc,{tb:b}),H("div[className=grid]",null,a.j.G.map(({content:d},f)=>H("div",{D:{slot:f},F:{first:9>f}},[d&&F(pc,{amount:d.amount,data:d.data,u:c,id:d.id})])))]),b.content&&H("div[className=hand]",{S:{transform:`translate(${a.fb}px, ${a.gb}px)`}},[F(pc,{amount:b.content.amount,data:b.content.data,u:0,id:b.content.id})])]}
const tc=({I:{kb:a,time:b,value:c},la:d})=>(A(a?"div[className=minor]":"div",{innerText:c,S:{opacity:O(1,1-.001*(d-b-4500))}}),null);function uc({N:a,la:b}){A("div[className=messages]");const c=b-5E3;return[qa(tc,a.slice(-10).filter(d=>d.time>c),{la:b})]}
function vc({actions:{qb:a,Va:b},g:c,o:d,Aa:f}){D(()=>dc(d));A("div[className=menu overlay]");return[H("h1[innerText=Einstellungen]"),E(H("center",null,[H("button[innerText=Zur\u00fcck zum Spiel]",{onclick:()=>{d.l=0;d.world.A=!1;bc(d)}})])),H("div[className=settings]",null,[H("button",{innerText:"Oberfl\u00e4chen:\n"+(c.ia?"Texturiert":"Einfarbig"),onclick:E(()=>a(l=>({ia:!l.ia})))}),H("label[innerText=Aufl\u00f6sung:]",null,[H("input[type=range][min=1][max=100][step=1]",{value:101-c.V,onchange:E(l=>
b({V:101-Number(l.target.value)}))})]),H("label[innerText=Blickwinkel:]",null,[H("input[type=range][min=1][max=180][step=1]",{value:c.za,onchange:E(l=>b({za:Number(l.target.value)}))})]),H("label[innerText=Sichtweite:]",null,[H("input[type=range][min=1][max=128][step=1]",{value:c.da,onchange:E(l=>b({da:Number(l.target.value)}))})]),H("label[innerText=Mausempfindlichkeit:]",null,[H("input[type=range][min=1][max=15][step=1]",{value:c.ra,onchange:E(l=>b({ra:Number(l.target.value)}))})])]),E(H("center",
null,[H("button[innerText=Welt verlassen]",{onclick:()=>{f(0)}})]))]}const wc=({I:{kb:a,value:b}})=>(A(a?"div[className=minor]":"div",{innerText:b}),null);
function xc({o:a,N:b}){const c=E({history:null,input:null});A("div[className=menu overlay terminal]",{onclick:d=>{d.target!==c.input&&c.input.focus()}});D(d=>{d&&$a(()=>c.history.scrollTop=1E9,0)},[b.length&&b[b.length-1].id]);return[E(H("div[className=toolbar]",null,[H("button[innerText=\u274c]",{onclick:()=>{a.l=0;a.world.A=!1;bc(a)}})])),H("div[className=history]",{R:E(d=>{c.history=d})},[qa(wc,b)]),E(H("input[enterkeyhint=send][mozactionhint=send][name=message][required]",{onkeydown:d=>{const f=
d.keyCode;d=d.target;13===f?(nc(a,d.value),d.value=""):27===f&&(a.A=!1,a.l=0)},R:d=>{c.input=d;$a(()=>d.focus(),0)}}))]}const yc=[["pick",-2],["up",-14],["down",-15],["E",69],["T",84],["F1",112],["F3",114],["...",27]],zc=[["up",-10],["down",-11],["left",-12],["right",-13],["center",-1]],Ac=[["up",-16],["down",-17],["left",-18],["right",-19],["center",-3]];
function Bc({o:a}){const b=a.U,c=([d,f])=>H("div",{D:{code:f},F:{button:!0,[d]:!0,active:b.has(f)}});A("div[className=touch]",E({ontouchstart:d=>{d.preventDefault();const f=Number(d.target.dataset.code);if(null!=f&&X(a,f,!0)){const l=d.changedTouches[0].identifier,m=p=>{p.changedTouches[0].identifier===l&&(removeEventListener("touchend",m),X(a,f,!1))};addEventListener("touchend",m)}}}));return[H("div[className=top]",null,yc.map(([d,f])=>H(`div[innerText=${d}]`,{D:{code:f},F:{button:!0,active:b.has(f)}}))),
H("div[className=move]",null,zc.map(c)),H("div[className=move sec]",null,Ac.map(c))]}
function Cc({account:a,actions:b,g:c,frame:d,$a:f,Aa:l}){const m=ra(),p=ta.pointerLockElement===d,e=ja(()=>f.o=cc(b,d,c,a));D(()=>{const g=v=>{if(0!==e.l)return!0;e.qa=!1;ta.pointerLockElement===d?X(e,-1-v.button,"mousedown"===v.type):bc(e);v.preventDefault();return!1},h=v=>{if(e.world.A)e.fb=v.clientX,e.gb=v.clientY;else{const n=e.g.ra*za/(Ea(e.Ma,e.Na)*e.ja);sb(e.j,v.movementX*n,-v.movementY*n)}},t=v=>{e.qa=!1;if(0===e.l&&!e.world.A&&5<Math.abs(v.deltaY)){const n=0<v.deltaY?-5:-4;X(e,n,!0);X(e,
n,!1);v.preventDefault()}},w=v=>{e.qa=!0;0===e.l&&(e.world.A=!1,v.preventDefault())};d.addEventListener("mousedown",g);d.addEventListener("mouseup",g);d.addEventListener("mousemove",h);d.addEventListener("wheel",t);d.addEventListener("touchstart",w);return()=>{d.removeEventListener("mousedown",g);d.removeEventListener("mouseup",g);d.removeEventListener("mousemove",h);d.removeEventListener("wheel",t);d.removeEventListener("touchstart",w);fb(e.Za);gb(e.ub);Gb(e.world,e.j);gb(e.B.rb);f.o=null}});D(()=>
{e.g=c;e.B&&(e.B.T=!0);const g=e.world;var h=Ca(Ma(e.g.da/16*2+2));if(g.L!==h){var t=e.j;g.Z&&Gb(g,t);const w=1<<(g.L=h),v=g.Z=[];for(let n=0;n<w;++n)for(let u=0;u<w;++u)for(let q=0;4>q;++q)v.push({ha:!1,loaded:!1,x:n,y:q,z:u,Ca:0,Pa:0});h=w<<h+12+2;null===g.Y||g.Y.length<h?g.Ea=new Va((g.Y=new Ua(h)).buffer):g.Ea.fill(0);Eb(g,t,!0)}},[c]);D((g,h,t)=>{e.ja=t;e.Ma=Ea(1,g);e.Na=Ea(1,h);h=e.g.V;g=Ca(e.Ma*e.ja/h);h=Ca(e.Na*e.ja/h);if(g!==e.ua||h!==e.va)e.ua=g,e.va=h,e.B&&(e.B.T=!0,Yb(e.B))},[d.offsetWidth,
d.offsetHeight,sa.devicePixelRatio||1,c.V]);D(()=>{p||e.world.A||0!==e.l||(e.l=1);e.world.A=!p},[p]);D(g=>p&&g&&ta.exitPointerLock(),[e.world.A||0!==e.l]);D(()=>{if(e.world){if(e.$&&!e.world.A){var g=e.j,h=O(5,.01*(m-e.$));g.aa-=.1*g.aa*h;g.ba-=.1*g.ba*h;g.ca-=.1*g.ca*h;g.aa+=(Fa(g.O)*g.Qa+Ga(g.O)*g.Ra)*h;g.ba+=g.bb*h;g.ca+=(-Ga(g.O)*g.Qa+Fa(g.O)*g.Ra)*h;sb(g,g.lb*h,g.mb*h);g.H+=g.aa*h;g.J+=g.ba*h;g.K+=g.ca*h}if(e.B){g=e.B;++g.Xa;h=g.Sa;var t=g.cb;const ba=g.o,ua=ba.g,bb=ba.pa,y=ba.j,U=ba.ua,Z=ba.va,
I=ba.world;if(!I.A||g.T){g.T=!1;const ka=t.data,Dc=ua.da;var w=y.O,v=y.ea;const Ec=y.fa,Fc=y.ga;var n=y.H,u=y.J,q=y.K;const Gc=bb?y.X:-1,Hc=I.Y;var k=I.L;const Ic=ua.ia&&null!==Vb;var x=1/U,B=1/Z;const la=U>>1,ma=Z>>1,Hb=O(U,Z),Ib=32<Hb,Jb=Fa(w);w=Ga(w);const Kb=Fa(-v);v=Ga(-v);var C=ua.za/45;const Jc=x*(U<Z?C*U*B:C);x=B*(Z<U?C*Z*x:C);n+=65536;u+=65536;q+=65536;B=n%1;C=u%1;const Kc=q%1;k=4+k;const Lb=(1<<k)-1;let Mb=1===y.u?6:4,ca=y.fa=y.ga=y.Da=0;y.X=-1;for(let Ia=0;Ia<Z;++Ia){var z=(ma-Ia)*x;const Nb=
z*Kb-v;var V=z*v+Kb;z=V*w;V*=Jb;for(let Ja=0;Ja<U;++Ja){var R=(Ja-la)*Jc;const Ob=z+Jb*R;R=V-w*R;let va=16757124,Ka=1,Pb=Dc;for(let G=0;3>G;++G){let M=R;0===G&&(M=Ob);1===G&&(M=Nb);var W=1/(0>M?-M:M);const La=Ob*W,da=Nb*W;W*=R;const Qb=Ha(La*La+da*da+W*W);var K=Kc;0===G&&(K=B);1===G&&(K=C);0<M&&(K=1-K);let wa=n+La*K-(0===G&0>M|0),xa=u+da*K-(1===G&0>M|0),ya=q+W*K-(2===G&0>M|0);K*=Qb;for(let cb,db,eb,N;K<Pb;wa+=La,xa+=da,ya+=W,K+=Qb)if(65536>xa){if(0>da)break}else if(65600<=xa){if(0<da)break}else if(0!==
(N=Hc[((cb=wa&Lb)<<k|(eb=ya&Lb))<<6|(db=xa&63)])){Ia===ma&&Ja===la&&K<=Mb&&(y.fa=cb,y.X=db,y.ga=eb,y.Da=0>M|G<<1,Mb=K);if(Ic){--N;1===G?6===N?N=25:13===N?N=4:1===N&&0<da&&(N=2):1===N&&(N=24);const Rb=Vb[N<<8|(16*(1===G?ya:xa)&15)<<4|16*(1===G?wa:(0<M?wa-ya:ya-wa)+65536)&15];if(0===Rb>>>24)continue;va=Rb&16777215}else va=mb[N];Pb=K;Ka=(0===G?.8:2===G?.6:0<M?.4:1)+(db!==Gc||cb!==Ec||eb!==Fc?0:.2);break}}ka[ca]=(va&255)*Ka;ka[++ca]=(va>>8&255)*Ka;ka[++ca]=(va>>16)*Ka;ca+=2}}bb&&!Ib&&(ka[ca=U*ma+la<<
2]+=128,ka[++ca]+=128,ka[++ca]+=128);h.putImageData(t,0,0);bb&&Ib&&(t=Ca(.05*Hb),h.fillRect(la-t,ma-1,t<<1,2),h.fillRect(la-1,ma-t,2,t-1),h.fillRect(la-1,ma+1,2,t-1))}g.hb=ba.Ha?"Minicraft 0.9.7 "+L(g.ib).toString().padStart(2,"\u00a0")+" fps, T: "+L(24*I.Oa).toString().padStart(2,"0")+":"+L(24*I.Oa%1*60).toString().padStart(2,"0")+"; "+(I.A&&500>m%1E3?"":I.time)+"\nR: "+U+"x"+Z+" (x"+ua.V+"), D: "+ua.da+", C: "+I.oa+"/"+I.Ga.length+", M: "+(64*S(1<<4+I.L)>>10)+"k\nE: 0/0 M: "+y.u+"\n\nPosition: "+
y.H.toFixed(2)+" "+y.J.toFixed(2)+" "+y.K.toFixed(2)+"\nAngle: "+(y.O*Ba).toFixed(2)+" "+(y.ea*Ba).toFixed(2)+"\nBlock: "+(0>y.X?0:y.fa+" "+y.X+" "+y.ga+" "+nb[y.Da]+": "+zb(I,y.fa,y.X,y.ga))+"\nChunk abs: "+(L(y.H)>>4)+" "+(L(y.K)>>4)+" "+(L(y.J)>>4)+" rel: "+I.Ia+" "+I.Ka+" "+I.Ja:""}}e.$=m},[m]);oa();return[H("canvas",{R:E(g=>{e.B=Zb(e,g)})}),e.pa&&2!==e.l&&F(uc,{N:e.N,la:m}),e.B&&e.Ha&&H("div[className=diagnostics]",{innerText:e.B.hb}),e.qa&&F(Bc,{o:e,Ya:e.Ya}),e.pa&&3!==e.l&&2!==e.j.u&&F(qc,
{j:e.j,la:m}),3===e.l&&F(sc,{o:e,la:m}),1===e.l&&F(vc,{actions:b,g:c,o:e,Aa:l}),2===e.l&&F(xc,{o:e,N:e.N})]}function Lc({I:a,vb:b,wb:c,xb:d}){A("div",{F:{selected:a===c},onclick:()=>{d(a.id)}});c=`${a.local?"L":"_"}${a.local&&a.remote?a.local>a.remote?">":a.local<a.remote?"<":"=":"_"}${a.remote?"R":"_"}`;b===a.id&&(c=`[${c}]`);return[H("span",{innerText:`${c} ${a.label}`,title:a.account_name?"Nutzer: "+a.account_name:"Nur lokale Welt"}),H("span",{innerText:ib(Math.max(a.local,a.remote))})]}
function Mc({account:a,actions:b,g:c,Aa:d}){A("div[className=menu]");const [f,l,m]=pa(0),p=E(()=>{l(m()+1)}),e=E({value:null}),g=ia(()=>aa(function*(){try{const q=!e.value&&!f,k=yield fetch("/api/minicraft/"+`world?what=${q?"initial":"meta_all"}`);if(!k.ok)throw Error("Verbindungsfehler.");const x=yield k.json();if(!q)return x;if("0.9.7"!==x.version_latest)return location.reload(),null;ea();b.ob(x.account);return x.worlds}catch(q){return alert("Fehler beim Laden der Weltenliste: "+q.message),[]}}()),
[f],null),h=ja(()=>{g&&(e.value=g);const q=[];e.value&&q.push(...e.value.map(k=>({account_name:k.account_name,hash:k.hash,id:k.id,label:k.label,local:0,remote:k.modified,writable:k.writable})));for(const k of c.worlds){const x=q.find(B=>B.id===k.id);if(x){const B=x.local=k.mod_l,C=x.remote,z=k.mod_r;B>z&&C>z&&(confirm('Konflikt! Die Welt "'+k.label+'" wurde sowohl hier als auch woanders ge\u00e4ndert.\nOK: Die vom Server \u00fcbernehmen ('+ib(C)+") | Abbrechen: Die hier hochladen ("+ib(B)+")")?b.W(k.id,
{mod_l:x.local=z}):b.W(k.id,{mod_r:x.remote=z}))}else 1<k.mod_r&&g&&g.length&&(alert('Die Welt "'+k.label+'" wurde auf dem Server nicht gefunden, ist also jetzt eine lokale!'),b.W(k.id,{mod_r:0})),q.push({account_name:"",hash:0,id:k.id,label:k.label,local:k.mod_l,remote:1===k.mod_r?1:0,writable:!0})}return q.sort((k,x)=>Math.max(x.local,x.remote)-Math.max(k.local,k.remote))},[g,c.worlds]),[t,w,v]=pa(c.Ba),n=ja(()=>h.find(q=>q.id===t)||null,[t,h]),u=ja(()=>{let q,k;return null!=(k=null==h?void 0:null==
(q=h.find(x=>0<x.local&&0<x.remote&&x.local!==x.remote))?void 0:q.id)?k:null},[h]);D(()=>{if(null!==u){var q=!1,k=h.find(B=>B.id===u),x=`minicraft.world.${u}:`;if(k.local<k.remote)fetch("/static/minicraft/worlds/"+`${k.hash}.json`).then(B=>B.json()).then(B=>{if(!q){for(const [C,z]of Za(B))Sa(x+C,z);Sa("__margin",Array(4097).join("x"));Ta("__margin");b.W(u,{mod_l:k.remote,mod_r:k.remote})}}).catch(B=>{if(!q)if("QuotaExceededError"===B.name){alert("Der Speicherplatz reicht nicht!");for(const C of Ya(P))C.startsWith(x)&&
Ta(C);b.nb(u)}else alert("Fehler beim Herunterladen der Welt: "+B.message)});else{if(!k.writable){b.W(u,{mod_l:c.worlds.find(z=>z.id===u).mod_r});return}const B=x.length;let C=u;(1===k.remote?fetch("/api/minicraft/world",{method:"POST",headers:{"Content-Type":"application/json"},body:Qa({what:"meta",label:k.label})}).then(z=>{if(!z.ok)throw Error(403===z.status?"Keine Berechtigung. Angemeldet?":"Verbindungsfehler.");return z.json()}).then(z=>{C=z.id}):Promise.resolve()).then(()=>{if(q)throw null;
const z={};for(const V of Ya(P))V.startsWith(x)&&(z[V.substr(B)]=P.getItem(V));return fetch("/api/minicraft/world",{method:"POST",headers:{"Content-Type":"application/json"},body:Qa({what:"data",world:C,data:z})})}).then(z=>{if(!z.ok)throw Error(403===z.status?"Keine Berechtigung. Angemeldet?":"Verbindungsfehler.");return z.json()}).then(z=>{ea();if(C===u)b.W(u,{mod_l:z.modified,mod_r:z.modified});else{const V=`minicraft.world.${C}:`;for(const R of Ya(P))if(R.startsWith(x)){const W=P.getItem(R);Ta(R);
Sa(V+R.substr(B),W)}b.nb(u);b.ab({id:C,label:k.label,mod_l:z.modified,mod_r:z.modified});q||v()!==u||w(C)}q||p();fa()}).catch(z=>{q||(alert("Fehler beim Hochladen der Welt: "+z.message),ea(),b.W(u,{mod_r:0}),fa())})}return()=>{q=!0}}},[u]);return[H("h1[innerText=Welten]"),H("button[innerText=Aktualisieren][style=position:absolute;left:0;top:0;height:2rem][title=Liste neu laden]",{disabled:!g,onclick:p}),H("button[style=position:absolute;right:0;top:0;height:2rem]",{disabled:0<a.rank,innerText:a.rank?
a.label:"Anmelden",onclick:()=>{location.href="/account?redir=minicraft"}}),H("div[className=worlds]",null,[qa(Lc,h,{yb:f,vb:u,wb:n,xb:w})]),H("center",null,[H("button[innerText=\u00d6ffnen]",{disabled:!n||!n.local||n.remote>n.local,onclick:()=>{ea();b.Va({Ba:n.id});d(1);fa()},title:n?n.local?n.remote>n.local?"Die Welt wird noch geladen!":"Ausgew\u00e4hlte Welt betreten":"Die Welt ist noch nicht heruntergeladen!":"Keine Welt ausgew\u00e4hlt!"}),H("button",{disabled:!g||!n||0<n.local&&0<n.remote||
!n.remote&&!a.rank,innerText:n&&!n.local?"Herunterladen":g&&n&&!n.remote?"Hochladen":"\u00dcbertragen",onclick:()=>{n.local?n.remote||b.W(n.id,{mod_r:1}):b.ab({id:n.id,label:n.label,mod_l:1,mod_r:n.remote})},title:g?n?n.local?n.remote?"Die Welt ist schon auf beiden Seiten vorhanden!":a.rank?"Welt auf den Server hochladen":"Nicht angemeldet!":"Welt von Server herunterladen":"Keine Welt ausgew\u00e4hlt!":"Liste wird noch geladen!"})]),H("hr"),H("center",null,[H("button[innerText=Neue Welt]",{onclick:()=>
{const q=prompt("Name der neuen Welt:\n(max. 16 Zeichen)","Neue Welt");q&&(16<q.length?alert("Der Name ist zu lang!"):b.ab({id:Math.min(0,...c.worlds.map(k=>k.id))-1,label:q,mod_l:Date.now(),mod_r:0}))}}),H("button[innerText=Projektseite]",{onclick:()=>{open("//github.com/L3P3/minicraft")}})]),H("center",null,[H("small[innerText=Version 0.9.7 von L3P3]")])]}
function Nc({account:a,actions:b,g:c,$a:d}){const [f,l]=pa(0),m=A("div[className=game]");return[0===f&&F(Mc,{account:a,actions:b,g:c,Aa:l}),1===f&&F(Cc,{account:a,actions:b,g:c,frame:m,$a:d,Aa:l})]}
r.init(()=>{const [a,b]=na(jb),c=E({o:null});D(()=>{let f=!1;onbeforeunload=onunload=onpagehide=onblur=()=>{f||(f=!0,c.o&&dc(c.o),b.Ta())};onpageshow=onfocus=()=>{f=!1};setInterval(()=>{b.Ta()},500)});const d=E(f=>{if("INPUT"===f.target.tagName||!c.o)return!0;c.o.qa=!1;X(c.o,f.keyCode,"keydown"===f.type);f.preventDefault();return!1});return[{onkeydown:d,onkeyup:d,oncontextmenu:hb,ondragstart:hb},[F(Nc,{account:a.account,actions:b,g:a.g,$a:c})]]});
