const v=lui,aa=v.hook_callback,B=v.hook_dom,C=v.hook_effect,ba=v.hook_memo,ca=v.hook_reducer,da=v.hook_rerender,H=v.hook_static,ia=v.node,I=v.node_dom,ja=v.node_map,ka=v.now,la=[0,8487297,4305266,4349313,8092539,5342114,7039851,3561583,4172910,6384533,15526888,10671324,8092798,16447200,4151672,1970708,8092539,9686227,9126695,15198183,5567485,14541182,7920469,662956,14936813],ma=la.length,sa="WEBTSN".split(""),ta=window,ua=document,J=Math,L=J.PI,va=.5*L,wa=180/L,N=J.floor,Ba=J.ceil,Ca=J.round,Da=J.min,
X=J.max,Ea=J.cos,Fa=J.sin,Ga=J.sqrt,Ha=String.fromCharCode,Ia=JSON,Y=localStorage,Ja=Uint8Array,Ka=Uint32Array,La=Map,Ma=setTimeout,Na=setInterval,Oa=clearInterval,Pa=()=>!1,Qa=[()=>{const a={P:!0,$:3,M:10,ca:80,N:64};var c=Y.getItem("minicraft.config");if(c){c=Ia.parse(c);let f=c.flag_textures;null!=f&&(a.P=f);null!=(f=c.mouse_sensitivity)&&(a.$=f);a.M=c.resolution_scaling;a.ca=c.view_angle;a.N=c.view_distance}return{l:a}},a=>{const c=a.l;Y.setItem("minicraft.config",Ia.stringify({version:"0.5.0",
flag_textures:c.P,mouse_sensitivity:c.$,resolution_scaling:c.M,view_angle:c.ca,view_distance:c.N}));return a},(a,c)=>Object.assign({},a,{l:Object.assign({},a.l,c)})],Ra=a=>{a+=32;33<a&&39>a?a++:38<a&&44>a?a+=2:43<a&&127>a?a+=3:126<a&&55258>a?a+=37:55295<a&&(a+=8485);return Ha(a)},Sa=a=>a-(63743<a?8517:159<a?69:46<a&&130>a?35:40<a&&46>a?34:34<a&&40>a?33:32),Ua=()=>{var a=Ta;const c=a.length,f=new La,b=u=>{p=p<<1|u&1;15===++m&&(h+=Ra(p),p=m=0)},g=()=>{for(let u=0;u<k;++u)b(0)},n=u=>{b(u);b(u>>1);b(u>>
2);b(u>>3);b(u>>4);b(u>>5);b(u>>6);b(u>>7)},l=()=>{0===--t&&(t=1<<k++)},e=()=>{if(x)x=!1;else{let u=r.id;for(let F=0;F<k;F++)b(u>>F)}};let d=a[0],h="",p=0,m=2,k=2,t=2,w=2,r={id:w++,ga:new La},x=!0;n(d);f.set(d,r);for(let u=1;u<c;++u){const F=r.ga.get(d=a[u]);F?r=F:(e(),f.has(d)||(l(),g(),n(d),f.set(d,{id:w++,ga:new La}),x=!0),r.ga.set(d,{id:w++,ga:new La}),r=f.get(d),l())}e();f.has(d)||(l(),g(),n(d));l();b(1);--k;g();return h+=Ra(p<<15-m)},Va=a=>{var c=Ta;if(!a)return null;const f=a.length,b=()=>
{m+=(w>>--r&1)<<k++;0===r&&(r=15,w=Sa(a.charCodeAt(t++)))};let g=[0,1],n=1,l=3,e=2,d=null;var h=null;let p=0,m=0;h=2;let k=0,t=0,w=Sa(a.charCodeAt(t++)),r=15;for(;k<h;)b();if(1===m)return null;for(m=k=0;8>k;)b();d=[m];g[2]=d;for(c[p++]=m;t<=f;){h=e;for(m=k=0;k<h;)b();if(0===m){for(m=k=0;8>k;)b();g[l]=[m];m=l++;0===--n&&(n=1<<e++)}else if(1===m)return c;h=m<g.length?g[m]:d.concat(d[0]);for(let x=0;x<h.length;x++)c[p++]=h[x];g[l++]=d.concat(h[0]);d=h;0===--n&&(n=1<<e++)}return null},Z=new Ka(1024),
Ta=new Ja(Z.buffer),Wa=new La,hb=(a,c,f,b,g)=>{const n=a.o;a.X[(c<<n+4|b)<<6|f]=g;a.G[(c>>4<<n|b>>4)<<2|f>>4].H=!0},kb=(a,c,f)=>{const b=X(Da(c.K,63),0)>>4,g=N(c.J)>>4;c=N(c.L)>>4;if(f||a.la!==b||a.aa+a.ka!==g||a.ba+a.ma!==c)f=1<<a.o,a.la=b,a.aa=g-(a.ka=(65536+g)%f),a.ba=c-(a.ma=(65536+c)%f),ib(a);jb(a)},ib=a=>{const c=a.ka,f=a.la,b=a.ma,g=a.o,n=`${g} ${c} ${b} ${f}`;let l=Wa.get(n);if(null==l){const e=1<<g;Wa.set(n,l=a.G.map(({x:d,y:h,z:p},m)=>{var k=d-c;k*=k;var t=p-b;t*=t;var w=d-c-e;let r=w*w,
x=w=0;r<k&&(k=r,w=-e);d=d-c+e;(r=d*d)<k&&(k=r,w=e);d=p-b-e;(r=d*d)<t&&(t=r,x=-e);p=p-b+e;(r=p*p)<t&&(t=r,x=e);h-=f;return{Ga:k+t+h*h,Ea:m,aa:w,ba:x}}).sort((d,h)=>d.Ga-h.Ga))}a.ha=l;a.Y=0},lb=(a,c,f,b)=>`minicraft.world.${a.id}:${c}/${f}`+(0<b?"/"+b:""),mb=(a,c)=>{const f=a.sa;var b=a.o;const g=c.y,n=(256<<b)-256;for(let l=0,e=-1,d=((c.x<<b+4|c.z)<<6|g)<<2;16>l;++l){for(b=0;16>b;++b)Z[++e]=f[d],Z[++e]=f[++d],Z[++e]=f[++d],Z[++e]=f[++d],d+=13;d+=n}Y.setItem(lb(a,c.da,c.pa,g),Ua());c.H=!1},jb=a=>{var c=
a.G,f=a.ha,b=a.aa;const g=a.ba,n=f.length;for(;a.Y<n;){var l=f[a.Y++];const k=c[l.Ea];var e=k.loaded,d=k.x,h=k.y,p=k.z;const t=b+l.aa+d;l=g+l.ba+p;if(!e||t!==k.da||l!==k.pa){k.H&&mb(a,k);k.loaded=!0;var m=Va(Y.getItem(lb(a,k.da=t,k.pa=l,h)));if(e||0===h||m){c=a.sa;b=a.o;f=(256<<b)-256;d=((d<<b+4|p)<<6|h)<<2;if(m)for(let w=0,r=-1;16>w;++w){for(e=0;16>e;++e)c[d]=Z[++r],c[++d]=Z[++r],c[++d]=Z[++r],c[++d]=Z[++r],d+=13;d+=f}else for(p=0;16>p;++p){for(m=0;16>m;++m)c[d]=0<h?0:50397446,c[++d]=0<h?0:131843,
e?(c[++d]=0,c[++d]=0,d+=13):d+=15;d+=f}if(0===(t|l|h)){for(h=1;h<ma;++h)hb(a,h%9,7,N(h/9),h);k.H=!1}break}}}};let nb=null,ob=new Image;ob.crossOrigin="anonymous";ob.onload=()=>{var a=ua.createElement("canvas");a.width=256;a.height=26;a=a.getContext("2d");a.drawImage(ob,0,0);ob=null;nb=new Ka(a.getImageData(0,0,256,26).data.buffer)};ob.src=ASSETS+"blocks.png";
const qb=(a,c)=>{const f={ua:c,ta:null,Da:null,Fa:"",O:!1,Ha:0,wa:0,Oa:Na(()=>(f.Ha=f.wa,f.wa=0),1E3),i:a};pb(f);return f},pb=a=>{var c=a.ua.width=a.i.na,f=a.ua.height=a.i.oa;c=(a.Da=(a.ta=a.ua.getContext("2d")).createImageData(c,f)).data;a.ta.fillStyle="rgba(255,255,255,.5)";a=c.length;for(f=3;f<a;f+=4)c[f]=255};let rb=0;
const sb=()=>{const a={X:null,sa:null,G:null,ha:null,Y:0,ka:0,la:0,ma:0,id:0,aa:0,ba:0,o:0,Ka:.5,La:8.5,Ma:.5};return{l:null,ia:!1,h:!0,ja:!1,Ia:null,xa:0,Z:new Set,ya:"",j:0,T:[],g:{qa:0,Ca:0,ra:0,v:0,ea:0,fa:0,A:0,u:-1,B:0,Ja:9,J:a.Ka,K:a.La,L:a.Ma,U:0,V:0,W:0},m:null,za:1,Aa:1,na:0,oa:0,Na:null,time:0,Ba:0,s:a}},tb=(a,c)=>{a.m=qb(a,c);a.Na=Na(()=>{a.h||(a.time=(a.time+1)%24E3,a.Ba=1/24E3*(a.time+6E3)%1,kb(a.s,a.g,!1))},50)},ub=a=>{var c=a.g,f=(a=a.Z).has(-12)||a.has(65);a=a.has(-13)||a.has(68);
c.qa=f===a?0:.1-.2*f},vb=a=>{var c=a.g,f=(a=a.Z).has(-15)||a.has(16);a=a.has(-14)||a.has(32);c.Ca=f===a?0:.1-.2*f},wb=a=>{var c=a.g,f=(a=a.Z).has(-11)||a.has(83);a=a.has(-10)||a.has(87);c.ra=f===a?0:.1-.2*f},xb=(a,c,f)=>{const b=a.Z;if(f){if(b.has(c))return!1;b.add(c);switch(c){case -1:0<=a.g.u&&hb(a.s,a.g.A,a.g.u,a.g.B,0);break;case -2:case 71:0<=a.g.u&&(c=a.s,f=a.g.u,a.g.Ja=0>f||63<f?0:c.X[(a.g.A<<c.o+4|a.g.B)<<6|f]);break;case -3:if(0<=a.g.u){c=a.g.A;f=a.g.u;var g=a.g.B;switch(a.g.fa){case 0:--c;
break;case 1:++c;break;case 2:--f;break;case 3:++f;break;case 4:--g;break;default:++g}0<=f&&64>f&&hb(a.s,c&(1<<4+a.s.o)-1,f,g&(1<<4+a.s.o)-1,a.g.Ja)}break;case 27:a.j?(a.h=!1,a.j=0):(a.h=!0,a.j=1);break;case -15:case -14:case 16:case 32:vb(a);break;case -12:case -13:case 65:case 68:ub(a);break;case 80:a.h=!a.h;break;case -11:case -10:case 83:case 87:wb(a);break;case 84:if(!a.j){a.j=2;for(g of b)xb(a,g,!1)}break;case 114:a.ia=!a.ia;break;default:return!1}}else{if(!b.delete(c))return!1;switch(c){case -15:case -14:case 16:case 32:vb(a);
break;case -12:case -13:case 65:case 68:ub(a);break;case -11:case -10:case 83:case 87:wb(a)}}a.ya=[...b].join();return!0},yb=(a,c)=>{a.T=[...a.T.slice(-30),{id:++rb,time:ka(),value:c}]};
function zb({l:a,va:c,i:f}){B("div[className=menu]");return[I("h1[innerText=Men\u00fc]"),I("div[className=settings]",null,[I("button",{innerText:"Oberfl\u00e4chen: "+(a.P?"Texturiert":"Einfarbig"),onclick:aa(b=>{c(2,{P:!b})},[a.P])}),I("label[innerText=Aufl\u00f6sung:]",null,[I("input[type=range][min=1][max=100][step=1]",{value:101-a.M,onchange:H(b=>c(2,{M:101-Number(b.target.value)}))})]),I("label[innerText=Blickwinkel:]",null,[I("input[type=range][min=1][max=180][step=1]",{value:a.ca,onchange:H(b=>
c(2,{ca:Number(b.target.value)}))})]),I("label[innerText=Sichtweite:]",null,[I("input[type=range][min=1][max=128][step=1]",{value:a.N,onchange:H(b=>c(2,{N:Number(b.target.value)}))})]),I("label[innerText=Mausempfindlichkeit:]",null,[I("input[type=range][min=1][max=15][step=1]",{value:a.$,onchange:H(b=>c(2,{$:Number(b.target.value)}))})])]),I("center",null,[I("button[innerText=Zur\u00fcck]",{onclick:H(b=>(f.j=0,"mouse"===b.pointerType?f.Ia.requestPointerLock():f.h=!1))})])]}
const Ab=({I:{value:a}})=>(B("div",{innerText:a}),null);
function Bb({i:a,T:c}){B("div[className=menu terminal]");const f=H({history:null});C(b=>{b&&Ma(()=>f.history.scrollTop=1E9,0)},[c.length&&c[c.length-1].id]);return[I("div[className=history]",{R:H(b=>{f.history=b})},[ja(Ab,c)]),I("input[enterkeyhint=send][mozactionhint=send][name=message][required]",H({onkeydown:b=>{var g=b.keyCode;b=b.target;if(13===g){if(g=b.value)if("/"===g.charAt(0))switch(g=g.substr(1).split(" ").shift(),g){case "clear":a.T=[];break;case "exit":a.h=!1;a.j=0;break;case "help":yb(a,
"commands: clear, exit, help, spawn, version, /regen");break;case "spawn":a.g.J=a.s.Ka;a.g.K=a.s.La;a.g.L=a.s.Ma;a.m.O=!0;break;case "version":yb(a,"Minicraft 0.5.0");break;case "/regen":g=a.s;const n=g.G[g.ha[g.Y=0].Ea];Y.removeItem(lb(g,n.da,n.pa,n.y));n.H=!1;++n.da;jb(g);yb(a,"regenerate chunk");a.m.O=!0;break;default:yb(a,"unknown command: "+g)}else yb(a,"<me> "+g);b.value=""}else 27===g&&(a.h=!1,a.j=0)},R:b=>Ma(()=>b.focus(),0)}))]}
const Cb=[["place",-3],["pick",-2],["up",-14],["down",-15],["R",82],["T",84],["F3",114],["...",27]],Db=[["up",-10],["down",-11],["left",-12],["right",-13],["center",-1]];
function Eb({i:a}){const c=a.Z;B("div[className=touch]",H({ontouchstart:f=>{f.preventDefault();const b=Number(f.target.dataset.code);if(null!=b&&xb(a,b,!0)){const g=f.changedTouches[0].identifier,n=l=>{l.changedTouches[0].identifier===g&&(removeEventListener("touchend",n),xb(a,b,!1))};addEventListener("touchend",n)}}}));return[I("div[className=top]",null,Cb.map(([f,b])=>I(`div[innerText=${f}]`,{D:{code:b},F:{button:!0,active:c.has(b)}}))),I("div[className=move]",null,Db.map(([f,b])=>I("div",{D:{code:b},
F:{button:!0,[f]:!0,active:c.has(b)}})))]}
function Fb({l:a,va:c,Pa:f}){const b=ba(sb),g=B("div[className=game]",ba(()=>{const l=e=>0!==b.j||(b.ja=!1,ua.pointerLockElement===g?b.h||xb(b,-1-e.button,"mousedown"===e.type):b.Ia.requestPointerLock(),e.preventDefault(),!1);return{onmousedown:l,onmousemove:e=>{if(!b.h&&!b.j){const d=b.l.$*L/X(b.za,b.Aa);b.g.v=(b.g.v+e.movementX*d+100*L)%(2*L);b.g.ea=X(-va,Da(va,b.g.ea-e.movementY*d))}},onmouseup:l,ontouchstart:e=>{b.ja=!0;b.j||(b.h=!1,e.preventDefault())}}})),n=ua.pointerLockElement===g;C(()=>(b.Ia=
g,f.i=b,()=>{Oa(b.Na);Oa(b.m.Oa);return f.i=null}));C(()=>{b.l=a;b.m&&(b.m.O=!0);const l=b.g,e=b.s;var d=b.l.N;d=17>d?2:49>d?3:113>d?4:241>d?5:497>d?6:1009>d?7:2033>d?8:4081>d?9:8177>d?10:16369>d?11:32753>d?12:13;if(e.o!==d){if(e.G)for(var h of e.G)h.H&&mb(e,h);h=1<<(e.o=d);const p=e.G=[];for(let m=0;m<h;++m)for(let k=0;k<h;++k)for(let t=0;4>t;++t)p.push({H:!1,loaded:!1,x:m,y:t,z:k,da:0,pa:0});e.X=new Ja((e.sa=new Ka(h<<d+12+2-2)).buffer);kb(e,l,!0)}},[a]);C((l,e,d)=>{b.za=X(1,l*d);b.Aa=X(1,e*d);
e=b.l.M;l=X(1,Ca(b.za/e));e=X(1,Ca(b.Aa/e));if(l!==b.na||e!==b.oa)b.na=l,b.oa=e,b.m&&(b.m.O=!0,pb(b.m))},[g.offsetWidth,g.offsetHeight,ta.devicePixelRatio||1,a.M]);C(()=>{n||b.h||b.j||(b.j=1);b.h=!n},[n]);C(l=>n&&l&&ua.exitPointerLock(),[b.h||b.j]);C(l=>{if(b.xa&&!b.h){var e=b.g,d=Da(5,.01*(l-b.xa));e.U-=.1*e.U*d;e.V-=.1*e.V*d;e.W-=.1*e.W*d;e.U+=(Ea(e.v)*e.qa+Fa(e.v)*e.ra)*d;e.V+=e.Ca*d;e.W+=(-Fa(e.v)*e.qa+Ea(e.v)*e.ra)*d;e.J+=e.U*d;e.K+=e.V*d;e.L+=e.W*d}if(b.m){e=b.m;++e.wa;var h=e.ta,p=e.Da;d=e.i;
const ea=d.l,q=d.g,K=d.na,M=d.oa,G=d.s;if(!d.h||e.O){e.O=!1;const R=p.data,Gb=ea.N;var m=q.v,k=q.ea;const Hb=q.A,Ib=q.u,Jb=q.B;var t=q.J,w=q.K,r=q.L;const Kb=G.X;var x=G.o;const Lb=ea.P&&null!==nb;var u=1/K,F=1/M,z=K>>1;const S=M>>1,Xa=Da(K,M),Ya=32<Xa,Za=Ea(m);m=Fa(m);const $a=Ea(-k);k=Fa(-k);var T=ea.ca/45;const Mb=u*(K<M?T*K*F:T);u=F*(M<K?T*M*u:T);t+=65536;w+=65536;r+=65536;F=t%1;T=w%1;const Nb=r%1;x=4+x;const ab=(1<<x)-1;let bb=5,O=q.A=q.B=q.fa=0;q.u=-1;for(let na=0;na<M;++na){var oa=(S-na)*u;
const cb=oa*$a-k;var xa=oa*k+$a;oa=xa*m;xa*=Za;for(let pa=0;pa<K;++pa){var fa=(pa-z)*Mb;const db=oa+Za*fa;fa=xa-m*fa;let ha=16757124,qa=1,eb=Gb;for(let y=0;3>y;++y){let D=fa;0===y&&(D=db);1===y&&(D=cb);var P=1/(0>D?-D:D);const ra=db*P,Q=cb*P;P*=fa;const fb=Ga(ra*ra+Q*Q+P*P);var A=Nb;0===y&&(A=F);1===y&&(A=T);0<D&&(A=1-A);let U=t+ra*A,V=w+Q*A,W=r+P*A;A*=fb;0===y&&(U+=.5-(0>D|0));1===y&&(V+=.5-(0>D|0));2===y&&(W+=.5-(0>D|0));for(let ya,za,Aa,E;A<eb;U+=ra,V+=Q,W+=P,A+=fb)if(65536>V){if(0>Q)break}else if(65600<=
V){if(0<Q)break}else if(0!==(E=Kb[((ya=U&ab)<<x|(Aa=W&ab))<<6|(za=V&63)])){na===S&&pa===z&&A<=bb&&(q.A=ya,q.u=za,q.B=Aa,q.fa=0>D|y<<1,bb=A);if(Lb){--E;1===y?6===E?E=25:13===E?E=4:1===E&&0<Q&&(E=2):1===E&&(E=24);const gb=nb[E<<8|(16*(1===y?W:V)&15)<<4|16*(1===y?U:(0<D?U-W:W-U)+65536.5)&15];if(0===gb>>>24)continue;ha=gb&16777215}else ha=la[E];eb=A;qa=(0===y?.8:2===y?.6:0<D?.4:1)+(za!==Ib||ya!==Hb||Aa!==Jb?0:.2);break}}R[O]=(ha&255)*qa;R[++O]=(ha>>8&255)*qa;R[++O]=(ha>>16)*qa;O+=2}}Ya||(R[O=K*S+z<<2]+=
128,R[++O]+=128,R[++O]+=128);h.putImageData(p,0,0);Ya&&(p=Ba(.05*Xa),h.fillRect(z-p,S-1,p<<1,2),h.fillRect(z-1,S-p,2,p-1),h.fillRect(z-1,S+1,2,p-1))}d.ia?(h=1<<4+G.o,0>q.u?z=0:(z=q.u,z=q.A+" "+q.u+" "+q.B+" "+sa[q.fa]+": "+(0>z||63<z?0:G.X[(q.A<<G.o+4|q.B)<<6|z])),d="Minicraft 0.5.0 "+N(e.Ha).toString().padStart(2,"\u00a0")+" fps, T: "+N(24*d.Ba).toString().padStart(2,"0")+":"+N(24*d.Ba%1*60).toString().padStart(2,"0")+"; "+(d.h&&500>l%1E3?"":d.time)+"\nR: "+K+"x"+M+" (x"+ea.M+"), D: "+ea.N+", C: "+
G.Y+"/"+G.ha.length+", M: "+(h*h*64>>10)+"k\nE: 0/0\n\nPosition: "+q.J.toFixed(2)+" "+q.K.toFixed(2)+" "+q.L.toFixed(2)+"\nAngle: "+(q.v*wa).toFixed(2)+" "+(q.ea*wa).toFixed(2)+"\nBlock: "+z+"\nChunk abs: "+(N(q.J)>>4)+" "+(N(q.L)>>4)+" "+(N(q.K)>>4)+" rel: "+G.ka+" "+G.ma+" "+G.la):d="";e.Fa=d}b.xa=l},[ka()]);da();return[I("canvas",{R:H(l=>tb(b,l))}),b.m&&b.ia&&I("div[className=diagnostics]",{innerText:b.m.Fa}),b.ja&&ia(Eb,{i:b,ya:b.ya}),1===b.j&&ia(zb,{l:a,va:c,i:b}),2===b.j&&ia(Bb,{i:b,T:b.T})]}
v.init(()=>{const [a,c]=ca(Qa),f=H({i:null});C(()=>{onbeforeunload=()=>{c(1);if(f.i){var g=f.i.s;for(const n of g.G)n.H&&mb(g,n)}}});const b=H(g=>"INPUT"===g.target.tagName||!f.i||(g.preventDefault(),xb(f.i,g.keyCode,"keydown"===g.type),f.i.ja=!1));return[{onkeydown:b,onkeyup:b,oncontextmenu:Pa,ondragstart:Pa},[ia(Fb,{l:a.l,va:c,Pa:f})]]});
