const l=lui,ba=l.hook_dom,p=l.hook_effect,ca=l.hook_memo,da=l.hook_reducer,ea=l.hook_rerender,t=l.hook_static,fa=l.node,u=l.node_dom,ha=l.now,A=Math,H=A.PI,ia=180/H,I=A.floor,ja=A.round,ka=A.min,J=A.max,Q=A.cos,R=A.sin,ya=JSON,za=localStorage,Aa=()=>!1,Ba=[()=>{const a={A:10,L:80,H:64};var c=za.getItem("minicraft.config");c&&(c=ya.parse(c),a.A=c.resolution_scaling,a.L=c.view_angle,a.H=c.view_distance);return{h:a}},a=>{const c=a.h;za.setItem("minicraft.config",ya.stringify({version:"0.1.13",resolution_scaling:c.A,
view_angle:c.L,view_distance:c.H}));return a},(a,c)=>Object.assign({},a,{h:Object.assign({},a.h,c)})];
function Ca({h:a,$:c,m:d}){ba("div[className=menu]");return[u("h1[innerText=Men\u00fc]"),u("div[className=settings]",null,[u("label[innerText=Aufl\u00f6sung:]",null,[u("input[type=range][min=1][max=100][step=1]",{value:101-a.A,onchange:t(h=>c(2,{A:101-Number(h.target.value)}))})]),u("label[innerText=Blickwinkel:]",null,[u("input[type=range][min=1][max=180][step=1]",{value:a.L,onchange:t(h=>c(2,{L:Number(h.target.value)}))})]),u("label[innerText=Sichtweite:]",null,[u("input[type=range][min=1][max=128][step=1]",
{value:a.H,onchange:t(h=>c(2,{H:Number(h.target.value)}))})])]),u("div",null,[u("button[innerText=Zur\u00fcck]",{onclick:t(()=>{d.l=d.T=!1})})])]}
const Da=[0,7960953,8370002,7885881,8553090,9927501,4539717,6311215,3113506,12094592,14145495],Ea="WEBTSN".split(""),Ga=()=>{const a={v:Fa(),oa:8,pa:32,qa:8};for(let c=0;16>c;c+=2)a.v[1024+(c<<4)]=3,a.v[1024+c]=3;["X   XXX XXX XXX","X     X X X   X","X   XXX XXX XXX","X     X X     X","XXX XXX X   XXX"].forEach((c,d,h)=>{d=h.length-d;c.split("").forEach((e,k)=>{"X"===e&&(a.v[1024+(k+1<<4)+d]=6)})});return a},Fa=()=>{const a=new Uint8Array(16384),c=[6,3,3,3,2];for(let d=-1,h=0;h<c.length;++h){const e=
c[h];for(let k=0;16>k;++k)for(let b=0;16>b;++b)a[++d]=e}return a},Ia=(a,c)=>{const d={canvas:c,ga:null,ha:null,ia:"",P:!1,ja:0,aa:0,la:setInterval(()=>{d.ja=d.aa;d.aa=0},1E3),m:a};Ha(d);return d},Ha=a=>{var c=a.canvas.width=a.m.X,d=a.canvas.height=a.m.Y;a=(a.ha=(a.ga=a.canvas.getContext("2d")).createImageData(c,d)).data;c=a.length;for(d=3;d<c;d+=4)a[d]=255},Ja=()=>({h:null,O:!1,T:!1,l:!1,ba:0,g:{J:0,M:0,K:0,U:0,V:10,W:0,B:0,D:0,G:0,o:0,Z:0,s:0,j:-1,u:0,N:0},i:null,ca:1,da:1,X:0,Y:0,ka:null,time:0,
ea:0,fa:Ga()}),La=(a,c)=>{onmousemove=d=>{a.l||(a.g.o=2*(d.clientX/a.ca-.5)*H,a.g.Z=(.5-d.clientY/a.da)*H)};onmousedown=onmouseup=d=>a.l||(Ka(a,-1-d.button,"mousedown"===d.type),d.preventDefault(),!1);a.i=Ia(a,c);a.ka=setInterval(()=>{a.l||(a.time=(a.time+1)%24E3,a.ea=1/24E3*(a.time+6E3)%1)},50)},Ka=(a,c,d)=>{if(d)switch(c){case -1:0<=a.g.j&&(a.fa.v[(a.g.j<<8)+(a.g.s<<4)+a.g.u]=0);break;case -3:if(0<=a.g.j){c=a.g.s;d=a.g.j;let h=a.g.u;switch(a.g.N){case 0:--c;break;case 1:++c;break;case 2:--d;break;
case 3:++d;break;case 4:--h;break;default:++h}0<=d&&64>d&&(a.fa.v[(d<<8)+((c&15)<<4)+(h&15)]=9)}break;case 27:a.l=a.T=!a.T;break;case 16:a.g.M=-.1;break;case 32:a.g.M=.1;break;case 65:a.g.J=-.1;break;case 68:a.g.J=.1;break;case 80:a.l=!a.l;break;case 83:a.g.K=-.1;break;case 87:a.g.K=.1;break;case 114:a.O=!a.O;break;default:return!0}else switch(c){case 16:case 32:a.g.M=0;break;case 65:case 68:a.g.J=0;break;case 83:case 87:a.g.K=0;break;default:return!0}return!1};
function Ma({h:a,$:c,ma:d}){const h=ba("div[className=game]"),e=ca(Ja);p(()=>(d.m=e,()=>{onmousemove=onmousedown=onmouseup=null;clearInterval(e.ka);clearInterval(e.i.la);return d.m=null}));p(()=>{e.h=a;e.i&&(e.i.P=!0)},[a]);p((k,b)=>{e.ca=J(1,k);e.da=J(1,b);b=e.h.A;k=J(1,ja(e.ca/b));b=J(1,ja(e.da/b));if(k!==e.X||b!==e.Y)e.X=k,e.Y=b,e.i&&(e.i.P=!0,Ha(e.i))},[h.offsetWidth,h.offsetHeight,a.A]);p(k=>{if(e.ba&&!e.l){var b=e.g,g=ka(5,.01*(k-e.ba));b.B-=.1*b.B*g;b.D-=.1*b.D*g;b.G-=.1*b.G*g;b.B+=(Q(b.o)*
b.J+R(b.o)*b.K)*g;b.D+=b.M*g;b.G+=(-R(b.o)*b.J+Q(b.o)*b.K)*g;b.U+=b.B*g;b.V+=b.D*g;b.W+=b.G*g}if(e.i){b=e.i;++b.aa;var x=b.ha;g=b.m;const K=g.h,f=g.g,r=g.X,v=g.Y;var B=g.fa;if(!g.l||b.P){b.P=!1;const y=x.data,Na=K.H;var C=f.o,D=f.Z;const Oa=f.s,Pa=f.j,Qa=f.u,la=1/r,ma=1/v,S=r>>1,T=v>>1,na=Q(C);C=R(C);const oa=Q(-D);D=R(-D);var z=K.L/45;const Ra=r<v?z*r*ma:z;z=v<r?z*v*la:z;const pa=f.U+1073741824,qa=f.V+1073741824,ra=f.W+1073741824,Sa=pa%1,Ta=qa%1,Ua=ra%1;let w=f.s=f.u=f.N=0;f.j=-1;for(let L=0;L<v;++L){var E=
(T-L)*ma*z;const sa=E*oa-D;E=E*D+oa;for(let M=0;M<r;++M){var F=(M-S)*la*Ra;const ta=E*C+F*na;F=E*na-F*C;let N=8696319,O=1,ua=Na;for(let n=0;3>n;++n){let q=F;0===n&&(q=ta);1===n&&(q=sa);const G=1/(0>q?-q:q),va=ta*G,wa=sa*G,xa=F*G;var m=Ua;0===n&&(m=Sa);1===n&&(m=Ta);0<q&&(m=1-m);let U=pa+va*m,V=qa+wa*m,W=ra+xa*m;m*=G;0===n&&(U+=.5-(0>q|0));1===n&&(V+=.5-(0>q|0));2===n&&(W+=.5-(0>q|0));let X,Y,Z;for(var P;m<ua;){P=X=U&15;var aa=Y=V&1073741823,Va=Z=W&15;if(0===(P=0>aa||64<=aa?0:B.v[(aa<<8)+(P<<4)+Va]))U+=
va,V+=wa,W+=xa,m+=G;else{ua=m;N=Da[P];O=1-(n+2)%3*.2+(Y!==Pa||X!==Oa||Z!==Qa?0:.1);if(L!==T||M!==S||5<m)break;f.s=X;f.j=Y;f.u=Z;f.N=0>q|n<<1;break}}}y[w]=(N>>16&255)*O;y[++w]=(N>>8&255)*O;y[++w]=(N&255)*O;w+=2}}y[w=r*T+S<<2]*=2;y[++w]*=2;y[++w]*=2;b.ga.putImageData(x,0,0)}g.O?(0>f.j?B=0:(x=f.j,B=f.s+" "+f.j+" "+f.u+" "+Ea[f.N]+": "+(0>x||64<=x?0:B.v[(x<<8)+(f.s<<4)+f.u])),g="Minicraft 0.1.13 "+I(b.ja).toString().padStart(2,"\u00a0")+" fps, T: "+I(24*g.ea).toString().padStart(2,"0")+":"+I(24*g.ea%
1*60).toString().padStart(2,"0")+"; "+(g.l&&500>k%1E3?"":g.time)+"\nR: "+r+"x"+v+" (x"+K.A+"), C: 1, D: "+K.H+"\nE: 0/0\n\nPosition: "+f.U.toFixed(2)+" "+f.V.toFixed(2)+" "+f.W.toFixed(2)+"\nAngle: "+(f.o*ia).toFixed(2)+" "+(f.Z*ia).toFixed(2)+"\nBlock: "+B+"\nChunk: 0 0"):g="";b.ia=g}e.ba=k},[ha()]);ea();return[u("canvas",{R:t(k=>La(e,k))}),e.i&&e.O&&u("div[className=diagnostics]",{innerText:e.i.ia}),e.T&&fa(Ca,{h:a,$:c,m:e})]}
l.init(()=>{const [a,c]=da(Ba),d=t({m:null});p(()=>{onbeforeunload=()=>{c(1)}});const h=t(e=>!d.m||Ka(d.m,e.keyCode,"keydown"===e.type)||(e.preventDefault(),!1));return[{onkeydown:h,onkeyup:h,oncontextmenu:Aa,na:Aa},[fa(Ma,{h:a.h,$:c,ma:d})]]});
