#!/bin/env node

import {
	appendFile,
	readdir,
	readFile,
	writeFile,
} from 'fs/promises';
import {exec as child_process_exec} from 'child_process';

import lui_ssr from 'lui-ssr';

const GCC_COMMAND = './node_modules/.bin/google-closure-compiler --';

const prod = !!process.env.CI;
const checks_only = prod && process.env.GITHUB_REF_NAME !== 'master';
const {version} = JSON.parse(
	await readFile('./package.json', 'utf8')
);

let languages = process.argv.includes('css') ? [] : ['en'];
if (prod && !checks_only) {
	const files = await readdir('./locales');
	languages = (
		files
		.filter(name => name.endsWith('.csv'))
		.map(name => name.split('.')[0])
	);
}

const exec = cmd => (
	new Promise(resolve =>
		child_process_exec(
			cmd,
			(...args) => resolve(args)
		)
	)
);

async function file_replace(path, replacements, charset = 'utf8') {
	let content = await readFile(path, charset);
	for (const [from, to] of replacements) content = content.replaceAll(from, to);
	await writeFile(path, content, charset);
}

async function lang_generate(lang) {
	const csv = await readFile(`./locales/${lang}.csv`, 'utf8');
	let output = '// generated by build.js, for changes go to locales directory\n\n';
	for (const line of csv.split('\n')) {
		if (!line) continue;
		const index_colon = line.indexOf(': ');
		const key = line.substring(0, index_colon);
		const value = line.substring(index_colon + 2);
		output += `export const locale_${key} = '${value}';\n`;
	}
	await writeFile(
		'./src/etc/locale.js',
		output,
		'utf8'
	);
}

const env_set = async (version, debug, lang, legacy, api, api_data, ssr) => Promise.all([
	writeFile(
		'./src/etc/env.js',
`export const API = '${api}';
export const API_DATA = '${api_data}';
export const DEBUG = ${debug};
export const LANG = '${lang}';
export const LEGACY = ${legacy};
export const SSR = ${ssr};
export const VERSION = '${version}';
`,
		'utf8'
	),
	lang_generate(lang),
]);

async function build_css() {
	console.log('css...');
	await Bun.build({
		entrypoints: ['./src/app.css'],
		outdir: 'dist',
		minify: true,
		sourcemap: 'linked',
	});
	console.log('css done.');
}

const promises = [];

async function build_js(lang, legacy, ssr) {
	await env_set(
		prod ? version : 'dev',
		false,
		lang,
		legacy,
		prod ? '/api/minicraft/' : '//l3p3.de/api/minicraft/',
		prod ? '/static/minicraft/' : '//l3p3.de/static/minicraft/',
		ssr
	);

	let combo = lang;
	if (legacy) combo += '-legacy';
	if (ssr) combo += '-ssr';
	const tmp_path = `/tmp/app-${combo}.js`;

	console.log(combo + ' js pass 1...');
	const gcc_output = (await exec(
		GCC_COMMAND +
		[
			'assume_function_wrapper',
			'compilation_level ADVANCED',
			'dependency_mode PRUNE',
			'entry_point ./src/app.js',
			'js ./src',
			'js_output_file ' + tmp_path,
			'create_source_map ' + tmp_path + '.map',
			'language_in ECMASCRIPT_NEXT',
			'language_out ECMASCRIPT6_STRICT',
			'module_resolution BROWSER',
			'rewrite_polyfills false',
			'strict_mode_input',
			'use_types_for_optimization',
			'warning_level VERBOSE',
			checks_only ? 'checks_only' : null,
		]
		.filter(Boolean)
		.join(' --')
	))[2].trim();
	if (gcc_output) console.log(gcc_output);
	console.log(combo + ' js pass 1 done.');

	checks_only ||
	promises.push((async () => {
		if (ssr) {
			console.log(combo + ' html...');
			await writeFile(
				`./dist/app-${combo}.html`,
				lui_ssr(
					await readFile(tmp_path, 'ascii')
				)(),
				'utf8'
			);
			console.log(combo + ' html done.');
			return;
		}

		console.log(combo + ' js pass 2...');
		await appendFile(
			tmp_path,
			`\n//# sourceMappingURL=app-${combo}.js.map\n`,
			'ascii'
		);
		const gcc_output = (await exec(
			GCC_COMMAND +
			[
				'assume_function_wrapper',
				'compilation_level SIMPLE',
				'externs ./src/externs.js',
				'js ' + tmp_path,
				`js_output_file ./dist/app-${combo}.js`,
				`create_source_map ./dist/app-${combo}.js.map`,
				'language_in ECMASCRIPT6_STRICT',
				`language_out ECMASCRIPT${legacy ? '3' : '6_STRICT'}`,
				'rewrite_polyfills false',
				'strict_mode_input',
				'warning_level VERBOSE',
			]
			.join(' --')
		))[2].trim();
		if (gcc_output) console.log(gcc_output);
		await Promise.all([
			appendFile(
				`./dist/app-${combo}.js`,
				`\n//# sourceMappingURL=app-${combo}.js.map\n`,
				'ascii'
			),
			file_replace(
				`./dist/app-${combo}.js.map`,
				[
					[ // closure compiler internals
						'/tmp/src/com/google/',
						'//raw.githubusercontent.com/google/closure-compiler/refs/heads/master/src/com/google/'
					],
					[ // all other paths are mine
						'/tmp/', 
						(
							prod
							?	`../minicraft@${process.env.GITHUB_SHA || 'master'}/`
							:	'../'
						),
					],
				]
			),
			exec(`rm ${tmp_path} ${tmp_path}.map`),
		]);
		console.log(combo + ' js pass 2 done.');
	})());
}

if(
	!(
		await exec(GCC_COMMAND + 'version')
	)[1].includes('Version: v')
) {
	throw new Error('google closure compiler required!');
}

await exec('rm ./dist/app*');

console.log(`build ${version} (${prod ? 'production' : 'dev'})...`);

try {
	await file_replace(
		'./src/etc/lui.js',
		[["@type {typeof import('lui/index')}", "@type {Object}"]]
	);
	for (const lang of languages) {
		await build_js(lang, false, false);
		await build_js(lang, true, false);
		await build_js(lang, false, true);
	}
	promises.push(build_css());
	await Promise.all(promises);
}
finally {
	if (!prod) {
		await Promise.all([
			env_set(
				'dev',
				true,
				'en',
				false,
				'//l3p3.de/api/minicraft/',
				'//l3p3.de/static/minicraft/',
				false
			),
			file_replace(
				'./src/etc/lui.js',
				[["@type {Object}", "@type {typeof import('lui/index')}"]]
			),
		]);
	}
}

console.log('done.');
