#!/bin/env node

import {exec as child_process_exec} from 'child_process';
import {
	appendFile,
	readdir,
	readFile,
	watch,
	writeFile,
} from 'fs/promises';
import {setTimeout} from 'node:timers/promises';
import lui_ssr from 'lui-ssr';

const GCC_COMMAND = 'node_modules/.bin/google-closure-compiler --';

const {version} = JSON.parse(
	await readFile('./package.json', 'utf8')
);
const CI = !!process.env.CI;
const checks_only = CI && process.env.GITHUB_REF_NAME !== 'master';
const css_only = process.argv.includes('--css');
const watch_enabled = process.argv.includes('--watch');

let languages = ['en'];
if (CI && !checks_only) {
	const files = await readdir('./locales');
	languages = (
		files
		.filter(name => name.endsWith('.csv'))
		.map(name => name.split('.')[0])
	);
	// make sure english is last so it does not need to be generated again at the end
	if (languages[languages.length - 1] !== 'en') {
		languages = languages.filter(lang => lang !== 'en');
		languages.push('en');
	}
}

const exec = cmd => (
	new Promise((resolve, reject) =>
		child_process_exec(
			cmd,
			(error, stdout, stderr) => {
				if (error) reject(error);
				else if (stderr.trim()) {
					console.error(stderr);
					reject(new Error('error output'));
				}
				else resolve(stdout);
			}
		)
	)
);

async function file_replace(path, replacements, charset = 'utf8') {
	let content = await readFile(path, charset);
	for (const [from, to] of replacements) content = content.replaceAll(from, to);
	await writeFile(path, content, charset);
}

async function lang_generate(lang) {
	const csv = await readFile(`./locales/${lang}.csv`, 'utf8');
	let output = '// generated by build.js, for changes go to locales directory\n\n';
	for (const line of csv.split('\n')) {
		if (!line) continue;
		const index_colon = line.indexOf(': ');
		const key = line.substring(0, index_colon);
		const value = line.substring(index_colon + 2);
		output += `export const locale_${key} = '${value}';\n`;
	}
	await writeFile(
		'./src/etc/locale.js',
		output,
		'utf8'
	);
}

const env_set = async (version, debug, lang, legacy, api, api_data, ssr) => (
	writeFile(
		'./src/etc/env.js',
`export const API = '${api}';
export const API_DATA = '${api_data}';
export const DEBUG = ${debug};
export const LANG = '${lang}';
export const LEGACY = ${legacy};
export const SSR = ${ssr};
export const VERSION = '${version}';
`,
		'utf8'
	)
);

async function build_css() {
	console.log('css...');
	await Bun.build({
		entrypoints: ['./src/app.css'],
		outdir: 'dist',
		minify: true,
		sourcemap: 'linked',
	});
	console.log('css done.');
}

async function build_js(promises_before, lang, legacy, ssr) {
	await env_set(
		CI ? version : 'dev',
		false,
		lang,
		legacy,
		CI ? '/api/minicraft/' : '//l3p3.de/api/minicraft/',
		CI ? '/static/minicraft/' : '//l3p3.de/static/minicraft/',
		ssr
	);
	await promises_before;

	let combo = lang;
	if (legacy) combo += '-legacy';
	if (ssr) combo += '-ssr';
	const tmp_path = `/tmp/app-${combo}.js`;

	console.log(combo + ' js pass 1...');
	await exec(
		GCC_COMMAND +
		[
			'assume_function_wrapper',
			'compilation_level ADVANCED',
			'dependency_mode PRUNE',
			'entry_point ./src/app.js',
			'js ./src',
			'js_output_file ' + tmp_path,
			'create_source_map ' + tmp_path + '.map',
			'language_in ECMASCRIPT_NEXT',
			'language_out ECMASCRIPT6_STRICT',
			'module_resolution BROWSER',
			'rewrite_polyfills false',
			'strict_mode_input',
			'use_types_for_optimization',
			'warning_level VERBOSE',
			checks_only ? 'checks_only' : null,
		]
		.filter(Boolean)
		.join(' --')
	);
	console.log(combo + ' js pass 1 done.');

	if (checks_only) return null;

	return (async () => {
		if (ssr) {
			console.log(combo + ' html...');
			await writeFile(
				`./dist/app-${combo}.html`,
				lui_ssr(
					await readFile(tmp_path, 'ascii')
				)(),
				'utf8'
			);
			console.log(combo + ' html done.');
			return;
		}

		console.log(combo + ' js pass 2...');
		await appendFile(
			tmp_path,
			`\n//# sourceMappingURL=app-${combo}.js.map\n`,
			'ascii'
		);
		await exec(
			GCC_COMMAND +
			[
				'assume_function_wrapper',
				'compilation_level SIMPLE',
				'externs ./src/externs.js',
				'js ' + tmp_path,
				`js_output_file ./dist/app-${combo}.js`,
				`create_source_map ./dist/app-${combo}.js.map`,
				'language_in ECMASCRIPT6_STRICT',
				`language_out ECMASCRIPT${legacy ? '3' : '6_STRICT'}`,
				'rewrite_polyfills false',
				'strict_mode_input',
				'warning_level VERBOSE',
			]
			.join(' --')
		);
		await Promise.all([
			appendFile(
				`./dist/app-${combo}.js`,
				`\n//# sourceMappingURL=app-${combo}.js.map\n`,
				'ascii'
			),
			file_replace(
				`./dist/app-${combo}.js.map`,
				[
					[ // closure compiler internals
						'/tmp/src/com/google/',
						'//raw.githubusercontent.com/google/closure-compiler/refs/heads/master/src/com/google/'
					],
					[ // all other paths are mine
						'/tmp/', 
						(
							CI
							?	`../minicraft@${process.env.GITHUB_SHA || 'master'}/`
							:	'../'
						),
					],
				]
			),
			exec(`rm ${tmp_path} ${tmp_path}.map`),
		]);
		console.log(combo + ' js pass 2 done.');
	})();
}

const gcc_version_output = await exec(GCC_COMMAND + 'version');
if(!gcc_version_output.includes('Version: v202')) {
	console.log('command output: ' + gcc_version_output);
	throw new Error('newer closure compiler version required!');
}

if (!css_only) {
	await exec('mkdir -p ./dist;rm ./dist/app*').catch(() => {});
}

console.log(`build ${version} (${CI ? 'production' : 'dev'})...`);

const watcher = (
	watch_enabled
	?	watch('./src', {recursive: true})[Symbol.asyncIterator]()
	:	null
);

let lang_last = null;
let css_changed = true;
let js_changed = !css_only;

while (true) {
	try {
		const promises_after = [];
		if (js_changed) {
			const promise_lui_replace = file_replace(
				'./src/etc/lui.js',
				[["@type {typeof import('lui/index')}", "@type {Object}"]]
			);
			for (const lang of languages) {
				const promises_before = Promise.all([
					lang_generate(lang),
					promise_lui_replace,
				]);
				lang_last = lang;
				promises_after.push(
					await build_js(promises_before, lang, false, false),
					await build_js(promises_before, lang, true, false),
					await build_js(promises_before, lang, false, true),
				);
			}
		}
		if (css_changed) promises_after.push(build_css());
		await Promise.all(promises_after);
	}
	catch (error) {
		console.error(error);
		process.exitCode = 1;
	}
	finally {
		if (!CI && js_changed) {
			await Promise.all([
				env_set(
					'dev',
					true,
					'en',
					false,
					'//l3p3.de/api/minicraft/',
					'//l3p3.de/static/minicraft/',
					false
				),
				file_replace(
					'./src/etc/lui.js',
					[["@type {Object}", "@type {typeof import('lui/index')}"]]
				),
				lang_last === 'en' ? null : lang_generate('en'),
			]);
		}
	}

	if (!watch_enabled) break;

	css_changed = false;
	js_changed = false;

	// await for any file change in src dir
	let {value: event} = await watcher.next();

	while (event) {
		const path = event.filename;
		if (path.endsWith('.css')) css_changed = true;
		else if (
			!path.endsWith('env.js') &&
			!path.endsWith('locale.js') &&
			!path.endsWith('lui.js')
		) js_changed = true;

		// consume all other events that happened during build
		const result = await Promise.race([
			watcher.next(),
			setTimeout(10, null),
		]);

		if (!result || result.done) break;
		event = result.value;
	}
}

console.log('done.');
