#!/bin/env node

import {
	appendFile,
	readdir,
	readFile,
	writeFile,
} from 'fs/promises';
import {exec as child_process_exec} from 'child_process';

import cssnano from 'cssnano';
import lui_ssr from 'lui-ssr';

const GCC_COMMAND = './node_modules/.bin/google-closure-compiler --';

const prod = !!process.env.CI;
const {version} = JSON.parse(
	await readFile('./package.json', 'utf8')
);

let languages = ['en'];
if (prod) {
	const files = await readdir('./locales');
	languages = (
		files
		.filter(name => name.endsWith('.csv'))
		.map(name => name.split('.')[0])
	);
}

const exec = cmd => (
	new Promise(resolve =>
		child_process_exec(
			cmd,
			(...args) => resolve(args)
		)
	)
);

async function file_replace(path, replacements, charset = 'utf8') {
	let content = await readFile(path, charset);
	for (const [from, to] of replacements) content = content.replaceAll(from, to);
	await writeFile(path, content, charset);
}

async function lang_generate(lang) {
	const csv = await readFile(`./locales/${lang}.csv`, 'utf8');
	let output = '// generated by build.js, for changes go to locales directory\n\n';
	for (const line of csv.split('\n')) {
		if (!line) continue;
		const index_colon = line.indexOf(': ');
		const key = line.substring(0, index_colon);
		const value = line.substring(index_colon + 2);
		output += `export const locale_${key} = '${value}';\n`;
	}
	await writeFile(
		'./src/etc/locale.js',
		output,
		'utf8'
	);
}

const env_set = async (version, debug, lang, api, api_data) => Promise.all([
	writeFile(
		'./src/etc/env.js',
`export const VERSION = '${version}';
export const DEBUG = ${debug};
export const LANG = '${lang}';
export const API = '${api}';
export const API_DATA = '${api_data}';
`,
		'utf8'
	),
	lang_generate(lang),
]);

async function build_css() {
	const css_raw = await readFile('./src/app.css', 'utf8');

	console.log('css...');
	const css_minified = '' + await (
		cssnano()
		.process(
			css_raw,
			{from: undefined}
		)
	);
	console.log('css done.');

	await writeFile(
		'./dist/app.css',
		css_minified,
		'ascii'
	);
}

const promises = [];

async function build_js(lang) {
	await env_set(
		prod ? version : 'dev',
		false,
		lang,
		prod ? '/api/minicraft/' : '//l3p3.de/api/minicraft/',
		prod ? '/static/minicraft/' : '//l3p3.de/static/minicraft/'
	);

	const TMP_FILE = `/tmp/app-${lang}.js`;

	console.log(lang + ' js pass 1...');
	const gcc_output = (await exec(
		GCC_COMMAND +
		[
			'assume_function_wrapper',
			'compilation_level ADVANCED',
			'dependency_mode PRUNE',
			'entry_point ./src/app.js',
			'js ./src',
			'js_output_file ' + TMP_FILE,
			'create_source_map ' + TMP_FILE + '.map',
			'language_in ECMASCRIPT_NEXT',
			'language_out ECMASCRIPT6_STRICT',
			'module_resolution BROWSER',
			'rewrite_polyfills false',
			'strict_mode_input',
			'use_types_for_optimization',
			'warning_level VERBOSE',
		]
		.join(' --')
	))[2].trim();
	if (gcc_output) console.log(gcc_output);
	console.log(lang + ' js pass 1 done.');

	promises.push(
		(async () => {
			console.log(lang + ' js pass 2...');
			await appendFile(
				TMP_FILE,
				`\n//# sourceMappingURL=app-${lang}.js.map\n`,
				'ascii'
			);
			const gcc_output = (await exec(
				GCC_COMMAND +
				[
					'assume_function_wrapper',
					'compilation_level SIMPLE',
					'externs ./src/externs.js',
					'js ' + TMP_FILE,
					`js_output_file ./dist/app-${lang}.js`,
					`create_source_map ./dist/app-${lang}.js.map`,
					'language_in ECMASCRIPT6_STRICT',
					'language_out ECMASCRIPT6_STRICT',
					'rewrite_polyfills false',
					'strict_mode_input',
					'warning_level VERBOSE',
				]
				.join(' --')
			))[2].trim();
			if (gcc_output) console.log(gcc_output);
			await Promise.all([
				appendFile(
					`./dist/app-${lang}.js`,
					`\n//# sourceMappingURL=app-${lang}.js.map\n`,
					'ascii'
				),
				file_replace(
					`./dist/app-${lang}.js.map`,
					[
						[ // closure compiler internals
							'/tmp/src/com/google/',
							'//raw.githubusercontent.com/google/closure-compiler/refs/heads/master/src/com/google/'
						],
						[ // all other paths are mine
							'/tmp/', 
							(
								prod
								?	`../minicraft@${process.env.GITHUB_SHA}/`
								:	'../'
							),
						],
					]
				),
				exec(`rm ${TMP_FILE} ${TMP_FILE}.map`),
			]);
			console.log(lang + ' js pass 2 done.');
		})(),
		(async () => {
			console.log(lang + ' ssr html...');
			await writeFile(
				`./dist/app-${lang}-ssr.html`,
				lui_ssr(
					await readFile(TMP_FILE, 'ascii')
				)(),
				'utf8'
			);
			console.log(lang + ' ssr html done.');
		})()
	);
}

if(
	!(
		await exec(GCC_COMMAND + 'version')
	)[1].includes('Version: v202')
) {
	throw new Error('google closure compiler required!');
}

await exec('rm ./dist/app*');

console.log(`build ${version} (${prod ? 'production' : 'dev'})...`);

try {
	await file_replace(
		'./src/etc/lui.js',
		[["@type {typeof import('lui/index')}", "@type {Object}"]]
	);
	for (const lang of languages) await build_js(lang);
	promises.push(build_css());
	await Promise.all(promises);
}
finally {
	if (!prod) {
		await Promise.all([
			env_set(
				'dev',
				true,
				'en',
				'//l3p3.de/api/minicraft/',
				'//l3p3.de/static/minicraft/'
			),
			file_replace(
				'./src/etc/lui.js',
				[["@type {Object}", "@type {typeof import('lui/index')}"]]
			),
		]);
	}
}

console.log('done.');
