// This file was automatically generated by packer.js

export const TILE_STONE = 0;
export const TILE_GRASS_SIDE = 1;
export const TILE_DIRT = 2;
export const TILE_COBBLE = 3;
export const TILE_PLANKS = 4;
export const TILE_BEDROCK = 5;
export const TILE_LOG_SIDE = 6;
export const TILE_LEAVES = 7;
export const TILE_BRICKS = 8;
export const TILE_WOOL = 9;
export const TILE_GRASS_TOP = 10;
export const TILE_LOG_TOP = 11;

export const TILES_RESOLUTION = 1;
export const TILES_DATA = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAAMCAIAAAAs6UAAAAAAM0lEQVR4AWOorKxkqAixBOOmpiaG6dW+DK6urgwJvvoM+k1KDDt6GhiuX7/OUL89CCQHAGZIEAn8oVpuAAAAAElFTkSuQmCC';
